### ISSUE TITLE
Error creating bean with name 'io.github.jhipster.config.metrics.PrometheusRegistry'

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#10039]
##### **Overview of the issue**

I get this error when starting app:

`Error creating bean with name 'io.github.jhipster.config.metrics.PrometheusRegistry': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.codahale.metrics.MetricRegistry' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

##### **Reproduce the error**

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in io.github.jhipster.config.metrics.PrometheusRegistry required a bean of type 'com.codahale.metrics.MetricRegistry' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'dropwizardRegistry' in 'JHipsterLoggingMetricsExportConfiguration' not loaded because @ConditionalOnProperty (jhipster.metrics.logs.enabled) found different value in property 'jhipster.metrics.logs.enabled'

Action:

Consider revisiting the entries above or defining a bean of type 'com.codahale.metrics.MetricRegistry' in your configuration.
```

##### **Suggest a Fix**

Run the app without error

##### **JHipster Version(s)**

`6.1.2`

##### **JHipster Version(s)**

```
openprovider@0.0.0 /Users/milan/Sites/jhipster
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.logate.openprovider"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "openprovider",
    "packageName": "com.logate.openprovider",
    "packageFolder": "com/logate/openprovider",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.0.0

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS Mojave
Version 10.14.5 (18F132)

**Comment by clement26695** [comment]
Hi @micobarac !

I didn't manage to reproduce your error, on either my mac or linux with 6.1.2 version (and master version). Did you modify anything, or were you trying to upgrade from a previous version of JHipster ? 

I can try to take a look if you have a repo you can share.

**Comment by micobarac** [comment]
HI @clement26695 !

I created a new app, and started copying java files from my old project into the new one. I just cannot find a reason why would metrics go wild, as I am not changing anything involving it or using it at all?

**Comment by clement26695** [comment]
Which version of the jhipster-dependencies do you have in your pom.xml ?

+ I think, as you point out, that you can remove the use of the MetricRegistry in the CassandraConfiguration file + the import, as I think we don't use it anymore

**Comment by micobarac** [comment]
`<jhipster-dependencies.version>3.0.3</jhipster-dependencies.version>`

**Comment by clement26695** [comment]
Do you have a jhipster.metrics.prometheus property ? It was removed in 5.8.0. As we switched from dropwizard metrics to micrometer to collect the application metrics, some configuration changed at that time.

**Comment by micobarac** [comment]
application.yaml:

```
  metrics:
    export:
      # Prometheus is the default metrics backend
      prometheus:
        enabled: true
        step: 60
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}
    web:
      server:
        auto-time-requests: true
```

application-prod.yaml:

```
management:
  metrics:
    export:
      prometheus:
        enabled: false
```
