### ISSUE TITLE
Add resourse limits on all generated Kubernetes specs

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#10769]
We do not have any resource limits on some of the spec we generate for Kubernetes. For example the MySQL deployment spec below. We should add limits to avoid starving of resourses

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-mysql
  namespace: jhipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice-mysql
  template:
    metadata:
      labels:
        app: invoice-mysql
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:8.0.17
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: invoice
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
```
