### ISSUE TITLE
Better defaults for security configuration

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#11081]
##### **Overview of the feature request**

Hi,

In the current version, we trust the developers to secure there endpoints using `authorized-microservices-endpoints` to decrease the attack surface, I believe that very few people know about this, and even fewer use it. I suggest therefore to have better defaults, instead of:
```
jhipster:
    gateway:
        authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
            app1: /api # recommended prod configuration
```
 have:
```
jhipster:
    gateway:
        authorized-microservices-default-endpoints: /api # recommended prod configuration
        authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
            app1: /api
```
And adjust the code:
https://github.com/jhipster/generator-jhipster/blob/e22ba2f3cbd275570f08c60149917c7d9c73f363/generators/server/templates/src/main/java/package/gateway/accesscontrol/AccessControlFilter.java.ejs#L91
accordingly to fallback to authorized-microservices-default-endpoints instead of returning true for everything...

-   [X] Checking this box is mandatory (this is just to show you read everything)
