### ISSUE TITLE
docker swarm issue: Compose file contains unsupported options: extends: Support for `extends` is not implemented yet

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#11147]
##### **Overview of the issue**
 docker stack deploy --compose-file docker-compose.yml demo

docker swarm issue: 
Compose file contains unsupported options: extends: Support for `extends` is not implemented yet

##### **Reproduce the error**
```

  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
  jhipster-zipkin:
    extends:
      file: jhipster-console.yml
      service: jhipster-zipkin
    depends_on:
      - jhipster-elasticsearch
```

docker stack deploy --compose-file docker-compose.yml demo
##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)
