### ISSUE TITLE
k8s: PostgreSQL mount path misconfigured

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#11184]
##### **Overview of the issue**

The mount path of the persistent storage in our postgresql manifests, generated by our kubernetes sub-generator, is misconfigured. Postgres does its own ephemeral mount on `/var/lib/postgresql/data`, so the database only persists until the pod is deleted 

##### **Reproduce the error**

Given you have a JHipster application using PostgreSQL:

1. generate k8s manifests using `jhipster kubernetes` (and choose dynamic storage provisioning)
2. deploy your application and generate some data
3. delete the PostgreSQL pod and wait until it is back up
4. examine the application for the data. All data should be lost

Reason:

PostgreSQL uses its own mount which overrides the existing, so if you `kubectl exec -it` into the running pod you can list the mounts to see the configuration:

``` bash
root@psql: mount
/dev/rbd2 on /var/lib/postgresql type ext4 (rw,relatime,stripe=1024,data=ordered)
/dev/sda1 on /var/lib/postgresql/data type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

(in my case I am using ceph-rbd as external storage)

##### **Suggest a Fix**

We should add a subMount path to the configuration, like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-postgresql
  template:
    metadata:
      labels:
        app: app-postgresql
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: app-postgresql-pvc
      containers:
        - name: postgres
          image: postgres:11.6
          env:
            - name: POSTGRES_USER
              value: App
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
```

Then, the mount table is showing only one mount, and the data persists after pod restarts...

##### **JHipster Version(s)**
6.6.0

-   [X] Checking this box is mandatory (this is just to show you read everything)
