### ISSUE TITLE
K8S: use PodAntiAffinities

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#11186]
##### **Overview of the feature request**

We could use the [Affinity Feature](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) of Kubernetes for better smarter scheduling of Kubernetes Multi-Replica-Pods.

##### **Motivation for or Use Case**

Deployments in Kubernetes are capable of maintaining ReplicaSets with multiple replicas. However, if the user does not specify more rules, it is quite common that pods of the same Deployment end up running on the same node. This happens in particular for low replica counts. The basic idea of replicas is, that if one replica is failing for some reason, the other still can handle requests. 

One of the most common reasons for failing pods is some issues with its node. But if we have all pods running all on one node, and this node is failing, all the replica magic is lost. 

If we use AntiAffinity for pods for their labels, we can achieve a preferred constellation, where Kubernetes distribute replicas of the same deployment not to run on the same node.

The required code for this looks like this and I've battle-tested it already:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appname
  name: appname
spec:
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - appname
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      # ...
```

There are two kinds of affinity settings, 'preferred' and 'required'. The first (and proposed) tries to schedule pods so that affinity is satisfied, but ignores the affinity if it is not possible to fulfill. A 'required' affinity, in contrast, will prevent the scheduling of new pods, if the affinity can not be satisfied.

WDYT, is it a good idea to bring this into our k8s sub-generator for application pods? If nobody has concerns, I would PR that addition.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)
