### ISSUE TITLE
jhipster ci-cd does not generate a ci-cd pipelines whith --skip-server option

### ISSUE THREAD

**Issue by maznag** [jhipster/generator-jhipster#11274]
##### **Overview of the issue**

No ci-cd pipelines generated with "jhipster ci-cd" when we generate only a frontend app with --skip-server option

##### **Motivation for or Use Case**

Generate a ci-cd pipeline only for frontend applications.

##### **Reproduce the error**

* generate a new app with "jhipster --skip-server --db=sql --auth=jwt"
* generate a GitLab ci-cd pipeline for example with "jhipster ci-cd"
* check the generated file .gitlab-ci.yml

Only these lines are generated:

stages:
- check
- build
- test
- analyze
- package
- release
- deploy

##### **JHipster Version(s)**
V6.7.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.7.0",
    "applicationType": "monolith",
    "baseName": "TestCICD",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "databaseType": "sql",
    "devDatabaseType": "sql",
    "prodDatabaseType": "sql",
    "creationTimestamp": 1581324311414,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": ["fr"],
    "blueprints": [],
    "skipServer": true
  }
}

</pre>
</details>

##### **Environment and Tools**

java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

git version 2.13.1

node: v11.14.0

npm: 6.13.7

yeoman: 3.1.1

Docker version 19.03.1, build 74b1e89

docker-compose version 1.24.1, build 4667896b

**Comment by vishal423** [comment]
I believe we support this flow in the GitHub Actions. @maznag, can you try that?

**Comment by maznag** [comment]
With Github Actions I have this:

* github-ci.yml

```
name: Application CI
on: [push, pull_request]
jobs:
    pipeline:
        name: CICDTest pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.14.0
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.14.0
            - name: Install node.js packages
              run: npm install
            - name: Run frontend test
              run: npm run test
            - name: Analyze code with SonarQube
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [ -n $SONAR_TOKEN ]; then
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
            - name: Package application
              run: npm run build
```

* GitLab Ci .gitlab-ci.yml
```
stages:
  - check
  - build
  - test
  - analyze
  - package
  - release
  - deploy
```

* Jenkinsfile

```
#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }

    stage('quality analysis') {
        withSonarQubeEnv('sonar') {
        }
    }
}
```

**Comment by atomfrede** [comment]
So it looks like gitlab and jenkins pipelines are basically empty.

**Comment by avdev4j** [comment]
for Jenkinsfile it's because we do all steps under maven command:
`<%_ if (buildTool === 'maven') { _%>` https://github.com/jhipster/generator-jhipster/blob/master/generators/ci-cd/templates/jenkins/Jenkinsfile.ejs#L36 (or gradle ofc).

We can easily improve that by improving the templates by adding the case we don't have the server part.

same reason for gitlab.

Github-ci manage both case :
```
              if (skipServer && !skipClient) {
              _%>
              run: <%= clientPackageManager %> run build
              <%_
              }
```

We should do the same for other ci.

**Comment by pascalgrimaud** [comment]
@avdev4j : for Jenkins, it was done like this because you don't know which version of node, npm or yarn are used.
For my old customer, I saw a very old version of node, installed on the Jenkins server, and by this way, I can use the version of Node+NPM I need

**Comment by maznag** [comment]
For gitlab we need to have something like that for separated frontend:

```
cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - analyze
  - packaging

webpack-build:
  stage: build
  script:
    - npm install
    - npm run webpack:build
  artifacts:
    paths:
      - build/

webpack-test:
  stage: test
  dependencies:
    - webpack-build
  script:
    - npm run webpack:test
  artifacts:
    reports:
      junit: build/test-results/TESTS-results-jest.xml
    paths:
      - build/test-results
    expire_in: 1 day

sonar:
  stage: analyze
  dependencies:
    - npm-test
  script:
    - npm run sonar
  artifacts:
    paths:
      - build/
      - build/test-results

webpack-prod:
  stage: packaging
  script:
    - npm run webpack:prod
    # - add cmd to zip the app folder build/resources/main/static
  artifacts:
    paths:
      - build/
```

for sonar to work, we should add sonar npm package to package.json
* add  "sonar-scanner": "3.1.0" to "dependencies" section
* add "sonar": "sonar-scanner" to "scripts" section
