### ISSUE TITLE
Liquibase setup

### ISSUE THREAD

**Issue by mpages** [jhipster/generator-jhipster#1160]
hi Hipster

why do you init liquibase using java code and bean declaration while you can do it with yaml conf (standard conf)

you just add 
```
liquibase:
  dropFirst: false
  changeLog: classpath:/config/liquibase/master.xml
  contexts: production
  ...
```

options are available 
https://github.com/spring-projects/spring-boot/blob/v1.2.1.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseProperties.java
