### ISSUE TITLE
Add optional IPv6 reachability for containers

### ISSUE THREAD

**Issue by CentroricercheRPS** [jhipster/generator-jhipster#11901]
##### **Overview of the feature request**

When deployed with docker, the containers only have IPv4 address. If a microservice need to interface to a IPv6 host then it's not possible.

What I did:

edited `/etc/docker/daemon.json` (yes this is beyond the scope of JHipster, but it's assumed that the user does its part)
```
{
“ipv6”: true,
“fixed-cidr-v6”: “2001:db8:1::/64”
}
```
edited the `docker-compose.yml`

```
version: '2.1'

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:1:a:1::/80
          gateway: 2001:db8:1:a::1
```

Edited the jhipster-registry.yml:
`version: '2.1'`

I got partial sucess: the container can send a message to the target IP6 host, but don't receive an answer.
See https://stackoverflow.com/questions/62179545/docker-networking-with-ipv6

-   [X] Checking this box is mandatory (this is just to show you read everything)
