### ISSUE TITLE
Dockerized UAA Timedout.

### ISSUE THREAD

**Issue by haigopi** [jhipster/generator-jhipster#12099]
##### **Overview of the issue**

**Problem:** Non-Dockerized Microservice is timing out to connect to a Dockerized UAA. I am not 100% sure if this is a bug or maybe I am missing something. 

**Error:**       org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://uaa/oauth/token_key": Operation timed out (Connection timed out); 

**hosts file:**
----------------
127.0.0.1 jhipster-logstash
127.0.0.1 registry jhipster-registry

**Below is the list of Containers running:**
-------------------------------------------

```
 IMAGE                                   PORTS                                                                NAMES
 jhipster/jhipster-zipkin:v4.1.0         9410/tcp, 0.0.0.0:9411->9411/tcp                                     docker-compose_jhipster-zipkin_1
 jhipster/jhipster-console:v4.1.0        0.0.0.0:5601->5601/tcp                                               docker-compose_jhipster-console_1
 jhipster/jhipster-logstash:v4.1.0       5044/tcp, 0.0.0.0:5000->5000/tcp, 0.0.0.0:5000->5000/udp, 9600/tcp   docker-compose_jhipster-logstash_1
 jhipster/jhipster-curator:v4.1.0                                                                             docker-compose_jhipster-curator_1
 mongo:4.2.7                             27017/tcp                                                            docker-compose_publisher-mongodb_1
 uaa                          5701/udp, 0.0.0.0:9999->9999/tcp                                     docker-compose_uaa_1
 mongo:4.2.7                             27017/tcp                                                            docker-compose_consumer-mongodb_1
 mongo:4.2.7                             27017/tcp                                                            docker-compose_uaa-mongodb_1
 mongo:4.2.7                             27017/tcp                                                            docker-compose_gateway-mongodb_1
 consumer                     5701/udp, 8082/tcp                                                   docker-compose_consumer_1
 jhipster/jhipster-elasticsearch:v4.1.0  9200/tcp, 9300/tcp                                                   docker-compose_jhipster- elasticsearch_1
 jhipster/jhipster-registry:v6.3.0       0.0.0.0:8761->8761/tcp                                               docker-compose_jhipster-registry_1
 gateway                      0.0.0.0:8080->8080/tcp                                               docker-compose_gateway_1
```

While a newly generated Microservice registered successfully with the registry which is running inside a docker container along with others APP1, Gateway, UAA(as listed above), the new Microservice is timing out on UAA. 

Endpoints through GW also showing the same, per the below screenshot. (When this service runs as a docker instance its working fine).
![Screen Shot 2020-07-18 at 1 19 57 PM](https://user-images.githubusercontent.com/5770644/87859266-64b1b080-c8f9-11ea-85ec-6083ef8f43b4.png)

```
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-07-18 12:54:18.648  WARN 17310 --- [scoveryClient-1] c.netflix.discovery.TimedSupervisorTask  : task supervisor rejected the task

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3d4fb643 rejected from java.util.concurrent.ThreadPoolExecutor@491ec3d9[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-07-18 12:54:58.649  WARN 17310 --- [scoveryClient-1] c.netflix.discovery.TimedSupervisorTask  : task supervisor rejected the task

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3ef1780e rejected from java.util.concurrent.ThreadPoolExecutor@491ec3d9[Running, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2020-07-18 12:55:27.651 ERROR 17310 --- [  restartedMain] c.a.p.c.o.OAuth2JwtAccessTokenConverter  : could not get public key from OAuth2 server to create SignatureVerifier

org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://uaa/oauth/token_key": Operation timed out (Connection timed out); nested exception is java.net.ConnectException: Operation timed out (Connection timed out)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:748)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583)
	at com.app.publisher.security.oauth2.UaaSignatureVerifierClient.getSignatureVerifier(UaaSignatureVerifierClient.java:46)
	at com.app.publisher.config.oauth2.OAuth2JwtAccessTokenConverter.tryCreateSignatureVerifier(OAuth2JwtAccessTokenConverter.java:69)
	at com.app.publisher.config.oauth2.OAuth2JwtAccessTokenConverter.<init>(OAuth2JwtAccessTokenConverter.java:29)
	at com.app.publisher.config.SecurityConfiguration.jwtAccessTokenConverter(SecurityConfiguration.java:60)
	at com.app.publisher.config.SecurityConfiguration$$EnhancerBySpringCGLIB$$a7054c3d.CGLIB$jwtAccessTokenConverter$1(<generated>)
```

##### **Motivation for or Use Case**

Simplifying the development environment. While the rest of the needed services are running inside the docker which is easy to bring them up using docker-compose up, being a developer I would like to focus on the services that I am actively working on in a non-dockerized fashion.

##### **Reproduce the error**

1. Generated two Microservices(APP1, APP2) & UAA, Gateway.
2. Generated the docker-compose as below:
```
version: '2'
services:
  consumer:
    **image: consumer**
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=mongodb://consumer-mongodb:27017'
      - SPRING_DATA_MONGODB_DATABASE=consumer
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://jhipster-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://jhipster-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
  consumer-mongodb:
    image: 'mongo:4.2.7'


  gateway:
    **image: gateway**
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=mongodb://gateway-mongodb:27017'
      - SPRING_DATA_MONGODB_DATABASE=gateway
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://jhipster-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://jhipster-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'
  gateway-mongodb:
    image: 'mongo:4.2.7'

  publisher:
    **image: publisher**
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=mongodb://publisher-mongodb:27017'
      - SPRING_DATA_MONGODB_DATABASE=publisher
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://jhipster-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://jhipster-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
  publisher-mongodb:
    image: 'mongo:4.2.7'

  uaa:
    **image: uaa**
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATA_MONGODB_URI=mongodb://uaa-mongodb:27017'
      - SPRING_DATA_MONGODB_DATABASE=uaa
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://jhipster-elasticsearch:9200'
      - 'SPRING_ELASTICSEARCH_REST_URIS=http://jhipster-elasticsearch:9200'
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '9999:9999'
  uaa-mongodb:
    image: 'mongo:4.2.7'

  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
  jhipster-zipkin:
    extends:
      file: jhipster-console.yml
      service: jhipster-zipkin
    depends_on:
      - jhipster-elasticsearch
```
3. Stopped & removed the container of APP2 (publisher).
4. Start the APP2 locally using ./gradlew

##### **Related issues**

Yes. I read as below, but still, I am not able to solve by referring to them. 
https://github.com/jhipster/generator-jhipster/issues/10764
https://github.com/jhipster/generator-jhipster/issues/5545
https://github.com/jhipster/generator-jhipster/issues/4810
https://gitter.im/jhipster/generator-jhipster/archives/2018/04/02

##### **JHipster Version(s)**
6.10.1 

##### **JHipster configuration**

APP2: (MicroService)
`
INFO! Using JHipster version installed locally in the current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
publisher@0.0.0 /Users/gopimac/Documents/Workspace/VS/publisher
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.publisher"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "microservice",
    "baseName": "publisher",
    "packageName": "com.app.publisher",
    "packageFolder": "com/app/publisher",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1595035238706,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v13.12.0

npm: 6.14.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6`

UAA:

`INFO! Using JHipster version installed locally in current project's node_modules
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
uaa@0.0.0 /Users/gopimac/Documents/Workspace/VS/uaa
└── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.uaa"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.app.uaa",
    "packageFolder": "com/app/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1595034996353,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v13.12.0

npm: 6.14.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

INFO! Congratulations, JHipster execution is complete!`

**Gateway:**

`
INFO! Using JHipster version installed locally in current project's node_modules
INFO! No custom sharedOptions found within blueprint: generator-jhipster-vuejs at /Users/gopimac/Documents/Workspace/VS/gateway/node_modules/generator-jhipster-vuejs
INFO! No custom commands found within blueprint: generator-jhipster-vuejs at /Users/gopimac/Documents/Workspace/VS/gateway/node_modules/generator-jhipster-vuejs
INFO! Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 /Users/gopimac/Documents/Workspace/VS/gateway
└─┬ generator-jhipster-vuejs@1.9.1
  └── generator-jhipster@6.10.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.app.gateway",
    "packageFolder": "com/app/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "caffeine",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "cosmo",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1595093224353,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.9.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "bn", "hi", "mr", "ta", "te"],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.9.1"
      }
    ]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v13.12.0

npm: 6.14.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

INFO! Congratulations, JHipster execution is complete!`
`

APP2: .yo-rc
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.publisher"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "microservice",
    "baseName": "publisher",
    "packageName": "com.app.publisher",
    "packageFolder": "com/app/publisher",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "REMOVED",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1595035238706,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}
```
GW: .yo-rc
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.app.gateway",
    "packageFolder": "com/app/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "caffeine",
    "enableHibernateCache": false,
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "vue",
    "clientTheme": "cosmo",
    "clientThemeVariant": "dark",
    "creationTimestamp": 1595093224353,
    "testFrameworks": ["gatling"],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.9.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": ["en", "bn", "hi", "mr", "ta", "te"],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.9.1"
      }
    ]
  }
}
```
UAA: .yo-rc
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.app.uaa"
    },
    "jhipsterVersion": "6.10.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.app.uaa",
    "packageFolder": "com/app/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "REMOVED",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1595034996353,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "blueprints": [],
    "skipClient": true
  }
}
```

##### **Browsers and Operating System**

OSX, BRAVE/CHROME

-   [X] Checking this box is mandatory (this is just to show you read everything)
