### ISSUE TITLE
Expose management endpoints on a different port

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#12184]
##### **Overview of the feature request**

Set the [`management.server.port` property](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-customizing-management-server-port) to a different value from the one in `server.port` on generated apps to expose the management API to a different port.

##### **Motivation for or Use Case**

Exposing the management API on a different port is generally a good practice but was not implemented because it could break the existing admin screens. However, with the JHCC becoming available, there is a way to access those screens on a different app which could work even if those endpoints are on a different port.

Moreover, in the [JHCC RFC design document](https://github.com/jhipster/generator-jhipster/blob/master/rfcs/2-jhipster-rfc-jhipster-control-center.md#architecture-overview), there is the example of the JHCC connecting to the management endpoints on port 9999. To improve security, the JHCC should support any port and be able to dynamically discover the port from instance metadata with these settings (eg for eureka) : 

```
eureka:                                                                                                                                                                                                                                                                                           
  instance:                                                                                                                                                                                                                                                               
    metadata-map:                                                                                                                                                         
      management-port: ${management.server.port:}                                                                                   
```

However this asks the question, should we expose a different management port by default for JHipster v7 or just leave it the same as the normal server port (with users being able to change it by themselves) ? What do you think @jhipster/developers ? It could also be set to a different port in deployment files only (Kubernetes, docker-compose...).

We should also add a log on startup to show that the management port is different.

-   [x] Checking this box is mandatory (this is just to show you read everything)

<!-- Love JHipster? Please consider supporting our collective:
👉  https://opencollective.com/generator-jhipster/donate -->
