### ISSUE TITLE
Implement stale workflow.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12694]
##### **Overview of the feature request**

Implement https://github.com/actions/stale.
Proposed configuration:
```
name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days'
        days-before-stale: 30
        days-before-close: 7
```

##### **Motivation for or Use Case**

Implement stale workflow to keep open issues/PRs on flux.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)
