### ISSUE TITLE
Jhipster gateway service API returns index page even with valid Authorization Header(Bearer token)

### ISSUE THREAD

**Issue by xantusDev** [jhipster/generator-jhipster#12799]
My team is creating a microservice project and have successfully implemented Discovery(Jhipster Registry), API Gateway(jhipster gateway) with custom angular application and a microservice application. context path is set to both registry(/registry) and gateway application(/gateway). Authentication: JWT
CORS: Enabled default gateway cors rules in application.yml file.
```
# CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: 'GET, PUT, POST, DELETE, OPTIONS'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
```

Everything works fine in local machine setup.

Registry service URL: http://localhost:8761/registry.
Gateway URL: http://localhost:8080/gateway.
Authenticate: http://localhost:8080/gateway/api/authenticate
Microservice API is accessed through gateway(URL:
http://localhost:8080/gateway/service/micro1/api/{resource}).
Angular application URL :http://localhost:4200.

Every inter communication is working as expected including CORS.

But the moment all the above set up is deployed to DEV server we are facing unexpected behaviours:

Even though CORS is enabled(as I mentioned above - default cors settings is enabled in gateway), we are not able to test the DEV microservice API url:
https://{DEV IP}/gateway/service/micro1/api/{resource} from Angular application running locally at http://localhost:4200 as its throwing CORS issue:
"Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 'resource URL'. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing) - status: 403 Forbidden".
Note: - https://{DEVIP}/gateway/api/authenticate can be accessed without any CORS problems and valid token is returned.

When the application deployed in DEV server is accessed post successful authentication,the API response for https://{DEVIP}/gateway/service/micro1/api/{resource} is not JSON but returns index.html.

In the above two scenarios gateway authentication endpoint works fine but any other API calls through gateway is not working as expected.

Kindly help me resolve the same.
