### ISSUE TITLE
CircleCI Improvements

### ISSUE THREAD

**Issue by tillias** [jhipster/generator-jhipster#12891]
##### **Overview of the feature request**

circle-ci config.yaml can be greatly simplified if using docker instead of vm:

```
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.8-node
```

##### **Motivation for or Use Case**

Currently build from generared config is not working anymore:
https://discuss.circleci.com/t/maven-shared-incremental-1-1-pom-connection-reset/37934

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster/issues/12877 -> cimg/openjdk:11.0.8-node has node 12 installed, but I'm pretty sure will also work with node 14, cause maven-frontend-plugin is used?
