### ISSUE TITLE
Spring Cloud Config: no retry and failed to start

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#13800]
##### **Overview of the issue**

Following the discussion here
https://groups.google.com/g/jhipster-dev/c/S9a5AwMEIcc/m/SqokH83qCwAJ

Currently, when starting a Gateway or Microservice with prod profile, without starting the Registry, the application failed and stopped, instead of waiting the Registry to be up

The behaviour has changed since Spring Boot 2.4

##### **Motivation for or Use Case**

The application should wait and should not stop.
Because of this, all daily builds failed:

![JDLMS_failures](https://user-images.githubusercontent.com/9156882/106525385-3043c180-64e4-11eb-9df4-5fdd645f83d1.png)

##### **Reproduce the error**

- create a Gateway or Microservice with current master -> https://github.com/jhipster/generator-jhipster/commit/a8ea5b5da06fd2ee1e7350385096a3601adbafd4
- start the database if needed
- start the application with prod profile

##### **JHipster Version(s)**

```
micro@0.0.0 /home/pgrimaud/tmp/05-micro-7.0.0-beta.2-master
└── generator-jhipster@7.0.0-beta.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "microservice",
    "baseName": "micro",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipClient": true,
    "skipUserManagement": true,
    "skipServer": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1612215247827,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": "eureka",
    "reactive": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8081",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "withAdminUi": true,
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)

git version 2.30.0

node: v14.15.3

npm: 6.14.9

yeoman: 3.1.1

Docker version 18.03.0-ce, build 0520e24

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

**Comment by pascalgrimaud** [comment]
@mraible : the work around is:

Add this dependency

```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>
```

Remove this property:

```yaml
  config:
    import: 'configserver:'
```

Then, add back bootstrap-prod.yml :

```yml
# ===================================================================
# Spring Cloud Config bootstrap configuration for the "prod" profile
# ===================================================================

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 100
      uri: http://admin:${jhipster.registry.password}@localhost:8761/config
      # name of the config server's property source (file.yml) that we want to use
      name: jhipster
      profile: prod # profile(s) of the property source
      label: main # toggle to switch to a different version of the configuration as stored in git
      # it can be set to any label, branch or commit of the configuration source Git repository

jhipster:
  registry:
    password: admin
```
