### ISSUE TITLE
Swagger in Gateway: broken when compression is true

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#14198]
##### **Overview of the issue**

When generating a Gateway, which is reactive, it can't not get the swagger from other microservices, if there are started using prod profile, with compression to true
I think it's because the response is compressed

```yaml
server:
  port: 8081
  shutdown: graceful # see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-graceful-shutdown
  compression:
    enabled: true
```

##### **Motivation for or Use Case**

Swagger should work with / without compression

##### **Related issues**

Following https://github.com/jhipster/generator-jhipster/pull/14029 by @nassimerrahoui 

##### **Suggest a Fix**

Maybe have a look to this old PR https://github.com/jhipster/generator-jhipster/pull/8417/files

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)
