### ISSUE TITLE
Username for email not set properly

### ISSUE THREAD

**Issue by Yacine-krk** [jhipster/generator-jhipster#1465]
Hello,

In application.yml, in the mail block, the user variable is set as "user"
```yml
mail:
    host: smtp.gmail.com
    port: 587
    user: 
    password:
    protocol: smtp
    tls: true
    auth: true
    from: 
```
But in MailConfiguration.java, the variable is used as "username" :
```java
private static final String PROP_USER = "username";
```

Regards,
Yacine
