### ISSUE TITLE
JHipster Resigtry & Keycloak

### ISSUE THREAD

**Issue by vwiencek** [jhipster/generator-jhipster#14756]
Hello, 

it seems that the connection between JHipster Registry and Keycloak is broken.

The scenario:
- create an Oauth 2 application (see .yo-rc.json after)
- start keycloak docker 11.0.2 within docker (see yml docker compose file after)
- start jhipster registry 6.7.1 within docker (see yml docker compose file after)

The symptoms:
- I can log in to the registry app through keycloak
- I can see metrics from the jhipster app
- When I try to look at my app metrics I get a 401 error (my app is called irrc)

request header
```
GET /services/irrc/irrc:a9a4c1c94ec9feb829f0988a15bb8b79/management/jhimetrics HTTP/1.1
Host: localhost:8761
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Referer: http://localhost:8761/admin/metrics
Cookie: JSESSIONID_REGISTRY=gp_biHavb30_dXF6qcBWAemmq-5YqQQlWyY_3eT-
```

Response header
```
HTTP/1.1 401 Unauthorized
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Content-Security-Policy: default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:
Date: Thu, 22 Apr 2021 10:05:11 GMT
Connection: keep-alive
WWW-Authenticate: Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: The iss claim is not valid", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
Feature-Policy: geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; fullscreen 'self'; payment 'none'
Transfer-Encoding: chunked
```

It seems that the JHipster Registry app tries to authenticate to the app with JWT ... which is odd since I'm using OAuth2.

##### **Overview of the issue**

The application
```
{
  "generator-jhipster": {
    "jhipsterVersion": "6.10.5",
    "baseName": "JHipsterRegistry",
    "packageName": "io.github.jhipster.registry",
    "packageFolder": "io/github/jhipster/registry",
    "serverPort": "8761",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "c9d37cefc48581919939d587c750ea215020765b",
    "useSass": true,
    "enableTranslation": false,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": false,
    "skipUserManagement": false,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "embeddableLaunchScript": false,
    "clientTheme": "none",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "blueprints": [],
    "creationTimestamp": 1576848019661,
    "gcpProjectId": "jhipsterproject",
    "gcpCloudSqlInstanceName": "jhipsterproject:us-central1:jhipster",
    "gcpCloudSqlUserName": "root",
    "gcpCloudSqlDatabaseName": "jhipsterregistry",
    "gaeServiceName": "jhipster-registry",
    "gaeLocation": "us-central",
    "gaeInstanceClass": "F2",
    "gaeScalingType": "automatic",
    "gaeMinInstances": "1",
    "gaeMaxInstances": "2",
    "gaeCloudSQLInstanceNeeded": "Y"
  }
}
```

The keycloak docker-file 

```
version: '2'
services:
  keycloak:
    image: jboss/keycloak:11.0.2
    command:
      [
        '-b',
        '0.0.0.0',
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config',
        '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
        '-Djboss.socket.binding.port-offset=1000',
        '-Dkeycloak.profile.feature.upload_scripts=enabled',
      ]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=keycloak_user
      - DB_PASSWORD=keycloak_password
      - DB_ADDR=keycloak_database
      - PROXY_ADDRESS_FORWARDING=true
      - DB_SCHEMA=public
      - DB_DATABASE=keycloak
    ports:
      - 9080:9080
      - 9443:9443
      - 10990:10990

  keycloak_database:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=keycloak_password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=keycloak
          
```

the jhipster registry file

```
# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.7.1
    volumes:
      - ./central-server-config:/central-config
    # When run with the "dev" Spring profile, the JHipster Registry will
    # read the config from the local filesystem (central-server-config directory)
    # When run with the "prod" Spring profile, it will read the configuration from a Git repository
    # See https://www.jhipster.tech/jhipster-registry/#spring-cloud-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs,oauth2
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jhipster/jhipster-registry/
      # - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
      # For keycloak to work, you need to add '127.0.0.1 keycloak' to your hosts file
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/mla
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=jhipster-registry
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=jhipster-registry
  #    - ZUUL_SENSITIVE_HEADERS=Cookie,Set-Cookie
  #    - ZUUL_IGNORE_SECURITY_HEADERS=false
  #    - ZUUL_IGNORED_HEADERS=cookie,set-cookie
  
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8761:8761

```

##### **Browsers and Operating System**
macOS 11.2.3, node 14.16.1, jhipster 7.0.1

- [X] Checking this box is mandatory (this is just to show you read everything)
