### ISSUE TITLE
OpenAPI subgenerator mapping JHipster entities to openapi schemas/resources

### ISSUE THREAD

**Issue by ivangsa** [jhipster/generator-jhipster#16685]
##### **Overview of the feature request**

With JHipster is easy to generate CRUD microservices for a given domain model described as JDL (DDD)

With OpenAPI/Swagger we can describe an API.

If we add some extension tags to OpenAPI definitions mapping schemas to entities then a subgenerator could generate api controller implementation that links repository/services/entities with openapi resources.

Customizing the famous petstore:

```yml
Pet:
  required:
  - name
  - photoUrls
  x-jhipster-model: **PetEntity**
  type: object
  properties:
    id:
      type: integer
      format: int64
      example: 10
      **x-jhipster-id: true**
    name:
      type: string
      example: doggie
```

could generate something like this:

```java
@Service
public class PetApiDelegateImpl implements PetApiDelegate {
    @Autowired
    PetRepository petRepository;
    @Autowired
    PetMapper petMapper;
    @Override
    public ResponseEntity<List<Pet>> findPetsByStatus(List<String> status) {
        return ResponseEntity.ok(
            petMapper.map(petRepository.findAll())
        );
    }
}
```

##### **Motivation for or Use Case**

This is just an idea inspired on this project https://github.com/apiaddicts/apigen (sorry it's in spanish) that generates full backend from an OpenAPI sprinkled with some special _x-<models>_ tags

I think this could be a good addition to the richness of JHipster model based code generation

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)
