### ISSUE TITLE
Generate a default circle.yml

### ISSUE THREAD

**Issue by phouverneyuff** [jhipster/generator-jhipster#1670]
I have a circle.yml set. I can make a PR for Jhipster generate it by default.

Anyone have interest?

CircleCI allow to test until 1 private repository and 3 open without limit and all this for free.
I prefer CircleCI instead of Travis.

We can generate both files to set environment and generate test.

I think that Continuous Integration is so important.

**Comment by phouverneyuff** [comment]
e.g.:

```yml
general:
  build_dir: .

  artifacts:
    - "build/reports/tests"

machine:
  node:
    version: 0.12.5

  java:
    version: oraclejdk8

dependencies:
  cache_directories:
    - "~/.gradle"

test:
 pre:
   - npm install -g bower

 override:
   - ./gradlew clean build -i

 post:
   - mkdir -p $CIRCLE_TEST_REPORTS/junit/
   - find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
```
