### ISSUE TITLE
Improved support for docker secrets

### ISSUE THREAD

**Issue by crowne** [jhipster/generator-jhipster#17943]
##### **Overview of the feature request**

I'd like to be able to set environment variable values using docker secrets
in a similar way to how it is done by keycloak.
See https://github.com/keycloak/keycloak-containers/blob/main/server/tools/docker-entrypoint.sh

It should be as simple as changing one template file
generators\server\templates\src\main\docker\jib\entrypoint.sh.ejs

The way that it is implemented allows variables to be defined normally in a docker-compose file for example,
alternatively if the variable name is suffixed by _FILE then the env var value will be loaded from the file.

In the proposal below the list of secret supported environment variables is static.
Also it would always define the variables for every app even if they were not used for example a gateway app without a database.

from
``` shell
#!/bin/sh

echo "The application will start in ${JHIPSTER_SLEEP}s..." && sleep ${JHIPSTER_SLEEP}
exec java ${JAVA_OPTS} -noverify -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/./urandom -cp /app/resources/:/app/classes/:/app/libs/* "<%= packageName %>.<%= mainClass %>"  "$@"
```

to
``` shell
#!/bin/bash

echo "The application will start in ${JHIPSTER_SLEEP}s..." && sleep ${JHIPSTER_SLEEP}


# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
    local var="$1"
    local fileVar="${var}_FILE"
    local def="${2:-}"
    if [[ ${!var:-} && ${!fileVar:-} ]]; then
        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
        exit 1
    fi
    local val="$def"
    if [[ ${!var:-} ]]; then
        val="${!var}"
    elif [[ ${!fileVar:-} ]]; then
        val="$(< "${!fileVar}")"
    fi

    if [[ -n $val ]]; then
        export "$var"="$val"
    fi

    unset "$fileVar"
}

file_env 'SPRING_DATASOURCE_URL'
file_env 'SPRING_DATASOURCE_USERNAME'
file_env 'SPRING_DATASOURCE_PASSWORD'
file_env 'SPRING_LIQUIBASE_URL'
file_env 'SPRING_LIQUIBASE_USER'
file_env 'SPRING_LIQUIBASE_PASSWORD'
file_env 'JHIPSTER_REGISTRY_PASSWORD'

exec java ${JAVA_OPTS} -noverify -XX:+AlwaysPreTouch -Djava.security.egd=file:/dev/./urandom -cp /app/resources/:/app/classes/:/app/libs/* "<%= packageName %>.<%= mainClass %>"  "$@"

```

docker-compose.yml
``` yml
version: '3.8'

secrets:
  myapp_db_url:
    file: ~.secrets/myapp/${app_env}/myapp_db_url.txt
  myapp_db_user:
    file: ~.secrets/myapp/${app_env}/myapp_db_user.txt
  myapp_db_password:
    file: ~.secrets/myapp/${app_env}/myapp_db_password.txt
  jhipster_registry_password:
    file: ~.secrets/myapp/${app_env}/jhipster_registry_password.txt

services:
  myapp:
    depends_on:
      - "jhipster-registry"
    image: myapp
    secrets:
      - myapp_db_url
      - myapp_db_user
      - myapp_db_password
      - jhipster_registry_password
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL_FILE=/run/secrets/myapp_db_url
      - SPRING_DATASOURCE_USERNAME_FILE=/run/secrets/myapp_db_user
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/myapp_db_password
      - SPRING_LIQUIBASE_URL_FILE=/run/secrets/myapp_db_url
      - SPRING_LIQUIBASE_USER_FILE=/run/secrets/myapp_db_user
      - SPRING_LIQUIBASE_PASSWORD_FILE=/run/secrets/myapp_db_password
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      - JHIPSTER_REGISTRY_PASSWORD_FILE=/run/secrets/jhipster_registry_password

```

##### **Motivation for or Use Case**

This improves security for the custom build images as the sensitive values are not stored in the deployment files.

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)
