### ISSUE TITLE
mongodb cluster does not start on kubernetes: lookup no such host

### ISSUE THREAD

**Issue by indiepopart** [jhipster/generator-jhipster#18651]
##### **Overview of the issue**

The issue happens when running a local kubernetes cluster for the reactive-jhipster example, in the [java-microservices-examples](https://github.com/oktadev/java-microservices-examples). Mongodb cluster does not start.

The boot container of the store-mongodb-0 pod never completes execution and just logs:
```
2022/04/12 19:36:09 lookup store-mongodb on 10.245.0.10:53: no such host
```

##### **Motivation for or Use Case**

It seems the boot container can't find its mongodb peers, because the generated store-k8s/store-mongodb.yml is using a deprecated property. In the headless service definition for store-mongodb, the spec includes:

```yml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: store-mongodb
  namespace: demo
```

`service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"` seems to be [deprecated](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.11.md#kubernetes-111-release-notes) since Kubernetes 1.11. 

When using `spec.publishNotReadyAddresses: true`, the mongodb cluster starts.

```yml
apiVersion: v1
kind: Service
metadata:
  name: store-mongodb
  namespace: demo
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
```

##### **Reproduce the error**

```bash
git clone https://github.com/oktadev/java-microservices-examples.git
cd java-microservices-examples/jhipster-k8s/k8s
minikube --cpus <ncpu> start
./kubectl-apply.sh -f
```

##### **Suggest a Fix**

The generator should use `Service.spec.publishNotReadyAddresses` .

##### **JHipster Version(s)**

INFO! Using JHipster version installed globally
7.6.0

minikube v1.25.2 on Ubuntu 18.04
Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)
