### ISSUE TITLE
Use H2 disk-based persistence by default

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2134]
We currently use H2 in-memory persistence by default. It's easy to use, but of course you lose your data at each restart (and need to log in again as you lose your persistent session token), which is annoying.

We could use H2 disk-based persistence by default, and save the database state in the target/ directory:

- H2 in-memory would still be available, but wouldn't be the default -> no consequence for existing apps or people who prefer this mode
- Doing a "mvn clean" would remove the data, so it's easy to clean up if needed
- This is what we do with ElasticSearch (the index is in the target/ directory in dev mode)

**Comment by andidev** [comment]
+1
You probably already know this but anyway. This is a simple configuration in application-dev.yml 

```
    datasource:
        driver-class-name: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:file:./target/h2db/db:jhipster;DB_CLOSE_DELAY=-1
        name: 
        username: 
        password:
```

I already do this in my own project. 

Do you want me to provide a PR?
