### ISSUE TITLE
Gradle packaging : war.original contains tomcat-embed libs

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2561]
When packaging a JHipster project with Gradle, the war.original contains tomcat-embed libs although it shouldn't. The maven version is correct.

**Step1** : generate a project, all default except **gradle**, with this `.yo-rc.json`:
```yaml
{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "85dece1388bfa5e93d95eb46b49864e9b705c92f",
    "testFrameworks": []
  }
}
```

**Step2** : package for production
```ShellSession
./gradlew bootRepackage -Pprod
```

```ShellSession
$ ls -al build/libs/
total 115108
drwxr-xr-x 2 pgrimaud pgrimaud     4096 janv.  2 23:50 .
drwxr-xr-x 8 pgrimaud pgrimaud     4096 janv.  2 23:50 ..
-rwxr--r-- 1 pgrimaud pgrimaud 62094944 janv.  2 23:50 jhipster-0.0.1-SNAPSHOT.war
-rw-r--r-- 1 pgrimaud pgrimaud 55765100 janv.  2 23:50 jhipster-0.0.1-SNAPSHOT.war.original
```

**Step3** : check the file war.original
There are `tomcat-*.jar` libs inside the war.original, and there shouldn't be here (refered to [Using JHipster in production](http://jhipster.github.io/production.html))

```ShellSession
-rw-r--r-- 1 pgrimaud pgrimaud   14316 oct.  11 21:59 swagger-annotations-1.5.0.jar
-rw-r--r-- 1 pgrimaud pgrimaud  105427 oct.  11 21:59 swagger-models-1.5.0.jar
-rw-r--r-- 1 pgrimaud pgrimaud  799284 oct.  11 21:59 thymeleaf-2.1.4.RELEASE.jar
-rw-r--r-- 1 pgrimaud pgrimaud   99276 nov.  16 22:35 thymeleaf-layout-dialect-1.3.1.jar
-rw-r--r-- 1 pgrimaud pgrimaud  224290 oct.  11 21:59 thymeleaf-spring4-2.1.4.RELEASE.jar
-rw-r--r-- 1 pgrimaud pgrimaud 2829987 déc.  24 06:05 tomcat-embed-core-8.0.30.jar
-rw-r--r-- 1 pgrimaud pgrimaud  238012 déc.  24 06:05 tomcat-embed-el-8.0.30.jar
-rw-r--r-- 1 pgrimaud pgrimaud   40845 déc.  24 06:05 tomcat-embed-logging-juli-8.0.30.jar
-rw-r--r-- 1 pgrimaud pgrimaud  245948 déc.  24 06:05 tomcat-embed-websocket-8.0.30.jar
-rw-r--r-- 1 pgrimaud pgrimaud  135946 déc.  24 06:05 tomcat-jdbc-8.0.30.jar
-rw-r--r-- 1 pgrimaud pgrimaud   40845 déc.  24 06:05 tomcat-juli-8.0.30.jar
-rw-r--r-- 1 pgrimaud pgrimaud  139881 oct.  11 21:59 unbescape-1.1.0.RELEASE.jar
-rw-r--r-- 1 pgrimaud pgrimaud   63777 oct.  11 21:59 validation-api-1.1.0.Final.jar
-rw-r--r-- 1 pgrimaud pgrimaud  109318 oct.  11 21:59 xml-apis-1.0.b2.jar
```

Maybe solution? By adding this exclude to `gradle.properties` file :
```Groovy
war {
    rootSpec.exclude("**/tomcat-*.jar")
}
```

The main file war is inchanged and I got:
```ShellSession
$ ls -al build/libs/
total 111900
drwxr-xr-x 2 pgrimaud pgrimaud     4096 janv.  2 23:53 .
drwxr-xr-x 8 pgrimaud pgrimaud     4096 janv.  2 23:53 ..
-rwxr--r-- 1 pgrimaud pgrimaud 62094944 janv.  2 23:53 jhipster-0.0.1-SNAPSHOT.war
-rw-r--r-- 1 pgrimaud pgrimaud 52480420 janv.  2 23:53 jhipster-0.0.1-SNAPSHOT.war.original
```

Inside **jhipster-0.0.1-SNAPSHOT.war.original**
```ShellSession
-rw-r--r-- 1 pgrimaud pgrimaud   14316 oct.  11 21:59 swagger-annotations-1.5.0.jar
-rw-r--r-- 1 pgrimaud pgrimaud  105427 oct.  11 21:59 swagger-models-1.5.0.jar
-rw-r--r-- 1 pgrimaud pgrimaud  799284 oct.  11 21:59 thymeleaf-2.1.4.RELEASE.jar
-rw-r--r-- 1 pgrimaud pgrimaud   99276 nov.  16 22:35 thymeleaf-layout-dialect-1.3.1.jar
-rw-r--r-- 1 pgrimaud pgrimaud  224290 oct.  11 21:59 thymeleaf-spring4-2.1.4.RELEASE.jar
-rw-r--r-- 1 pgrimaud pgrimaud  139881 oct.  11 21:59 unbescape-1.1.0.RELEASE.jar
-rw-r--r-- 1 pgrimaud pgrimaud   63777 oct.  11 21:59 validation-api-1.1.0.Final.jar
-rw-r--r-- 1 pgrimaud pgrimaud  109318 oct.  11 21:59 xml-apis-1.0.b2.jar
```

Maven has these exclusions :
https://github.com/jhipster/generator-jhipster/blob/3becfa8c7e1fea1700eb6eec6395e435470c6c27/app/templates/_pom.xml#L706-L708
I don't find them for gradle.

@atomfrede : as you are our gradle expert, can you confirm this. Am I correct? Thanks in advance.
