### ISSUE TITLE
Issue connecting to postgresql database using default generated files

### ISSUE THREAD

**Issue by adaykin** [jhipster/generator-jhipster#2604]
When I try and startup I get an error that says:
Liquibase could not start correctly, your database is NOT ready: org.postgresql.util.PSQLException: This connection has been closed.

My application.yml looks like this:
driver-class-name: org.postgresql.ds.PGSimpleDataSource
url: jdbc:postgresql://localhost:5432/test
username: postgres
password: password

I can tell the connection is sort of working, since if I change the password to something else, the connection will fail and I get an error message about a bad password, but if I change it to the correct one, the app will get farther along and fail at the error message I listed above.

Here is the stack trace:

2016-01-10 21:25:15.610  WARN 4568 --- [swap-Executor-1] com.zaxxer.hikari.proxy.ConnectionProxy  : HikariPool-0 - Connection null, created Jan 10, 21:25:15.192, last release 416ms ago, REMOVED marked as broken because of SQLSTATE(08003), ErrorCode(0)

org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:851) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at org.postgresql.jdbc42.Jdbc42Connection.getMetaData(Jdbc42Connection.java:51) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.getMetaData(HikariConnectionProxy.java) [HikariCP-2.4.1.jar:na]
	at liquibase.database.jvm.JdbcConnection.getDatabaseProductName(JdbcConnection.java:41) [liquibase-core-3.4.1.jar:na]
	at liquibase.database.core.FirebirdDatabase.isCorrectDatabaseImplementation(FirebirdDatabase.java:23) [liquibase-core-3.4.1.jar:na]
	at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:111) [liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.createDatabase(SpringLiquibase.java:474) [liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:440) [liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:389) [liquibase-core-3.4.1.jar:na]
	at com.my.app.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:63) [main/:na]
	at com.my.app.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$2(AsyncSpringLiquibase.java:49) [main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]

2016-01-10 21:25:15.614 ERROR 4568 --- [swap-Executor-1] c.e.a.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: org.postgresql.util.PSQLException: This connection has been closed.

liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: This connection has been closed.
	at liquibase.database.jvm.JdbcConnection.getDatabaseProductName(JdbcConnection.java:43) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.database.core.FirebirdDatabase.isCorrectDatabaseImplementation(FirebirdDatabase.java:23) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.database.DatabaseFactory.findCorrectDatabaseImplementation(DatabaseFactory.java:111) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.createDatabase(SpringLiquibase.java:474) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.createLiquibase(SpringLiquibase.java:440) ~[liquibase-core-3.4.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:389) ~[liquibase-core-3.4.1.jar:na]
	at com.my.app.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:63) ~[main/:na]
	at com.my.app.config.liquibase.AsyncSpringLiquibase.lambda$afterPropertiesSet$2(AsyncSpringLiquibase.java:49) ~[main/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:851) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at org.postgresql.jdbc42.Jdbc42Connection.getMetaData(Jdbc42Connection.java:51) ~[postgresql-9.4-1203-jdbc42.jar:9.4]
	at com.zaxxer.hikari.proxy.HikariConnectionProxy.getMetaData(HikariConnectionProxy.java) ~[HikariCP-2.4.1.jar:na]
	at liquibase.database.jvm.JdbcConnection.getDatabaseProductName(JdbcConnection.java:41) ~[liquibase-core-3.4.1.jar:na]
	... 10 common frames omitted

**Comment by pascalgrimaud** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines) about submitting an issue and provide some details.

Just tried and it works fine:
My docker-compose file to start a postgresql database:
```yaml
test-dev-postgresql:
  container_name: test-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/test/dev-postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_DB=test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
  ports:
    - "5432:5432"
```

My application.yml config :
```yaml
spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Grunt + BrowserSync for livereload
    datasource:
        driver-class-name: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost:5432/test
        name:
        username: postgres
        password: password
```
