### ISSUE TITLE
The Gateway should only forward the "/api" and Swagger URLs

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2954]
Currently the gateway forwards applications automatically, which is the default with Zuul.

However, for security reasons, we shouldn't forward everything, like all the "/info" URLs.

So the gateway should be reconfigured to only forward URLs to:

- "/api": where all the application's APIs are
- "/v2/api-docs": where Swagger is -> this should only work in "dev" mode, not "prod" mode (still for security reasons)

**Comment by gmarziou** [comment]
Yes and also the SecurityConfiguration of micro services applications should be largely simplified.

**Comment by PierreBesson** [comment]
Currently, micro-services don't have a SecurityConfiguration.java file as the JHipster's one was dependent on userDetailsService so it could not be kept while I was working on --skipUserManagement (recently the flag is used by default for microservices) but now I realize that it should have one, maybe by enriching the current template (_SecurityConfiguration.java)or by doing a new one (_MicroserviceSecurityConfiguration.java). However, I don't know how to do it myself.

I think maybe we should provide access to some of the microservices endpoints on the gateway (/audits, /logs, /health, etc) so that they can be monitored from the gateway's UI. I was planning to extend the gateway's Health, Config and Logs screen so that you could monitor your microservices. However they should be configured so that only the Admin user can access them.

On the matter of Zuul configuration, as far as I know it is not possible to configure it to forward only a specific endpoint of a microservice when referring to it by serviceId. For example;

This doesn't work:
```
zuul:
    routes:
        route1:
            path: /app1/api/**
            serviceId: app1/api/
```
This work:
```
zuul:
    routes:
        route2:
            path: /app2/api-docs/**
            url: http://172.17.0.1:8082/v2/api-docs
```
On a side note, it works really well to edit the zuul configuration on the config server (in gateway-prod.yml) and then when you do a POST on gateway:8080/refresh it reloads the config !
