### ISSUE TITLE
[Feature] Microservice workflow with docker

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#2988]
For microservices, we would like to be able to have a workflow that uses docker to run the registry, the gateway, microservices, databases, monitoring tools.
This could take the form of one or several docker-compose file.

What needs to be done:
- Every app should have a Dockerfile that is used to create a docker image of this app.
- The app must be composed with it's dependencies: for example a database
- All apps are composed with the registry and  additional tools (ELK, Graphite/Grafana).

What is already decided:
- Our images will be based on Alpine as having small images is important.

Interrogation:
- How to build the docker image ? Should we build the jar with Maven/Gradle (using a docker plugin) and then copy it to a container ? Should we use a separate container to build the apps from sources ? The latter way would allow to (re)build the image from docker only if the sources have been updated.

I started experimenting for some time and have managed to start everything at once using the following  setup:

**docker-compose.yml**
```
jhipster-registry:
  container_name: jhipster-registry
  build: ./jhipster-registry/
  environment:
    - "SPRING_PROFILES=dev,native"
  ports:
    - "8761:8761"
  volumes:
    - ./central-config:/central-config
gateway:
  container_name: gateway
  build: ./gateway/
  ports:
    - "8080:8080"
  links:
    - jhipster-registry:registry
app1:
  container_name: app1
  build: ./app1/
  ports:
    - "8081:8081"
  links:
    - jhipster-registry:registry
app2:
  container_name: app2
  build: ./app2/
  ports:
    - "8082:8081"
  links:
    - jhipster-registry:registry
```

**Microservice and gateway Dockerfile**
```
FROM anapsix/alpine-java
ADD target/*.war app.war
RUN bash -c 'touch /app.war'
EXPOSE 8080
VOLUME /tmp
CMD java -jar -Deureka.client.serviceUrl.defaultZone=http://registry:8761/eureka/ -Dspring.cloud.config.uri=http://registry:8761/config app.war
```

If you are already familiar with docker and are interested in this, please give your feedback and contribute ideas so that we can release a first POC. It would be nice to have this ready for the JH3 release in two weeks.
