### ISSUE TITLE
Classes that implements Serializable would be nice to have serialVersionUID

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#2992]
##### **Overview of the issue**

My application is deployed on AWS. Sometimes, not everytime, when I change a domain (using liquibase and new xml files to add changes without recreate the database) the application brokes because of the class serialVersionUID.

Is there any reason to not include in the generator the 

`private static final long serialVersionUID = 1L;`

for classes that implements Serializable?

It would help me a lot.

It is important to mention that once it happens the only one solution that I found is to recreate the database and restore my backup.

**Comment by jdubois** [comment]
With the default setup, we do not put any domain class in httpsession, and I would not recommend you to do so.
I guess you have a setup where you try to restore sessions after an app server restart? As you would then to make them managed again by Hibernate, this is also something we don't provide out of the box. We could do it, and in fact I've done this for years, but this is quite different to the kind of architecture we try to set up with JHipster.
So as far as I'm concerned: it's trivial to set up if you need it, but as I won't recommend it, I don't want to help you :-)

**Comment by marcelinobadin** [comment]
Well, I didn't change any configuration, it is as it was generated, the only thing I did was to add some new fields to certain entity and added a new xml for liquibase do the change on the database. Once I did it I got the error. Please, leave this issue open until I reproduce the error to send more info. I'm working on it.

**Comment by jdubois** [comment]
Oh sorry, this is quite different : you are not putting any entities in HTTP session?
Are you using a distributeur cache (Hazelcast...) ?
Otherwise yes you have found something strange, I'll be very interested to know what.
Are you using Beanstalk ? Can you share your exact AWS setup ?

**Comment by marcelinobadin** [comment]
That's my jhipster options:

```json
{
  "generator-jhipster": {
    "baseName": "Newton",
    "packageName": "br.com.indra.ips.newton",
    "packageFolder": "br/com/indra/ips/newton",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "useCompass": true,
    "buildTool": "maven",
    "frontendBuilder": "gulp",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "??",
    "useSass": true,
    "enableSocialSignIn": false,
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ]
  }
}
```

and my AWS configuration

```
EnvironmentConfigurationMetadata:
  DateCreated: '1452714303000'
  DateModified: '1452714303000'
SolutionStack: 64bit Amazon Linux 2015.09 v2.0.4 running Tomcat 8 Java 8
OptionSettings:
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elasticbeanstalk:container:tomcat:jvmoptions:
    Xmx: 512m
  aws:elasticbeanstalk:application:environment:
    spring.profiles.active: prod
  aws:elasticbeanstalk:application:
    Application Healthcheck URL: /info
  aws:autoscaling:trigger:
    LowerThreshold: '1'
    MeasureName: Latency
    UpperThreshold: '3'
    Unit: Seconds
  aws:rds:dbinstance:
    DBEngineVersion: 5.6.23
    DBPassword: ???
    DBAllocatedStorage: '10'
    DBInstanceClass: db.t2.small
    DBEngine: mysql
    DBUser: newton
    MultiAZDatabase: false
    DBDeletionPolicy: Snapshot
  aws:autoscaling:asg:
    MaxSize: '100'
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateType: Health
    RollingUpdateEnabled: true
  aws:elasticbeanstalk:sns:topics:
    Notification Endpoint: ips@indra.com.br
  aws:elb:policies:
    ConnectionDrainingEnabled: true
    ConnectionDrainingTimeout: '20'
  aws:elb:loadbalancer:
    CrossZone: true
  aws:elasticbeanstalk:environment:
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:healthreporting:system:
    AWSEBHealthdGroupId: ????
    SystemType: enhanced
  aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.small
    EC2KeyName: ???
    RootVolumeType: gp2
EnvironmentTier:
  Type: Standard
  Name: WebServer
Extensions:
  RDS.EBConsoleSnippet:
    Order: null
    SourceLocation: https://s3-external-1.amazonaws.com/elasticbeanstalk-env-resources-us-east-1/eb_snippets/rds/rds.json
AWSConfigurationTemplateVersion: 1.1.0.0
```
