### ISSUE TITLE
microservice app always complain missing registry

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3166]
Gateways and Microservices always complain of missing config server in logs though everything works fine
```
2016-03-15 21:13:42.818  INFO 1844 --- [           main] com.mycompany.myapp.GatewayApp           :
----------------------------------------------------------
        Config Server:  Not found or not setup for this application
----------------------------------------------------------
```

**Comment by gmarziou** [comment]
Yes I confirm this behavior

**Comment by PierreBesson** [comment]
I have done a PR to fix this issue https://github.com/jhipster/jhipster-registry/pull/23.
And it even works in docker: https://github.com/jhipster/jhipster-registry/pull/24

`docker pull jhipster/jhipster-registry` to force re-downloading of latest image. By default it gets its conf from the registry's git repo but it can be changed easily with an environment variable.

**Comment by gmarziou** [comment]
Works fine now

**Comment by deepu105** [comment]
@PierreBesson Im still seeing this with app generated using latest master. on both gateway and microservice

```
----------------------------------------------------------
Application 'gateway' is running! Access URLs:
Local: 	http://127.0.0.1:8080
External: 	http://172.18.0.3:8080
----------------------------------------------------------
2016-03-23 15:37:10.453  INFO 1 --- [           main] com.singaporeair.cmiv.GatewayApp         : 
----------------------------------------------------------
Config Server: 	Not found or not setup for this application
----------------------------------------------------------
```

**Comment by deepu105** [comment]
bt I used docker-compose sub gen to generate registry hope the image is updated with the fix

**Comment by PierreBesson** [comment]
@deepu105, do you have the last version of the registry ? This is properly dealt with on 3.0.0 as we have put a tag on the registry image.

**Comment by deepu105** [comment]
I dont understand Imusing the sub gen on master to generate the files which has this 
```
version: '2'
services:
    jhipster-registry:
        container_name: jhipster-registry
        image: jhipster/jhipster-registry
        volumes:
            - ./central-server-config:/central-config
        # By default the JHipster Registry runs with the "prod" and "native"
        # Spring profiles.
        # "native" profile means the filesystem is used to store data, see
        # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
        # environment:
            # - SPRING_PROFILES_ACTIVE=prod,native
            # - GIT_URI=https://github.com/jhipster/jhipster-registry/
            # - GIT_SEARCH_PATH=central-config
        ports:
            - 8761:8761

```

isnt this the latest?
