### ISSUE TITLE
Minification for prod skips js files in folders with a `-` on name

### ISSUE THREAD

**Issue by anoop2811** [jhipster/generator-jhipster#3636]
##### **Overview of the issue**

Production profile does not include custom controller js and image files. It works fine in the dev mode though. I added a new controller and edited the index.html to include a new ui-view. 
##### **Motivation for or Use Case** 

I expect that the behavior of the app in dev and production profile on UI would be the same

##### **JHipster Version(s)** 

version : 3.3.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "bodha",
    "packageName": "org.bodha",
    "packageFolder": "org/bodha",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn",
      "fr",
      "de",
      "hi",
      "it",
      "ko",
      "mr",
      "es",
      "tr",
      "ta"
    ]
  }
}
```
##### **Browsers and Operating System** 

Mac OSX El Capitan

##### **Reproduce the error** 

<!-- an unambiguous set of steps to reproduce the error. If you have a JavaScript error, maybe you can provide a live example with
`
 [ng:areq] Argument 'CarouselController' is not a function, got undefined
http://errors.angularjs.org/1.5.2/ng/areq?p0=CarouselController&p1=not%20aNaNunction%2C%20got%20undefined
    at http://localhost:8080/app/vendor-a239639bba.js:4:27633
    at fe (http://localhost:8080/app/vendor-a239639bba.js:5:4697)
    at de (http://localhost:8080/app/vendor-a239639bba.js:5:4816)
    at http://localhost:8080/app/vendor-a239639bba.js:6:8321
    at http://localhost:8080/app/vendor-a239639bba.js:16:6481
    at pe (http://localhost:8080/app/vendor-a239639bba.js:6:4148)
    at h (http://localhost:8080/app/vendor-a239639bba.js:5:28659)
    at s (http://localhost:8080/app/vendor-a239639bba.js:5:24919)
    at http://localhost:8080/app/vendor-a239639bba.js:5:24450
    at http://localhost:8080/app/vendor-a239639bba.js:5:27041
`

##### **Related issues** 

I think its shown up as issues in the 2.x versions but they were marked as fixed, so not sure if this is a regression or if I am doing something wrong. A similar issue is below:
http://stackoverflow.com/questions/36877425/jhipster-some-css-files-did-not-appear-in-vendor-file-made-by-gulp

##### **Suggest a Fix** 

Newbie to angular and jhipster
