### ISSUE TITLE
Unable to find host entries of linked containers in /etc/hosts of app container

### ISSUE THREAD

**Issue by kkorada** [jhipster/generator-jhipster#3639]
##### **Unable to find host entries of linked containers in /etc/hosts of app container**

after attaching to container i am unable to see host entries of linked containers in app container

##### **JHipster Version(s)** 

version 3.0.0

Note: I am running `mvn package docker:build` i.e. in dev profile as the link **mysql** is not working application is throwing errors

my app.yml file is

```
version: '2'
services:
    orchestrationengine-app:
        image: orchestrationengine
        external_links:
            - orchestrationengine-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=dev
            #- SPRING_DATASOURCE_URL=jdbc:mysql://mysql:4406/orchestrationengine?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 7123:8080
    orchestrationengine-mysql:
        extends:
            file: mysql.yml
            service: orchestrationengine-mysql
```

and mysql.yml is

```
version: '2'
services:
    orchestrationengine-mysql:
        container_name: orchestrationengine-mysql
        image: IN-PNQ-DEVOPS02:5000/mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/OrchestrationEngine/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=orchestrationengine
        ports:
            - 4406:3306
        command: mysqld --lower_case_table_names=1
```

after attaching to container

cat /etc/hosts is giving me

```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.3      37cb266dd98b
```

and `echo $MYSQL_PORT` is giving me nothing

but ping `ping mysql` is still working
