### ISSUE TITLE
Can't login with "admin" or "user" credentials after adding "ddl-auto: create-drop" to application-dev.yml

### ISSUE THREAD

**Issue by davidyarbrough** [jhipster/generator-jhipster#3652]
##### **Overview of the issue**

I added "ddl-auto: create-drop" to $APP_DIR/src/main/resources/config/application-dev.yml as shown:

```
spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    datasource:
        url: jdbc:postgresql://localhost:5432/test_db
        name:
        username: test_user
        password: test
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: com.argodata.dss.qd2.domain.util.FixedPostgreSQL82Dialect
        database: POSTGRESQL
        show_sql: true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

```

and it seems to have broken the existing users in the application. I reverted the change but I still can't login, so I guess whatever jhipster does to add the default users is only done at create time.

##### **Motivation for or Use Case** 

I want to be able to drop and recreate my test db, and log in as a user (or admin) during testing

##### **JHipster Version(s)** 

1.8.3

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.3.0",
    "baseName": "myapp",
    "packageName": "com.companyname.branch.test", 
    "packageFolder": "com/companyname/branch/test",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "", //redacted
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 

This error occurs before any entities are created

##### **Browsers and Operating System** 

OS: Ubuntu 16.04 
Browsers tested: Firefox and Google Chrome

##### **Reproduce the error** 

1. create a new jhipster project with the options listed in the .yo-rc pasted above
2. start the app and sign in as "admin" to validate that it is working
3. bring down the application
4. add "ddl-auto: create-drop" to application-dev.yml as shown above and start the application
5. attempt to log in as "admin" and get the "Failed to sign in! Please check your credentials and try again." error
6. bring down the application and revert the change to application-dev.yml and restart 
7. attempt to log in as "admin" and get the failure message again.

##### **Related issues** 

I haven't found any similar issues

##### **Suggest a Fix** 

I'm not familiar enough with Spring security to know how best to fix this. As a workaround right not I'm trying to figure out how I can get a "create user" script to run with the dev profile.
