### ISSUE TITLE
[Microservices] Zuul Forwarding Error

### ISSUE THREAD

**Issue by ghahramani** [jhipster/generator-jhipster#3771]
Hi, I always get Forwarding Error at the first time when the microservices came up and registered on jhipster-registry

Even I increase the timeout time like this

```
zuul:
    host:
        connect-timeout-millis: 30000
        socket-timeout-millis: 60000

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000
```

Note: The first call takes too long so it gets Forwarding Error because of timeout but it takes less than 30 seconds which I configured above. 

You can produce it like this: 
 - Run gateway first
 - Run one micoservice
 - Call any microservice api through gateway

Any suggestions?
