### ISSUE TITLE
Kubernetes generator - sharing my experience

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#3937]
This is less an issue and more to share my experience and bring discussions to improve Kubernetes generator.

#### ReplicationControllers instead of Deployments
kubectl component from gcloud creates your cluster. Together it brings some tools for monitoring and a dashboard with all your applications if you have deployed them as ReplicationControllers. This dashboard gives you easy access to your logs and provide a easy way to scale up or down each pod (for some people, graphic UI are better then the console).

Another cool stuff using ReplicationController is to update your application using kubectl rolling-update which gives you the ability to update your application in a new pod, once it gets updated it scales down the old one to zero pods and change the name from the new one to the old name and voillá, very low downtime.

#### Persistent Volume and Persistent Volume Claims (PV and PVC)
To persist your data you will need something like that. I will show my jhipster-elasticsearch (Jhipster Console) configuration as an example.

This is my Persistent Volume:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jhipster-elasticsearch
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: jhipster-elasticsearch
    fsType: ext4
```

This is my Persistent Volume Claim:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jhipster-elasticsearch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
```

This is my ReplicationController:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: jhipster-elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jhipster-elasticsearch
        tier: console
        role: master
    spec:
      containers:
      - name: jhipster-elasticsearch
        image: elasticsearch:2.3.3
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: jhipster-elasticsearch
        env:
          - name: JAVA_OPTS
            value: "-Des.cluster.name=console -Des.discovery.zen.ping.unicast.hosts=jhipster-elasticsearch"
      volumes:
      - name: jhipster-elasticsearch
        persistentVolumeClaim:
          claimName: jhipster-elasticsearch
```
And finally, my service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: jhipster-elasticsearch
    role: service
  name: jhipster-elasticsearch
spec:
  ports:
    - port: 9200
      name: http
      targetPort: 9200
      protocol: TCP
    - port: 9300
      name: transport
      targetPort: 9300
      protocol: TCP
  selector:
    app: jhipster-elasticsearch
````

One important thing to notice here, and this is a problem that I still didn't solve, is once you persist your data it creates more complexity scaling your application because you cannot create another pod using the same disk. There is a example that we can use to solve this [(production cluster)](https://github.com/kubernetes/kubernetes/blob/release-1.3/examples/elasticsearch/production_cluster/README.md).

And solving this, using MariaDB with cluster configuration will not be that hard [(something like this)](https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/mysql-galera).

One cool thing to use, to solve an old issue about using logstash specific configuration file is to use Secrets. I am using because I had to add some specific configuration to logstash on console. I am using it like this:

This is my secret configuration:
```yaml
apiVersion: v1
data:
  logstash.conf: |
    input {
      udp {
        port => 5000
        type => syslog
        codec => json
      }
      s3 {
        # removed for safety
      }
    }

    filter {

      if [logger_name] =~ "metrics" {
        kv {
          source => "message"
          field_split => ", "
          prefix => "metric_"
        }
        mutate {
          convert => { "metric_value" => "float" }
          convert => { "metric_count" => "integer" }
          convert => { "metric_min" => "float" }
          convert => { "metric_max" => "float" }
          convert => { "metric_mean" => "float" }
          convert => { "metric_stddev" => "float" }
          convert => { "metric_median" => "float" }
          convert => { "metric_p75" => "float" }
          convert => { "metric_p95" => "float" }
          convert => { "metric_p98" => "float" }
          convert => { "metric_p99" => "float" }
          convert => { "metric_p999" => "float" }
          convert => { "metric_mean_rate" => "float" }
          convert => { "metric_m1" => "float" }
          convert => { "metric_m5" => "float" }
          convert => { "metric_m15" => "float" }
        }
      } 
      mutate {
        add_field => { "instance_name" => "%{app_name}-%{host}:%{app_port}" }
      }
    }

    output {
      elasticsearch {
        hosts => ["jhipster-elasticsearch"]
      }
      stdout {
        codec => rubydebug
      }
    }
kind: ConfigMap
metadata:
  name: logstash-conf
  namespace: default
```

And this is my replicationcontroller:
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: jhipster-logstash
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jhipster-logstash
        tier: console
        role: master
    spec:
      containers:
      - name: jhipster-logstash
        image: logstash:2.3.2
        command: [ "logstash", "-f", "/conf/logstash.conf" ]
        volumeMounts:
        - name: config-volume
          mountPath: /conf
      volumes:
        - name: config-volume
          configMap:
            name: logstash-conf
```

I also have the service file but it is not the case to put here.

I hope with this examples I can bring some discussions and improvement to the kubernetes generator because Kubernetes is awesome!
