### ISSUE TITLE
No qualifying bean of type [org.springframework.security.oauth2.provider.token.store.JdbcTokenStore] using docker-compose

### ISSUE THREAD

**Issue by tsaqova** [jhipster/generator-jhipster#4009]
##### **Overview of the issue**

When i run application using docker-compose app.yml (default) with following config:
- fresh jhipster 3.6.1 using gradle
- monolith application
- oauth2 for authentication.
- mysql for datastore dev/prod profiles.

i get an error :
`No qualifying bean of type [org.springframework.security.oauth2.provider.token.store.JdbcTokenStore] ` inside UserService class

but if i run using gradle bootRun it just work as usual.

##### **Motivation for or Use Case**

Can''t running application inside docker.

##### **Reproduce the error**

- Install jhipster 3.6.1
- Generate entity (uml)
- Run gradle builddocker task
- Run docker-compose app.yml (default config).
ERROR

I try to create a bean with type JdbcTokenStore but the error still exist.

##### **JHipster Version(s)**

fresh 3.6.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "myapp",
    "packageName": "com.myapp.myapp",
    "packageFolder": "com/myapp/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

```
##### **Operating System**

Linux

**Comment by jdubois** [comment]
I'm not sure of what you are doing: you want to develop within Docker? Are you using our jhipster/jhipster Docker image?

**Comment by tsaqova** [comment]
i want to test running application inside docker (use case updated).
ref : [http://jhipster.github.io/docker-compose/](url)

when i just run using gradle bootRun it just work, however when i use docker image generated from jhipster which located at src/main/docker (app.yml, mysql.yml etc) it can't wire JdbcTokenStore. All configuration within db is work and liquibase migration is success.

**Comment by jdubois** [comment]
Thanks for updating your use case!

- You have quite an uncommun configuration, so maybe you hit some edge case -> I need to test this, to see if I can reproduce (not sure when I will have time)
- But there shouldn't be any differences between "bootRun" and running the app in Docker

-> could you send the whole stacktrace?

**Comment by pascalgrimaud** [comment]
Unable to reproduce
1) use the same .yo-rc.json
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "myapp",
    "packageName": "com.myapp.myapp",
    "packageFolder": "com/myapp/myapp",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "gradle",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "enableSocialSignIn": false
  }
}
```
2) I package and build docker image with: `./gradlew bootRepackage -Pprod buildDocker`
3) I launch everything with Docker: `docker-compose -f src/main/docker/app.yml up`

See the log:
```
myapp-app_1            | 2016-08-20 19:15:14.468  INFO 8 --- [           main] com.myapp.myapp.MyappApp                 : Started MyappApp in 41.632 seconds (JVM running for 43.195)
myapp-app_1            | 2016-08-20 19:15:14.471  INFO 8 --- [           main] com.myapp.myapp.MyappApp                 : 
myapp-app_1            | ----------------------------------------------------------
myapp-app_1            | 	Application 'myapp' is running! Access URLs:
myapp-app_1            | 	Local: 		http://127.0.0.1:8080
myapp-app_1            | 	External: 	http://172.18.0.3:8080
myapp-app_1            | ----------------------------------------------------------
myapp-app_1            | 2016-08-20 19:15:29.586  INFO 8 --- [nio-8080-exec-1] c.h.partition.InternalPartitionService   : [172.18.0.3]:5701 [dev] [3.6.4] Initializing cluster partition table arrangement...
```
