### ISSUE TITLE
" TypeError: Cannot read property 'length' of undefined" while doing "gulp inject"

### ISSUE THREAD

**Issue by mfhanif** [jhipster/generator-jhipster#4016]
##### **Overview of the issue**

when gulp install after creating new project shows

```
[14:27:06] Using gulpfile ~/java workspaces/jhipsterworkspace/myapp/gulpfile.js
[14:27:06] Starting 'install'...
[14:27:06] Starting 'inject:test'...
[14:27:06] 'inject:test' errored after 3.36 ms
[14:27:06] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/glob2base/index.js:9:25)
    at setToBase (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/glob2base/index.js:48:12)
    at module.exports (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/gulp/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/gulp/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.test (/home/hanif/java workspaces/jhipsterworkspace/myapp/gulp/inject.js:49:17)
    at module.exports (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/run-sequence/index.js:86:16)
    at runSequence (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/run-sequence/index.js:97:2)
    at Gulp.<anonymous> (/home/hanif/java workspaces/jhipsterworkspace/myapp/gulpfile.js:201:5)
    at module.exports (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:273:3)
[14:27:06] TypeError in plugin 'run-sequence(inject:test)'
Message:
    Cannot read property 'length' of undefined
Stack:
TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/glob2base/index.js:9:25)
    at setToBase (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/glob2base/index.js:48:12)
    at module.exports (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/gulp/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/gulp/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/gulp/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.test (/home/hanif/java workspaces/jhipsterworkspace/myapp/gulp/inject.js:49:17)
    at module.exports (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/run-sequence/index.js:86:16)
    at runSequence (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/run-sequence/index.js:97:2)
    at Gulp.<anonymous> (/home/hanif/java workspaces/jhipsterworkspace/myapp/gulpfile.js:201:5)
    at module.exports (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/hanif/java workspaces/jhipsterworkspace/myapp/node_modules/orchestrator/index.js:273:3)
[14:27:06] Finished 'install' after 7.48 ms
```

and cause application won't start, in browser shows jhipster error page

##### **Motivation for or Use Case**

clear enough

##### **Reproduce the error**

create new project with these options respectively:
monolithic
myapp
{enter}
jwt
no
sql
postgresql
h2 disk based
yes, ehcache,
yes,elasticsearch
no
no
maven
y
y
english
{enter}
gatling, cucumber, protractor

##### **JHipster Version(s)**

```
myapp@0.0.0 /home/hanif/java workspaces/jhipsterworkspace/myapp
└── generator-jhipster@3.6.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.6.1",
    "baseName": "myapp",
    "packageName": "com.klikpeta.uligeo",
    "packageFolder": "com/klikpeta/uligeo",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2278e2acef4f190a81f70245e57c66fe7f095846",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 1.9.1

node: v4.3.1

npm: 3.7.3

bower: 1.7.9

gulp:
[14:30:20] CLI version 1.2.1
[14:30:20] Local version 3.9.1

yeoman: 1.8.4
