### ISSUE TITLE
o.h.engine.jdbc.spi.SqlExceptionHelper  : HikariPool Connection is not available, request timed out after 30072ms

### ISSUE THREAD

**Issue by hugotown** [jhipster/generator-jhipster#4023]
sometimes the app gets a connection timeout, because the /api/authenticate takes a lot of time Why ??

**Comment by hugotown** [comment]
I found a workaround...

```
    datasource:
        url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: uusername
        password: upassword
        connectionTimeout: 300000 #( example wait connection 5 mins  )
        hikari:
            connectionTimeout: 300000 #( example wait connection 5 mins  )
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
```
