### ISSUE TITLE
jHipster gateway and mircoservice generated apps unable to interact on PCF Dev Platform.

### ISSUE THREAD

**Issue by chauhanr** [jhipster/generator-jhipster#4093]
**Overview of the issue**
On the Pivotal Cloud Foundry Dev (PCFDev) platform when I deploy the jhipster registry, gateway and microservices (the last two jhipster generated) the gateway cannot interact with the micro service and I get the following error: 

 OUT 2016-09-07 11:02:01.639  WARN 13 --- [nio-8080-exec-2] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
OUT 2016-09-07 11:02:01.644  WARN 13 --- [nio-8080-exec-2] o.s.web.servlet.PageNotFound             : Request method 'POST' not supported

This error occurs when the gateway app tries to get entity information from the micro service. 

When I run all the apps (registry, gateway and empms - mircoservice)  as standalone spring boot applications on the Linux box all of them work fine: 

1. jhipster registry runs properly and registers both the gateway and the microservice and reports them as "UP". 
2. gateway works properly and I can navigate the app UI to the entities sections and create entries which makes a call to the micro service using the registry and persists data to the back end. 

I think it is because the gateway and mirco service cannot properly register with the registry app I am facing the issue. 

How ever when I using the jhipster subgenerator for cloud foundry and deploy the components to the PCF environment the applications does not seem to work and gives the error mentioned earlier. 

**Next I document the steps taken to generate artifacts for cloud foundry deployment :** 

I used the jhipster sub generator to move the components to the Pivotal Cloud Foundry environment. The names given for the apps are: 

1. registry (jhipster registry) - url created on deployment -  **registry.local.pcfdev.io** 
2. gateway  - url created on deployment - **gateway.local.pcfdev.io** 
3. mircoservice (name empms)  - url created on deployment - **empms.local.pcfdev.io** 

![image](https://cloud.githubusercontent.com/assets/21304380/18310359/82be30e8-751b-11e6-9a6a-395792ea10ee.png)

as we can see that both the gateway and the microservice are recognized by the registry but are never reported with status as "UP". 

This issue suggested to me that I might have missed something on the configurations side in the application-prod-yml and bootstrap-prod.yml files and therefore I looked at other issues in this project and added the necessary configurations to the above mentioned files: 

**Registry [application-prod.yml snippet]**

```
eureka:
    env: prod
    instance:
        prefer-ip-address: false
        hostname: ${vcap.application.uris[0]}
        non-secure-port: 80
    server:
        enable-self-preservation: true
    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://admin:${security.user.password:admin}@registry.local.pcfdev.io/eureka/
```

 **gateway [application-prod.yml] snippet** 

```
eureka:
    instance:
        prefer-ip-address: false
        hostname: ${vcap.application.uris[0]}
        non-secure-port: 80
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:admin@registry.local.pcfdev.io/eureka/
```

**gateway [bootstrap-prod.yml] snippet**

```
 spring:
    cloud:
        config:
            fail-fast: true
            retry:
                initial-interval: 1000
                max-interval: 2000
                max-attempts: 100
            uri: http://admin:admin@registry.local.pcfdev.io/config/
            # name of the config server's property source (file.yml) that we want to use
            name: gateway
            profile: prod # profile(s) of the property source
            label: master # toggle to switch to a different version of the configuration as stored in git
            # it can be set to any label, branch or commit of the config source git repository
```

**empms (mirco service) [application-prod.yml] snippet** 

```
eureka:
    instance:
        prefer-ip-address: false
        hostname: ${vcap.application.uris[0]}
        non-secure-port: 80
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:admin@registry.local.pcfdev.io/eureka/
```

**empms (mirco service) [bootstrap-prod.yml] snippet** 

```
spring:
    cloud:
        config:
            fail-fast: true
            retry:
                initial-interval: 1000
                max-interval: 2000
                max-attempts: 100
            uri: http://admin:admin@registry.local.pcfdev.io/config/
            # name of the config server's property source (file.yml) that we want to use
            name: empms
            profile: prod # profile(s) of the property source
            label: master # toggle to switch to a different version of the configuration as stored in git
            # it can be set to any label, branch or commit of the config source git repository
```
I use the standard cf cli to push artifacts to the PCF dev environment with manifest.yml files generated by the jHipster sub generator. The Spring profiles activated for each app using a manifest.yml file are: 

1. Registry -   prod, cloudfoundry 
2. Gateway -  prod, cloudfoundry
3. empms - prod, cloudfoundry 

**JHipster Version(s)**

- jHipster Registry version - 2.4.0 
- jHipster verison - 3.5.1 
- PCF Dev version used - 0.18 

Gateway .yo-rc.json file : 

{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "gateway",
    "packageName": "com.comp.ms.gateway",
    "packageFolder": "com/comp/ms/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "42134793d262346da16769caf47e3f350b679469",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "enableSocialSignIn": false
  }
}

Micro service named - empms  
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "empms",
    "packageName": "com.comp.ms.service.empms",
    "packageFolder": "com/comp/ms/service/empms",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "jwtSecretKey": "53bd748b4076ce1ae4bdc57ca91d47ddde002022",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "hi"
    ],
    "clusteredHttpSession": "no",
    "websocket": "no",
    "enableSocialSignIn": false
  }
}

Kindly let me know if you need any other information or configuration that I may have used.
