### ISSUE TITLE
README instructions are out-of-date for Jenkins

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#4101]
Currently, it has the information below, with makes sense for Jenkins 1. We should change this to point to https://jhipster.github.io/setting-up-ci/. 

## Continuous Integration

To setup this project in Jenkins, use the following configuration:

* Project name: `21points`
* Source Code Management
    * Git Repository: `git@github.com:xxxx/21points.git`
    * Branches to build: `*/master`
    * Additional Behaviours: `Wipe out repository & force clone`
* Build Triggers
    * Poll SCM / Schedule: `H/5 * * * *`
* Build
    * Invoke Gradle script / Use Gradle Wrapper / Tasks: `-Pprod clean test bootRepackage`
    * Execute Shell / Command:
        ````
        ./gradlew bootRun &
        bootPid=$!
        sleep 30s
        gulp itest
        kill $bootPid
        ````
* Post-build Actions
    * Publish JUnit test result report / Test Report XMLs: `build/test-results/*.xml,build/reports/e2e/*.xml`

**Comment by mraible** [comment]
On a related note, I think it'd be good to add a `.travis.yml` file by default:

```
os:
  - linux
services:
  - docker
language: java
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install:
  - sudo /etc/init.d/postgresql stop
install:
  - java -version
  - ./gradlew --version
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - ./gradlew assemble
script:
  - ./gradlew check
  - docker-compose up -d
  - sleep 20s
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./gradlew bootRun &
  - bootPid=$!
  - sleep 120s
  - grunt itest
```

**Comment by deepu105** [comment]
we have a default travis file, with below content
```
language: node_js
node_js:
  - "4.4.3"
sudo: false
before_install: npm install -g gulp
install: npm install
before_script: gulp build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

```
