### ISSUE TITLE
Broken Link header w/Undertow

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#4158]
##### **Overview of the issue**

Some of the non-ASCII letters (such as cyrillic л) are causing an error in Angular parse-links service when I'm trying to use search.
```
Error: section could not be split on ";"
parse/<@http://localhost/app/components/util/parse-links.service.js:28:27
[...]
```
Seems like it is caused by Undertow's link header processing system. It returns a header like
```
</api/_search/somethings?page=0&size=20&query=;5=>; rel="last",</api/_search/somethings?page=0&size=20&query=;5=>; rel="first"
```
which contains a char ";" that cannot be correctly processed.

##### **Reproduce the error**

1. Generate a project with JHipster 3.7.1 and Elasticsearch. 
2. Generate any entity with a string field.
3. Create a new <entityname>.
4. Try to search "лен".

##### **JHipster Version(s)**

JHipster 3.7.0 and 3.7.1.
It's a regression. It worked without issues with embedded Tomcat in project generated by 3.6.1.

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "ecc0c4b025c3178ec4c715805099cfa68d217d1d",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "ru",
    "languages": [
      "ru",
      "en"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
Something.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160916220258",
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "something",
    "pagination": "pagination"
}

```

##### **Browsers and Operating System**

Ubuntu 16.04.1, Firefox 48.0
