### ISSUE TITLE
The entity crud back button doesn't work in a particular case

### ISSUE THREAD

**Issue by sohibegit** [jhipster/generator-jhipster#4188]
##### **Overview of the issue**

Back button doesn't work when coming from entity detail page to any related entity detail page.
##### **Reproduce the error**

Chose an entity that contains a relation after that click view (eye icon) on any record after that click on any relation it will go from entity detail page to related entity detail page after that click on back button Boom won't go back to previous state this is the issue.
##### **JHipster Version(s)**

```
golden-c@0.0.0 /home/sohibe/jhipwork/GoldenC
└── generator-jhipster@3.7.0 

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.7.0",
    "baseName": "GoldenC",
    "packageName": "tech.fikra.goldenc",
    "packageFolder": "tech/fikra/goldenc",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "removed",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
```
##### **Browsers and Operating System**

openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-3ubuntu1~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

git version 2.7.4

node: v6.5.0

npm: 3.10.3

bower: 1.7.9

gulp:
[01:14:18] CLI version 1.2.2
[01:14:18] Local version 3.9.1

yeoman: 1.8.5
##### **Browsers and Operating System**

LinuxMint 18 & Google Chrome Version 53.0.2785.116 (64-bit)
