### ISSUE TITLE
Entity tests fail in microservices due to cloud config lookup

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4202]
In short, since 3.8.0 it works again to fetch config via cloud config for microservice applications, but JHipster is trying that during tests as well, which leads to fails in CI..

## reproduce

Generate microservice using version 3.8.0 (I used gradle option) and a entity (to have some tests), and run tests. It should fail with connect exceptions

## fix

adding a bootstrap.yml to testroot with

```
spring:
    cloud:
        config:
            enabled: false
```
