### ISSUE TITLE
microservices with SpringFox 2.6.0 are broken

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#4283]
#### Reproduce the error

1. Install new Jhipster version(v3.9.0)
1. Create UAA service 
1. Copy jhipster-registry from github
1. Start jhipster-registry(success)
1. Start uaa(success)
1. Start mogile-gateway (error)

throw java.lang.IllegalStateException: No instances available for uaa

but v3.8.0 is ok

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.0",
    "baseName": "patient",
    "packageName": "com.shunneng.patient",
    "packageFolder": "com/shunneng/patient",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "9ae31c58d18f1977d515065dc0203f2e80b9d6ec",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

git version 2.9.0.windows.1

node: v6.3.1

npm: 3.10.6

bower: 1.7.9

gulp:
[17:11:47] CLI version 3.9.1

yeoman: 1.8.5

Docker version 1.12.2-rc1, build 45bed2c, experimental

docker-compose version 1.8.1, build 004ddae
