### ISSUE TITLE
CreateProcess error=206, The filename or extension is too long.

### ISSUE THREAD

**Issue by mehmet-aslan** [jhipster/generator-jhipster#4323]
##### **Overview of the issue**

Gradle `bootRun` task of generated microservice gateway applicaton fails on Windows due to the limit of [Windows’ CreateProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx) function. Classpath length of default gateway application exceeds that limit if too much framework selected.

For more info:
http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/

`gradlew --stacktrace` output:
``` text
...
:bootRun FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':bootRun'.

> A problem occurred starting process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe''
> ..
> Exception is:
> org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bootRun'.
> ..
> Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
>         ... 6 more

BUILD FAILED
```
##### **Motivation for or Use Case**

Generated microservice gateway application cannot be run on Windows.
##### **Reproduce the error**

Generate a microservice gateway application on Windows with preferences of following `.yo-rc.json` file
##### **Related issues**

`_gatling.gradle` has this issue solved #1514 
##### **Suggest a Fix**

Add `pathingJar` task to `_build.gradle` and make `bootRun` dependent to it

http://tuhrig.de/gradles-bootrun-and-windows-command-length-limit/
##### **JHipster Version(s)**

3.9.1/master
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

There is no entity, only default gateway application
##### **Browsers and Operating System**

Windows only
