### ISSUE TITLE
CLOB validation annotations are wrong

### ISSUE THREAD

**Issue by mehmet-aslan** [jhipster/generator-jhipster#4344]
##### **Overview of the issue**

`@Min` and `@Max` annotations are generated for validation of string that is generated for CLOB field.
##### **Reproduce the error**

Generate an entity with a clob field having minimum and maximum validations.
The generator will generate `@Min` and `@Max` annotations that are not work as intended.
##### **Suggest a Fix**

Change these annotations to `@Size`.
##### **JHipster Version(s)**

3.9.1/master
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "monolithic",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Foo.json

``` yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "someClob",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required",
                "min",
                "max"
            ],
            "fieldValidateRulesMin": "100",
            "fieldValidateRulesMax": "999"
        }
    ],
    "changelogDate": "20161018071522",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo",
    "pagination": "no"
}

```

**Comment by deepu105** [comment]
would you like to do a PR?

**Comment by mehmet-aslan** [comment]
I think clob type could use same validation prompts of string type.
This will change structure of json files from
```yaml
"fieldValidateRules": [
	"min",
	"max"
],
"fieldValidateRulesMin": "10",
"fieldValidateRulesMax": "99"
```
to
```yaml
"fieldValidateRules": [
	"minlength",
	"maxlength"
],
"fieldValidateRulesMinlength": "10",
"fieldValidateRulesMaxlength": "99"
```
and annotations will change to `@Size` without requiring any other change.

Is backward compatibility required for old json files while the blob option is in beta?
