### ISSUE TITLE
Docker in prod fails when using Kafka

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#4354]
##### **Overview of the issue**
Running an app through Docker in the `prod` profile fails when that app uses Kafka.  Everything seems to work fine in the `dev` and `prod` profile when only using Docker for Kafka.

The stacktrace can be found [in this gist](https://gist.github.com/ruddell/451d39f19d1503cd42ab5c20c3d63630).  With Pascal's changes, I get a different error: `Caused by: java.lang.IllegalArgumentException: Broker cannot be null` ([full stacktrace](https://gist.github.com/ruddell/30904cd8f9b58f6b941be79d10d90e1a)). 

##### **Reproduce the error**

Generate a microservice with kafka
Create the docker image for that microservice with `./mvnw package -Pprod docker:build -DskipTests`
Use `docker-compose -f src/main/docker/app.yml up -d` to start app, database, registry, Kafka, and Zookeeper
Use `docker-logs -f containerIdOrName` to see logs from the app

##### **Suggest a Fix**

I'm not sure why it fails

##### **JHipster Version(s)**

Master, v3.9.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "test",
    "packageName": "com.company.test",
    "packageFolder": "com/company/test",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "7e2c2e2512970a08d933546fb18d8f8e27756ea9",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```

##### **Browsers and Operating System**

macOS and Ubuntu 16.04

**Comment by pascalgrimaud** [comment]
Maybe some issues:
- use `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES` instead of `SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK-NODES` in `app.yml` file
- override var environment with `KAFKA_ADVERTISED_HOST_NAME: kafka` instead of letting it to `localhost` (from kafka.yml)
- maybe adding external_links `zookeeper:zookeeper`

The final app.yml should be:
```yaml
version: '2'
services:
    test-app:
        image: test
        external_links:
            - test-mysql:mysql
            - kafka:kafka
            - zookeeper:zookeeper
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
    test-mysql:
        extends:
            file: mysql.yml
            service: test-mysql

    kafka:
        extends:
            file: kafka.yml
            service: kafka
        external_links:
            - zookeeper:zookeeper
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper

    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
```

@ruddell : can you try this plz ?
