### ISSUE TITLE
Many-To-Many dto compile error

### ISSUE THREAD

**Issue by beaussart** [jhipster/generator-jhipster#4356]
##### **Overview of the issue**

When there is a Many-To-Many of an entity with himself, the mapstruct dto fail to compile. The mapper throw a `java.lang.StackOverflowError` when doing so.

##### **Motivation for or Use Case**

I need for a project to have a entity Step requiring previous Steps to be done before and I would like a dto for the rest endpoint.

##### **Reproduce the error**

Just create a entity with many-to-many with himself and with dto.
##### **Suggest a Fix**

I think the problem is comming from the mapstruct dto himself, trying to map a looping graph.
##### **JHipster Version(s)**

```
jhipster-test@0.0.0 /home/beaussan/jhipsterTest
└── generator-jhipster@3.9.1 

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

``` yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "jhipsterTest",
    "packageName": "jh.test",
    "packageFolder": "jh/test",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Step.json

``` yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "requiredSteps",
            "otherEntityName": "step",
            "relationshipType": "many-to-many",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "step"
        }
    ],
    "fields": [
        {
            "fieldName": "isDone",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20161019133829",
    "dto": "mapstruct",
    "service": "no",
    "entityTableName": "step",
    "pagination": "no"
}


```
##### **Browsers and Operating System**

Linux, Arch
