### ISSUE TITLE
Generate a custom Docker-Compose configuration without uaa

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#4395]
I create  uaa application and gateway applicaton

```bash
cd uaa
./mvnw package -Pprod docker:build
cd ../gateway
./mvnw package -Pprod docker:build
cd ../
mkdir docker-compose
cd docker-compose
yo jhipster:docker-compose
```
the output 

```bash
$ yo jhipster:docker-compose
Welcome to the JHipster Docker Compose Sub-Generator 
Files will be generated in folder:  /xxx/xxx/xx/docker-compose ### my directory

Found .yo-rc.json config file...
? Which *type* of application would you like to deploy? Microservice application


? Enter the root directory where your gateway(s) and microservices are located .
./
1 applications found at /xxx/xxx/xx  ### my directory

? Which applications do you want to include in your configuration? (Press <space
> to select)
❯◉ gateway ###only gateway 

###continue

? Do you want the JHipster Console (based on ELK) to monitor your applications? 
Yes
JHipster registry detected as the service discovery and configuration provider used by your apps
? Enter the admin password used to secure the JHipster Registry admin

Checking Docker images in applications' directories...
   create docker-compose.yml
   create jhipster-registry.yml
   create central-server-config/application.yml
   create jhipster-console.yml
   create log-conf/logstash.conf
   create log-data/.gitignore

Docker Compose configuration successfully generated!
You can launch all your infrastructure by running : docker-compose up -d

```
`docker-compose.yml`

```yml
version: '2'
services:
    gateway-app:
        image: gateway
        external_links:
            - gateway-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
        ports:
            - 8080:8080
    gateway-mysql:
        container_name: gateway-mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl

    ### without uaa-app and  uaa-mysql

    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry

    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
```

$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s) 3.9.1**

```
/xxx/xxx/xxx/docker-compose
└── (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "appsFolders": [
      "gateway"
    ],
    "directoryPath": "../",
    "useElk": true,
    "serviceDiscoveryType": "eureka",
    "adminPassword": "admin",
    "jwtSecretKey": "f0f88fb3ea822adb9d7d791e9e9584de59f6d5dd"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.7.4

node: v6.7.0

npm: 3.10.3

bower: 1.7.9

gulp:
[10:12:38] CLI version 3.9.1
[10:12:38] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.2, build bb80604

docker-compose version 1.8.1, build 878cff1
