### ISSUE TITLE
duplicate class while compiling

### ISSUE THREAD

**Issue by LaurSo** [jhipster/generator-jhipster#4427]
##### **Overview of the issue**

I get the hipster project generated, I configure my eclipse, and when I compile the project, I get the error.
I have found other post but that not help or that are not clear. Can you help

 COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /xxx/target/generated-sources/com/camaieu/fasst/service/mapper/UserMapperImpl.java:[16,8] duplicate class: com.xxx.service.mapper.UserMapperImpl
[INFO] 1 error

##### **JHipster Version(s)**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
fasst@0.0.0 D:\Dev\1 - Dev\02 - Camaieux\03 - Projet\fasst
`-- generator-jhipster@3.10.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "fasst",
    "packageName": "com.camaieu.fast",
    "packageFolder": "com/camaieu/fast",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "49cdc2357627eed6bb22985ae96a2b5b93b543b5",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "serviceDiscoveryType": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.10.1.windows.1

node: v4.6.0

npm: 3.10.8

bower: 1.7.9

gulp:
[14:39:22] CLI version 1.2.2
[14:39:22] Local version 3.9.1

yeoman: 1.8.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "fasst",
    "packageName": "com.camaieu.fast",
    "packageFolder": "com/camaieu/fast",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "49cdc2357627eed6bb22985ae96a2b5b93b543b5",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "serviceDiscoveryType": false
  }
}

##### **Browsers and Operating System**
windows xp
