### ISSUE TITLE
blank page on startup with no exceptions

### ISSUE THREAD

**Issue by krishna81m** [jhipster/generator-jhipster#4466]
* **Overview of the request**
blank page on startup on FireFox and Chrome in windows OS with no exceptions

* **Motivation for or Use Case** 
tried jhipster-sample-app as well as building a new application from generator-jhipster

* **Browsers and Operating System** 
all browsers

C:\Work\neon-workspace\jhipster-sample-app\.jhipster>yo jhipster:info

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: C:\Work\neon-workspace\jhipster-sample-app
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster-sample-application@0.0.0 C:\Work\neon-workspace\jhipster-sample-app
`-- (empty)

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "baseName": "jhipsterSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "rememberMeKey": "5c37379956bd1242f5636c8cb322c2966ad81277",
    "searchEngine": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "3.10.0",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

BankAccount.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login"
        },
        {
            "relationshipId": 2,
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "bankAccount"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "balance",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805124838",
    "dto": "no",
    "pagination": "no"
}
```

Label.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "many-to-many",
            "ownerSide": false,
            "otherEntityRelationshipName": "label"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "label",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        }
    ],
    "changelogDate": "20150805124936",
    "dto": "no",
    "pagination": "no"
}
```

Operation.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "bankAccount",
            "otherEntityName": "bankAccount",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipId": 2,
            "relationshipName": "label",
            "otherEntityName": "label",
            "relationshipType": "many-to-many",
            "otherEntityField": "label",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "date",
            "fieldType": "DateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldId": 3,
            "fieldName": "amount",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805125054",
    "dto": "no",
    "pagination": "infinite-scroll"
}
```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode, sharing)

node: v6.9.1
npm: 3.10.8
bower: 1.8.0
gulp:
[23:55:49] CLI version 3.9.1
yeoman: 1.8.5
Docker version 1.9.0, build 76d6bc9
docker-compose version: 1.5.0

Logs:
C:\Work\neon-workspace\jhipster-sample-app>mvnw
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Jhipster Sample Application 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) > test-compile @ jhipster-sample-application >>>
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ jhipster-sample-application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 12 resources
[INFO] Copying 11 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ jhipster-sample-application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 12 resources
[INFO] Copying 11 resources
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ jhipster-sample-application ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (pre-unit-tests) @ jhipster-sample-application ---
..
[INFO]
[INFO] --- maven-processor-plugin:2.2.4:process (process) @ jhipster-sample-application ---
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jhipster-sample-application ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 94 source files to C:\Work\neon-workspace\jhipster-sample-app\target\classes
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ jhipster-sample-application ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ jhipster-sample-application ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) < test-compile @ jhipster-sample-application <<<
[INFO]
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:run (default-cli) @ jhipster-sample-application ---
[INFO] Attaching agents: []

        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

:: JHipster ?  :: Running Spring Boot 1.4.1.RELEASE ::
:: http://jhipster.github.io ::

2016-11-13 23:58:14.453  INFO 10624 --- [  restartedMain] i.g.j.s.JhipsterSampleApplicationApp     : Starting JhipsterSampleApplicationApp on LT1 with PID 10624 (C:\Work\neon-workspace\jhipster-sample-app\target\classes started by prod in C:\Work\neon-workspace\jhipster-sample-app
)
2016-11-13 23:58:14.457 DEBUG 10624 --- [  restartedMain] i.g.j.s.JhipsterSampleApplicationApp     : Running with Spring Boot v1.4.1.RELEASE, Spring v
4.3.3.RELEASE
2016-11-13 23:58:14.457  INFO 10624 --- [  restartedMain] i.g.j.s.JhipsterSampleApplicationApp     : The following profiles are active: swagger,dev
2016-11-13 23:58:14.596 DEBUG 10624 --- [kground-preinit] org.jboss.logging                        : Logging Provider: org.jboss.logging.Slf4jLoggerPr
ovider found via system property
2016-11-13 23:58:18.080 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.AsyncConfiguration   : Creating Async Task Executor
2016-11-13 23:58:18.850 DEBUG 10624 --- [  restartedMain] i.g.j.s.config.MetricsConfiguration      : Registering JVM gauges
2016-11-13 23:58:18.911 DEBUG 10624 --- [  restartedMain] i.g.j.s.config.MetricsConfiguration      : Monitoring the datasource
2016-11-13 23:58:18.912 DEBUG 10624 --- [  restartedMain] i.g.j.s.config.MetricsConfiguration      : Initializing Metrics JMX reporting
2016-11-13 23:58:19.525  WARN 10624 --- [  restartedMain] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDep
loymentInfo, the default worker will be used
2016-11-13 23:58:19.526  WARN 10624 --- [  restartedMain] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDep
loymentInfo, the default pool will be used
2016-11-13 23:58:20.373  INFO 10624 --- [  restartedMain] i.g.j.sample.config.WebConfigurer        : Web application configuration, using profiles: [s
wagger, dev]
2016-11-13 23:58:20.373 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.WebConfigurer        : Initializing Metrics registries
2016-11-13 23:58:20.376 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.WebConfigurer        : Registering Metrics Filter
2016-11-13 23:58:20.377 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.WebConfigurer        : Registering Metrics Servlet
2016-11-13 23:58:20.381 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.WebConfigurer        : Initialize H2 console
2016-11-13 23:58:20.381  INFO 10624 --- [  restartedMain] i.g.j.sample.config.WebConfigurer        : Web application fully configured
2016-11-13 23:58:20.674 DEBUG 10624 --- [  restartedMain] i.g.j.s.config.DatabaseConfiguration     : Configuring Liquibase
2016-11-13 23:58:20.690  WARN 10624 --- [tion-Executor-1] i.g.j.s.c.l.AsyncSpringLiquibase         : Starting Liquibase asynchronously, your database
might not be ready at startup!
2016-11-13 23:58:22.010 DEBUG 10624 --- [tion-Executor-1] i.g.j.s.c.l.AsyncSpringLiquibase         : Started Liquibase in 1319 ms
2016-11-13 23:58:22.712  INFO 10624 --- [  restartedMain] i.g.j.s.JhipsterSampleApplicationApp     : Running with Spring profile(s) : [swagger, dev]
2016-11-13 23:58:25.771 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.CacheConfiguration   : Starting Ehcache
2016-11-13 23:58:25.775 DEBUG 10624 --- [  restartedMain] i.g.j.sample.config.CacheConfiguration   : Registering Ehcache Metrics gauges
2016-11-13 23:58:26.395 DEBUG 10624 --- [  restartedMain] i.g.j.s.c.apidoc.SwaggerConfiguration    : Starting Swagger
2016-11-13 23:58:26.408 DEBUG 10624 --- [  restartedMain] i.g.j.s.c.apidoc.SwaggerConfiguration    : Started Swagger in 13 ms
2016-11-13 23:58:32.402  INFO 10624 --- [  restartedMain] i.g.j.s.JhipsterSampleApplicationApp     : Started JhipsterSampleApplicationApp in 19.08 sec
onds (JVM running for 19.718)
2016-11-13 23:58:32.404  INFO 10624 --- [  restartedMain] i.g.j.s.JhipsterSampleApplicationApp     :
----------------------------------------------------------
        Application 'jhipsterSampleApplication' is running! Access URLs:
        Local:          http://localhost:8080
        External:       http://10.20.20.12:8080
----------------------------------------------------------
2016-11-14 00:00:00.042 DEBUG 10624 --- [pool-2-thread-1] i.g.j.sample.aop.logging.LoggingAspect   : Enter: io.github.jhipster.sample.service.UserServ
ice.removeOldPersistentTokens() with argument[s] = []
Hibernate: select persistent0_.series as series1_4_, persistent0_.ip_address as ip_addre2_4_, persistent0_.token_date as token_da3_4_, persistent0_.to
ken_value as token_va4_4_, persistent0_.user_id as user_id6_4_, persistent0_.user_agent as user_age5_4_ from jhi_persistent_token persistent0_ where p
ersistent0_.token_date<?
2016-11-14 00:00:00.368 DEBUG 10624 --- [pool-2-thread-1] i.g.j.sample.aop.logging.LoggingAspect   : Exit: io.github.jhipster.sample.service.UserServi
ce.removeOldPersistentTokens() with result = null
