### ISSUE TITLE
Entity name instead of tablename used to generate foreign keys

### ISSUE THREAD

**Issue by NilsWild** [jhipster/generator-jhipster#4475]
##### **Overview of the issue**

if you got a long entity name but shortened its tablename. the tablename in the liquibasefile is updated but the entityname is used for the foreignkeys

##### **Motivation for or Use Case**

limited foreignkeylength

##### **Reproduce the error**

generate two entities with an relationship to each othe and long name and shorten their tablenames. then regenerate your project

##### **Suggest a Fix**

use the tablename instead of entityname

##### **JHipster Version(s)**

3.10.0

**Comment by jdubois** [comment]
I couldn't reproduce your issue... Maybe it is has already been corrected??

Here is my configuration:

##### **JHipster Version(s)**

```
tmp-2@0.0.0 /Users/julien/workspace/tmp2
└── generator-jhipster@3.12.0  -> /Users/julien/workspace/generator-jhipster

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.0",
    "baseName": "tmp2",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "f4744ed8ff7477e0d52c939ae9039480c9118fa4",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "serviceDiscoveryType": false
  }
}
```


##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Bar123456789123456789.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "foo123456789123456789",
            "otherEntityName": "foo123456789123456789",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "zzz",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161206111104",
    "dto": "no",
    "service": "no",
    "entityTableName": "bar",
    "pagination": "no"
}

```

Foo123456789123456789.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "bar",
            "otherEntityName": "bar123456789123456789",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "aaa",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161206111015",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo",
    "pagination": "no"
}

```


##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.11.0

node: v6.9.1

npm: 3.10.8

bower: 1.8.0

gulp:
[14:01:40] CLI version 1.2.2
[14:01:40] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.3, build 6b644ec

docker-compose version 1.8.1, build 878cff1
