### ISSUE TITLE
JWT authentication doesn't compile

### ISSUE THREAD

**Issue by arunas-stonis** [jhipster/generator-jhipster#4536]
##### **Overview of the issue**

Project doesn't compile after generation 

##### **Reproduce the error**

Generate a new project with: yo jhipster

You will get a compilation error while running: gulp build
...
[16:00:38] Starting 'tscompile'...
src\main\webapp\app\app.ng2module.ts(81,25): error TS2304: Cannot find name 'AuthInterceptor'.
[16:00:46] TypeScript: 1 semantic error
...

##### **Suggest a Fix**

The following line should be inserted at line 37 in file _app.ng2module.ts
import {AuthInterceptor} from "./blocks/interceptor/auth.interceptor";

Also there is another bug in the same file. Attributes in 'useFactory' and 'deps' section should be listed in same order. Should change the lines at 'deps' section from:
            deps: [
                XHRBackend,
                RequestOptions,
                Injector,
                <%_ if (authenticationType === 'oauth2' || authenticationType === 'jwt' || authenticationType === 'uaa') { _%>
                LocalStorageService,
                SessionStorageService
                <%_ } if (authenticationType === 'session') { _%>
                StateStorageService
                <%_ } _%>
            ]
to:
            deps: [
                XHRBackend,
                RequestOptions,
                <%_ if (authenticationType === 'oauth2' || authenticationType === 'jwt' || authenticationType === 'uaa') { _%>
                LocalStorageService,
                SessionStorageService,
                Injector
                <%_ } if (authenticationType === 'session') { _%>
                StateStorageService,
                Injector
                <%_ } _%>
            ]

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

generator-jhipster@3.9.1 **angular-2 branch**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.9.1",
    "baseName": "myapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "8360f0ac2b3e238118a4dfe74083dc54d20ffdf4",
    "useSass": false,
    "applicationType": "monolith",
    "angularVersion": "angular2",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "sv"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.10.0.windows.1

node: v6.7.0

npm: 3.10.3

bower: 1.8.0

gulp:
[16:34:58] CLI version 1.2.2
[16:34:58] Local version 3.9.1

yeoman: 1.8.5

##### **Browsers and Operating System**

Microsoft Windows [Version 10.0.14393]

Please forgive me if I messed up. I am new to JHipster, Angular2 and JWT
