### ISSUE TITLE
Bug in _UserService - updateUser method

### ISSUE THREAD

**Issue by mhavrlent** [jhipster/generator-jhipster#4551]
##### **Overview of the issue**

I think I found a bug in the following:
file: generators/server/templates/src/main/java/package/service/_UserService.java
method: updateUser
code: 
196                 <%_ } else { // Cassandra _%>
197                 u.setAuthorities(authorities);
198                 <%_ } _%>
199                 <%_ if (databaseType == 'mongodb' || databaseType == 'cassandra') { _%>
200                 userRepository.save(u);
201                 <%_ } _%>

When the databaseType is sql like for mysql, the following two lines will be excluded from the generated code. That will prevent the record from being updated in the database.
u.setAuthorities(authorities);
userRepository.save(u);

##### **Reproduce the error**

1. generate app
mkdir myapp
cd myapp
yo jhipster

Use sql database!

2. Open user management page and hit the "activated" button to deactivate user.
3. Record in the database for that user wasn't changed. Activated is 1 instead of 0.

##### **JHipster Version(s)**

```
l4-portal@0.0.0 /home/toor/git/l4-portal
└── generator-jhipster@3.10.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.10.0",
    "baseName": "app",
    "packageName": "com.app.gw",
    "packageFolder": "com/app/gw",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "secret",
    "useSass": false,
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v6.9.1

npm: 3.10.6

bower: 1.8.0

gulp:
[21:44:11] CLI version 1.2.2
[21:44:11] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.12.3, build 6b644ec
