### ISSUE TITLE
Hazelcast for clustered http sessions: compile+tests in error

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4564]
##### **Overview of the issue**

 When using Hazelcast for clustered http sessions, there are some compile + tests in error.
 It's probably related to :
 - [Hibernate 5.2, Ehcache 3, JCache support](https://github.com/jhipster/generator-jhipster/pull/4454) -> https://github.com/jhipster/generator-jhipster/pull/4454
 - [fixed Hazelcast initialization](https://github.com/jhipster/generator-jhipster/pull/4482) -> https://github.com/jhipster/generator-jhipster/pull/4482

 ##### **Reproduce the error**

 Generate an application with all default options, except:

 ```
 ? (10/13) Which other technologies would you like to use?
  ◯ Social login (Google, Facebook, Twitter)
  ◯ Search engine using ElasticSearch
 ❯◉ Clustered HTTP sessions using Hazelcast
  ◯ WebSockets using Spring Websocket
  ◯ [BETA] Asynchronous messages using Apache Kafka
 ```

 ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

 ```yaml
 {
   "generator-jhipster": {
     "jhipsterVersion": "3.11.0",
     "baseName": "jhazsess",
     "packageName": "io.github.pascalgrimaud",
     "packageFolder": "io/github/pascalgrimaud",
     "serverPort": "8080",
     "authenticationType": "session",
     "hibernateCache": "ehcache",
     "clusteredHttpSession": "hazelcast",
     "websocket": false,
     "databaseType": "sql",
     "devDatabaseType": "h2Disk",
     "prodDatabaseType": "mysql",
     "searchEngine": false,
     "messageBroker": false,
     "buildTool": "maven",
     "enableSocialSignIn": false,
     "rememberMeKey": "3e0e7165411275a71705dd865871a721917d6d00",
     "useSass": false,
     "yarn": true,
     "applicationType": "monolith",
     "testFrameworks": [
       "gatling"
     ],
     "jhiPrefix": "jhi",
     "enableTranslation": true,
     "nativeLanguage": "en",
     "languages": [
       "en"
     ]
   }
 }
 ```

 ##### **Browsers and Operating System**

 openjdk version "1.8.0_111"
 OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
 OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

 git version 2.10.2

 node: v6.9.1

 npm: 3.10.9

 bower: 1.7.9

 gulp:
 [15:44:21] CLI version 1.2.2
 [15:44:21] Local version 3.9.1

 yeoman: 1.8.5

 Docker version 1.12.2, build bb80604

 docker-compose version 1.9.0-rc4, build 181a4e9
