### ISSUE TITLE
Broken jhipster:upgrade in 3.12.0

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#4593]
##### **Overview of the issue**

yo jhipster:upgrade fails to upgrade project. Seems like the problem is in the second stage which should update jhipster and regenerate project using its new version. In some projects it also reverts jhipster version in .yo-rc to 3.10.0.
```
Successfully regenerated app with jhipster 3.11.0
Committed with message "Generated with JHipster 3.11.0"
Checked out branch "master"
Current code recorded as generated with version 3.11.0
Updating generator-jhipster. This might take some time...
Updated generator-jhipster to version 3.12.0
Checked out branch "jhipster_upgrade"
Cleaned up directory
Regenerating app with jhipster 3.12.0...
 
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

                            http://jhipster.github.io

Welcome to the JHipster Generator v3.11.0
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /home/ashakhov/jh-test
 ______________________________________________________________________________

  JHipster update available: 3.12.0 (current: 3.11.0)
  Run npm install -g generator-jhipster to update.
 ______________________________________________________________________________

This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...
```

##### **Reproduce the error**

yo jhipster:upgrade

##### **JHipster Version(s)**
Trying to update project generated with 3.11.0 to 3.12.0.
```
jhipster@0.0.0 /home/ashakhov/jh-test
└── generator-jhipster@3.11.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.11.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e0051e23b0c3f2b739ed8aab4ccb32a87ce74969",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
##### **Browsers and Operating System**
ubuntu 14.04.5
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 1.9.1
node: v4.6.2
npm: 4.0.2
bower: 1.8.0

gulp:
[15:00:51] CLI version 1.2.2
[15:00:51] Local version 3.9.1

yeoman: 1.8.5
