### ISSUE TITLE
Broken metrics page in 3.12.0

### ISSUE THREAD

**Issue by ashakhov** [jhipster/generator-jhipster#4596]
##### **Overview of the issue**
```
Error: Could not resolve 'jhi-metrics' from state 'app'
transitionTo@http://127.0.1.1:8080/bower_components/angular-ui-router/release/angular-ui-router.js:3180:17
go@http://127.0.1.1:8080/bower_components/angular-ui-router/release/angular-ui-router.js:3108:14
clickHook/</transition<@http://127.0.1.1:8080/bower_components/angular-ui-router/release/angular-ui-router.js:4159:9
timeout/timeoutId<@http://127.0.1.1:8080/bower_components/angular/angular.js:19612:28
completeOutstandingRequest@http://127.0.1.1:8080/bower_components/angular/angular.js:5964:7
Browser/self.defer/timeoutId<@http://127.0.1.1:8080/bower_components/angular/angular.js:6243:7
```
##### **Reproduce the error**
Generate a new application, run it, login and try to open metrics page.

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/ashakhov/jh-test
└── generator-jhipster@3.12.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e0051e23b0c3f2b739ed8aab4ccb32a87ce74969",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "serviceDiscoveryType": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
ubuntu 14.04.5
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 1.9.1

node: v6.9.1

npm: 4.0.2

bower: 1.8.0

gulp:
[14:33:38] CLI version 1.2.2
[14:33:38] Local version 3.9.1

yeoman: 1.8.5
