### ISSUE TITLE
code compilation gets stuck after running gradlew

### ISSUE THREAD

**Issue by AlienWareSumant** [jhipster/generator-jhipster#4675]
I have done everything as the jhipster installation guide suggests. But when I try to run the code using gradlew, it works for sometime and then gets stuck at gulpconstantdev. No change was done in any file after running "yo jhipster" from cmd. Please find the image attached below and let me know what the resolution should be.
![jhipsterissue](https://cloud.githubusercontent.com/assets/13749340/21182336/876d98e0-c228-11e6-9dec-fbdb144de5c4.JPG)

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by kaidohallik** [comment]
I have the same issue. I have 2 workarounds:
1. if using `gradlew --info` then everything works again
2. closing current command window and opening new command window, then `gradlew` works for a while in this new command window

##### **JHipster Version(s)**

```
jhipster@0.0.0 c:\projects\jhipster-test
`-- generator-jhipster@3.12.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "65c1391bc15928034869154f58a65c34bd70e7f5",
    "useSass": true,
    "applicationType": "monolith",
    "clientFw": "angular1",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "et",
    "languages": [
      "et",
      "en"
    ]
  }
}
```


##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.0.windows.1

node: v6.9.1

npm: 3.10.9

bower: 1.8.0

gulp:
[15:40:44] CLI version 1.2.2
[15:40:44] Local version 3.9.1

yeoman: 1.8.5
