### ISSUE TITLE
gulp serve delete content of index.html

### ISSUE THREAD

**Issue by anibalardid** [jhipster/generator-jhipster#4816]
Hi, sometimes when I run `gulp serve` the content of index.html is erased/deleted and the webpage started in browser as blank.

It didn't happened allways, it happens sometimes without relation ...

I'm using this repo:
https://github.com/jhipster/jhipster-sample-app-gradle.git

This is the info of _yo jhipster:info_ : 

elcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster-gradle-sample-application@0.0.0 /var/www/gitlab/symphonica/jhipster-sample-app-gradle
└── generator-jhipster@3.12.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "baseName": "jhipsterGradleSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "gradle",
    "rememberMeKey": "e48612ba1fd46fa7089fe9f5085d8d164b53ffb2",
    "searchEngine": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "3.12.2",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

BankAccount.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login"
        },
        {
            "relationshipId": 2,
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "bankAccount"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "balance",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805124838",
    "dto": "no",
    "pagination": "no"
}
```

Label.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "many-to-many",
            "ownerSide": false,
            "otherEntityRelationshipName": "label"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "label",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        }
    ],
    "changelogDate": "20150805124936",
    "dto": "no",
    "pagination": "no"
}
```

Operation.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "bankAccount",
            "otherEntityName": "bankAccount",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipId": 2,
            "relationshipName": "label",
            "otherEntityName": "label",
            "relationshipType": "many-to-many",
            "otherEntityField": "label",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "date",
            "fieldType": "DateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldId": 3,
            "fieldName": "amount",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805125054",
    "dto": "no",
    "pagination": "infinite-scroll"
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v6.2.2

npm: 3.10.8

bower: 1.8.0

gulp:
[16:06:41] CLI version 1.2.2
[16:06:41] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.16.1

Docker version 1.12.0, build 8eab29e
