### ISSUE TITLE
Entity generator issue for one-to-one relation with User

### ISSUE THREAD

**Issue by ecukalla** [jhipster/generator-jhipster#4843]
##### **Overview of the issue**

When I create a monolitic jhipster app configured as follow:

    cat .yo-rc.json
    {
      "generator-jhipster": {
        "jhipsterVersion": "3.12.2",
        "baseName": "testapp",
        "packageName": "com.company.testapp",
        "packageFolder": "com/company/testapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "jwtSecretKey": "4c6cc7ff646df03adc18836b9c4e41438df0d162",
        "useSass": false,
        "applicationType": "monolith",
        "testFrameworks": [
          "gatling"
        ],
        "jhiPrefix": "jhi",
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": [
          "en",
          "it"
        ]
      }
    }%

and then try to add an entity Subscriber which must contain at least an one-to-one relation with entity User. (it can contain even other fields but for the purpose of this issue I'm omitting them)

    ➜  testapp cat .jhipster/Subscriber.json 
    {
        "fluentMethods": true,
        "relationships": [
            {
                "relationshipName": "user",
                "otherEntityName": "user",
                "relationshipType": "one-to-one",
                "ownerSide": true
            }
        ],
        "fields": [],
        "changelogDate": "20170110195824",
        "dto": "no",
        "service": "no",
        "entityTableName": "subscriber",
        "pagination": "no"
    }
    ➜  testapp

If I start the app `./mvnw` and go to Entities->Subscriber and try to "Create a new Subscriber" there are no User on the User drop-down section.
Attached is the screenshot of `Create a new subscriber`
<img width="1280" alt="screen shot 2017-01-10 at 21 08 28" src="https://cloud.githubusercontent.com/assets/775064/21822797/fd415880-d778-11e6-882e-ba32c75099fb.png">

##### **Reproduce the error**

Every time you create an entity for the first time with an one-to-one relation with User entity you will get this result.

##### **Related issues**

I think #3773 is the same, but it was supposed to be fix at jhipster version 3.5.0 right?

##### **Suggest a Fix**

In order to make a workaround for this I do the following which can give light to what is being wrongly generated. After generating the Subscriber entity I do my first git commit `git init . && git add . && git commit -m 'initial commit with Subscriber not working'` and then re-run the `yo jhipster:entity Subscriber`. After this the Subscriber entity works which can be shown even from git diff command:

    ➜  testapp git:(master) yo jhipster:entity Subscriber
    
    Found the .jhipster/Subscriber.json configuration file, entity can be automatically generated!
    
    
    The entity Subscriber is being updated.
    
    ? Do you want to update the entity? This will replace the existing files for this entity, all your custom code will be     overwritten Yes, re generate the entity
    WARNING! otherEntityRelationshipName is missing in .jhipster/Subscriber.json for relationship {
        "relationshipName": "user",
        "otherEntityName": "user",
        "relationshipType": "one-to-one",
        "ownerSide": true,
        "otherEntityRelationshipName": "subscriber"
    }, using subscriber as fallback
    WARNING! otherEntityField is missing in .jhipster/Subscriber.json for relationship {
        "relationshipName": "user",
        "otherEntityName": "user",
        "relationshipType": "one-to-one",
        "ownerSide": true,
        "otherEntityRelationshipName": "subscriber"
    }, using id as fallback
    identical src/main/resources/config/liquibase/changelog/20170110195824_added_entity_Subscriber.xml
    identical src/main/resources/config/liquibase/changelog/20170110195824_added_entity_constraints_Subscriber.xml
    identical src/main/resources/config/liquibase/master.xml
    identical src/main/java/com/company/testapp/domain/Subscriber.java
    identical src/main/java/com/company/testapp/repository/SubscriberRepository.java
    identical src/main/java/com/company/testapp/web/rest/SubscriberResource.java
    identical src/main/resources/ehcache.xml
     conflict src/main/webapp/app/entities/subscriber/subscribers.html
    ? Overwrite src/main/webapp/app/entities/subscriber/subscribers.html? overwrite this and all others
        force src/main/webapp/app/entities/subscriber/subscribers.html
        force src/main/webapp/app/entities/subscriber/subscriber-detail.html
        force src/main/webapp/app/entities/subscriber/subscriber-dialog.html
        force src/main/webapp/app/entities/subscriber/subscriber-delete-dialog.html
        force src/main/webapp/app/layouts/navbar/navbar.html
        force src/main/webapp/app/entities/subscriber/subscriber.state.js
        force src/main/webapp/app/entities/subscriber/subscriber.controller.js
        force src/main/webapp/app/entities/subscriber/subscriber-dialog.controller.js
        force src/main/webapp/app/entities/subscriber/subscriber-delete-dialog.controller.js
        force src/main/webapp/app/entities/subscriber/subscriber-detail.controller.js
        force src/main/webapp/app/entities/subscriber/subscriber.service.js
        force src/main/webapp/i18n/en/subscriber.json
        force src/main/webapp/i18n/en/global.json
        force src/main/webapp/i18n/it/subscriber.json
        force src/main/webapp/i18n/it/global.json
        force src/test/javascript/spec/app/entities/subscriber/subscriber-detail.controller.spec.js
        force src/test/java/com/company/testapp/web/rest/SubscriberResourceIntTest.java
        force src/test/gatling/simulations/SubscriberGatlingTest.scala
    
    Running gulp Inject to add javascript to index
    
    [21:15:23] Using gulpfile ~/testapp/gulpfile.js
    [21:15:23] Starting 'inject:app'...
    [21:15:23] gulp-inject 105 files into index.html.
    [21:15:23] Finished 'inject:app' after 228 ms
    ➜  testapp git:(master) ✗
    

and the `git diff`

    diff --git a/src/main/webapp/app/entities/subscriber/subscriber-detail.html b/src/main/webapp/app/entities/subscriber/subscriber-detail.html
    index f3ab01f..330b1e0 100644
    --- a/src/main/webapp/app/entities/subscriber/subscriber-detail.html
    +++ b/src/main/webapp/app/entities/subscriber/subscriber-detail.html
    @@ -6,7 +6,7 @@
         <dl class="dl-horizontal jh-entity-details">
             <dt><span data-translate="testappApp.subscriber.user">User</span></dt>
             <dd>
    -            {{vm.subscriber.user.undefined}}
    +            {{vm.subscriber.user.id}}
             </dd>
         </dl>
     
    diff --git a/src/main/webapp/app/entities/subscriber/subscriber-dialog.html b/src/main/webapp/app/entities/subscriber/subscriber-dialog.html
    index 6797a62..f0b3e6a 100644
    --- a/src/main/webapp/app/entities/subscriber/subscriber-dialog.html
    +++ b/src/main/webapp/app/entities/subscriber/subscriber-dialog.html
    @@ -16,7 +16,7 @@
     
             <div class="form-group">
                 <label data-translate="testappApp.subscriber.user" for="field_user">User</label>
    -            <select class="form-control" id="field_user" name="user" ng-model="vm.subscriber.user" ng-options="user as user. for user in vm.users track by user.id">
    +            <select class="form-control" id="field_user" name="user" ng-model="vm.subscriber.user" ng-options="user as user.id for user in vm.users track by user.id">
                     <option value=""></option>
                 </select>
             </div>
    diff --git a/src/main/webapp/app/entities/subscriber/subscribers.html b/src/main/webapp/app/entities/subscriber/subscribers.html
    index 822e611..5a6d7a0 100644
    --- a/src/main/webapp/app/entities/subscriber/subscribers.html
    +++ b/src/main/webapp/app/entities/subscriber/subscribers.html
    @@ -27,7 +27,7 @@
                     <tr ng-repeat="subscriber in vm.subscribers track by subscriber.id">
                         <td><a ui-sref="subscriber-detail({id:subscriber.id})">{{subscriber.id}}</a></td>
                         <td>
    -                        {{subscriber.user.undefined}}
    +                        {{subscriber.user.id}}
                         </td>
                         <td class="text-right">
                             <div class="btn-group flex-btn-group-container">
    (END)    

##### **JHipster Version(s)**

    ➜  testapp git:(master) ✗ yo jhipster:info
    Welcome to the JHipster Information Sub-Generator
    
    ##### **JHipster Version(s)**
    
    ```
    testapp@0.0.0 /Users/edmond/testapp
    └── generator-jhipster@3.12.2 
    
    ```
    
    
    ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
    
    ```yaml
    {
      "generator-jhipster": {
        "jhipsterVersion": "3.12.2",
        "baseName": "testapp",
        "packageName": "com.company.testapp",
        "packageFolder": "com/company/testapp",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "jwtSecretKey": "4c6cc7ff646df03adc18836b9c4e41438df0d162",
        "useSass": false,
        "applicationType": "monolith",
        "testFrameworks": [
          "gatling"
        ],
        "jhiPrefix": "jhi",
        "enableTranslation": true,
        "nativeLanguage": "en",
        "languages": [
          "en",
          "it"
        ]
      }
    }
    ```
    
    
    ##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
    
    Subscriber.json
    
    ```yaml
    {
        "fluentMethods": true,
        "relationships": [
            {
                "relationshipName": "user",
                "otherEntityName": "user",
                "relationshipType": "one-to-one",
                "ownerSide": true
            }
        ],
        "fields": [],
        "changelogDate": "20170110195824",
        "dto": "no",
        "service": "no",
        "entityTableName": "subscriber",
        "pagination": "no"
    }
    
    ```
    
    
    ##### **Browsers and Operating System**
    
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
    
    git version 2.10.1 (Apple Git-78)
    
    node: v6.9.4
    
    npm: 4.0.3
    
    bower: 1.8.0
    
    gulp:
    [21:19:59] CLI version 3.9.1
    [21:19:59] Local version 3.9.1
    
    yeoman: 1.8.5
    
    yarn: 0.17.10
    
    Docker version 1.12.5, build 7392c3b
    
    docker-compose version 1.9.0, build 2585387
    

I also tested in on a debian linux with:

    ➜  testapp git:(master) ✗ node -v
    v6.9.4
    ➜  testapp git:(master) ✗ npm -v
    3.10.10
    ➜  testapp git:(master) ✗ npm list generator-jhipster
    testapp@0.0.0 /home/edmond/testapp
    └── generator-jhipster@3.12.2
