### ISSUE TITLE
Cannot find module 'randexp' issue

### ISSUE THREAD

**Issue by nghib** [jhipster/generator-jhipster#4855]
#### **Overview of the issue**

yo jhipster:entity FileStore --regenerate

module.js:471
    throw err;
    ^

Error: Cannot find module 'randexp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

##### **Reproduce the error**

FileStore.json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "contentType",
            "fieldType": "String"
        },
        {
            "fieldName": "size",
            "fieldType": "String"
        },
        {
            "fieldName": "path",
            "fieldType": "String"
        },
        {
            "fieldName": "content",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20161202031626",
    "dto": "mapstruct",
    "service": "serviceClass",
    "entityTableName": "file_store",
    "pagination": "pagination"
}

##### **Suggest a Fix**

I run "yarn update" to update yarn.lock file and It works well.

It look like we need to update yarn.lock file on master branch

##### **JHipster Version(s)**

JHipster master branch - git hash: f2befef828c5703bcc5f64744cd0c1c3496ffd85

**Comment by pascalgrimaud** [comment]
Plz use yo jhipster:info
So we have your .yo-rc.json to reproduce and all version about your tools too

**Comment by nghib** [comment]
this is my .yo-rc.json

{
  "generator-jhipster": {
    "baseName": "myapp",
    "packageName": "com.rf.myapp",
    "packageFolder": "com/rf/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "73a2b4f6246112334728c77c8e215b71ae3025f2",
    "useSass": true,
    "yarn": true,
    "applicationType": "monolith",
    "clientPackageManager": "yarn",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "myapp",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "vi"
    ],
    "serviceDiscoveryType": false,
    "jhipsterVersion": "3.12.1",
    "clientFramework": "angular1"
  }
}

**Comment by gmarziou** [comment]
If Pascal asked you to paste infos from Plz yo jhipster:info, it's because it lists also your environment like nodejs version, etc... your .yo-rc.json file is not enough.

**Comment by kaidohallik** [comment]
I think `npm install` or `yarn install` should fix the problem. New module in `package.json`.

**Comment by seawenzhu** [comment]
Hi, I have the same issue:
➜  dos-server git:(dev) yo jhipster:entity factory
module.js:471
    throw err;
    ^

Error: Cannot find module 'randexp'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/seawenzhu/GitHub/generator-jhipster/generators/entity/files.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
➜  dos-server git:(dev) yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
dos@0.0.0 /Users/seawenzhu/Seawen/jhipster/dos-server
├── UNMET PEER DEPENDENCY @angular/common@2.4.1
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.1
├── UNMET PEER DEPENDENCY @angular/core@2.4.1
├── UNMET PEER DEPENDENCY @angular/forms@2.4.1
├── generator-jhipster@3.12.2  -> /Users/seawenzhu/GitHub/generator-jhipster
└── UNMET PEER DEPENDENCY webpack@2.2.0-rc.3

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
    "generator-jhipster": {
        "jhipsterVersion": "3.12.2",
        "baseName": "dos",
        "packageName": "com.yaowu.dos",
        "packageFolder": "com/yaowu/dos",
        "serverPort": "8080",
        "authenticationType": "jwt",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "searchEngine": "elasticsearch",
        "messageBroker": false,
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "jwtSecretKey": "7fa614428691c7f694b5642c4ac840b3b7b942aa",
        "useSass": true,
        "clientPackageManager": "yarn",
        "applicationType": "monolith",
        "clientFramework": "angular2",
        "testFrameworks": [
            "protractor"
        ],
        "jhiPrefix": "dos",
        "enableTranslation": true,
        "nativeLanguage": "zh-cn",
        "languages": [
            "zh-cn",
            "en"
        ]
    }
}
```


##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v6.9.1

npm: 3.10.8

bower: 1.8.0

gulp:
[15:36:10] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.18.1

➜  dos-server git:(dev)
