### ISSUE TITLE
Issue with camel case entity when doing a many to many relation

### ISSUE THREAD

**Issue by ecukalla** [jhipster/generator-jhipster#4860]
##### **Overview of the issue**

On a microservice jhipster app I add two entities `Channel(name, description)` and `ProductData(name,number)`
Than I do a many to many relation owned by ProductData. After `yo jhipster:entity` is finished and I try to start (./mvnw) the app or test (./mvnw test) or even open it on an IDE I'll get errors.

    ➜  micro git:(master) ✗ ./mvnw     
    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building Micro 0.0.1-SNAPSHOT
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] >>> spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) > test-compile @ micro >>>
    [INFO] 
    [INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ micro ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 13 resources
    [INFO] Copying 3 resources
    [INFO] 
    [INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ micro ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 13 resources
    [INFO] Copying 3 resources
    [INFO] 
    [INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ micro ---
    [INFO] 
    [INFO] --- jacoco-maven-plugin:0.7.7.201606060606:prepare-agent (pre-unit-tests) @ micro ---
    [INFO] argLine set to -javaagent:/Users/edmond/.m2/repository/org/jacoco/org.jacoco.agent/0.7.7.201606060606/org.jacoco.agent-0.7.7.201606060606-runtime.jar=destfile=/Users/edmond/Documents/micro/target/test-results/coverage/jacoco/jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ micro ---
    [INFO] Changes detected - recompiling the module!
    [INFO] Compiling 67 source files to /Users/edmond/Documents/micro/target/classes
    [INFO] -------------------------------------------------------------
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] /Users/edmond/Documents/micro/src/main/java/com/company/micro/domain/Channel.java:[82,20] cannot find symbol
      symbol:   method add(com.company.micro.domain.ProductData)
      location: variable productData of type com.company.micro.domain.ProductData
    [ERROR] /Users/edmond/Documents/micro/src/main/java/com/company/micro/domain/Channel.java:[88,20] cannot find symbol
      symbol:   method remove(com.company.micro.domain.ProductData)
      location: variable productData of type com.company.micro.domain.ProductData
    [INFO] 2 errors 
    [INFO] -------------------------------------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 5.390 s
    [INFO] Finished at: 2017-01-13T22:07:13+01:00
    [INFO] Final Memory: 56M/545M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project micro: Compilation failure: Compilation failure:
    [ERROR] /Users/edmond/Documents/micro/src/main/java/com/company/micro/domain/Channel.java:[82,20] cannot find symbol
    [ERROR] symbol:   method add(com.company.micro.domain.ProductData)
    [ERROR] location: variable productData of type com.company.micro.domain.ProductData
    [ERROR] /Users/edmond/Documents/micro/src/main/java/com/company/micro/domain/Channel.java:[88,20] cannot find symbol
    [ERROR] symbol:   method remove(com.company.micro.domain.ProductData)
    [ERROR] location: variable productData of type com.company.micro.domain.ProductData
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

##### **Reproduce the error**

You will face this issue every time you will create an entity with camel case name and do a many to many relationship.

##### **Suggest a Fix**

In my case on the Channel domain it is added

    @ManyToMany(mappedBy = "channels")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<ProductData> productData = new HashSet<>();

and for this `addProductData(ProductData productData)` & `removeProductData(ProductData productData)` with failed because of a missing `this.` on:
<img width="934" alt="screen shot 2017-01-13 at 23 23 16" src="https://cloud.githubusercontent.com/assets/775064/21947917/14a4dd6e-d9e8-11e6-9400-fa7e45cbfcf9.png">

I've noticed that when creating entities with non camel case names the variable name of the relationship will be named in plural. Fox example Channel - Product on channel the variable name will be:

    @ManyToMany(mappedBy = "channels")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Product> products = new HashSet<>();

so the issue will not be faced in non camel cases.

##### **JHipster Version(s)**

    Welcome to the JHipster Information Sub-Generator
    
    ##### **JHipster Version(s)**
    
    ```
    /Users/edmond/Documents/micro
    └── (empty)
    
    ```
    
    
    ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
    
    ```yaml
    {
      "generator-jhipster": {
        "jhipsterVersion": "3.12.2",
        "baseName": "micro",
        "packageName": "com.company.micro",
        "packageFolder": "com/company/micro",
        "serverPort": "8081",
        "authenticationType": "jwt",
        "hibernateCache": "ehcache",
        "clusteredHttpSession": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "mysql",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "jwtSecretKey": "080764b70400bbf3e1a650eb21ba5ed76f8a6317",
        "enableTranslation": false,
        "applicationType": "microservice",
        "testFrameworks": [
          "gatling"
        ],
        "jhiPrefix": "jhi",
        "skipClient": true,
        "skipUserManagement": true
      }
    }
    ```
    
    
    ##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
    
    Channel.json
    
    ```yaml
    {
        "fluentMethods": true,
        "relationships": [
            {
                "relationshipName": "productData",
                "otherEntityName": "productData",
                "relationshipType": "many-to-many",
                "ownerSide": false,
                "otherEntityRelationshipName": "channel"
            }
        ],
        "fields": [
            {
                "fieldName": "name",
                "fieldType": "String"
            },
            {
                "fieldName": "description",
                "fieldType": "String"
            }
        ],
        "changelogDate": "20170113204625",
        "dto": "no",
        "service": "no",
        "entityTableName": "channel",
        "pagination": "pagination",
        "microserviceName": "micro",
        "searchEngine": false
    }
    
    ```
    
    ProductData.json
    
    ```yaml
    {
        "fluentMethods": true,
        "relationships": [
            {
                "relationshipName": "channel",
                "otherEntityName": "channel",
                "relationshipType": "many-to-many",
                "otherEntityField": "name",
                "ownerSide": true,
                "otherEntityRelationshipName": "productData"
            }
        ],
        "fields": [
            {
                "fieldName": "name",
                "fieldType": "String"
            },
            {
                "fieldName": "number",
                "fieldType": "Integer"
            }
        ],
        "changelogDate": "20170113204539",
        "dto": "no",
        "service": "no",
        "entityTableName": "product_data",
        "pagination": "pagination",
        "microserviceName": "micro",
        "searchEngine": false
    }
    
    ```
    
    
    ##### **Browsers and Operating System**
    
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
    
    git version 2.10.1 (Apple Git-78)
    
    node: v6.9.4
    
    npm: 4.0.3
    
    bower: 1.8.0
    
    gulp:
    [23:38:06] CLI version 3.9.1
    
    yeoman: 1.8.5
    
    yarn: 0.17.10
    
    Docker version 1.12.6, build 78d1802
    
    docker-compose version 1.9.0, build 2585387
