### ISSUE TITLE
Create a property for the JHipster Registry password

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#4905]
While working on deploying microservices to Kubernetes I noticed something that we could improve.
Here :
```
eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:admin@localhost:8761/eureka/
```
This is not really good as it mixes up the secret "admin" with the configuration for the registry host. The secret should be in a separate environment variable.

This is particularly bad if we want to transmit the serviceUrl host with the config server then it should not contain the secret password.

So I would like to propose we add a new property : `jhipster.registry.password` and set it like this :

```
eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
```

Should I put this property in the jhipster lib or in the user's application properties ? 
I would prefer to put it in the jhipster lib has it is clearly a "jhipster" property even though it will be useless to some users.
