### ISSUE TITLE
OneToMany relationship not generating liquibase column

### ISSUE THREAD

**Issue by nixgadget** [jhipster/generator-jhipster#4942]
##### **Overview of the issue**
It appears that if I include a column (`subOrganization`) for the OneToMany relationship specified as in the `jdl` below however in the corresponding  generated liquibase changeset the column is missing.

```
entity OrgDetails {
    organizationId String required
    organizationName String required maxlength(512)
    organizationType OrgType required
}

entity OrgHierarchy {
    relationshipId String required
}

// One-to-One relationship definitions
relationship OneToOne {
    OrgHierarchy{parentOrganization} to OrgDetails
}

// One-to-Many relationship definitions
relationship OneToMany {
    OrgHierarchy{subOrganization} to OrgDetails
}
```

##### **Motivation for or Use Case**
Trying to establish a OneToMany relationship for one of the columns in OrgHierarchy,
```
OrgHierarchy {parentOrganization} (1) ----------------------> (1) OrgDetails
OrgHierarchy {subOrganization}  (1) ----------------------> (*) OrgDetails
```

The generated liquibase doesnt contain the column for some reason.

```
<?xml version="1.0" encoding="utf-8"?>
<databaseChangeLog
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.4.xsd
                        http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd">

    <property name="now" value="now()" dbms="mysql,h2"/>
    <property name="now" value="current_timestamp" dbms="postgresql"/>
    <property name="now" value="sysdate" dbms="oracle"/>
    <property name="now" value="GETDATE()" dbms="mssql"/>

    <property name="autoIncrement" value="true" dbms="mysql,h2,postgresql,oracle,mssql"/>

    <property name="floatType" value="float4" dbms="postgresql, h2"/>
    <property name="floatType" value="float" dbms="mysql, oracle, mssql"/>

    <!--
        Added the entity OrgHierarchy.
    -->
    <changeSet id="20170123225316-1" author="onboarding">
        <createTable tableName="org_hierarchy">
            <column name="id" type="bigint" autoIncrement="${autoIncrement}">
                <constraints primaryKey="true" nullable="false"/>
            </column>

            <column name="relationship_id" type="varchar(256)">
                <constraints nullable="false" />
            </column>

            <column name="parent_organization_id" type="bigint">
                <constraints unique="true" nullable="true" />
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

##### **Reproduce the error**
NA

##### **Related issues**
NA

##### **Suggest a Fix**
NA

##### **JHipster Version(s)**

```
onboarding@0.0.0 /Volumes/STORAGE/Projects/Test/onboarding
└── generator-jhipster@3.12.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "onboarding",
    "packageName": "com.orchestral.dsm.onboarding",
    "packageFolder": "com/orchestral/dsm/onboarding",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f8254d93b9c60283bea2efe74eef1033922e5e01",
    "useSass": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.2.2"
      }
    ],
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Metadata.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "medicaidProviderStatus",
            "fieldType": "MedicaidProviderStatus",
            "fieldValues": "ELIGIBLE,NON_ELIGIBLE"
        },
        {
            "fieldName": "certifiedEHR",
            "fieldType": "CertifiedEHR",
            "fieldValues": "CERTIFIED,NON_CERTIFIED"
        },
        {
            "fieldName": "medicaidParticipation",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "medicaidStage",
            "fieldType": "String"
        },
        {
            "fieldName": "medicaidEnrollmentDate",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20170123225317",
    "javadoc": "Metadata Entity\n\n@author kasunt",
    "entityTableName": "metadata",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

OrgDetails.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "orgTenant",
            "otherEntityName": "orgTenants",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "orgDetails"
        },
        {
            "relationshipType": "one-to-one",
            "relationshipName": "metadata",
            "otherEntityName": "metadata",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "orgDetails"
        },
        {
            "relationshipName": "orgHierarchy",
            "otherEntityName": "orgHierarchy",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "organizationId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        },
        {
            "fieldName": "organizationName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "organizationType",
            "fieldType": "OrgType",
            "fieldValues": "CONNECT,WEBMAIL,DIRECTXDR,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "smimeSupport",
            "fieldType": "SMIMESupport",
            "fieldValues": "SERVER,CLIENT,WEBMAIL,HIE_CONVERSION,RC,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "xdrSupport",
            "fieldType": "XDRSupport",
            "fieldValues": "SUPPORTED,HIE_CONVERSION,RC,NONE",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "domain",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "uri",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "sslCertificateSerialNumber",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        },
        {
            "fieldName": "mdn",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "createdDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "updatedDate",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20170123225314",
    "javadoc": "Organization Details Entity\n\n@author kasunt",
    "entityTableName": "org_details",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl"
}
```

OrgHierarchy.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "parentOrganization",
            "otherEntityName": "orgDetails",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "orgHierarchy"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "subOrganization",
            "otherEntityName": "orgDetails",
            "otherEntityRelationshipName": "orgHierarchy"
        }
    ],
    "fields": [
        {
            "fieldName": "relationshipId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        }
    ],
    "changelogDate": "20170123225316",
    "javadoc": "Organization Hierarchy Entity\n\n@author kasunt",
    "entityTableName": "org_hierarchy",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl"
}
```

OrgTenants.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "organizationId",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 256
        },
        {
            "fieldName": "organizationName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 512
        },
        {
            "fieldName": "aliasName",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 128
        }
    ],
    "changelogDate": "20170123225315",
    "javadoc": "Tenant Entity\n\n@author kasunt",
    "entityTableName": "org_tenants",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.11.0

node: v6.2.2

npm: 3.9.5

bower: 1.8.0

gulp:
[15:23:40] CLI version 3.9.1
[15:23:40] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a
