### ISSUE TITLE
jhipster entity generator not able to create relationships

### ISSUE THREAD

**Issue by bajdekm** [jhipster/generator-jhipster#4946]
I'm trying to generate simple project with few entities and relationships between them. I am not able to launch my project due to following error:

`
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-manager/2.8.1/plexus-compiler-manager-2.8.1.jar (5 KB at 2.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-api/2.8.1/plexus-compiler-api-2.8.1.jar (26 KB at 12.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-compiler-javac/2.8.1/plexus-compiler-javac-2.8.1.jar (20 KB at 8.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/mapstruct/mapstruct-processor/1.1.0.Final/mapstruct-processor-1.1.0.Final.jar
Downloaded: https://repo.maven.apache.org/maven2/org/mapstruct/mapstruct-processor/1.1.0.Final/mapstruct-processor-1.1.0.Final.jar (1502 KB at 507.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/mapstruct/mapstruct-processor/1.1.0.Final/mapstruct-processor-1.1.0.Final.pom
Downloaded: https://repo.maven.apache.org/maven2/org/mapstruct/mapstruct-processor/1.1.0.Final/mapstruct-processor-1.1.0.Final.pom (12 KB at 36.2 KB/sec)
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 94 source files to C:\Users\michal\Desktop\kompetencyjny\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/michal/Desktop/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Participant.java:[97,16] cannot find symbol
  symbol:   method setParticipant(com.mycompany.myapp.domain.Participant)
  location: variable meeting of type com.mycompany.myapp.domain.Meeting
[ERROR] /C:/Users/michal/Desktop/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Participant.java:[103,16] cannot find symbol
  symbol:   method setParticipant(<nulltype>)
  location: variable meeting of type com.mycompany.myapp.domain.Meeting
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:06 min
[INFO] Finished at: 2017-01-24T11:44:13+01:00
[INFO] Final Memory: 43M/217M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project kompetencyjny: Compilation failure: Compilation failure:
[ERROR] /C:/Users/michal/Desktop/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Participant.java:[97,16] cannot find symbol
[ERROR] symbol:   method setParticipant(com.mycompany.myapp.domain.Participant)
[ERROR] location: variable meeting of type com.mycompany.myapp.domain.Meeting
[ERROR] /C:/Users/michal/Desktop/kompetencyjny/src/main/java/com/mycompany/myapp/domain/Participant.java:[103,16] cannot find symbol
[ERROR] symbol:   method setParticipant(<nulltype>)
[ERROR] location: variable meeting of type com.mycompany.myapp.domain.Meeting
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

C:\Users\michal\Desktop\kompetencyjny>
`
I did several attempts on MacOS ElCapitan,Ubuntu 16.04 and Windows 10 home edition using yo jhipster:entity generator, and everytime I'm getting the same error. My project details:

`
##### **JHipster Version(s)**

```
kompetencyjny@0.0.0 C:\Users\michal.bajdek\Desktop\kompetencyjny
`-- generator-jhipster@3.12.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "kompetencyjny",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e4de78becf42069b2504f2a7ed91231432b54d10",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Meeting.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "date",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170124103516",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "meeting",
    "pagination": "pager"
}

```

Participant.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "meeting",
            "otherEntityName": "meeting",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "participant"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "surname",
            "fieldType": "String"
        },
        {
            "fieldName": "jakisNumber",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170124103651",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "participant",
    "pagination": "pager"
}

```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.11.0.windows.1

node: v6.9.4

npm: 4.1.1

bower: 1.8.0

gulp:
[11:51:03] CLI version 3.9.1
[11:51:03] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1
`

my jo-rc.json file:

`
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "kompetencyjny",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "e4de78becf42069b2504f2a7ed91231432b54d10",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
`
How can I generate entities with repositories and service-implementations when automatic generator does not work properly?
