### ISSUE TITLE
Error when running microservice + gateway applications without registry

### ISSUE THREAD

**Issue by SWEnthusiast** [jhipster/generator-jhipster#4952]
##### **Overview of the issue**
I am trying to run both my micro service and gateway applications without the service discovery(eureka).
1. Unable to connect to the micro service from gateway
2. Can't see the swagger documentation for micro services under Admin->API
3. Unable to access the endpoints from POSTMAN

##### **Motivation for or Use Case**
When applications doesn't need registry

##### **JHipster Version(s)**
3.12.2

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "wrpWeb",
    "packageName": "com.mycompany.wrp",
    "packageFolder": "com/mycompany/wrp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxxxxxxxxx",
    "useSass": true,
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
MY JDL
```
entity Country {
	countryCode String maxlength(2) required,
	countryName String required,
	affiliateCountryCode String maxlength(3) required
}
entity State {
	stateCode String required,
	stateName String required
}
entity Warehouse {
	warehouseId String maxlength(3) required,
	warehouseName String required,	
	addressLine1 String required,
	addressLine2 String,
	addressLine3 String, 
	city String required,
	postalCode String required,
	deliveryWarehouse Flag required,
	pickUpCenter Flag required,
	storeFlag Flag required,	
	wmsWarehouseArea WMS required, 
	wmsWarehouseId String required
}
entity CountryWarehouse {
}
entity DefaultWarehouseAssignment {
	postalCode String required,
	startDate ZonedDateTime required,
	endDate ZonedDateTime required,
	altWarehouseAllowed Flag required
}
entity SkuMaster {
	orderingItem String required,		
  	skuNumber String required,
  	skuDescription String required,
   	brandName String required,
	itemStatus Flag required,
	itemWeight Float required,
  	itemTaxCd String required,
  	vendorShipCd String required,
  	availQty Integer required
}
entity SkuWarehouse {
	availQty Integer required		
}
relationship OneToOne {
	Warehouse{state(stateCode)} to State,
	Warehouse{country(countryCode)} to Country
}
relationship ManyToMany {
	CountryWarehouse{country(countryCode)} to Country,
	CountryWarehouse{warehouse(warehouseId)} to Warehouse
}
relationship ManyToOne {
	DefaultWarehouseAssignment{warehouse(warehouseId)} to Warehouse,
	State{country(countryCode)} to Country,
	DefaultWarehouseAssignment{country(countryCode)} to Country,
	SkuMaster{country(countryCode)} to Country,
	SkuWarehouse{country(countryCode)} to Country,
	DefaultWarehouseAssignment{state(stateCode)} to State,
	SkuWarehouse{warehouse(warehouseId)} to Warehouse,
	SkuWarehouse{skuMaster(skuNumber)} to SkuMaster 			
}
enum Flag {
	Y, N
}
enum WMS {
	W, S, NONE
}
```
// Set pagination options
paginate * with pagination
//Creates DTO's and maps the fields using mapstruct generator
dto * with mapstruct
//Creates service classes, which will make the resource call the service class which will call the repository interface
service all with serviceClass
//To generate microservices for entities, will be used by the front-end application
microservice * with wrpServices
//For search by keyword
search * with elasticsearch

##### **Browsers and Operating System**

Windows 7

Thank you

**Comment by jdubois** [comment]
It cannot work without Eureka (or Consul). That's how the gateway finds the microservices.

**Comment by PierreBesson** [comment]
Well, there is actually a way to do it that might be desirable for some use cases (if you use the service discovery provided by your platform instead of Eureka or Consul) but we have not documented yet.
I helped someone make it work on Stackoverflow : 
http://stackoverflow.com/questions/40905303/integrate-eureka-with-kubernetes-issue/41000005#41000005
As I'm not using it myself I have not tried it yet but I know it should work.

**Comment by SWEnthusiast** [comment]
@PierreBesson  Thanks for providing the link but in my case I don't want to use Kubernetes discovery either. I am trying to make connections to my micro services through an API gateway but for my sandbox testing I don't have the API gateway in place so all I want is to connect directly to the end points and get the response. 

This is how my config looks. 

```
# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    gateway:
        rate-limiting: # Read the documentation in the GatewayConfiguration class before enabling.
            enabled: false
        authorized-microservices-endpoints: # Access Control Policy, if left empty for a route, all endpoints will be accessible
            app1: /api,/v2/api-docs # recommended dev configuration
    cache: # Hibernate 2nd level cache, used by CacheConfiguration
        hazelcast:
            timeToLiveSeconds: 3600
            backupCount: 1
```
