### ISSUE TITLE
Images can't be loaded with Angular2

### ISSUE THREAD

**Issue by asanzdiego** [jhipster/generator-jhipster#4989]
- [x] For bug reports run `yo jhipster:info` in your project folder and copy paste the info after the **Suggest a Fix** section or fill the below template manually.
- [ ] For feature requests, label the title with [FEATURE] and explain your use case and ideas clearly below, you can remove sections which are not relevant.
- [x] Remove sensitive info if any
- [x] Make sure the first checkbox is followed(checked) for bug reports else the issue will be closed :smiling_imp:

##### **Overview of the issue**

Images can't be loaded with Angular2

##### **Motivation for or Use Case**

With AngularJS woks fine, but  not with Angular2.

##### **Reproduce the error**

```
? (1/15) Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? (2/15) Which *Framework* would you like to use for the client? [BETA] Angular 2.x
? (3/15) What is the base name of your application? dgise
? (4/15) Would you like to install other generators from the JHipster Marketplace? No
? (5/15) What is your default Java package name? dgise
? (6/15) Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? (7/15) Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle, MSSQL)
? (8/15) Which *production* database would you like to use? MariaDB
? (9/15) Which *development* database would you like to use? H2 with in-memory persistence
? (10/15) Do you want to use Hibernate 2nd level cache? Yes, with ehcache (local cache, for a single node)
? (11/15) Would you like to use Maven or Gradle for building the backend? Maven
? (12/15) Which other technologies would you like to use? Search engine using ElasticSearch
? (13/15) Would you like to use the LibSass stylesheet preprocessor for your CSS? No
? (14/15) Would you like to enable internationalization support? Yes
? Please choose the native language of the application? Spanish
? Please choose additional languages to install English
? (15/15) Besides JUnit and Karma, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to inverse selection) No one selected.
```

Afer:

`yo jhipster:import-jdl jhipster-jdl.jh`

With jhipster-jdl.jh:

```
entity Actuacion {
	actuacionNombre String required,
    actuacionDescripcion String required
}

entity Informe {
	informeDescripcion String required,
    informeFoto ImageBlob required
}

relationship OneToMany {
	Actuacion{informe} to Informe
}

paginate Actuacion, Informe with pagination
```

##### **Related issues**

I don't know.

##### **Suggest a Fix**

I don't know how to fix buy I think is in [_entity-management-dialog.component.ts](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.ts).

##### **JHipster Version(s)**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
dgise@0.0.0 /home/adolfo/Proyectos/workspace-sts-3.7.3-e4.6/dgise
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@3.12.2  -> /home/adolfo/Proyectos/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "dgise",
    "packageName": "dgise",
    "packageFolder": "dgise",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "...",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Actuacion.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "informe",
            "otherEntityName": "informe",
            "otherEntityRelationshipName": "actuacion"
        }
    ],
    "fields": [
        {
            "fieldName": "actuacionNombre",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "actuacionDescripcion",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170127142409",
    "entityTableName": "actuacion",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}
```

Informe.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "actuacion",
            "otherEntityName": "actuacion",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "informeDescripcion",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "informeFoto",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170127142410",
    "entityTableName": "informe",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}
```

##### **Browsers and Operating System**

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v7.4.0

npm: 4.1.1

bower: 1.8.0

gulp:
[16:28:45] CLI version 3.9.1
[16:28:45] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.12.3, build 6b644ec

docker-compose version 1.7.1, build 0a9ab35
```

Commit [3ccf0b8](https://github.com/jhipster/generator-jhipster/commit/3ccf0b8ea0b4506379d6606f0e0ac868c1d6ac16)

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "dgise",
    "packageName": "dgise",
    "packageFolder": "dgise",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "...",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Actuacion.json

```
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "informe",
            "otherEntityName": "informe",
            "otherEntityRelationshipName": "actuacion"
        }
    ],
    "fields": [
        {
            "fieldName": "actuacionNombre",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "actuacionDescripcion",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170127142409",
    "entityTableName": "actuacion",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}
```

Informe.json

```
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "actuacion",
            "otherEntityName": "actuacion",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "informeDescripcion",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "informeFoto",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170127142410",
    "entityTableName": "informe",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}
```

##### **Browsers and Operating System**

Chromium Versión 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
