### ISSUE TITLE
Property '$json' does not exist on type 'JhiTrackerService' [oauth2]

### ISSUE THREAD

**Issue by aricooperman** [jhipster/generator-jhipster#5050]
##### **Overview of the issue**

When trying to generate a new Angular2 based app, after the prompts and generation/yarn kickoff, at end I get this error:

`
ERROR in [at-loader] src/main/webapp/app/shared/tracker/tracker.service.ts:41:32
`
`
    Property '$json' does not exist on type 'JhiTrackerService'.
`

##### **Motivation for or Use Case**

JHipster generation fails for (some versions at least) of Angular2

##### **Reproduce the error**

Generate with this config below

##### **Related issues**

Have not seen

##### **Suggest a Fix**

Unsure

##### **JHipster Version(s)**

3.12.2

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
b-d-manager@0.0.0 /Users/acooperman/Development/workspaces/bd-management
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@3.12.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "BizDevManager",
    "packageName": "XXXX",
    "packageFolder": "XXXX",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "bdm",
    "otherModules": [
      {
        "name": "generator-jhipster-nav-element",
        "version": "0.0.5"
      },
      {
        "name": "generator-jhipster-swagger-cli",
        "version": "2.0.5"
      },
      {
        "name": "generator-jhipster-material",
        "version": "0.0.0"
      },
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.2.2"
      },
      {
        "name": "generator-jhipster-elasticsearch-reindexer",
        "version": "0.2.0"
      },
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-angular-datatables",
        "version": "1.3.1"
      },
      {
        "name": "generator-jhipster-basic-auth",
        "version": "1.0.1"
      },
      {
        "name": "generator-jhipster-docker",
        "version": "2.2.0"
      },
      {
        "name": "generator-jhipster-swagger2markup",
        "version": "1.1.0"
      },
      {
        "name": "generator-jhipster-ci",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-spring-social-connectors",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v6.9.4

npm: 4.1.1

bower: 1.8.0

gulp:
[14:48:20] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a
