### ISSUE TITLE
Exception Social Login Without Intenationalization

### ISSUE THREAD

**Issue by paulohenriqu** [jhipster/generator-jhipster#5061]
##### **Overview of the issue**

When generating a new project using ng2 with Social Login but without Internatinalization webpack throws this error:

Property 'languageService' does not exist on type 'JhiSocialComponent'

##### **Motivation for or Use Case**

When running the yarn start tha client side of the app won't start

##### **Reproduce the error**

Generate a new project with Angular 2, Social Login and without internationalization.

##### **Suggest a Fix**

I think that the generator on the file shared/social/social.component.ts removes the LanguageService on the imports and also from the JhiSocialComponent constructor, but inside the ngOnInit reamains the line
this.languageService.addLocation('social');

##### **JHipster Version(s)**

JHipster 4.0.0

##### **JHipster Version(s)**

```
ecommerce@0.0.0 C:\Users\psiqueira\Desktop\5asec delivery
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.4
+-- UNMET PEER DEPENDENCY @angular/core@2.4.4
`-- generator-jhipster@4.0.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.0",
    "baseName": "ecommerce",
    "packageName": "com.fncit.ecommerce",
    "packageFolder": "com/fncit/ecommerce",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,  
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.9.4

npm: 3.10.5

bower: 1.7.9

gulp:
[11:43:41] CLI version 3.9.1

yeoman: 1.8.4

yarn: 0.19.1

##### **Browsers and Operating System**

Windows 10 64 bits

- [x ] Checking this box is mandatory (this is just to show you read everything)
