### ISSUE TITLE
Dismissing modal using ESC button doesn't change the router URL

### ISSUE THREAD

**Issue by sohibegit** [jhipster/generator-jhipster#5100]
##### **Overview of the issue**

dismissing almost any modal using ESC button doesn't change the router URL and this will cause a problem when trying to open the same modal.

##### **Reproduce the error**

go to any entity for example "Country" press on create new Country Button this will open a dialog modal 
now exit Using ESC Button and try to press on Create new Country again. 

##### **JHipster Version(s)**

```
hip-4-test@0.0.0 /home/sohibe/jhip4workspace/hip4Test
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.1",
    "baseName": "hip4Test",
    "packageName": "tech.fikra.hip4",
    "packageFolder": "tech/fikra/hip4",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "1340a68205749c45cb4a93b7e06690198ee82814",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Bank.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001302",
    "entityTableName": "bank",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

BankBranch.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "bank",
            "otherEntityName": "bank",
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001303",
    "entityTableName": "bank_branch",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

CalculateSalaryVM.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "chequeSeries",
            "otherEntityName": "chequeSeries",
            "otherEntityField": "chequeFrom"
        }
    ],
    "fields": [
        {
            "fieldName": "salaryDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "forcee",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20170203001312",
    "entityTableName": "calculate_salary_vm",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

CareerDegree.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "degree",
            "fieldType": "Integer"
        },
        {
            "fieldName": "basicIncome",
            "fieldType": "Double"
        },
        {
            "fieldName": "annualIncrease",
            "fieldType": "Double"
        },
        {
            "fieldName": "degreeFrom",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "degreeTo",
            "fieldType": "LocalDate"
        }
    ],
    "changelogDate": "20170203001305",
    "entityTableName": "career_degree",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

ChequeSeries.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "chequeFrom",
            "fieldType": "Long"
        },
        {
            "fieldName": "chequeTo",
            "fieldType": "Long"
        }
    ],
    "changelogDate": "20170203001313",
    "entityTableName": "cheque_series",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

DeductionAllowance.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "",
            "relationshipName": "priority",
            "otherEntityName": "deductionAllowance",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "value",
            "fieldType": "Double"
        },
        {
            "fieldName": "daFrom",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "daTo",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "generateReport",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "reportTitle",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001310",
    "entityTableName": "deduction_allowance",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

DeductionAllowanceLog.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "deductionAllowance",
            "otherEntityName": "deductionAllowance",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "empsallog",
            "otherEntityName": "empsallog",
            "otherEntityField": "salDate"
        }
    ],
    "fields": [
        {
            "fieldName": "value",
            "fieldType": "Double"
        }
    ],
    "changelogDate": "20170203001311",
    "entityTableName": "deduction_allowance_log",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Employee.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "nationality",
            "otherEntityName": "nationality",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "bankBranch",
            "otherEntityName": "bankBranch",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "careerDegree",
            "otherEntityName": "careerDegree",
            "otherEntityField": "degree"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "qualification",
            "otherEntityName": "qualification",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "specialization",
            "otherEntityName": "specialization",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "employment",
            "otherEntityName": "employment",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "careerDegreeNadeb",
            "otherEntityName": "careerDegree",
            "otherEntityField": "degree"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "momName",
            "fieldType": "String"
        },
        {
            "fieldName": "birthDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "accountNumber",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "attendDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "wivesCount",
            "fieldType": "Integer"
        },
        {
            "fieldName": "dependentChildrenCount",
            "fieldType": "Integer"
        },
        {
            "fieldName": "designationDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "familyPaperNo",
            "fieldType": "Integer"
        },
        {
            "fieldName": "nationaltyNo",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "socialSecurityNo",
            "fieldType": "String"
        },
        {
            "fieldName": "bonusCount",
            "fieldType": "Integer"
        },
        {
            "fieldName": "marital",
            "fieldType": "Marital",
            "fieldValues": "SINGLE,MARRIED,MARRIED_SONS,DIVORCED,WIDOW"
        },
        {
            "fieldName": "state",
            "fieldType": "State",
            "fieldValues": "LOCAL,TRAVELING",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "gender",
            "fieldType": "Gender",
            "fieldValues": "MALE,FEMALE"
        },
        {
            "fieldName": "active",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "bonusCountNadeb",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170203001301",
    "entityTableName": "employee",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Employment.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001309",
    "entityTableName": "employment",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Empsallog.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "employee",
            "otherEntityName": "employee",
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "basic",
            "fieldType": "Double"
        },
        {
            "fieldName": "total",
            "fieldType": "Double"
        },
        {
            "fieldName": "netSalary",
            "fieldType": "Double"
        },
        {
            "fieldName": "salDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "state",
            "fieldType": "State",
            "fieldValues": "LOCAL,TRAVELING"
        },
        {
            "fieldName": "sohTotal",
            "fieldType": "Double"
        },
        {
            "fieldName": "chequeNumber",
            "fieldType": "Long"
        }
    ],
    "changelogDate": "20170203001306",
    "entityTableName": "empsallog",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Foorooq.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "foorooqName",
            "otherEntityName": "foorooqName",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "employee",
            "otherEntityName": "employee",
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "val",
            "fieldType": "Double"
        },
        {
            "fieldName": "salDate",
            "fieldType": "LocalDate"
        }
    ],
    "changelogDate": "20170203001314",
    "entityTableName": "foorooq",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

FoorooqName.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001315",
    "entityTableName": "foorooq_name",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Nationality.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001304",
    "entityTableName": "nationality",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Qualification.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001307",
    "entityTableName": "qualification",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Specialization.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170203001308",
    "entityTableName": "specialization",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.5.0

npm: 4.1.2

bower: 1.8.0

gulp:
[00:01:37] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.12.3, build 6b644ec

Linux Mint 18.1 Cinnamon 64-bit
