### ISSUE TITLE
node version too old : 7.5.0

### ISSUE THREAD

**Issue by NilsRenaud** [jhipster/generator-jhipster#5117]
##### **Overview of the issue**

When launching JHipster ("yo jhipster" command), I get this warning : 

> WARNING! Your node version is too old (v7.5.0). You should use at least Node v6.9.0+

Although node has 2 running version, I though this is a bug.

##### **Motivation for or Use Case**

I think this is a bug because nodeJs last version is currently 7.5.0 (which I currently have).
I guess the message could disappears or be replaced by something like "Your node version is experimental, use LTS instead".

##### **Reproduce the error**

Just run yo JHipster with nodejs v7.5.0 installed.

##### **Related issues**

None.

##### **Suggest a Fix**

I guess this bug could be fixed by adding a max nodejs version or adding a behavior if the version on the computer is much higher (major digit) than the one required.

##### **JHipster Version(s)**

JHipster v4.0.1

##### **JHipster configuration**
$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
testng@0.0.0 /xxx/gateaway_ng
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.1",
    "baseName": "testng",
    "packageName": "org.testng.gateway",
    "packageFolder": "org/testng/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxx",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.10.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.3

node: v7.5.0

npm: 4.1.2

bower: 1.8.0

gulp:
[14:16:21] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.12.2, build bb80604

docker-compose version 1.7.1, build 0a9ab35

##### **Browsers and Operating System**
$ uname -a
Linux xxx 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- [x] Checking this box is mandatory (this is just to show you read everything)
