### ISSUE TITLE
prod generate war running has javascript error 

### ISSUE THREAD

**Issue by sonersivri** [jhipster/generator-jhipster#5119]
I generate war with 
./mvnw -Pprod clean package -DskipTests

~~~
in app.module.js infinite-scroll, angular-loading-bar cannot be found when running the war

Error: [$injector:modulerr] Failed to instantiate module ceptecafeApp due to:
[$injector:modulerr] Failed to instantiate module infinite-scroll due to:
[$injector:nomod] Module 'infinite-scroll' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=infinite-scroll
t/<@http://52.23.175.251/app/vendor-a935ac298f.js:4:28233
ge/</</<@http://52.23.175.251/app/vendor-a935ac298f.js:5:6380
n@http://52.23.175.251/app/vendor-a935ac298f.js:5:5853
ge/</<@http://52.23.175.251/app/vendor-a935ac298f.js:5:6165
f/<@http://52.23.175.251/app/vendor-a935ac298f.js:5:15513
r@http://52.23.175.251/app/vendor-a935ac298f.js:4:28679
f@http://52.23.175.251/app/vendor-a935ac298f.js:5:15361
f/<@http://52.23.175.251/app/vendor-a935ac298f.js:5:15530
r@http://52.23.175.251/app/vendor-a935ac298f.js:4:28679
f@http://52.23.175.251/app/vendor-a935ac298f.js:5:15361
rt@http://52.23.175.251/app/vendor-a935ac298f.js:5:17290
ie/a@http://52.23.175.251/app/vendor-a935ac298f.js:5:3923
ie@http://52.23.175.251/app/vendor-a935ac298f.js:5:4233
re@http://52.23.175.251/app/vendor-a935ac298f.js:5:3472
@http://52.23.175.251/app/vendor-a935ac298f.js:10:4045
o/</p@http://52.23.175.251/app/vendor-a935ac298f.js:2:8690
o/</f<@http://52.23.175.251/app/vendor-a935ac298f.js:2:9007

http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=infinite-scroll&p1=%5B%24injector%3Anomod%5D%20Module%20'infinite-scroll'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dinfinite-scroll%0At%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28233%0Age%2F%3C%2F%3C%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A6380%0An%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A5853%0Age%2F%3C%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A6165%0Af%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15513%0Ar%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28679%0Af%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15361%0Af%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15530%0Ar%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28679%0Af%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15361%0Art%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A17290%0Aie%2Fa%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A3923%0Aie%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A4233%0Are%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A3472%0A%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A10%3A4045%0Ao%2F%3C%2Fp%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A2%3A8690%0Ao%2F%3C%2Ff%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A2%3A9007%0A
t/<@http://52.23.175.251/app/vendor-a935ac298f.js:4:28233
f/<@http://52.23.175.251/app/vendor-a935ac298f.js:5:15789
r@http://52.23.175.251/app/vendor-a935ac298f.js:4:28679
f@http://52.23.175.251/app/vendor-a935ac298f.js:5:15361
f/<@http://52.23.175.251/app/vendor-a935ac298f.js:5:15530
r@http://52.23.175.251/app/vendor-a935ac298f.js:4:28679
f@http://52.23.175.251/app/vendor-a935ac298f.js:5:15361
rt@http://52.23.175.251/app/vendor-a935ac298f.js:5:17290
ie/a@http://52.23.175.251/app/vendor-a935ac298f.js:5:3923
ie@http://52.23.175.251/app/vendor-a935ac298f.js:5:4233
re@http://52.23.175.251/app/vendor-a935ac298f.js:5:3472
@http://52.23.175.251/app/vendor-a935ac298f.js:10:4045
o/</p@http://52.23.175.251/app/vendor-a935ac298f.js:2:8690
o/</f<@http://52.23.175.251/app/vendor-a935ac298f.js:2:9007

http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=ceptecafeApp&p1=%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20infinite-scroll%20due%20to%3A%0A%5B%24injector%3Anomod%5D%20Module%20'infinite-scroll'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3Dinfinite-scroll%0At%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28233%0Age%2F%3C%2F%3C%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A6380%0An%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A5853%0Age%2F%3C%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A6165%0Af%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15513%0Ar%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28679%0Af%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15361%0Af%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15530%0Ar%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28679%0Af%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15361%0Art%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A17290%0Aie%2Fa%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A3923%0Aie%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A4233%0Are%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A3472%0A%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A10%3A4045%0Ao%2F%3C%2Fp%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A2%3A8690%0Ao%2F%3C%2Ff%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A2%3A9007%0A%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fmodulerr%3Fp0%3Dinfinite-scroll%26p1%3D%255B%2524injector%253Anomod%255D%2520Module%2520'infinite-scroll'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.8%252F%2524injector%252Fnomod%253Fp0%253Dinfinite-scroll%250At%252F%253C%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A4%253A28233%250Age%252F%253C%252F%253C%252F%253C%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A6380%250An%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A5853%250Age%252F%253C%252F%253C%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A6165%250Af%252F%253C%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A15513%250Ar%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A4%253A28679%250Af%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A15361%250Af%252F%253C%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A15530%250Ar%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A4%253A28679%250Af%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A15361%250Art%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A17290%250Aie%252Fa%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A3923%250Aie%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A4233%250Are%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A5%253A3472%250A%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A10%253A4045%250Ao%252F%253C%252Fp%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A2%253A8690%250Ao%252F%253C%252Ff%253C%2540http%253A%252F%252F52.23.175.251%252Fapp%252Fvendor-a935ac298f.js%253A2%253A9007%250A%0At%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28233%0Af%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15789%0Ar%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28679%0Af%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15361%0Af%2F%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15530%0Ar%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A4%3A28679%0Af%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A15361%0Art%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A17290%0Aie%2Fa%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A3923%0Aie%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A4233%0Are%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A5%3A3472%0A%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A10%3A4045%0Ao%2F%3C%2Fp%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A2%3A8690%0Ao%2F%3C%2Ff%3C%40http%3A%2F%2F52.23.175.251%2Fapp%2Fvendor-a935ac298f.js%3A2%3A9007%0A
	

vendor-...298f.js (line 4, col 28233)
~~~

##### **Motivation for or Use Case**

cannot run the application

##### **Reproduce the error**

you can generate empty project and war it and run production profile

##### **Related issues**

No 

##### **Suggest a Fix**

delete the dependecy

##### **JHipster Version(s)**

4.0.1

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
ceptecafe@0.0.0 /home/jhipster/app
`-- generator-jhipster@4.0.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.1",
    "baseName": "ceptecafe",
    "packageName": "com.ceptecafe",
    "packageFolder": "com/ceptecafe",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "438bbdb14edc12a0a5edc66d23770cafd1bbf9f5",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular1",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": [
      "tr",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Beacon.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "companyResource",
            "otherEntityName": "companyResource",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "beaconId",
            "fieldType": "Long"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "beacon",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

Company.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "id",
            "ownerSide": true
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "companyResource",
            "otherEntityName": "companyResource",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 3,
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "workPhone",
            "fieldType": "String"
        },
        {
            "fieldName": "cellPhone",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "email",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "company",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

CompanyResource.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "company",
            "otherEntityName": "company",
            "otherEntityRelationshipName": "companyResource"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "beacon",
            "otherEntityName": "beacon",
            "otherEntityRelationshipName": "companyResource"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "menu",
            "otherEntityName": "menu",
            "otherEntityRelationshipName": "companyResource"
        }
    ],
    "fields": [
        {
            "fieldName": "slogan",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 3,
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "photo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "company_resource",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

CustomerFeedback.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "mobileUser",
            "otherEntityName": "mobileUser",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "beacon",
            "otherEntityName": "beacon",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "message",
            "fieldType": "String"
        },
        {
            "fieldName": "sendTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "customer_feedback",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

Menu.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "companyResource",
            "otherEntityName": "companyResource",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "value",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "menu",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

MobileUser.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "surname",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": 2,
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "cellPhone",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "email",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "birthDay",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "mobile_user",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Promotion.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "",
            "relationshipName": "mobileUser",
            "otherEntityName": "mobileUser",
            "otherEntityField": "id",
            "ownerSide": true
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "",
            "relationshipName": "beacon",
            "otherEntityName": "beacon",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "text",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "sendTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "startTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "endTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "promotion",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

PromotionFeedback.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "mobileUser",
            "otherEntityName": "mobileUser",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "beacon",
            "otherEntityName": "beacon",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "sendTime",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170205202809",
    "entityTableName": "promotion_feedback",
    "dto": "no",
    "pagination": "pager",
    "service": "serviceClass"
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.9.5

npm: 4.1.2

bower: 1.8.0

gulp:
[21:20:35] CLI version 1.2.2
[21:20:35] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.1",
    "baseName": "ceptecafe",
    "packageName": "com.ceptecafe",
    "packageFolder": "com/ceptecafe",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "438bbdb14edc12a0a5edc66d23770cafd1bbf9f5",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular1",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": [
      "tr",
      "en"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

service all with serviceClass
entity Company {
	name String required minlength(3) maxlength(50),
    workPhone String,
    cellPhone String required,
    email String required
}
entity CompanyResource {
	slogan String required minlength(3) maxlength(50),
    description String,
    photo ImageBlob
    
}
entity Beacon  {
	beaconId Long,
    description String
}

entity Menu {
	name String required,
    value BigDecimal required
}
entity MobileUser {
	name String required minlength(2) maxlength(100),
    surname String required minlength(2) maxlength(100),
    cellPhone String required,
    email String required,
    birthDay LocalDate required
}
entity CustomerFeedback {
	message String,
    sendTime ZonedDateTime required
}
entity Promotion {
	text String required,
    sendTime ZonedDateTime required,
    startTime ZonedDateTime required,
    endTime ZonedDateTime required
}
entity PromotionFeedback {
	sendTime ZonedDateTime required
}
paginate Company with pager
paginate CompanyResource with pager
paginate Beacon with pager
paginate Menu with pager
paginate CustomerFeedback with pager
paginate Promotion with pager
paginate PromotionFeedback with pager

skipClient for MobileUser

relationship OneToMany {
	CompanyResource{company} to Company{companyResource},
    CompanyResource{beacon} to Beacon{companyResource},
    CompanyResource{menu} to Menu{companyResource}
}
relationship ManyToMany {
  Company{user} to User,
  Promotion{mobileUser} to MobileUser,
  Promotion{beacon} to Beacon
}
relationship ManyToOne {
	CustomerFeedback{mobileUser} to MobileUser,
    CustomerFeedback{beacon} to Beacon,
    PromotionFeedback{mobileUser} to MobileUser,
    PromotionFeedback{beacon} to Beacon
}

##### **Browsers and Operating System**
Firefox Chrome linux

- [ X] Checking this box is mandatory (this is just to show you read everything)
