### ISSUE TITLE
JavaScript entity detail component spec test fails with Cassandra

### ISSUE THREAD

**Issue by danielsabinasz** [jhipster/generator-jhipster#5133]
##### **Overview of the issue**

When running "yarn webpack:build", it fails with the following error:

```
ERROR in [at-loader] src/test/javascript/spec/app/entities/sketch/sketch-detail.component.spec.ts:66:77 
    Argument of type '10' is not assignable to parameter of type 'string'.
```

I started out on a 4.0.0 project but then I ran "yo jhipster:upgrade" for upgrading to 4.0.2, and it comes to the point where it says "Successfully regenerated app with jhipster 4.0.2" and later "Upgraded successfully. Please now fix conflicts if any, and commit!". After that, "yo jhipster:info" still says that it is version 4.0.0. I'm not sure if this is an error.

##### **Reproduce the error**

- Generate app with Cassandra
- Generate any entity
- Run yarn webpack:build

##### **Suggest a Fix**

The test spec should be generated by passing a string as the ID, not an integer (since IDs are Strings in Cassandra).
##### **JHipster Version(s)**

```
cluefabric@0.0.0 /Users/danielsabinasz/IdeaProjects/cluefabric
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.0",
    "baseName": "Cluefabric",
    "packageName": "com.cluefabric",
    "packageFolder": "com/cluefabric",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "c964654abdd2a41eb3fc65a137febbcd218c9988",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Contact.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [],
    "changelogDate": "20170207152556",
    "dto": "no",
    "service": "no",
    "entityTableName": "contact",
    "pagination": "no"
}

```

Sketch.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        },
        {
            "fieldName": "owner",
            "fieldType": "String",
            "fieldValidateRules": []
        }
    ],
    "changelogDate": "20170207152527",
    "dto": "no",
    "service": "no",
    "entityTableName": "sketch",
    "pagination": "no"
}

```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.8.4 (Apple Git-73)

node: v6.9.2

npm: 3.10.9

bower: 1.8.0

gulp:
[22:22:03] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.12.5, build 7392c3b

docker-compose version 1.9.0, build 2585387
