### ISSUE TITLE
html elements erased in production

### ISSUE THREAD

**Issue by Steven-Garcia** [jhipster/generator-jhipster#5157]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

When uploading application to server there are elements erased from the html templates, yet when checking the war file, they are all present in the gulp generated .js files

##### **Motivation for or Use Case**

After developing several JHipster generated projects I started finding these issues with the two latter ones.  This is a huge issue as the resulting view is nothing like I need it to be

##### **Reproduce the error**

I cannot reproduce the error, as I don't understand what's producing it, for visual information (images) please visit this question in StackOverFlow: http://stackoverflow.com/questions/42116019/missing-html-elements-on-production-server

##### **Related issues**

No, I have thorougly checked most commonly used forums, google searches and here and couldn't find similar issue

##### **Suggest a Fix**

Wish I could

##### **JHipster Version(s)**

v3.12.2

##### **JHipster Version(s)**

```
nmfisurveyor-data-management-ui@0.0.0 /home/steven/dev/All-Surveyors/All-Surveyors/nmfisurveyorDataManagementUI
└── generator-jhipster@3.0.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.0.0",
    "baseName": "nmfisurveyorDataManagementUI",
    "packageName": "org.wwarn.nmfisurveyor.datamanagement",
    "packageFolder": "org/wwarn/nmfisurveyor/datamanagement",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Browsers and Operating System**

openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.7.4

node: v4.0.0

npm: 4.0.2

bower: 1.8.0

gulp:
[10:11:30] CLI version 3.9.1
[10:11:30] Local version 3.9.1

yeoman: 1.8.5

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Error is not during Entity Config

##### **Browsers and Operating System**

I am on linux mint virtual machines that the application is deployed on are also ubuntu based, error replicates in opera, firefox and chrome (those are the three browsers I've tested)

- [] Checking this box is mandatory (this is just to show you read everything)
