### ISSUE TITLE
Swagger UI does not send OAuth2 tokens

### ISSUE THREAD

**Issue by theigl** [jhipster/generator-jhipster#5158]
##### **Overview of the issue**

OAuth2 token is not sent by Swagger UI resulting in 401 responses from protected endpoints.

##### **Reproduce the error**

Generate clean new application with the configuration below, run with `./gradlew`, login as admin, open the API page and try to call any protected API endpoint.

The API responds with:

```
{
  "timestamp": "2017-02-09T17:03:03.360+0000",
  "status": 401,
  "error": "Unauthorized",
  "message": "Access Denied",
  "path": "/api/users"
}
```

##### **JHipster Version(s)**

```
webapi@0.0.0 /Volumes/beeone/gm/george-webapi
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.2",
    "baseName": "webapi",
    "packageName": "com.example.api",
    "packageFolder": "com/example/api",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.1

node: v7.5.0

npm: 4.2.0

bower: 1.8.0

gulp:
[18:05:58] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a

- [x] Checking this box is mandatory (this is just to show you read everything)
