### ISSUE TITLE
yarn lint dosent call lint at all

### ISSUE THREAD

**Issue by beaussart** [jhipster/generator-jhipster#5169]
##### **Overview of the issue**

When using the command `yarn lint` it dosen't run tslint. However, if I run it using `node_modules/tslint/bin/tslint src/main/webapp/app/**/*.ts` works

Same for lint:fix
##### **Reproduce the error**

Should be on every fresh jhipster 4 project

##### **JHipster Version(s)**

```
dashy@0.0.0 /home/beaussan/gits/dashy
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.2",
    "baseName": "dashy",
    "packageName": "io.nbe.dashy",
    "packageFolder": "io/nbe/dashy",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "XXX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.2.2"
      },
      {
        "name": "generator-jhipster-elasticsearch-reindexer",
        "version": "0.2.0"
      },
      {
        "name": "generator-jhipster-entity-audit-and-delete",
        "version": "2.2.2"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.10.2

node: v7.1.0

npm: 4.0.2

bower: 1.8.0

yeoman: 1.8.5

yarn: 0.17.8

Docker version 1.12.3, build 6b644ec

docker-compose version 1.9.0, build 2585387

**Comment by gmarziou** [comment]
Have you tried with run:  `yarn run lint` ?

**Comment by deepu105** [comment]
You need to do as Gmarzio said you cant do yarn lint it needs to be yarn run lint. Let us know after trying that

**Comment by jdubois** [comment]
I tried it very quickly and indeed the lint didn't work

Le 11 févr. 2017 4:11 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by gmarziou** [comment]
`yarn run lint` works for me on Windows, `yarn lint` does not.

~~~
> yarn run lint
yarn run v0.19.1
$ tslint src/main/webapp/app/**/*.ts --force
Done in 21.41s.
~~~

**Comment by jdubois** [comment]
Yes I have the same result, but if I write something wrong I have no warning.

**Comment by pascalgrimaud** [comment]
strange, I have both working:

```shell
$ yarn lint
yarn lint v0.19.1
$ tslint src/main/webapp/app/**/*.ts --force 
Done in 1.97s.
```

```shell
$ yarn run lint
yarn run v0.19.1
$ tslint src/main/webapp/app/**/*.ts --force 
Done in 1.94s.
```

```shell
$ yarn something
yarn something v0.19.1
error Command "something" not found.
```

**Comment by jdubois** [comment]
The issue for me is that when you write something wrong, there is no warning. Try using a "test" instead of 'test'.

**Comment by pascalgrimaud** [comment]
same as you, @jdubois 

The warning is displayed during `yarn run webpack:build` but not with `yarn lint` :
```shell
WARNING in ./src/main/webapp/app/app.main.ts
[7, 12]: " should be '
[8, 12]: " should be '

Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 1.21 kB {0} [built]
Done in 23.63s.
╭─pgrimaud@xps  ~/projects/pascalgrimaud/test-4  ‹master*› 
╰─$ yarn lint
yarn lint v0.19.1
$ tslint src/main/webapp/app/**/*.ts --force 
Done in 1.98s.
```

**Comment by jdubois** [comment]
Yes exactly :-)
Now I understand why we had so many lint issues!

**Comment by gmarziou** [comment]
On Windows, it works as expetced:

~~~
>yarn run lint
yarn run v0.19.1
$ tslint src/main/webapp/app/**/*.ts --force

src/main/webapp/app/app.main.ts[7, 12]: " should be '
Done in 19.66s.

>yarn lint
yarn lint v0.19.1
$ tslint src/main/webapp/app/**/*.ts --force

src/main/webapp/app/app.main.ts[7, 12]: " should be '
Done in 18.15s.
~~~

**Comment by ruddell** [comment]
I think the glob in the path (`src/main/webapp/app/**/*.ts`) expands differently based on your CLI.  

It looks like the shared folder isn't being linted for me.  If I add `"` instead of `'` in a component, I don't see any issues until I add quotes around the lint path.  After adding quotes, I see lint issues from more files (html?) in deeper folders - notice the time difference too:

Without quotes:
```
$ tslint src/main/webapp/app/**/*.ts --force 
✨  Done in 1.38s.
```
With quotes:
```
$ tslint "src/main/webapp/app/**/*.ts" --force 
src/main/webapp/app/shared/login/login.component.ts[83, 31]: " should be '   #I ADDED THIS ERROR
src/main/webapp/app/shared/login/login.component.html[2, 89]: You can bind only to public class members.
✨  Done in 6.61s.
```

Related to https://github.com/palantir/tslint/issues/1091

**Comment by pascalgrimaud** [comment]
@ruddell : your suggestion works for me. I modify my `package.json` by adding simple quote with:

```yaml
  "scripts": {
    "lint": "tslint 'src/main/webapp/app/**/*.ts' --force",
    "lint:fix": "tslint 'src/main/webapp/app/**/*.ts' --fix --force",
```

I'm on Linux Ubuntu 16.10. Is this solution working for Mac and Windows?
