### ISSUE TITLE
Duplicate field in entity ending with an 's' and relation with itself

### ISSUE THREAD

**Issue by iclavijos** [jhipster/generator-jhipster#5175]
##### **Overview of the issue**

When 'yarn start' is executed and the TypeScript files are compiled, I'm getting a compilation error due to a duplicate filed in the generated entity-dialog.component.ts

The entity name is Chassis and it has a relation with itself and the problem has been detected both when creating the entity with the command line tool and when importing a .jdl file.

When the TypeScript files are generated, the relationship with itself uses the plural of the entity name. As the plural of chassis is also chassis, two attributes with the same name are generated, so that .ts file does not compile

##### **Motivation for or Use Case**

As I'm modelling an application for storing racing cars information, I need to be able to keep track of some components of each car and their evolutions, so some entities have a one to many relationship with themselves. When the entity name does not end with an 's', everything works really fine.

##### **Reproduce the error**

When yarn start is executed, this output can be found in the console:

``` 
ERROR in [at-loader] src\main\webapp\app\entities\chassis\chassis-dialog.component.ts:21:5
    Duplicate identifier 'chassis'.

ERROR in [at-loader] src\main\webapp\app\entities\chassis\chassis-dialog.component.ts:21:5
    Subsequent variable declarations must have the same type.  Variable 'chassis' must be of type 'Chassis', but here has type 'Chassis[]'.
```
And this is the relevant part of chassis-dialog.component.ts

``` 
export class ChassisDialogComponent implements OnInit {

    chassis: Chassis;
    authorities: any[];
    isSaving: boolean;

    chassis: Chassis[];
    constructor(
        public activeModal: NgbActiveModal,
        private alertService: AlertService,
        private chassisService: ChassisService,
        private eventManager: EventManager
    ) {
    }
```
##### **Related issues**

Plenty of issues regarding the generation of plurals, but none like this one.

##### **Suggest a Fix**

Maybe, rather than the pluralized entity name, the name of the relationship should be used

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator                                                        
                                                                                                         
##### **JHipster Version(s)**                                                                            
                                                                                                         
```                                                                                                      
bug-report@0.0.0 C:\Desarrollo\Codigo\bugReport                                                          
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.4                                                        
+-- UNMET PEER DEPENDENCY @angular/core@2.4.4                                                            
`-- generator-jhipster@4.0.2                                                                             
                                                                                                         
```                                                                                                      
                                                                                                         
                                                                                                         
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**                      
                                                                                                         
```yaml                                                                                                  
{                                                                                                        
  "generator-jhipster": {                                                                                
    "jhipsterVersion": "4.0.2",                                                                          
    "baseName": "bugReport",                                                                             
    "packageName": "com.icesoft.msdb",                                                                   
    "packageFolder": "com/icesoft/msdb",                                                                 
    "serverPort": "8080",                                                                                
    "authenticationType": "jwt",                                                                         
    "hibernateCache": "ehcache",                                                                         
    "clusteredHttpSession": false,                                                                       
    "websocket": false,                                                                                  
    "databaseType": "sql",                                                                               
    "devDatabaseType": "h2Disk",                                                                         
    "prodDatabaseType": "mysql",                                                                         
    "searchEngine": false,                                                                               
    "messageBroker": false,                                                                              
    "buildTool": "gradle",                                                                               
    "enableSocialSignIn": false,                                                                         
    "jwtSecretKey": "",                                          
    "useSass": false,                                                                                    
    "clientPackageManager": "yarn",                                                                      
    "applicationType": "monolith",                                                                       
    "clientFramework": "angular2",                                                                       
    "testFrameworks": [],                                                                                
    "jhiPrefix": "jhi",                                                                                  
    "enableTranslation": false                                                                           
  }                                                                                                      
}                                                                                                        
```                                                                                                      
                                                                                                         
                                                                                                         
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**         
                                                                                                         
Chassis.json                                                                                             
                                                                                                         
```yaml                                                                                                  
{                                                                                                        
    "fluentMethods": true,                                                                               
    "relationships": [                                                                                   
        {                                                                                                
            "relationshipName": "evolutions",                                                            
            "otherEntityName": "chassis",                                                                
            "relationshipType": "one-to-many",                                                           
            "otherEntityRelationshipName": "derivedFrom"                                                 
        }                                                                                                
    ],                                                                                                   
    "fields": [                                                                                          
        {                                                                                                
            "fieldName": "name",                                                                         
            "fieldType": "String",                                                                       
            "fieldValidateRules": [                                                                      
                "required",                                                                              
                "maxlength"                                                                              
            ],                                                                                           
            "fieldValidateRulesMaxlength": "50"                                                          
        },                                                                                               
        {                                                                                                
            "fieldName": "manufacturer",                                                                 
            "fieldType": "String",                                                                       
            "fieldValidateRules": [                                                                      
                "required",                                                                              
                "maxlength"                                                                              
            ],                                                                                           
            "fieldValidateRulesMaxlength": "100"                                                         
        },                                                                                               
        {                                                                                                
            "fieldName": "yearFirstUse",                                                                 
            "fieldType": "Integer",                                                                      
            "fieldValidateRules": [                                                                      
                "required"                                                                               
            ]                                                                                            
        }                                                                                                
    ],                                                                                                   
    "changelogDate": "20170212111631",                                                                   
    "dto": "no",                                                                                         
    "service": "no",                                                                                     
    "entityTableName": "chassis",                                                                        
    "pagination": "pagination"                                                                           
}                                                                                                        
                                                                                                         
```                                                                                                      
                                                                                                         
                                                                                                         
##### **Browsers and Operating System**                                                                  
                                                                                                         
java version "1.8.0_111"                                                                                 
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)                                                    
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)                                         
                                                                                                         
git version 2.11.0.windows.3                                                                             
                                                                                                         
node: v7.5.0                                                                                             
                                                                                                         
npm: 4.1.2                                                                                               
                                                                                                         
yeoman: 1.8.5                                                                                            
                                                                                                         
yarn: 0.19.1                                                                                             


- [X] Checking this box is mandatory (this is just to show you read everything)
