### ISSUE TITLE
Angular 2 Internet Explorer problem

### ISSUE THREAD

**Issue by serkaneren78** [jhipster/generator-jhipster#5186]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**
Angular 2 monolithic application home page is not loading , getting error for IE 10-11.. There is no problem in chrome, edge and firefox.. 

IE 10 
------
SCRIPT5009: 'Map' is undefined
vendor.dll.js (45115,9)

IE 11
-----
SCRIPT5007: Unable to get property 'apply' of undefined or null reference
vendor.dll.js (54101,5)

##### **Reproduce the error**
 yarn start, page is not loading in IE 10-11.

##### **JHipster Version(s)**
4.0.3, 4.0.2

##### **JHipster configuration**
Angular 2 monolithic application

##### **JHipster Version(s)**

```
flow@0.0.0 D:\yeoman\jhipster\4.0.2\flow
`-- generator-jhipster@4.0.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "flow",
    "packageName": "com.liquidity.flow",
    "packageFolder": "com/liquidity/flow",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "45f8a07be79784ded6f6dc1bb868afeb9ecdf6a7",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.11.1.windows.1

node: v6.9.5

npm: 4.1.2

bower: 1.7.9

gulp:
[14:40:40] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

##### **Browsers and Operating System**
Windows 10 Home 64 Bit, Internet Explorer 11 - 10

- [X ] Checking this box is mandatory (this is just to show you read everything)
