### ISSUE TITLE
Created Entity not displayed under entity menu in Angular 2

### ISSUE THREAD

**Issue by mjanzs** [jhipster/generator-jhipster#5192]
##### **Overview of the issue**

Unable to view the created entities under entity menu. But the generated codes are available in the respected area. There is no error while creating the entity as well the application startup.

##### **Motivation for or Use Case**

Created entities aren't available under Entities menu

##### **Reproduce the error**

1. generate single page app
2. generate any entity
3. go to app to entity menu

![image](https://cloud.githubusercontent.com/assets/4049158/22902033/fad67cc6-f233-11e6-8e85-9787c65f1d3d.png)

##### **JHipster Version(s)**

4.0.3

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
app@0.0.0 d:\Projects\jhipster\app
`-- generator-jhipster@4.0.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "app",
    "packageName": "cz.janys",
    "packageFolder": "cz/janys",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "cs",
    "languages": [
      "cs",
      "en"
    ],
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Order.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        },
        {
            "fieldName": "time",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "price",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "dto": "no",
    "service": "no",
    "entityTableName": "order",
    "pagination": "infinite-scroll"
}

```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)

git version 2.5.0.windows.1

node: v7.4.0

npm: 4.0.5

bower: 1.8.0

gulp:
[21:33:30] CLI version 3.9.0

yeoman: 1.8.5

Docker version 1.9.1, build a34a1d5

docker-compose version 1.5.2, build e5cf49d

##### **Browsers and Operating System**

all browsers

- [-] Checking this box is mandatory (this is just to show you read everything)
