### ISSUE TITLE
If a many-to-many RelationshipName is equal to otherEntityNamePlural then Angular 2 does not work

### ISSUE THREAD

**Issue by hirzraimund** [jhipster/generator-jhipster#5208]
##### **Overview of the issue**

The Angular2 template in the **entity** subgenerator produces a naming conflict if the name of the relationship is the plural form of the name of the other entity.

This results in an exception in the JavaScript
`ItemDialogComponent - inline template:32:70 caused by: Cannot find a differ supporting object '[object Object]' of type 'tags'. NgFor only supports binding to Iterables such as Arrays.`
And because of this exception the whole Dialog does not work (no validation, no labels, no date pickers).

##### **Reproduce the error**

Use Angular 2 as Frontend and add a many-to-many relationship where the name at the owning site is the plurar form of the other entity like below
```
entity Item { name String required }

entity Tag {  name String required }

relationship ManyToMany {
	Item {tags (name) } to Tag {items (name) }
}
dto * with mapstruct
```

##### **Related issues**

It is similar to #5175 where a name clash was produced in the class definition when using self relation.

##### **Suggest a Fix**

I think the easiest solution is to change the **Template reference variable** which causes this problem, it can be found here [_entity-management-dialog.component.html:L209](https://github.com/jhipster/generator-jhipster/blob/b1da27b45414543f9d6fd5f9b0a91c9f2f115226/generators/entity/templates/client/angular/src/main/webapp/app/entities/_entity-management-dialog.component.html#L209)

For me it worked to remove the **Template reference variable** since it is never used. In the dialog also all other kind of relations do not use  a **Template reference variable**, but since I am not familiar with Angular I am not sure if this is the correct way.

##### **JHipster Version(s)**
```
many-many-bug@0.0.0 D:\Users\bla\workspace_neon\many_many_bug
`-- generator-jhipster@4.0.3 
```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "many_many_bug",
    "packageName": "lan.example",
    "packageFolder": "lan/example",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Item.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "items",
            "relationshipName": "tags",
            "otherEntityName": "tag",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170214195720",
    "entityTableName": "item",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "no"
}
```

Tag.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "relationshipName": "items",
            "otherEntityName": "item",
            "ownerSide": false,
            "otherEntityRelationshipName": "tags"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170214195720",
    "entityTableName": "tag",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

```
node: v6.9.5
npm: 4.2.0
bower: 1.8.0
gulp:
[21:13:47] CLI version 1.2.2
yeoman: 1.8.5
```

- [ x] Checking this box is mandatory (this is just to show you read everything)
