### ISSUE TITLE
JHipster 4.0.3 microservice UI is broken

### ISSUE THREAD

**Issue by srinisubra** [jhipster/generator-jhipster#5209]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Generate microservice gateway UI app is broken

Here is the content of .yo-rc.json

  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "gateway",
    "packageName": "com.xx.gateway",
    "packageFolder": "com/xx/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxx",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "clientFramework": "angular1",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

UI Error from chrome console:

Uncaught Error: [$injector:modulerr] Failed to instantiate module gatewayApp due to:
Error: [$injector:nomod] Module 'gatewayApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=gatewayApp
    at http://localhost:9000/bower_components/angular/angular.js:68:12
    at http://localhost:9000/bower_components/angular/angular.js:2082:17
    at ensure (http://localhost:9000/bower_components/angular/angular.js:2006:38)
    at module (http://localhost:9000/bower_components/angular/angular.js:2080:14)

##### **JHipster Version(s)**

4.0.3

##### **JHipster configuration**

$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@0.0.0 C:\git\hipster4\gateway
`-- generator-jhipster@4.0.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "gateway",
    "packageName": "com.xx.gateway",
    "packageFolder": "com/xx/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxx",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "clientFramework": "angular1",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

git version 2.9.2.windows.1

node: v6.9.5

npm: 3.10.8

bower: 1.8.0

gulp:
[14:49:48] CLI version 1.2.2
[14:49:48] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.12.3, build 6b644ec

docker-compose version 1.8.1, build 004ddae

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities generated

##### **Browsers and Operating System**

Windows 7 Enterprise and Chrome  56.0.2924.87 (64-bit)

- [X ] Checking this box is mandatory (this is just to show you read everything)
