### ISSUE TITLE
Model creation for angular 2 not working correctly for entity with multiple fields using same enum type

### ISSUE THREAD

**Issue by Drishika** [jhipster/generator-jhipster#5218]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I created an entity using JDL studio. The Entity has three fields that are of same enum type.

Example : 
fieldName1 enum1
fieldName2 enum1
fieldName3 enum1

on running jhipster on the .jh file the angular 2 model for the entity has enum1 declared three times that is causing compile errors.

const enum enum1 {
    'YES',
    'NO'
};
const enum enum1 {
    'YES',
    'NO'
};
const enum enum1 {
    'YES',
    'NO'
};

StackTrace 

ERROR in [at-loader] src/main/webapp/app/entities/candidate/candidate.model.ts:24:5 
    Duplicate identifier ''YES''.

ERROR in [at-loader] src/main/webapp/app/entities/candidate/candidate.model.ts:25:5 
    Duplicate identifier ''NO''.

##### **Motivation for or Use Case**

Use case : I wanted to define an enum with values 'YES', 'NO' that can be resued on fields of the entities.

##### **Reproduce the error**

Create an entity with multiple fields using same enum and run jhipster:import-jdl 

Check the model.ts and you will see errors.

##### **JHipster Version(s)**

JHipster version 4.0.2

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gradzcircle@0.0.0 /Users/Buni/JavaProjects/gradzcircle
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.4
├── UNMET PEER DEPENDENCY @angular/core@2.4.4
└── generator-jhipster@4.0.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.2",
    "baseName": "gradzcircle",
    "packageName": "com.drishika.gradzcircle",
    "packageFolder": "com/drishika/gradzcircle",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "865b94877cf467e179b9f5d864136cc94bdd533d",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Candidate.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-one",
            "relationshipName": "login",
            "otherEntityName": "user",
            "otherEntityField": "id",
            "ownerSide": true,
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "employabilitySkill",
            "otherEntityName": "candidateEmployability",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "education",
            "otherEntityName": "candidateEducation",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "nonacademic",
            "otherEntityName": "candidateNonAcademicWork",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "certification",
            "otherEntityName": "candidateCertification",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "country",
            "otherEntityName": "country",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "nationality",
            "otherEntityName": "nationality",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "employment",
            "otherEntityName": "candidateEmployment",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "skills",
            "otherEntityName": "skills",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "language",
            "otherEntityName": "language",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "candidate",
            "otherEntityName": "candidateProject",
            "otherEntityRelationshipName": "candidate"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "candidate",
            "relationshipName": "industry",
            "otherEntityName": "industryType",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "jobType",
            "fieldType": "JobType",
            "fieldValues": "FULLTIME,PARTTIME,INTERNSHIP,SUMMERJOB"
        },
        {
            "fieldName": "employmentType",
            "fieldType": "EmploymentType",
            "fieldValues": "CONTRACT,PERMANENT"
        },
        {
            "fieldName": "visaType",
            "fieldType": "VisaType",
            "fieldValues": "STUDENT_VISA,WORKING_VISA"
        },
        {
            "fieldName": "firstName",
            "fieldType": "String"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String"
        },
        {
            "fieldName": "middleName",
            "fieldType": "String"
        },
        {
            "fieldName": "facebookUrl",
            "fieldType": "String"
        },
        {
            "fieldName": "linkedInUrl",
            "fieldType": "String"
        },
        {
            "fieldName": "twitterUrl",
            "fieldType": "String"
        },
        {
            "fieldName": "aboutMe",
            "fieldType": "String"
        },
        {
            "fieldName": "primaryEmail",
            "fieldType": "String"
        },
        {
            "fieldName": "communicationEmail",
            "fieldType": "String"
        },
        {
            "fieldName": "address",
            "fieldType": "String"
        },
        {
            "fieldName": "dateOfBirth",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "gender",
            "fieldType": "Gender",
            "fieldValues": "MALE,FEMALE"
        },
        {
            "fieldName": "phoneNumber",
            "fieldType": "Integer"
        },
        {
            "fieldName": "maritialStatus",
            "fieldType": "MaritialStatus",
            "fieldValues": "SINGLE,MARRIED"
        },
** Fileds creating problem in angular 2 model for candidate entity**
        ** 
{
            "fieldName": "differentlyEnabled",
            "fieldType": "Consent",
            "fieldValues": "YES,NO"
        },
        {
            "fieldName": "availableForHiring",
            "fieldType": "Consent",
            "fieldValues": "YES,NO"
        },
        {
            "fieldName": "openToRelocate",
            "fieldType": "Consent",
            "fieldValues": "YES,NO"
        },
**
        {
            "fieldName": "candidatePicture",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "any"
        },
        {
            "fieldName": "phoneCode",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170214163115",
    "entityTableName": "candidate",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

git version 2.8.4 (Apple Git-73)

node: v7.4.0

npm: 4.0.5

bower: 1.8.0

gulp:
[23:09:09] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1
