### ISSUE TITLE
Move DTO option from entity to global

### ISSUE THREAD

**Issue by nicoraynaud** [jhipster/generator-jhipster#5227]
##### **Overview of the issue**

I have created a jdl file to reproduce the issue :
[jhipster-jdl.txt](https://github.com/jhipster/generator-jhipster/files/778903/jhipster-jdl.txt)

The link between Line and Category is not properly done in LineDTO. It creates a Set of CategoryDTO but Category does not have a DTO representing it.

##### **Motivation for or Use Case**

The DTO should link to the entity if there is no DTO representing it.

##### **Reproduce the error**

Create a new project, with the following domain : [jhipster-jdl.txt](https://github.com/jhipster/generator-jhipster/files/778903/jhipster-jdl.txt)

##### **JHipster Version(s)**

```
easycount@0.0.0 F:\workspace\easycount
`-- generator-jhipster@4.0.3  -> C:\Dev\jhipster\generator-jhipster
  `-- generator-jhipster@4.0.3  extraneous

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "easycount",
    "packageName": "org.tekinico.easycount",
    "packageFolder": "org/tekinico/easycount",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "7ce176028b1c46a004dcaaf7c3cca4391e809d1c",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "clientFramework": "angular2",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
See the enclosed jdl file : [jhipster-jdl.txt](https://github.com/jhipster/generator-jhipster/files/778903/jhipster-jdl.txt)

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.11.0.windows.3

node: v6.9.5

npm: 4.1.1

bower: 1.8.0

gulp:
[13:09:40] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a0
