### ISSUE TITLE
double coverage report in Karma

### ISSUE THREAD

**Issue by kaidohallik** [jhipster/generator-jhipster#5243]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

I found one hidden problem: there are two coverage subfolders generated by Karma (`yarn test`):
* one under build folder: `test-results/coverage`
* second: `src/test/javascript/coverage`

##### **Motivation for or Use Case**

Double coverage report seems wrong, especially when one is generated under `src` folder.

##### **Reproduce the error**

`yarn test`

##### **Suggest a Fix**

This additional configuration to `karma.conf.js` moves second test result also to build folder, into `test-results/coverage0` subfolder. But is this folder needed at all.
```
        coverageReporter: {
            dir: '../../../<%= BUILD_DIR %>test-results/coverage0'
        },
```

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\projects\test\jhipster-jenkins-test
`-- generator-jhipster@4.0.5  -> c:\projects\kaido-github\generator-jhipster
  `-- generator-jhipster@4.0.5  extraneous

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.5",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "be20d9ae8447ba5287bdc47245fcd9c8f727ebea",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.7.0.windows.1

node: v6.9.5

npm: 4.1.2

bower: 1.8.0

gulp:
[01:50:59] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.3

- [x] Checking this box is mandatory (this is just to show you read everything)
