### ISSUE TITLE
Karma Coverage Report shows always 100% coverage of nothing

### ISSUE THREAD

**Issue by kheckelmann** [jhipster/generator-jhipster#5271]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

After generating a jhipster gateway with Angular 2 frontend and starting the Karma Unit-Tests the coverage report shows 100% of everything and no files. That can't be right, because initially there is only one Karma-Unit-Test present.

##### **Motivation for or Use Case**

Coverage report is not very useful this way.

##### **Reproduce the error**

Generate a Gateway with Angular 2.

##### **JHipster Version(s)**

At least 4.0.3 and 4.0.5

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.3",
    "baseName": "person",
    "packageName": "com.diamos.person",
    "packageFolder": "com/diamos/person",
    "serverPort": "51286",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "14b70ac02ed21d1be0d0f7608754c21cdfd9be21",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "gateway",
    "clientFramework": "angular2",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en"
    ]
  }
}
```
##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 1.8.4.msysgit.0

node: v6.9.5

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.19.1

- [x] Checking this box is mandatory (this is just to show you read everything)
