### ISSUE TITLE
UaaAutoConfiguration triggered even if you don't select uaa option

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#5272]
##### **Overview of the issue**

UAA autoconf is triggered if ClientCredentialsResourceDetails and LoadBalancerClient classes are found on the classpath which can be the case even if you don't want to use UAA

##### **Motivation for or Use Case**

If you add spring-cloud-starter-oauth2 dependency, then the startup will fail because LoadBalancedResourceDetails bean doesn't find any LoadBalancerClient.

##### **Reproduce the error**

Generate a project without uaa and add dependency spring-cloud-starter-oauth2
```xml
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-oauth2</artifactId>
            <version>1.1.3.RELEASE</version>
        </dependency>
```
Start with `./mvnw`

The error is
```shell
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method loadBalancedResourceDetails in io.github.jhipster.security.uaa.UaaAutoConfiguration required a bean of type 'org.springframework.cloud.client.loadbalancer.LoadBalancerClient' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.cloud.client.loadbalancer.LoadBalancerClient' in your configuration.
```
##### **Suggest a Fix**

Something like a @ConditionalOnProperty on security.client-authorization.client-id
Also the LoadBalancedResourceDetails should probably be annotated by @ConditionalOnMissingBean so that the user can override it.

##### **JHipster Version(s)**

```
buguaa@0.0.0 /home/vagrant/workspace/jhipsterapps/buguaa
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.5  -> /home/vagrant/workspace/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.5",
    "baseName": "buguaa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "56cad4b8db0fe7143c49b54272f6c3cc465a6b67",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.7.4

node: v6.9.5

npm: 4.1.2

bower: 1.7.9

gulp:
[13:37:37] CLI version 3.9.1
[13:37:37] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.18.1

Docker version 1.12.6, build 78d1802

docker-compose version 1.8.0, build f3628c7

- [x] Checking this box is mandatory (this is just to show you read everything)
