### ISSUE TITLE
Date fields look funny in 4.0.6

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5277]
##### **Overview of the issue**

Date fields are wrapped with `<div class="input-group">`, which causes them to look funny.

![screen shot 2017-02-22 at 12 24 28 am](https://cloud.githubusercontent.com/assets/17892/23198423/73c7b7be-f895-11e6-9d52-e9d7ffbdeb7e.png)

##### **Motivation for or Use Case**

It doesn't look like a date field. It did in 4.0.5.

##### **Reproduce the error**

Create a new project, then import [blog.jh](https://raw.githubusercontent.com/jhipster/jdl-samples/master/blog.jh) using `yo jhipster:import-jdl`.

##### **Suggest a Fix**

Remove `<div class="input-group">` around date fields.

##### **JHipster Version(s)**

4.0.6. Yes it is a regression.

##### **JHipster Version(s)**

```
blog@0.0.0 /Users/mraible/blog
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.6

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "blog",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "a97ef04ff9e40fd25d4691b367aff1ad5d5074ff",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "zh-cn"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Blog.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "login"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 3
        },
        {
            "fieldName": "handle",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 2
        }
    ],
    "changelogDate": "20170222052144",
    "entityTableName": "blog",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Entry.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "blog",
            "otherEntityName": "blog",
            "otherEntityField": "name"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "entry",
            "relationshipName": "tag",
            "otherEntityName": "tag",
            "otherEntityField": "name",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "content",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "text",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "date",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170222052144",
    "entityTableName": "entry",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

Tag.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-many",
            "relationshipName": "entry",
            "otherEntityName": "entry",
            "ownerSide": false,
            "otherEntityRelationshipName": "tag"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": 2
        }
    ],
    "changelogDate": "20170222052144",
    "entityTableName": "tag",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

git version 2.10.2

node: v6.9.5

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.20.3

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7c5d5e4

- [x] Checking this box is mandatory (this is just to show you read everything)
