### ISSUE TITLE
Microservices Gateway with UAA always returns invalid access token for /uaa/api/account

### ISSUE THREAD

**Issue by rmelian** [jhipster/generator-jhipster#5285]
##### **Overview of the issue**
A "Microservice gateway" with UAA server always returns Invalid access token when accessing /uaa/api/account

![image](https://cloud.githubusercontent.com/assets/4565267/23220633/94d21fca-f8f0-11e6-9364-185579631f1b.png)

![image](https://cloud.githubusercontent.com/assets/4565267/23220683/c2d1777c-f8f0-11e6-8f1a-dd0d97656c99.png)

![image](https://cloud.githubusercontent.com/assets/4565267/23220713/d750c4f0-f8f0-11e6-93df-20dea38aec2b.png)

![image](https://cloud.githubusercontent.com/assets/4565267/23220789/0a8b1dde-f8f1-11e6-80b6-6c7b7e5a6e70.png)

![image](https://cloud.githubusercontent.com/assets/4565267/23220741/e92afa38-f8f0-11e6-86f7-086f05564796.png)

![image](https://cloud.githubusercontent.com/assets/4565267/23220759/f3a38a20-f8f0-11e6-90e9-6d30cfdbafe5.png)

##### **Reproduce the error**

- Generate a JHipster UAA server
- Generate a JHipster gateway
- Clone Jhipster registry (run this first)

##### **JHipster Version(s)**

4.0.6

##### **JHipster configuration**

UAA Server 

##### **JHipster Version(s)**

```
/home/jhipster/app/uaa
`-- generator-jhipster@4.0.6 

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "uaa",
    "packageName": "com.company.uaa",
    "packageFolder": "com/company/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableTranslation": false,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.9.5

npm: 4.2.0

bower: 1.8.0

gulp:
[04:45:21] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.3

Gateway Configs

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/jhipster/app/gateway
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.7
+-- UNMET PEER DEPENDENCY @angular/core@2.4.7
`-- generator-jhipster@4.0.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "gateway",
    "packageName": "com.viacom.gt",
    "packageFolder": "com/viacom/gt",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.9.5

npm: 4.2.0

bower: 1.8.0

gulp:
[05:03:16] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.3

##### **Browsers and Operating System**

OS El Capitan

- [X] Checking this box is mandatory (this is just to show you read everything)
