### ISSUE TITLE
$state is not defined. Bootstrap pagination bar component on Entity page does not work well.

### ISSUE THREAD

**Issue by hjgomez1975** [jhipster/generator-jhipster#5291]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Bootstrap pagination bar component on **Entity page** ( for example *Country*) does not work well. 

The size of each page is defined by default for 20 rows.  If you have more than 20 items and try to move to the second page a javascript error appears:

>  $state is not defined

**$state variable is missing on entity page generated by jhipster.**

##### **Reproduce the error**

Add 22 rows on the Country entity. Then click on page number 2 button on the Bootstrap pagination bar located at the bottom of the page. Nothing happen. Open Javascript console on the browser (For example Firefox or Chrome). You can visualize the error *$state is not defined*

##### **Suggest a Fix**

need to modify _entity-management.controller.js

This file is located on the directory: ../node_modules/generator-jhipster/generators/entity/templates/client/angularjs/src/main/webapp/app/entities/_entity-management.controller.js

You need to add **$state** variable on the $inject and function code on **line 8 and 10**. 

Here you have the solution code for jhipster 4.0.5 release:
```

(function() {
    'use strict';

    angular
        .module('<%=angularAppName%>')
        .controller('<%= entityAngularName %>Controller', <%= entityAngularName %>Controller);

    <%= entityAngularName %>Controller.$inject = [<% if (fieldsContainBlob) { %>'DataUtils', <% } %>'<%= entityClass %>'<% if (searchEngine == 'elasticsearch') { %>, '<%= entityClass %>Search'<% } %><% if (pagination != 'no') { %>, 'ParseLinks', 'AlertService', 'paginationConstants', '$state'<% } %> <%_ if (pagination == 'pager' || pagination == 'pagination'){ %>, 'pagingParams'<% } %>];

    function <%= entityAngularName %>Controller(<% if (fieldsContainBlob) { %>DataUtils, <% } %><%= entityClass %><% if (searchEngine == 'elasticsearch') { %>, <%= entityClass %>Search<% } %><% if (pagination != 'no') { %>, ParseLinks, AlertService, paginationConstants, $state<% } %> <%_ if (pagination == 'pager' || pagination == 'pagination'){ %>, pagingParams<% } %>) {

        var vm = this;

        <%_ if (pagination == 'pagination' || pagination == 'pager') { _%>
<%- include('pagination-template'); -%>
        <%_ } else if (pagination == 'infinite-scroll') { _%>
<%- include('infinite-scroll-template'); -%>
        <%_ } else { _%>
<%- include('no-pagination-template'); -%>
        <%_ } _%>
    }
})();
```

##### **JHipster Version(s)**

```
test@0.0.0 C:\Users\hgomez\git\otro
`-- generator-jhipster@4.0.5

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.5",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "5a1432f790f63f8347effbea5e69d927fbaee179",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Country.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "countryName",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170223151845",
    "entityTableName": "country",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl",
    "angularJSSuffix": "mySuffix"
}
```

Region.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "regionName",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170223151845",
    "entityTableName": "region",
    "dto": "mapstruct",
    "pagination": "infinite-scroll",
    "service": "serviceImpl",
    "angularJSSuffix": "mySuffix"
}
```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.1.windows.1

node: v6.9.5

npm: 4.2.0

bower: 1.8.0

gulp:
[16:34:11] CLI version 3.9.1
[16:34:11] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.20.3
