### ISSUE TITLE
[OAuth2] Cannot access to management 

### ISSUE THREAD

**Issue by abenmess** [jhipster/generator-jhipster#5298]
##### **Overview of the issue**

I generate a  Monolithic project using JHipster release 4.0.6.
after generate, all menus work except Administration/Configuration, i meet "You are not authorized to access the page" with an invitation to login.
I have the same error when i login again.

The error is reproductible using chrome and firefox

##### **Motivation for or Use Case**

I think that is bug related to the new version

##### **Reproduce the error**

The bug is reproducible 
##### **JHipster Version(s)**

JHipster release 4.0.6.

##### **JHipster configuration**

yo jhipster:info

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
ingoodnessportal@0.0.0 /home/test
└── generator-jhipster@4.0.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "test",
    "packageName": "test",
    "packageFolder": "test",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "tr"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.7.4

node: v7.6.0

npm: 4.1.2

bower: 1.8.0

gulp:
[21:39:54] CLI version 1.2.2
[21:39:54] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.20.3

Docker version 1.12.3, build 6b644ec

docker-compose version 1.9.0, build 2585387

##### **Browsers and Operating System**

Ubuntu 16
Chrome
Firefox
