### ISSUE TITLE
Malformed JWT gives error 500

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#5305]
##### **Overview of the issue**

A malformed JWT sends an error 500 instead of 401

##### **Reproduce the error**

Generate an app with JWT auth type
Login and send a request with browser network devtools
Re-send the request removing a character in the JWT token

##### **Suggest a Fix**

Catch MalformedJwtException (and probably the others: UnsupportedJwtException, UnsupportedJwtException and IllegalArgumentException) in  validateToken()

##### **JHipster Version(s)**
       
```
jwt@0.0.0 /home/vagrant/workspace/jhipsterapps/jwt
└── generator-jhipster@4.0.6  -> /home/vagrant/workspace/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "jwt",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ab2ad81a836308c5c4d8790fa96c8131152d7c62",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 3.10.10

bower: 1.7.9

gulp:
[23:30:46] CLI version 3.9.1
[23:30:46] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.20.3

Docker version 1.12.1, build 23cf638

docker-compose version 1.8.0, build f3628c7
