### ISSUE TITLE
Cannot activate registered user

### ISSUE THREAD

**Issue by xsalefter** [jhipster/generator-jhipster#5310]
##### **Overview of the issue**

After registration successful, user should activate him/herself via link sent to their email inbox. Clicking this link always result:
`Your user could not be activated. Please use the registration form to sign up.` 
In screen.

##### **Motivation for or Use Case**

This is bug because, if user follow normal use case / steps by steps for registering him/herself, message:
`Your user has been activated. Please sign in.` should be showing up instead of  `Your user could not be activated. Please use the registration form to sign up.` 

##### **Reproduce the error**
1. Run generated app.
2. Go to `account - > register` menu
3. Register your self.
4. See email / copy-paste generated messages from console for activation link, and click it.
5. There's message `Your user could not be activated. Please use the registration form to sign up.` 

*Expected result*
Message with value `Your user has been activated. Please sign in.`.

##### **Suggest a Fix**

For me, removing `json()` on [this line](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/account/activate/_activate.service.ts#L16) make it work. 

Note that if removing `json()` still not fix the problem, you may need to restart the app **and** call `yarn start` again. (Not sure whether this is as designed or just another bug).

##### **JHipster Version(s)**

```
hipsterapp@0.0.0 /mnt/data/vcs/git/github/xsalefter/hipsterapp
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "hipsterapp",
    "packageName": "com.xsalefter.hipsterapp",
    "packageFolder": "com/xsalefter/hipsterapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "6e8ef07e32eba058cc58c0991f6392ae21edd765",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.0.0

npm: 3.10.9

bower: 1.8.0

gulp:
[18:48:44] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.9.0, build 2585387

##### **Browsers and Operating System**

Chrome in Ubuntu 16.04 

- [x] Checking this box is mandatory (this is just to show you read everything)
