### ISSUE TITLE
After activation, sign-in not redirecting to proper URL

### ISSUE THREAD

**Issue by xsalefter** [jhipster/generator-jhipster#5312]
##### **Overview of the issue**

With assumption that #5310 fixed, sign-in action not redirect to home page after activation completed.

##### **Motivation for or Use Case**

This is bug because otherwise, user will keep 'activate' page with message `Your user has been activated. Please sign in.` even he/she already signed in successfully.

##### **Reproduce the error**

1. Register your self.
2. Get the activation URL. 
3. Click `sign in` link in the activation (success) page.
4. Sign in with your username and password.
5. User signed in, but keep in  'activate' page with message `Your user has been activated. Please sign in.`

*Expected Result*
Redirected to home page.

##### **Related issues**

#5310 

##### **Suggest a Fix**

In [this file](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/shared/login/_login.component.ts#L69), use `this.router.url.indexOf('/activate') === 0` (or any newer ES6 approach for checking substring) instead of  `this.router.url === '/activate'`

##### **JHipster Version(s)**

```
hipsterapp@0.0.0 /mnt/data/vcs/git/github/xsalefter/hipsterapp
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "hipsterapp",
    "packageName": "com.xsalefter.hipsterapp",
    "packageFolder": "com/xsalefter/hipsterapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "6e8ef07e32eba058cc58c0991f6392ae21edd765",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.0.0

npm: 3.10.9

bower: 1.8.0

gulp:
[18:48:44] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.9.0, build 2585387

- [x] Checking this box is mandatory (this is just to show you read everything)
