### ISSUE TITLE
UAA responding with 302 when requesting resources using a valid client_credentials JWT token

### ISSUE THREAD

**Issue by karlkyck** [jhipster/generator-jhipster#5328]
##### **Overview of the issue**

A freshly generated JHipster (4.0.6) UAA is responding with a 302 response when requesting a resource using a valid JWT token generated using the authorized grant type: client_credentials.

##### **Motivation for or Use Case**

We are using the JHipster UAA to secure our microservices and have recently generated a new UAA microservice using the latest JHipster (4.0.6). Our microservices cannot consume resources from that server.

##### **Reproduce the error**

Generate a fresh UAA using yo jhipster. Start the server, then:

curl internal:internal@localhost:9999/oauth/token -d grant_type=client_credentials

TOKEN="<access_token_from_response>"

curl -I -H "Authorization: bearer $TOKEN" http://localhost:9999/api/users

##### **Suggest a Fix**

JHipster (4.0.6) uses Spring Boot 1.5. In Spring Boot 1.5 the default order of the OAuth2 resource filter has changed from 3 to 1. This places it before the basic authentication filter chain and therefore the UAA resource configuration has no effect.

The migration docs from Spring Boot 1.4 to 1.5 suggests restoring the order by setting security.oauth2.resource.filter-order = 3

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter

We have done this and can confirm that it fixes the issue

##### **JHipster Version(s)**

```
/home/jhipster/app
`-- generator-jhipster@4.0.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "app",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.9.5

npm: 4.2.0

bower: 1.8.0

gulp:
[12:11:52] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.3

- [X] Checking this box is mandatory (this is just to show you read everything)
