### ISSUE TITLE
Hazelcast http clustering SessionId: null

### ISSUE THREAD

**Issue by rohajda** [jhipster/generator-jhipster#5330]
##### **Overview of the issue**

I have generated new application without any further changes. I have start it as it was generated. After connnecting to application and initial authentication by navigating to Administration/User management menu, I am asked again to authenticate as server is not recognizing me. From logs it shows sessionId: null

In server i can see

`
2017-02-28 19:34:50.516 DEBUG 48706 --- [ XNIO-2 task-56] sk.emm.portal.aop.logging.LoggingAspect  : Exit: sk.emm.portal.web.rest.AccountResource.getAccount() with result = <200 OK,UserDTO{login='admin', firstName='Administrator', lastName='Administrator', email='admin@localhost', imageUrl='', activated=true, langKey='en', createdBy=system, createdDate=2017-02-28T18:51:02.249964+01:00[Europe/Bratislava], lastModifiedBy='system', lastModifiedDate=null, authorities=[ROLE_USER, ROLE_ADMIN]},{}>
2017-02-28 19:34:53.491 DEBUG 48706 --- [ XNIO-2 task-57] sk.emm.portal.aop.logging.LoggingAspect  : Enter: org.springframework.boot.actuate.audit.AuditEventRepository.add() with argument[s] = [AuditEvent [timestamp=Tue Feb 28 19:34:53 CET 2017, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null, type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]]
2017-02-28 19:34:53.492 DEBUG 48706 --- [ XNIO-2 task-57] sk.emm.portal.aop.logging.LoggingAspect  : Exit: org.springframework.boot.actuate.audit.AuditEventRepository.add() with result = null
2017-02-28 19:34:53.492 DEBUG 48706 --- [ XNIO-2 task-57] i.g.j.s.Http401UnauthorizedEntryPoint    : Pre-authenticated entry point called. Rejecting access
`

##### **Motivation for or Use Case**

After connnecting to application by navigating to Administration/User management I am asked again to authenticate as server is not recognizing me.

##### **Reproduce the error**

Just generate new application, start it and connect. Then navigate to Administration/User Management and application is again requesting password as it cannot recognize you

##### **Related issues**

I found issue #4189 which sound very similar

##### **Suggest a Fix**

I am not able to find reason, therfore I am raising this issue

##### **JHipster Version(s)**

I am using 4.0.6

##### **JHipster Version(s)**

```
portal@0.0.0 /Users/robert/Documents/Work/Training/JHipster/portal
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "portal",
    "packageName": "sk.emm.portal",
    "packageFolder": "sk/emm/portal",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "blabla...",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "cs"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v7.5.0

npm: 4.1.2

bower: 1.8.0

gulp:
[19:29:58] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7c5d5e4

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

It is default project no adjustments or entity where created

##### **Browsers and Operating System**

OS x 10.12.3, Chrome Version 56.0.2924.87 (64-bit)

- [x] Checking this box is mandatory (this is just to show you read everything)
