### ISSUE TITLE
Request to fix Entities empty dropdown

### ISSUE THREAD

**Issue by vidhya03** [jhipster/generator-jhipster#5335]
##### **Overview of the issue**

I am so happy to explore jhipster for the first time after heard about angular2 support added in Jhipster 4

I followed https://jhipster.github.io/video-tutorial/  , however the Entities drop down shows empty

![bug-entities-dropdown-01](https://cloud.githubusercontent.com/assets/534679/23456065/f71a43fe-fe97-11e6-9bfb-832ee7838ece.PNG)
This shows that i made some mistake in setting up the projects

##### **Motivation for or Use Case**
First time users like me , will not be surprised about the usability issue!

##### **Suggest a Fix**
it will be nice if we show some helpful text like this 

![bug-entities-dropdown](https://cloud.githubusercontent.com/assets/534679/23456010/c79301fc-fe97-11e6-9c15-14131fd06372.PNG)

##### **JHipster Version(s)**

```
blog@0.0.0 X:\opensource12\jhipster\vidhyapp\myapp
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.7
+-- UNMET PEER DEPENDENCY @angular/core@2.4.7
`-- generator-jhipster@4.0.6

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.6",
    "baseName": "blog",
    "packageName": "com.labkit.jhipster",
    "packageFolder": "com/labkit/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ae9d4e2f915f1e14f8d449d6a42175f3b36ff3d0",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "es",
      "ca",
      "ta",
      "en"
    ]
  }
}

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
Firefox
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.9.2.windows.1

node: v6.10.0

npm: 3.10.5

gulp:
[15:28:08] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

[x] Checking this box is mandatory (this is just to show you read everything)
