### ISSUE TITLE
yarn now gets error on docker container build ver 4.0.7 (with Windows)

### ISSUE THREAD

**Issue by sonersivri** [jhipster/generator-jhipster#5343]
##### **Overview of the issue**

yarn install v0.21.3
info No lockfile found.
[1/4] Resolving packages...
warning protractor > jasmine > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning browser-sync > localtunnel > request > tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning phantomjs-prebuilt > request > node-uuid@1.4.7: use uuid module instead
warning browser-sync > localtunnel > request > node-uuid@1.4.7: use uuid module instead
warning generator-jhipster > yo > fullname > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as s
oon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "EINVAL: invalid argument, symlink '../semver/bin/semver' -> '/home/jhipster/app/node_modules/agent-base/node_modules/.bin/semver'".
info If you think this is a bug, please open a bug report with the information provided in "/home/jhipster/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
WARNING! yarn install failed. Retrying to launch yarn: 1/2 retries.

##### **Motivation for or Use Case**

yo jhipster command cannot be finished because of this error

##### **Reproduce the error**

every time yo jhipster command it occurs

##### **Related issues**

I could not find any issue from history

##### **Suggest a Fix**

No suggestion

##### **JHipster Version(s)**

4.0.7

##### **JHipster configuration**
yo jhipster:info

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
mavinci-license@0.0.0 /home/jhipster/app
`-- generator-jhipster@4.0.7

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
yo jhipster:info
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "mavinci_license",
    "packageName": "io.mavinci.license",
    "packageFolder": "io/mavinci/license",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f07187ceb9ed1be47aad2492b4e8fe4ab165bf5e",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": [
      "tr",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.3.0

bower: 1.8.0

gulp:
[12:09:52] CLI version 1.2.2
[12:09:52] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

cat .yo-rc.json
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "mavinci_license",
    "packageName": "io.mavinci.license",
    "packageFolder": "io/mavinci/license",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f07187ceb9ed1be47aad2492b4e8fe4ab165bf5e",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "tr",
    "languages": [
      "tr",
      "en"
    ]
  }

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

no entity first command run

##### **Browsers and Operating System**

Docker container which is run on windows 10 PRO; Docker Version is 1.13.1 (10072) Channel : stable, 94675c5

- [X ] Checking this box is mandatory (this is just to show you read everything)
