### ISSUE TITLE
Linter config on the Gulp level

### ISSUE THREAD

**Issue by NenadP** [jhipster/generator-jhipster#5376]
I am not able to understand where does linting take place when running jHipster with Angular 1.x on the Gulp level. I'm trying to understand how hard would it be to adopt our build to use es6.

When using classes , for example in ```home.js```, I get following from Gulp Notify:
```
[17:44:46] Tested 3 tests, 3 passes, 0 failures: PASS
[17:44:47] gulp-notify: [JHipster Gulp Build] Error: Error in parsing: "home\home.controller.js", Line 1: Unexpected reserved word
```
In ```gulpfile.js``` it seems that ```eslint``` task is not part of the ```serve``` / ```watch``` pipeline

If I take out ```.pipe(plumber({errorHandler: handleErrors}))``` from ```gulp/inject.js``` error is not being reported. I cannot track from there though, who is the reporter of the error.

Anyway I am not able to see where I can configure Gulp and/or linter I want es6  standard, or allow for reserved words etc.

This notification does not prevent building.

I would appreciate your guidelines there.

System is Windows 10, gulp run from within git-bash.

##### **JHipster configuration**
```
myapp@0.0.0 C:\Users\info\src\my-app
`-- generator-jhipster@4.0.7

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "myapp",
    "packageName": "com.bionic.app",
    "packageFolder": "com/bionic/app",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "afb3e3b010d686ca2a86b8704313a54c761a0b30",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
git version 2.11.0.windows.1
node: v6.9.2
npm: 3.10.9
bower: 1.8.0

gulp:
[18:04:14] Requiring external module babel-register
[18:04:14] CLI version 3.9.1
[18:04:14] Local version 3.9.1

yeoman: 1.8.5

- [+] Checking this box is mandatory (this is just to show you read everything)
