### ISSUE TITLE
Inconsistent Generator when executed for a second time

### ISSUE THREAD

**Issue by rmelian** [jhipster/generator-jhipster#5390]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**
After a new microservice application is generated and immediately the generator is executed again it changes some properties:
When the project is generated the first time the is a 
spring_boot_version=1.5.2.RELEASE
if you run the generator again it changes to spring_boot_version=1.5.1.RELEASE
and the same happens with node_version, yarn_version and many more

##### **Motivation for or Use Case**
 If the generator is run multiple times it should keep consistent with initial generated code

##### **Reproduce the error**
1- run yo 
2- run yo

##### **JHipster Version(s)**
latest from master

##### **JHipster Version(s)**

```
/home/jhipster/app/Testing/spring-cloud-eurekavsconsul-config
`-- generator-jhipster@4.0.7 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "6c7ce6d324fe9e8d56a8f00d15390eaa88689d97",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.9.5

npm: 4.2.0

bower: 1.8.0

gulp:
[04:05:22] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.3

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
none

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)
