### ISSUE TITLE
Having issue when execute Gatling task with Gradle build system

### ISSUE THREAD

**Issue by nghib** [jhipster/generator-jhipster#5393]
##### **Overview of the issue**
I used 4.0.7 released version of JHipster. I generated a fresh new project with no added entities  and try to execute gradle task "./gradlew gatlingRun -x cleanResources" as the document, but it failed to execute. This is the stack trace of error:

Exception in thread "main" java.lang.IllegalArgumentException: The requested class '*' can not be found in the classpath or does not extends Simulation.
        at io.gatling.app.Selection$Selector.io$gatling$app$Selection$Selector$$$anonfun$6(Selection.scala:80)
        at scala.Option.flatMap(Option.scala:171)
        at io.gatling.app.Selection$Selector.singleSimulationFromConfig$1(Selection.scala:73)
        at io.gatling.app.Selection$Selector.io$gatling$app$Selection$Selector$$$anonfun$8(Selection.scala:97)
        at scala.Option.orElse(Option.scala:289)
        at io.gatling.app.Selection$Selector.trySelectingSingleSimulation(Selection.scala:97)
        at io.gatling.app.Selection$Selector.selection(Selection.scala:40)
        at io.gatling.app.Selection$.apply(Selection.scala:33)
        at io.gatling.app.Runner.run0(Runner.scala:78)
        at io.gatling.app.Runner.run(Runner.scala:64)
        at io.gatling.app.Gatling$.start(Gatling.scala:56)
        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:41)
        at io.gatling.app.Gatling$.main(Gatling.scala:33)
        at io.gatling.app.Gatling.main(Gatling.scala)
:gatlingRun FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/Users/ngib/spring/jhipsterApp/gradle/gatling.gradle' line: 33
* What went wrong:
Execution failed for task ':gatlingRun*'.

> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

This is result from yo jhipster:info
yo jhipster:info                                                                                               (1) (1m 13s 901ms) ┃
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster-bench@0.0.0 /Users/phuctbui/spring/jhipsterBench
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.7

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "jhipsterBench",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "37cdbc8972db273b4fcecc675a27061db86524e8",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ca"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

Picked up _JAVA_OPTIONS: -Dspring.output.ansi.enabled=ALWAYS
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.0

node: v6.10.0

npm: 4.1.2

bower: 1.8.0

gulp:
[17:49:26] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build unknown

MAC OSX 10.12.3

- [x] Checking this box is mandatory (this is just to show you read everything)
