### ISSUE TITLE
Angular 2 jhi-alert-error i18n encoding issue

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#5401]
##### **Overview of the issue**

Encoding not working for specials characters in jhi-alert-error and jhi-alert.

##### **Motivation for or Use Case**

Use i8n for other languages.

1/ Generate Jhispter application with i8n and French langage as default.
2/ Throw alert error, example: create new user with admin login.

Text display will be :
![i8n issue](https://cloud.githubusercontent.com/assets/1721344/23822305/e182c588-064a-11e7-9e1f-9cdea71a721c.PNG)

##### **Related issues**

N/A

##### **Suggest a Fix**

N/A

##### **JHipster Version(s)**

Jhipster v4.0.8

##### **JHipster configuration**

`Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 D:\workspaces\jhipster\bug-i8n
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.7
+-- UNMET PEER DEPENDENCY @angular/core@2.4.7
`-- generator-jhipster@4.0.8

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "7c9bce61a246c99bdd3a1093ba3a6c131dda631f",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.11.0.windows.1

node: v6.9.5

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.21.3`

##### **Browsers and Operating System**

OS x64 :
Nom du système d’exploitation	Microsoft Windows 10 Famille
Version	10.0.14393 Numéro 14393

Chrome: Version 56.0.2924.87 (64-bit)

- [x ] Checking this box is mandatory (this is just to show you read everything)
