### ISSUE TITLE
Angular 2 jhi-alert-error issue on server validation error

### ISSUE THREAD

**Issue by elhoo** [jhipster/generator-jhipster#5402]
##### **Overview of the issue**

Created a project with one entity with two fields. One of them NotNull. 
After generation I change the other field to NotNull as well. Now, when I try to create 
the entity I don't get any error message in the UI. 

In the console I can only see:
POST http://localhost:8080/api/books 400 (Bad Request)

If I debug I can see the following error:
```
    * TypeError: Cannot read property 'toLowerCase' of undefined at Headers.has (http://localhost:8080/vendor.dll.js:22710:76) at Headers.getAll (http://localhost:8080/vendor.dll.js:22757:21) at Headers.get (http://localhost:8080/vendor.dll.js:22699:44) at SafeSubscriber._next (http://localhost:8080/main.bundle.js:5422:60) at SafeSubscriber.__tryOrUnsub (http://localhost:8080/vendor.dll.js:600:16) at SafeSubscriber.next (http://localhost:8080/vendor.dll.js:549:22) at Subscriber._next (http://localhost:8080/vendor.dll.js:502:26) at Subscriber.next (http://localhost:8080/vendor.dll.js:466:18) at FilterSubscriber._next (http://localhost:8080/vendor.dll.js:50379:30) at FilterSubscriber.Subscriber.next (http://localhost:8080/vendor.dll.js:466:18) at RefCountSubscriber.Subscriber._next (http://localhost:8080/vendor.dll.js:502:26) at RefCountSubscriber.Subscriber.next (http://localhost:8080/vendor.dll.js:466:18) at Subject.next (http://localhost:8080/vendor.dll.js:4239:25) at ConnectableSubscriber.Subscriber._next (http://localhost:8080/vendor.dll.js:502:26) at ConnectableSubscriber.Subscriber.next (http://localhost:8080/vendor.dll.js:466:18) 
```

##### **Motivation for or Use Case**

Would expect to see the error from the server (using jhi-alert-error)

##### **Reproduce the error**

Create basic project
add entity with two fields, the first required, the second no validation
Add NotNull annotation to the second field.
Start 
Add entity and don't add any value to second field.

##### **Related issues**

Couldn't find any.

##### **Suggest a Fix**

in JhiAlertErrorComponent the 
```
let errorHeader = httpResponse.headers.get(headers[0]);
let entityKey = httpResponse.headers.get(headers[1]);
```
Is the problem - httpResponse.headers seems to be null for me.

Fix that kind of works for me:
```
let errorHeader = null;
let entityKey = null;
if(httpResponse.headers && httpResponse.headers.length > 0) {
      errorHeader = httpResponse.headers.get(headers[0]);
     entityKey = httpResponse.headers.get(headers[1]);
}
```

##### **JHipster Version(s)**

4.0.8

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster-bug-1@0.0.0 /Users/lh/dev/projects/jhipster_bug1
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.8

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "jhipster_bug1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "cbb85385e07f7ce32c88dc4b96c83e7874eae34c",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Book.json

~~~json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "category",
            "fieldType": "String"
        }
    ],
    "dto": "no",
    "service": "no",
    "entityTableName": "book",
    "pagination": "no"
}
~~~

##### **Browsers and Operating System**

java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

git version 2.11.0

node: v7.4.0

npm: 4.1.1

bower: 1.8.0

gulp:
[18:48:32] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.20.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build dfed245

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

cat .jhipster/Book.json
~~~json
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "category",
            "fieldType": "String"
        }
    ],
    "dto": "no",
    "service": "no",
    "entityTableName": "book",
    "pagination": "no"
}
~~~

##### **Browsers and Operating System**
MacOS 10.12.3

- [x] Checking this box is mandatory (this is just to show you read everything)
