### ISSUE TITLE
Error ManyToOne relationship

### ISSUE THREAD

**Issue by jlopezjuy** [jhipster/generator-jhipster#5407]
- Please follow the issue template below for bug reports and feature requests.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

Relationship of an entity with two attributes to another entity

##### **Motivation for or Use Case**
ej
entity Encargo:
     estado ValorDominio,
     tipoEvento ValorDominio 

##### **Related issues**

~~~
liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/20170313030953_added_entity_Encargo.xml::20170313030953-1::jhipster:
     Reason: liquibase.exception.DatabaseException: Duplicate column name 'valor_dominio_id' [Failed SQL: CREATE TABLE Clothes.encargo (id BIGINT AUTO_INCREMENT NOT NULL, importe_total DOUBLE NULL, fecha_encargo date NULL, fecha_entrega date NULL, detalle_vestido VARCHAR(255) NULL, cliente_id BIGINT NULL, valor_dominio_id BIGINT NULL, valor_dominio_id BIGINT NULL, CONSTRAINT PK_ENCARGO PRIMARY KEY (id))]
~~~

##### **JHipster Version(s)**

Latest version

##### **JHipster Version(s)**

```
clothes@0.0.0 D:\Proyectos\JHipsterEjemplos\Clothes
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.7
+-- UNMET PEER DEPENDENCY @angular/core@2.4.7
`-- generator-jhipster@4.0.7

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.7",
    "baseName": "Clothes",
    "packageName": "ar.com.clothes",
    "packageFolder": "ar/com/clothes",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "74a8126402d4321731450bb1a82156fe8bcf23f9",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Cliente.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "modelo",
            "otherEntityName": "modelo",
            "otherEntityRelationshipName": "cliente"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "medida",
            "otherEntityName": "medida",
            "otherEntityRelationshipName": "cliente"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "encargo",
            "otherEntityName": "encargo",
            "otherEntityRelationshipName": "cliente"
        }
    ],
    "fields": [
        {
            "fieldName": "nombre",
            "fieldType": "String"
        },
        {
            "fieldName": "apellido",
            "fieldType": "String"
        },
        {
            "fieldName": "celular",
            "fieldType": "String"
        },
        {
            "fieldName": "telefono",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String"
        },
        {
            "fieldName": "domicilio",
            "fieldType": "String"
        },
        {
            "fieldName": "colegio",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "cliente",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

Dominio.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "valorDominio",
            "otherEntityName": "valorDominio",
            "otherEntityRelationshipName": "dominio"
        }
    ],
    "fields": [
        {
            "fieldName": "descripcion",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "dominio",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Encargo.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "cliente",
            "otherEntityName": "cliente",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipName": "valorDominio",
            "otherEntityName": "valorDominio",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipName": "valorDominio",
            "otherEntityName": "valorDominio",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "pago",
            "otherEntityName": "pago",
            "otherEntityRelationshipName": "encargo"
        }
    ],
    "fields": [
        {
            "fieldName": "importeTotal",
            "fieldType": "Double"
        },
        {
            "fieldName": "fechaEncargo",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "fechaEntrega",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "detalleVestido",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "encargo",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Medida.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "cliente",
            "otherEntityName": "cliente",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "contornoBusto",
            "fieldType": "Double"
        },
        {
            "fieldName": "anchoPecho",
            "fieldType": "Double"
        },
        {
            "fieldName": "altoBusto",
            "fieldType": "Double"
        },
        {
            "fieldName": "bajoBusto",
            "fieldType": "Double"
        },
        {
            "fieldName": "alturaPinza",
            "fieldType": "Double"
        },
        {
            "fieldName": "separacionBusto",
            "fieldType": "Double"
        },
        {
            "fieldName": "talleDeltantero",
            "fieldType": "Double"
        },
        {
            "fieldName": "talleEspalda",
            "fieldType": "Double"
        },
        {
            "fieldName": "largoCorset",
            "fieldType": "Double"
        },
        {
            "fieldName": "costado",
            "fieldType": "Double"
        },
        {
            "fieldName": "hombro",
            "fieldType": "Double"
        },
        {
            "fieldName": "anchoHombro",
            "fieldType": "Double"
        },
        {
            "fieldName": "largoManga",
            "fieldType": "Double"
        },
        {
            "fieldName": "sisa",
            "fieldType": "Double"
        },
        {
            "fieldName": "cintura",
            "fieldType": "Double"
        },
        {
            "fieldName": "anteCadera",
            "fieldType": "Double"
        },
        {
            "fieldName": "cadera",
            "fieldType": "Double"
        },
        {
            "fieldName": "largoPollera",
            "fieldType": "Double"
        },
        {
            "fieldName": "fechaMedida",
            "fieldType": "LocalDate"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "medida",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Modelo.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "cliente",
            "otherEntityName": "cliente",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "imagen",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        },
        {
            "fieldName": "nombreModelo",
            "fieldType": "String"
        },
        {
            "fieldName": "colorVestido",
            "fieldType": "String"
        },
        {
            "fieldName": "observacion",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "modelo",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Pago.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "encargo",
            "otherEntityName": "encargo",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "fechaPago",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "importe",
            "fieldType": "Double"
        },
        {
            "fieldName": "detalle",
            "fieldType": "String"
        },
        {
            "fieldName": "numeroRecibo",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "pago",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

ValorDominio.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "dominio",
            "otherEntityName": "dominio",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "tipoEvento",
            "otherEntityName": "encargo",
            "otherEntityRelationshipName": "valorDominio"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "estado",
            "otherEntityName": "encargo",
            "otherEntityRelationshipName": "valorDominio"
        }
    ],
    "fields": [
        {
            "fieldName": "descripcion",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170313030953",
    "entityTableName": "valor_dominio",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.10.2.windows.1

node: v6.10.0

npm: 4.3.0

bower: 1.8.0

gulp:
[00:38:38] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

##### **Browsers and Operating System**

Chrome

##### **Entity Encargo with two atributes ValorDominio

~~~java
@Entity
@Table(name = "encargo")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class Encargo implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "importe_total")
    private Double importeTotal;

    @Column(name = "fecha_encargo")
    private LocalDate fechaEncargo;

    @Column(name = "fecha_entrega")
    private LocalDate fechaEntrega;

    @Column(name = "detalle_vestido")
    private String detalleVestido;

    @ManyToOne
    private Cliente cliente;

    @ManyToOne
    private ValorDominio tipoEvento;

    @ManyToOne
    private ValorDominio estado;

    @OneToMany(mappedBy = "encargo")
    @JsonIgnore
    @Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
    private Set<Pago> pagos = new HashSet<>();

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getImporteTotal() {
        return importeTotal;
    }

    public Encargo importeTotal(Double importeTotal) {
        this.importeTotal = importeTotal;
        return this;
    }

    public void setImporteTotal(Double importeTotal) {
        this.importeTotal = importeTotal;
    }

    public LocalDate getFechaEncargo() {
        return fechaEncargo;
    }

    public Encargo fechaEncargo(LocalDate fechaEncargo) {
        this.fechaEncargo = fechaEncargo;
        return this;
    }

    public void setFechaEncargo(LocalDate fechaEncargo) {
        this.fechaEncargo = fechaEncargo;
    }

    public LocalDate getFechaEntrega() {
        return fechaEntrega;
    }

    public Encargo fechaEntrega(LocalDate fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
        return this;
    }

    public void setFechaEntrega(LocalDate fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

    public String getDetalleVestido() {
        return detalleVestido;
    }

    public Encargo detalleVestido(String detalleVestido) {
        this.detalleVestido = detalleVestido;
        return this;
    }

    public void setDetalleVestido(String detalleVestido) {
        this.detalleVestido = detalleVestido;
    }

    public Cliente getCliente() {
        return cliente;
    }

    public Encargo cliente(Cliente cliente) {
        this.cliente = cliente;
        return this;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Set<Pago> getPagos() {
        return pagos;
    }

    public Encargo pagos(Set<Pago> pagos) {
        this.pagos = pagos;
        return this;
    }

    public Encargo addPago(Pago pago) {
        this.pagos.add(pago);
        pago.setEncargo(this);
        return this;
    }

    public Encargo removePago(Pago pago) {
        this.pagos.remove(pago);
        pago.setEncargo(null);
        return this;
    }

    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }

    /**
	 * @return the tipoEvento
	 */
	public ValorDominio getTipoEvento() {
		return tipoEvento;
	}

	/**
	 * @param tipoEvento the tipoEvento to set
	 */
	public void setTipoEvento(ValorDominio tipoEvento) {
		this.tipoEvento = tipoEvento;
	}

	/**
	 * @return the estado
	 */
	public ValorDominio getEstado() {
		return estado;
	}

	/**
	 * @param estado the estado to set
	 */
	public void setEstado(ValorDominio estado) {
		this.estado = estado;
	}

	@Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Encargo encargo = (Encargo) o;
        if (encargo.id == null || id == null) {
            return false;
        }
        return Objects.equals(id, encargo.id);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(id);
    }

    @Override
    public String toString() {
        return "Encargo{" +
            "id=" + id +
            ", importeTotal='" + importeTotal + "'" +
            ", fechaEncargo='" + fechaEncargo + "'" +
            ", fechaEntrega='" + fechaEntrega + "'" +
            ", detalleVestido='" + detalleVestido + "'" +
            '}';
    }
}
~~~
