### ISSUE TITLE
Deeplinking into gateway doesn't work (e.g. http://jhip.gateway.example/post/1)

### ISSUE THREAD

**Issue by alarv** [jhipster/generator-jhipster#5412]
I've been following your amazing generator and tutorials, thanks for everything you're awesome!

##### **Overview of the issue**

I'm using microservices with Angular 2 (JHipster Generator v4.0.5). I have my Gateway setup on localhost:8080. When I go into production mode, my files are being minified, packed and served on localhost:8080. Tomcat is serving my files and my homepage normally, but when I go to some Angular routes e.g. http://localhost:8080/post/45 and refresh the browser, I get the classic tomcat error shown in the following screenshot:
![screenshot from 2017-03-14 00-17-41](https://cloud.githubusercontent.com/assets/4619900/23879160/b5fe70e4-084b-11e7-950f-d1cba153b7a7.png)

##### **Motivation for or Use Case**

If this is not a bug, please point me to the right direction of where to allow all requests on the gateway that are not for they API. I tried allowing all API requests on ```SecurityConfiguration``` but it doesn't work.

##### **Reproduce the error**

Build a Gateway and try to deeplink into an angular route.

##### **JHipster Version(s)**

JHipster Generator v4.0.5

##### **JHipster Version(s)**

```
sapila-frontend@0.0.0 /home/alarv/projects/sapilaProd/frontend
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
├── UNMET PEER DEPENDENCY ag-grid@8.1.1
└── generator-jhipster@4.0.5 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.5",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "el",
    "languages": [
      "el"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.2.0

npm: 4.0.2

bower: 1.8.0

gulp:
[00:21:00] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.2, build dfed245
