### ISSUE TITLE
version 4.0.8: wrong oracle.version

### ISSUE THREAD

**Issue by micmazza** [jhipster/generator-jhipster#5426]
##### **Overview of the issue**

Using the generator version 4.0.8 and selectiong Oracle DB, the version generated in the pom.xml is 12.1.0.2.0 (instead of 12.1.0.2).

##### **Motivation for or Use Case**

The generated project is not able to download the Oracle driver:

[ERROR] Failed to execute goal on project dbsync: Could not resolve dependencies for project com.italtel.inem.cm:dbsync:war:0.0.1-SNAPSHOT: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact com.oracle.jdbc:ojdbc7:jar:12.1.0.2.0 has not been downloaded from it before. -> [Help 1]

##### **Reproduce the error**

Generate a micorservice application selecting Oracle DB and the generate entities from a JDL file.

##### **Related issues**

No related issues.

##### **Suggest a Fix**

In the pom.xml generate:

<oracle.version>12.1.0.2</oracle.version>

instead of:

<oracle.version>12.1.0.2.0</oracle.version>

##### **JHipster Version(s)**

4.0.8

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\Users\mazzami\vbox_shared\CM-2.0\trunk\neinventory\dbsync
`-- generator-jhipster@4.0.8

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "dbsync",
    "packageName": "com.italtel.inem.cm",
    "packageFolder": "com/italtel/inem/cm",
    "serverPort": "52082",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "oracle",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "0e9e80480d70655fa7d38d222e124fd91a5e9c62",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling",
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

LA_PROPERTY.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dProp",
            "otherEntityName": "logAggr",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "nAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "iVALUE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 300
        },
        {
            "fieldName": "lOGICALAGGREGATIONID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_property",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaCompos.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "cHILDID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "pARENTID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "cHILDFULLQNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "pARENTFULLQNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_compos",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaDomains.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dDomains",
            "otherEntityName": "logAggr",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "lAGGRFULLQNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "sITEDOMAIN",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nETWORKDOMAIN",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "uSERDOMAIN",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lAGGRID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_domains",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaInt.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oIntCred",
            "otherEntityName": "laIntCred",
            "otherEntityRelationshipName": "dIntCred"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dInterface",
            "otherEntityName": "logAggr",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "iTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "iPADDRESS",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lOGICALAGGREGATIONID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_int",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaIntCrAttr.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dIntCredAttr",
            "otherEntityName": "laIntCred",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "nAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "iVALUE",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "eNCRYPT",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 1
        },
        {
            "fieldName": "lAGGRINTERFCREDID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_int_cr_attr",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaIntCred.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oIntCredAttr",
            "otherEntityName": "laIntCrAttr",
            "otherEntityRelationshipName": "dIntCredAttr"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dIntCred",
            "otherEntityName": "laInt",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "iTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "pORT",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lAGGRINTERFACEID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_int_cred",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaMvProp.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oValMVProp",
            "otherEntityName": "laValMvProp",
            "otherEntityRelationshipName": "dValMVProp"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dMVProp",
            "otherEntityName": "logAggr",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "nAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lOGICALAGGREGATIONID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_mv_prop",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaToNode.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "lAGGRTONGNNODEID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "lAGGRFULLQUALIFIEDNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nGNNODEFULLQUALIFIEDNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lAGGRID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "nGNNODEID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_to_node",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LaValMvProp.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dValMVProp",
            "otherEntityName": "laMvProp",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "iVALUE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 255
        },
        {
            "fieldName": "uNIT",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 20
        },
        {
            "fieldName": "lAGGRPROPID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "la_val_mv_prop",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

LogAggr.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oDomains",
            "otherEntityName": "laDomains",
            "otherEntityRelationshipName": "dDomains"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oInterface",
            "otherEntityName": "laInt",
            "otherEntityRelationshipName": "dInterface"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oProp",
            "otherEntityName": "lAPROPERTY",
            "otherEntityRelationshipName": "dProp"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oMVProp",
            "otherEntityName": "laMvProp",
            "otherEntityRelationshipName": "dMVProp"
        }
    ],
    "fields": [
        {
            "fieldName": "fULLQUALIFIEDNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "iTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "sUBTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "fAMILY",
            "fieldType": "Family",
            "fieldValues": "ENTITY,OSS,SIMPLE,NODE"
        },
        {
            "fieldName": "vERSION",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "lOCATION",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "sTATOAMMINISTRATIVO",
            "fieldType": "Status",
            "fieldValues": "ON,OFF"
        },
        {
            "fieldName": "sPECINFO",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 255
        },
        {
            "fieldName": "mODEL",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "vENDOR",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "cREATINGSTATUS",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "gROUPNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "gROUPTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "log_aggr",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

NIntCrAttr.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dNodeIntCredAttr",
            "otherEntityName": "nodeIntCred",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "nAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 25
        },
        {
            "fieldName": "iVALUE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "eNCRYPT",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 1
        },
        {
            "fieldName": "nGNINTERFACECREDENTIALSID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "n_int_cr_attr",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

Node.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oNodeInterface",
            "otherEntityName": "nodeInt",
            "otherEntityRelationshipName": "dNodeInterface"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oNodeProp",
            "otherEntityName": "nodeProp",
            "otherEntityRelationshipName": "dNodeProp"
        }
    ],
    "fields": [
        {
            "fieldName": "nGNNODEFULLQUALIFIEDNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nGNNODENAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nGNNODEHOSTNAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nGNNODETYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "nGNSTATOAMMINISTRATIVO",
            "fieldType": "Status",
            "fieldValues": "ON,OFF"
        },
        {
            "fieldName": "nGNSPECINFO",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 255
        },
        {
            "fieldName": "nGNNODEVERSION",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "nGNNODELOCATION",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        },
        {
            "fieldName": "nGNNODEMODEL",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 50
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "node",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

NodeInt.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oNodeIntCred",
            "otherEntityName": "nodeIntCred",
            "otherEntityRelationshipName": "dNodeIntCred"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dNodeInterface",
            "otherEntityName": "node",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "iTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "iPADDRESS",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nGNENTITYID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "node_int",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

NodeIntCred.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "oNodeIntCredAttr",
            "otherEntityName": "nIntCrAttr",
            "otherEntityRelationshipName": "dNodeIntCredAttr"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dNodeIntCred",
            "otherEntityName": "nodeInt",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "iTYPE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 25
        },
        {
            "fieldName": "pORT",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 15
        },
        {
            "fieldName": "nGNNODEINTERFACEID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "node_int_cred",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

NodeProp.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "dNodeProp",
            "otherEntityName": "node",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "nAME",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "iVALUE",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 100
        },
        {
            "fieldName": "nGNENTITYNODEID",
            "fieldType": "Long",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170316154545",
    "entityTableName": "node_prop",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceImpl"
}
```

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 1.9.5.msysgit.0

node: v6.9.5

npm: 3.10.10

bower: 1.8.0

gulp:
[17:04:46] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.20.3

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7afaa436

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

enum Family {
 ENTITY, OSS, SIMPLE, NODE
}

enum Status {
 ON, OFF
}

enum HaStatus {
 ACTIVE, STANDBY
}

entity LogAggr {
 FULLQUALIFIED_NAME String required maxlength(100),
 NAME               String required maxlength(100),
 ITYPE              String maxlength(100),
 SUB_TYPE           String maxlength(100),
 FAMILY             Family,
 VERSION            String maxlength(100),
 LOCATION          String maxlength(100),
 STATO_AMMINISTRATIVO Status,
 SPEC_INFO String maxlength(255),
 MODEL String maxlength(50),
 VENDOR String maxlength(50),
 CREATING_STATUS String maxlength(50),
 GROUP_NAME String maxlength(100),
 GROUP_TYPE String maxlength(100)
}

entity LaDomains {
 L_AGGR_FULL_QNAME String maxlength(100),
 SITE_DOMAIN String maxlength(100),
 NETWORK_DOMAIN String maxlength(100),
 USER_DOMAIN String maxlength(100),
 L_AGGR_ID Long required
}

entity LaInt {
 ITYPE String required maxlength(100),
 IP_ADDRESS String maxlength(100),
 LOGICAL_AGGREGATION_ID Long required
}

entity LaIntCred {
 ITYPE String required maxlength(100),
 PORT String maxlength(100),
 L_AGGR_INTERFACE_ID  Long required
}

entity LaIntCrAttr {
 NAME String required maxlength(100),
 IVALUE String maxlength(100),
 ENCRYPT String maxlength(1),
 L_AGGR_INTERF_CRED_ID Long required
}

entity LA_PROPERTY {
 NAME String required maxlength(100),
 IVALUE String required maxlength(300),
 LOGICAL_AGGREGATION_ID Long required
}

entity LaMvProp {
 NAME String required maxlength(100),
 LOGICAL_AGGREGATION_ID Long required
}

entity LaValMvProp {
 IVALUE String required maxlength(255),
 UNIT String maxlength(20),
 L_AGGR_PROP_ID Long required
}

entity LaCompos {
 CHILD_ID Long required,
 PARENT_ID Long required, 
 CHILD_FULLQ_NAME String required maxlength(100),
 PARENT_FULLQ_NAME String required maxlength(100)
}

entity Node {
 NGN_NODE_FULLQUALIFIED_NAME String required maxlength(100),
 NGN_NODE_NAME String required maxlength(100),
 NGN_NODE_HOSTNAME String required maxlength(100),
 NGN_NODE_TYPE String maxlength(50),
 NGN_STATO_AMMINISTRATIVO Status,
 NGN_SPEC_INFO String maxlength(255),
 NGN_NODE_VERSION String maxlength(50),
 NGN_NODE_LOCATION String maxlength(50),
 NGN_NODE_MODEL String maxlength(50)
}

entity NodeInt {
 ITYPE String required maxlength(100),
 IP_ADDRESS String maxlength(100),
 NGN_ENTITY_ID Long required
}

entity NodeIntCred {
 ITYPE String required maxlength(25),
 PORT String required maxlength(15),
 NGN_NODE_INTERFACE_ID Long required
}

entity NIntCrAttr {
 NAME String required maxlength(25),
 IVALUE String required maxlength(100),
 ENCRYPT String maxlength(1),
 NGN_INTERFACE_CREDENTIALS_ID Long required
}

entity NodeProp {
 NAME String required maxlength(100),
 IVALUE String required maxlength(100),
 NGN_ENTITY_NODE_ID Long required
}

entity LaToNode {
 L_AGGR_TO_NGN_NODE_ID Long required,
 L_AGGR_FULL_QUALIFIED_NAME String required maxlength(100),
 NGN_NODE_FULL_QUALIFIED_NAME String required maxlength(100),
 L_AGGR_ID Long required,
 NGN_NODE_ID Long required
}

relationship OneToMany {
 LogAggr{oDomains(L_AGGR_ID)} to LaDomains{dDomains},
 LogAggr{oInterface(LOGICAL_AGGREGATION_ID)} to LaInt{dInterface},
 LaInt{oIntCred(L_AGGR_INTERFACE_ID)} to LaIntCred{dIntCred},
 LaIntCred{oIntCredAttr(L_AGGR_INTERF_CRED_ID)} to LaIntCrAttr{dIntCredAttr},
 LogAggr{oProp(LOGICAL_AGGREGATION_ID)} to LA_PROPERTY{dProp},
 LogAggr{oMVProp(LOGICAL_AGGREGATION_ID)} to LaMvProp{dMVProp},
 LaMvProp{oValMVProp(L_AGGR_PROP_ID)} to LaValMvProp{dValMVProp},
 Node{oNodeInterface(NGN_ENTITY_ID)} to NodeInt{dNodeInterface},
 NodeInt{oNodeIntCred(NGN_NODE_INTERFACE_ID)} to NodeIntCred{dNodeIntCred},
 NodeIntCred{oNodeIntCredAttr(NGN_INTERFACE_CREDENTIALS_ID)} to NIntCrAttr{dNodeIntCredAttr},
 Node{oNodeProp(NGN_ENTITY_NODE_ID)} to NodeProp{dNodeProp}
}

dto * with mapstruct
service * with serviceImpl

##### **Browsers and Operating System**

Windows 7

- [x ] Checking this box is mandatory (this is just to show you read everything)
