### ISSUE TITLE
jhipster:client skips authentication part

### ISSUE THREAD

**Issue by gauravlanjekar** [jhipster/generator-jhipster#5429]
##### **Overview of the issue**

Hello guys,
First of all thanks for the amazing hipster :) . It is simply awesome. 
I have been trying to use the jhipster:client and jhipster:server as separate applications. I am using JWT as the authentication. The server app generates fine with all the required stuff. But when generating client It skips the authentication part completely. So I end up with a client that I cannot use with the server. 

As a work around I generate the monolith application and then move out the webapp part of it to a different application

##### **Motivation for or Use Case**

Separating the client will allow me to deploy the client on a highly available CDN as simple static files. And scale the backend as necessary. 

Another use case is to bundle the client as a jar and then plug it in only on the dev profile. or where ever required. 

##### **Reproduce the error**
yo jhipster:server in one folder 
use JWT as authentication.

yo jhipster:client in another

##### **Suggest a Fix**

when generating the client do not skip the authentication flow.

##### **JHipster Version(s)**
3.x

##### **JHipster Version(s)**

```
mateco@0.0.0 /Users/glanjekar/work/mateco-api-ui
└── generator-jhipster@4.0.8 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "clientFramework": "angular1",
    "useSass": false,
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.0

node: v7.7.2

npm: 4.1.2

bower: 1.8.0

gulp:
[10:15:16] CLI version 3.9.1
[10:15:16] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build dfed245
