### ISSUE TITLE
org.springframework.beans.factory.UnsatisfiedDependencyException out of the box

### ISSUE THREAD

**Issue by joaoandremartins** [jhipster/generator-jhipster#5431]
##### **Overview of the issue**

Spring Boot app created by jHipster with OAuth2 auth doesn't run out of the box, and fails with an unintuitive exception.

##### **Motivation for or Use Case**

This falls short of the premise that apps run out of the box, and isn't trivial to fix. There should at least be documentation somewhere that covers a workaround/what to do.

##### **Reproduce the error**

Run the automatically created Spring rule after importing the project to IntelliJ.

##### **Related issues**

No

##### **Suggest a Fix**

Not sure. Either fix the root cause or document missing steps. From the stack trace, it seems there should be some server running on my machine, and there isn't.

##### **JHipster Version(s)**

4.0.8

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "gfx2",
    "packageName": "com.google.gfx",
    "packageFolder": "com/google/gfx",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

Ubuntu

- [x ] Checking this box is mandatory (this is just to show you read everything)
