### ISSUE TITLE
Duplicate administrator navbar entry

### ISSUE THREAD

**Issue by thomas-burko** [jhipster/generator-jhipster#5435]
##### **Overview of the issue**

When I go to the user settings logged in as admin and click on save, it duplicates the Administrator li entry in the navbar. It repeats every time I click on save.

##### **Motivation for or Use Case**

It should not create another li administrator entry.

##### **Reproduce the error**

Create a new JHipster App (everything default, Angular 2)
Log in as admin
Go to Account -> Settings
Click on Save
Watch the navbar

##### **Suggest a Fix**

I'm not sure, but I think the problem caused in the file **has-any-authority.directive.ts**.
When I add the line _this.viewContainerRef.clear();_ in the method updateView() in the if query the problem is resolved. (Between Line 35 and 36). 

##### **JHipster Version(s)**

4.0.8

##### **JHipster Version(s)**

```
demo@0.0.0 /Users/Thomas/Downloads/demo
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.7
├── UNMET PEER DEPENDENCY @angular/core@2.4.7
└── generator-jhipster@4.0.8 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "demo",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

git version 2.12.0

node: v7.7.3

npm: 4.1.2

bower: 1.7.9

gulp:
[17:13:40] CLI version 1.2.2

yeoman: 1.8.5

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7c5d5e4

##### **Browsers and Operating System**

OSx 10.12.3 - Chrome 56

- [x] Checking this box is mandatory (this is just to show you read everything)
