### ISSUE TITLE
missing imageUrl and elasticsearch saves, various other updates with pending pull request

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5441]
##### **Overview of the issue**

Bug/Issues:

Issue 1: UserService.updateUser() and AccountResource.saveAccount()
imageUrl user update from /account REST layer is missing

Issue 2: UserService.updateUser(UserDTO userDTO)
elasticsearch save missing here, so "Admin Panel->User management" items aren't updated, query is getting stale data.

Issue 3: creationEmail.html
Email's link is for password reset key, not new account activation

Issue 4: User.java
email min size of 5 is missing from the Size annotation

Issue 5: AccountResourceIntTest.testRegisterDuplicateLogin():
"getLogin()" called twice instead of "getLastName()"

Issue 6: AccountResourceIntTest.testGetExistingAccount():
Add missing langKey insertion and check

SMALLER ITEMS - Code Cleanup Items

7. User.equals(): replace if else block with "return login.equals(user.login)"
8. activate.json: "Your user has been activated." to "Your user account has been activated."
9. activate.json: "Please" to "Please sign in."
10. comment updates: "succesful" to "successful" and "doesnt" to "doesn't"1
11. ManagedUserVM.java: ",  imageUrl" to ", imageUrl"
12. pom.xml: " </plugins" to "</plugins" (one extra space above </pluginManagement) 
13. ProfileInfoResourceIntTest.java: remove unused import ...beans.factory.annotation.Autowired;
14. RateLimiting.java:  remove unused import ... javax.servlet.http.HttpServletResponse;
15. user-management.components.ts: constructor alignment fixed
16. user-management.components.html: "<th  " to "<th "
17. UserResourceIntTest.java: rename "autorities" to "authorities" across file
18. UserResourceIntTest.updateUserExistingEmail(): remove unused variable "databaseSizeBeforeUpdate"
19. UserResourceIntTest.updateUserExistingLogin(): remove unused variable "databaseSizeBeforeUpdate"
20. UserService.java: "@Transactional(readOnly = true)    " to "@Transactional(readOnly = true)"

##### **Motivation for or Use Case**

These are issues and code clean up that is needed by the community.

##### **Reproduce the error**

For elasticsearch issue:
1. Use Elasticsearch enabled project
2. Update a setting from a normal user, e.g. change the email
3. Go to admin panel - User management and see the update has not come

##### **Related issues**

No

##### **Suggest a Fix**

Already made a pull request with all the fixes.  https://github.com/jhipster/generator-jhipster/pull/5440
#5440 

##### **JHipster Version(s)**

4.0.8 w/ Angular 2

##### **JHipster configuration**

>yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.7
+-- UNMET PEER DEPENDENCY @angular/core@2.4.7
`-- generator-jhipster@4.0.8

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "gtw",
    "packageName": "x.gtw",
    "packageFolder": "x/gtw",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxxxxxxxxxxxxx",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es",
      "tr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.0.windows.1

node: v6.10.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.21.3

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7afaa436

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

Windows 10.  I used Chrome in normal and in private browsing mode.

- [ X ] Checking this box is mandatory (this is just to show you read everything)
