### ISSUE TITLE
.gitattributes makes git mangle binary files unless explicitly listed

### ISSUE THREAD

**Issue by toolforger** [jhipster/generator-jhipster#5456]
##### **Overview of the issue**

The generated `.gitattributes` says

```
# All text files should have the "lf" (Unix) line endings
* text eol=lf
```

The comment diverges from what the file is actually doing: `*` is applying settings to _all files_, `text`is making them text by default, and `eol=lf` is another setting to define a default line ending of `lf` (which is ignored for binary files).

##### **Motivation for or Use Case**

We have corruption in files that the JHipster generator does not know about:
* `*.woff` (font file)
* `*.docx`, `*.xlsx`, and various other documentation files that live in our `/doc` directory.

##### **Reproduce the error**

See @mraible's comment from Oct 21, 2015 in issue #1611.

##### **Related issues**

Issue #1611.

##### **Suggest a Fix**

Multiple possibilities (I'm agnostic about which one to use myself):

* ~Remove `text` from the line above, allowing git to fall back on its autodetection if a text or binary file type isn't in `.gitattributes`.~
* ~Replace `text` with `binary`, making git assume binary format for all file types not in `.gitattributes`. (This also affects not just commit/fetch, but also diff and merge operations.)~
* ~Replace `text` with `-diff -merge`, which makes files non-text by default for commit/fetch and merge but not for diff, allowing git to at least try to diff files that its autodetection detects as text. (Sometimes you want that.)~
* Remove `.gitattributes`, on the grounds that git's autodetection is more reliable than what manual configuration can do. (Or maybe just leave `* eol=lf` in, for the sake of the Windows guys.)

_Turned out that the remaining `eol=lf` tells git to convert CRLF and CR to LF **even if the file is binary**, **still corrupting all binary file types not listed explicitly**. IOW these approaches do not work as described, but could be made to work if you move the `eol=lf` setting to the setting for each file type`._

##### **JHipster Version(s)**

```
ats@0.0.0 /home/jo/Projekte/fincons/ats
└── generator-jhipster@4.1.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "ch.fincons.bern",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "ATS",
    "packageName": "ch.fincons.bern",
    "packageFolder": "ch/fincons/bern",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de",
      "it",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.4.1

bower: 1.8.0

gulp:
[18:06:29] CLI version 3.9.1
[18:06:29] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

This is a freshly generated JHipster directory.

##### **Browsers and Operating System**

Linux, but this should affect all operating systems alike.

- [x] Checking this box is mandatory (this is just to show you read everything)
