### ISSUE TITLE
Not able to login with default username and password

### ISSUE THREAD

**Issue by sumitgargnic** [jhipster/generator-jhipster#5462]
##### **Overview of the issue**

I have created a monolithic app with Angular2. Homepage displayed at localhost:8080. Using Postgres for both Dev and Prod. Tables created. While logging in using default admin:admin or user:user a message is displayed "Failed to sign in! Please check your credentials and try again." .

##### **Motivation for or Use Case**

When i register one more user with the same default password admin. Its encrypted string in Database is different from the one associated with admin user. 

##### **Reproduce the error**

Continuously coming after rebuilding the app several times.

##### **Related issues**

No

##### **Suggest a Fix**

Dont know.

##### **JHipster Version(s)**

4.1.0

##### **JHipster Version(s)**

```
epds@0.0.0 D:\TPDS\epds
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.9
+-- UNMET PEER DEPENDENCY @angular/core@2.4.9
+-- generator-jhipster@4.1.0
`-- UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "nic.hr.epds",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "epds",
    "packageName": "nic.hr.epds",
    "packageFolder": "nic/hr/epds",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.10.1.windows.1

node: v7.7.4

npm: 4.4.1

bower: 1.7.9

gulp:
[12:14:13] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Have not tried

##### **Browsers and Operating System**
Google Chrome and Windows 10

Everywhere
- [- ] Checking this box is mandatory (this is just to show you read everything)
