### ISSUE TITLE
Jhipster-jdl : skipclient not working ?

### ISSUE THREAD

**Issue by fhemery** [jhipster/generator-jhipster#5471]
##### **Overview of the issue**

It looks like the JDL generator is generating client-side code although skipClient option is set. This is the first time I play with the JDL, so I might have missed something obvious.

##### **Motivation for or Use Case**

I would like to generate some entities without any client side code, as these entities will never be displayed as such on the screen.

##### **Reproduce the error**
JH file (simplified):
```
entity Project{
	name String
}

entity Revenue {
	amount Double
}
relationship OneToMany {
	Project{revenues} to Revenue{project}
}

dto * with mapstruct
skipClient for Revenue, Project
```

Then launched:
`yo jhipster:import-jdl environment/bpf_model.jh`

Folder src/webapp/app/entities/project is present and filled with several html / js files.

##### **Related issues**

Last occurrence I saw was issue #3532.

##### **Suggest a Fix**

I honestly have no clue on why the SkipClient is not considered in the file. Feel free to let me know if you need any more information about this.

##### **JHipster Version(s)**

I am using version 4.1.0

##### **JHipster configuration**

.yo-rc.json: 
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "xx.yyy.bpf",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "bpf",
    "packageName": "xx.yyy.bpf",
    "packageFolder": "xx/yyy/bpf",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "--",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Project.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "revenues",
            "otherEntityName": "revenue",
            "otherEntityRelationshipName": "project"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170323114039",
    "javadoc": "",
    "entityTableName": "project",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode

git version 2.7.2.windows.1

node: v7.5.0

npm: 4.4.1

bower: 1.8.0

gulp:
[13:47:22] CLI version 1.2.2
[13:47:22] Local version 3.9.1

yeoman: 1.8.5

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7afaa436

- [x] Checking this box is mandatory (this is just to show you read everything)
