### ISSUE TITLE
jhipster:upgrade failed

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#5485]
##### **Overview of the issue**

Hello,

I've a little bug with new jhipster upgrade.
During the upgrade the package.json is modified and uncommited in the current branch -> upgrade failed.

I've commited manually package.json and relaunch the upgrade command but the  process was always blocking after 2 hours to "Updating generator-jhipster to 4.1.1 . This might take some time...".

I've stopped the process, and relaunched the upgrade. Finally terminaned successfully in few secondes.
3 files was in conflicts. I resolved the conflicts and now all seem ok.

Note: May be it's normal but I notice also that :
`yo jhipster:upgrade` not upgrade the generator-jhipster npm global package :
```
λ npm list -g | grep jhipster
+-- generator-jhipster@4.0.8
| +-- jhipster-core@1.2.8
```


Full output : 
[upgrade_jhispter.txt](https://github.com/jhipster/generator-jhipster/files/870154/upgrade_jhispter.txt)



##### **Motivation for or Use Case**

Use upgrade tool to make Jhipster upgrade more easly.

##### **Reproduce the error**

Use `yo jhipster:upgrade` on jhipster v4.0.8.

##### **Related issues**

N/A

##### **Suggest a Fix**

Update script to commit package.json before check of the unversionning files

##### **JHipster Version(s)**

Project with Jihipster v4.0.8

`λ yo jhipster:info                                                                                               
Welcome to the JHipster Information Sub-Generator                                                                
                                                                                                                 
##### **JHipster Version(s)**                                                                                    
                                                                                                                 
```                                                                                                              
testupgrade@0.1.0 D:\workspaces\jhipster\testupgrade                                                             
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.9                                                                
+-- UNMET PEER DEPENDENCY @angular/core@2.4.9                                                                    
+-- generator-jhipster@4.1.1                                                                                     
`-- UNMET PEER DEPENDENCY zone.js@0.8.2                                                                          
                                                                                                                 
```                                                                                                              
                                                                                                                 
                                                                                                                 
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**                              
                                                                                                                 
```yaml                                                                                                          
{                                                                                                                
  "generator-jhipster": {                                                                                        
    "jhipsterVersion": "4.1.1",                                                                                  
    "baseName": "testupgrade",                                                                                   
    "packageName": "com.mycompany.myapp",                                                                        
    "packageFolder": "com/mycompany/myapp",                                                                      
    "serverPort": "8080",                                                                                        
    "authenticationType": "session",                                                                             
    "hibernateCache": "ehcache",                                                                                 
    "clusteredHttpSession": false,                                                                               
    "websocket": false,                                                                                          
    "databaseType": "sql",                                                                                       
    "devDatabaseType": "h2Disk",                                                                                 
    "prodDatabaseType": "postgresql",                                                                            
    "searchEngine": false,                                                                                       
    "messageBroker": false,                                                                                      
    "serviceDiscoveryType": false,                                                                               
    "buildTool": "maven",                                                                                        
    "enableSocialSignIn": false,                                                                                 
    "rememberMeKey": "54c791cd284b0600985be206d23cd2584c515982",                                                 
    "clientFramework": "angular2",                                                                               
    "useSass": true,                                                                                             
    "clientPackageManager": "yarn",                                                                              
    "applicationType": "monolith",                                                                               
    "testFrameworks": [],                                                                                        
    "jhiPrefix": "jhi",                                                                                          
    "enableTranslation": true,                                                                                   
    "nativeLanguage": "fr",                                                                                      
    "languages": [                                                                                               
      "fr"                                                                                                       
    ]                                                                                                            
  }                                                                                                              
}                                                                                                                
```                                                                                                              
                                                                                                                 
                                                                                                                 
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**                 
                                                                                                                 
ls: no such file or directory: .jhipster/*.json                                                                  
                                                                                                                 
##### **Browsers and Operating System**                                                                          
                                                                                                                 
java version "1.8.0_112"                                                                                         
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)                                                            
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)                                                 
                                                                                                                 
git version 2.11.0.windows.1                                                                                     
                                                                                                                 
node: v6.9.5                                                                                                     
                                                                                                                 
npm: 3.10.10                                                                                                     
                                                                                                                 
yeoman: 1.8.5                                                                                                    
                                                                                                                 
yarn: 0.21.3                                                                                                     
`

- [x] Checking this box is mandatory (this is just to show you read everything)
