### ISSUE TITLE
Swagger interface not using Authorization header

### ISSUE THREAD

**Issue by nicoraynaud** [jhipster/generator-jhipster#5501]
##### **Overview of the issue**

When generating a monolith app, building and running it, the swagger interface under Administration/API is not working as expected.

When debugging, i saw that requests made by swagger interface were not using the Authorization header of the app, thus getting some HTTP 403 Forbidden responses from the server.

I know it was working some time ago, something must have broken it recently.

##### **Motivation for or Use Case**

Be able to use the swagger interface.

##### **Reproduce the error**

Generate a monolith app with JHipster 4.1.1.

##### **Suggest a Fix**

-- no idea

##### **JHipster Version(s)**

JHipster generator-jhipster 4.1.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "nc.opt.sido"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "sido",
    "packageName": "nc.opt.sido",
    "packageFolder": "nc/opt/sido",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "a5fed59aa8712fe4626f200d765c63bc6b4f1356",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

none

##### **Browsers and Operating System**

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

git version 2.11.0.windows.3

node: v6.9.5

npm: 4.1.1

bower: 1.8.0

gulp:
[16:52:21] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.19.1

Docker version 1.13.0, build 49bf474

docker-compose version 1.10.0, build 4bd6f1a0

[x] Checking this box is mandatory (this is just to show you read everything)
