### ISSUE TITLE
Elevation of privileges

### ISSUE THREAD

**Issue by saponace** [jhipster/generator-jhipster#5509]
### **Overview of the issue**

Any user that can log into the application can elevate its privileges to admin by adding a value to a JSON array when retrieving the response of the server to the authentication requests.

##### **Motivation for or Use Case**

This is a security breach

### **Reproduce the error**

- Go to the application home
- Open javascript console
- Place a breakpoint on the file /app/services/auth/principal.service.js on line 79 (line of code: `_identity = account.data;`, in the function getAccountThen(account), in the function identity(force))
- Log in with the default user credentials: login: `user` pwd: `user`
- The execution will stop when reaching this given line
- Look at the value of `account.data` : it is an array with one element : 'ROLE_USER'
- Add a second element to this array: 'ROLE_ADMIN'
- `accoun.data` now has two elements: 'ROLE_USER' and 'ROLE_ADMIN'
- Carry on with the execution
- The user is now logged in with administrator privileges (access to metrics, Swagger API, etc.)

### **Related issues**

I did not see any related issue.

### **Suggest a Fix**

I have no idea how to fix that breach. It seems like fixing it would imply changing a big part of the authorization mechanism (notably: the backend should not accept requests that do not contain a proff of who sent the request). Sorry for the useless suggestion, I do not know anything about authentification :)

### **JHipster Version(s)**
```
generator-jhipster@3.7.0  invalid

```

### **JHipster configuration**
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "3.12.2",
    "baseName": "xxxxxxx",
    "packageName": "org.xxxxxx.xxxxxx",
    "packageFolder": "org/xxxxxx/xxxxxx",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "xxxxxx",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "messageBroker": false,
    "serviceDiscoveryType": false
  }
}
```

### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I can't really share the entityName.json publicly. But I can assure that none of the created entites are the cause of this issue.

### **Browsers and Operating System**

Windows 7, Chrome  56.0.2924.87

- [x ] Checking this box is mandatory (this is just to show you read everything)

I hope this issue will help !
