### ISSUE TITLE
building production war is blocked on PhantomJS

### ISSUE THREAD

**Issue by jeremie-H** [jhipster/generator-jhipster#5518]
##### **Overview of the issue**

I've just generate a empty monolithic project with jhipster 4.1.1, and everything is ok, but if i try to run mvnw -Pprod package, it's stuck on these last lines below. Then nothing appear, and the build is blocked on. Even after 12h, nothing more, and no errors.

##### **traces**
```
[INFO] --- frontend-maven-plugin:1.3:yarn (yarn install) @ monitoring ---
[INFO] Running 'yarn install' in C:\workspaceIntelliJ\monitoring
[INFO] yarn install v0.21.3
[INFO] [1/4] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ node node_modules/pngquant-bin/lib/install.js && node node_modules/phantomjs-prebuilt/install.js && yarn run webpack:build
[ERROR]   v pngquant pre-build test passed successfully
[INFO] Found PhantomJS at C:\workspaceIntelliJ\monitoring\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe ...verifying
[INFO] PhantomJS is previously installed at C:\workspaceIntelliJ\monitoring\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
```

##### **Reproduce the error**

generate a monolithic application, and just run mvnw -Pprod package

##### **JHipster configuration**
C:\workspaceIntelliJ\monitoring>yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
monitoring@0.0.0 C:\workspaceIntelliJ\monitoring
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.9
+-- UNMET PEER DEPENDENCY @angular/core@2.4.9
+-- generator-jhipster@4.1.1
`-- UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.sib.monitoring",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "monitoring",
    "packageName": "fr.sib.monitoring",
    "packageFolder": "fr/sib/monitoring",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "c4afc9daaa7a5b664944704850fecc6113e60f02",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode)
git version 2.9.0.windows.1
node: v6.10.0
npm: 3.10.5
bower: 1.8.0
gulp:
[10:33:50] CLI version 3.9.1
yeoman: 1.8.5
yarn: 0.21.3

- [X] Checking this box is mandatory (this is just to show you read everything)
