### ISSUE TITLE
Doesn't work http request from custom components/services

### ISSUE THREAD

**Issue by SerhiiTsybulskyi** [jhipster/generator-jhipster#5523]
##### **Overview of the issue**

When I create new components and services, http requests doesn't work in my components/services.
Sorry if I some skip and make wrong, but in the simple angular app this(http) works fine.

##### **Motivation for or Use Case**

I want to create own modules based on jHipster

##### **Reproduce the error**

I've created simple example and pushed to this repository
https://github.com/SerhiiTsybulskyi/jhiHttpIssue
See this file: https://github.com/SerhiiTsybulskyi/jhiHttpIssue/blob/master/src/main/webapp/app/test/test.component.ts

##### **Related issues**

Not found

##### **Suggest a Fix**

None

##### **JHipster Version(s)**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.1.1",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2004ea10d6097195fd8020f9c24590f2cd0fecbc",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
git version 2.7.4
node: v7.5.0
npm: 4.1.2
bower: 1.8.0
gulp: CLI version 3.9.1
yeoman: 1.8.5
yarn: 0.19.1

##### **Browsers and Operating System**

Chrome 57

- [x] Checking this box is mandatory (this is just to show you read everything)
