### ISSUE TITLE
Problem while packaging the jhipster app through mvnw -Pprod package

### ISSUE THREAD

**Issue by sumitgargnic** [jhipster/generator-jhipster#5538]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) wth the jHipster tag.
- For bug reports its mandatory to paste the result of command `yo jhipster:info` run in your project root folder.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**

When i run the jhipster app through mvnw and mvnw -Pprod everythiing works fine. but when mvnw -Pprod package All UI gets disturbed and in console there is no error 

##### **Motivation for or Use Case**

needs to package for production hosting

##### **Reproduce the error**
every time  mvnw and mvnw -Pprod everythiing works fine. but when mvnw -Pprod package All UI gets disturbed and in console there is no error 

##### **JHipster Version(s)**

4.0.3

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
epds@0.0.0 F:\Haryana EPDS\HARYANA TPDS 1\epds
`-- generator-jhipster@4.1.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "nic.hr.epds",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "epds",
    "packageName": "nic.hr.epds",
    "packageFolder": "nic/hr/epds",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "hi"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

git version 2.8.1.windows.1

node: v7.8.0

npm: 4.2.0

bower: 1.8.0

gulp:
[14:55:36] CLI version 3.9.1
[14:55:36] Local version 3.9.1

yeoman: 1.8.5
##### **Browsers and Operating System**

Windows 10 and Google Chrome

- [ ] Checking this box is mandatory (this is just to show you read everything)
