### ISSUE TITLE
Unable to register with angular 4

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#5542]
##### **Overview of the issue**

When trying to register a new account you can't access the page, because your are not allowed to open the register page

##### **Motivation for or Use Case**

No registration possible

##### **Reproduce the error**

Generate a new monolithic applications using jwt and angular 4

##### **Related issues**

Nothing found.

##### **Suggest a Fix**

I think the problem is in the `checkLogin` in `UserRouteAccessService.ts`. When the method `hasAnyAuthority` is called on the current principal this method always returns `false` as there is no current principal yet. So from my point of view, when a route has empty authorities (`[ ]`) like `register` it should return always true

##### **JHipster Version(s)**

Latest master.

##### **JHipster Version(s)**

```
matetracker@0.0.0 /home/fred/git/matetracker
├── UNMET PEER DEPENDENCY @angular/common@4.0.0
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
├── generator-jhipster@4.1.1 
└── UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.gitlab.atomfrede.matetracker",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "matetracker",
    "packageName": "com.gitlab.atomfrede.matetracker",
    "packageFolder": "com/gitlab/atomfrede/matetracker",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "cde6ceb8bd1abd7260f20b43a6a1005b95960a7f",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.2

node: v6.9.5

npm: 3.10.10

bower: 1.6.5

gulp:
[07:39:55] CLI version 3.9.0

yeoman: 1.8.5

yarn: 0.19.1

Docker version 17.03.1-ce, build c6d412e329

docker-compose version 1.11.2, build dfed245b

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

No entities generated.

##### **Browsers and Operating System**

Linux with latest Firefox

- [x] Checking this box is mandatory (this is just to show you read everything)

Of course I can provide a PR.
