### ISSUE TITLE
Unable to start microservices using UAA server

### ISSUE THREAD

**Issue by FisherYu-CN** [jhipster/generator-jhipster#5545]
##### **Overview of the issue**

I'm new to JHipster and want to create some demo projects. I created a UAA server and an microservice application. The UAA server is OK and get registered to registry. However, when I try to start the microservice application, it failed with some exceptions below.

```
2017-04-05 22:46:21.213 ERROR 1456 --- [scoveryClient-1] c.netflix.discovery.TimedSupervisorTask  : task supervisor timed out

java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.netflix.discovery.TimedSupervisorTask.run(TimedSupervisorTask.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
2017-04-05 22:47:23.956  WARN 1456 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenStore'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenStore' defined in class path resource [cn/taifinance/app1/config/MicroserviceSecurityConfiguration.class]: Unsatisfied dependency expressed through method 'tokenStore' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAccessTokenConverter' defined in class path resource [cn/taifinance/app1/config/MicroserviceSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtAccessTokenConverter' threw exception; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://uaa/oauth/token_key": Operation timed out (Connection timed out); nested exception is java.net.ConnectException: Operation timed out (Connection timed out)

```

##### **Motivation for or Use Case**

Unable to use UAA server with microservices.

##### **Reproduce the error**

1. create a UAA server
2. create a microservice application
3. run mvn to start JHipster Registry
4. run mvn to start UAA server
5. run mvn to start microservice application

##### **Related issues**

Not found

##### **Suggest a Fix**

Not able to identify the root cause.

##### **JHipster Version(s)**

```
/Users/miyuyu/Workspace/taifinance/uaa
└── generator-jhipster@4.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cn.taifinance.uaa",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "uaa",
    "packageName": "cn.taifinance.uaa",
    "packageFolder": "cn/taifinance/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ],
    "clientPackageManager": "yarn"
  }
}
```

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cn.taifinance.app1",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "app1",
    "packageName": "cn.taifinance.app1",
    "packageFolder": "cn/taifinance/app1",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "e51ff9249e76b1489dfde073d3e3e1010ac4665c",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.10.1

node: v7.8.0

npm: 4.1.2

gulp:
[23:03:22] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245
