### ISSUE TITLE
Build failed on Windows10 Professional

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#5547]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) wth the jHipster tag.
- For bug reports its mandatory to paste the result of command `yo jhipster:info` run in your project root folder.
- Tickets opened without any of these informations will be **closed** without any explanation.

##### **Overview of the issue**
Running "yo jhipster" but build failed on windows10

$ node node_modules/pngquant-bin/lib/install.js && node node_modules/phantomjs-prebuilt/install.js && yarn run webpack:build
  ‼ unable to verify the first certificate
  ‼ pngquant pre-build test failed
  i compiling from source
  × RequestError: pngquant failed to build, make sure that libpng-dev is installed
    at ClientRequest.<anonymous> (D:\dev\jhipster\myApp\node_modules\got\index.js:74:21)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Found PhantomJS at D:\dev\jhipster\myApp\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe ...verifying
PhantomJS is previously installed at D:\dev\jhipster\myApp\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

ERROR in ./src/main/webapp/content/images/logo-jhipster.png
Module build failed: Error: ϵͳ�Ҳ���ָ����·����
    at notFoundError (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 @ ./~/css-loader!./src/main/webapp/app/layouts/navbar/navbar.css 6:1586-1638
 @ ./src/main/webapp/app/layouts/navbar/navbar.css
 @ ./src/main/webapp/app/layouts/navbar/navbar.component.ts
 @ ./src/main/webapp/app/layouts/index.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/content/images/hipster2x.png
Module build failed: Error: ϵͳ�Ҳ���ָ����·����
    at notFoundError (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 @ ./~/css-loader!./src/main/webapp/app/home/home.css 6:896-941
 @ ./src/main/webapp/app/home/home.css
 @ ./src/main/webapp/app/home/home.component.ts
 @ ./src/main/webapp/app/home/index.ts
 @ ./src/main/webapp/app/home/home.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

ERROR in ./src/main/webapp/content/images/hipster.png
Module build failed: Error: ϵͳ�Ҳ���ָ����·����
    at notFoundError (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (D:\dev\jhipster\myApp\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
 @ ./~/css-loader!./src/main/webapp/app/home/home.css 6:307-350
 @ ./src/main/webapp/app/home/home.css
 @ ./src/main/webapp/app/home/home.component.ts
 @ ./src/main/webapp/app/home/index.ts
 @ ./src/main/webapp/app/home/home.module.ts
 @ ./src/main/webapp/app/app.module.ts
 @ ./src/main/webapp/app/app.main.ts

##### **JHipster Version(s)**

PS D:\dev\jhipster\myApp> yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
my-app@0.0.0 D:\dev\jhipster\myApp
+-- UNMET PEER DEPENDENCY @angular/common@4.0.0
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0
+-- generator-jhipster@4.2.0
`-- UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "myApp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d1f7578ed4956ce21a6d4ab5607e8a2459d9a74b",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

git version 2.9.0.windows.1

node: v6.9.5

npm: 4.1.2

bower: 1.8.0

yeoman: 1.8.5

yarn: 0.19.1

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build f963d76f
##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)
