### ISSUE TITLE
UI glitch using post entity hook

### ISSUE THREAD

**Issue by AdrienHorgnies** [jhipster/generator-jhipster#5548]
##### **Overview of the issue**

The output of the last task from the entity generator `install()` and the output from its post hooks collide.

See here the problem using the module `generator-jhipster-entity-audit`. This happens after (re)generating an entity, after all the `identical/overwrite?/force` messages.
```
I'm updating the entity for audit PUCK
 conflict .jhipster/PUCK.json
? Overwrite .jhipster/PUCK.json? (Ynaxdh) [09:37:55] Using gulpfile ~/JHipster/testAudit/gulpfile.js
[09:37:55] Starting 'inject:app'...
[09:37:55] gulp-inject 126 files into index.html.
[09:37:55] Finished 'inject:app' after 215 ms
? Overwrite .jhipster/PUCK.json? (Ynaxdh) 
```

It's because the function `install()` of the entity generator calls `spawnCommand` which is asynchronous.
```javascript
    install() {
        const injectJsFilesToIndex = () => {
            this.log(`\n${chalk.bold.green('Running `gulp inject` to add JavaScript to index.html\n')}`);
            this.spawnCommand('gulp', ['inject:app']);
        };
        // rebuild client for Angular
        const rebuildClient = () => {
            this.log(`\n${chalk.bold.green('Running `webpack:build:dev` to update client app\n')}`);
            this.spawnCommand(this.clientPackageManager, ['run', 'webpack:build:dev']);
        };
        if (!this.options['skip-install'] && !this.skipClient) {
            if (this.clientFramework === 'angular1') {
                injectJsFilesToIndex();
            } else {
                rebuildClient();
            }
        }
    }
```

```javascript
/**
 * Normalize a command across OS and spawn it (asynchronously).
 *
 * @param {String} command
 * @param {Array} args
 * @param {object} [opt]
 */
spawnCommand.spawnCommand = function (command, args, opt) {
  opt = opt || {};
  return spawn(command, args, _.defaults(opt, {stdio: 'inherit'}));
};
```

##### **Motivation for or Use Case**

It's ugly.
The user must enter a character to make the question appear again.
It makes the user very susceptible to make errors, answering without intending to it, ...

Also, I don't exactly know what `install()` does but I guess that if you try to use some files this task modifies, you'll have unpredictable results. Would it make sense to try something like that ? If yes, it's a problem and a bigger one than the UI glitch.

##### **Reproduce the error**

1. Generate a JHipster project : `$yo jhipster`
2. Install a module using a post entity hook : `$npm install generator-jhipster-entity-audit` [optional if you have already such a module]
3. Launch the module : `$ yo jhipster-entity-audit`
4. Create an entity : `yo jhipster:entity FooBar`

##### **Related issues**

None

##### **Suggest a Fix**

I guess using `spawnCommandSync` is not an option ?

Someone suggested making `install()` a promise the post hooks would receive and decide to wait or not.

##### **JHipster Version(s)**

jhipster 4.1.1 but shouldn't be relevant, need to test.

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
test-audit@0.0.0 /home/altissiadev/JHipster/testAudit
└── generator-jhipster@4.1.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.altissia.testapp"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "testAudit",
    "packageName": "com.altissia.testapp",
    "packageFolder": "com/altissia/testapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "838ce718ca56e87f33100f94fd70e1415b1849a7",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

FooBar.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [],
    "changelogDate": "20170406101806",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo_bar",
    "pagination": "no",
    "enableEntityAudit": true
}

```

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 3.10.10

bower: 1.8.0

gulp:
[12:20:03] CLI version 1.2.2
[12:20:03] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.9.0, build 2585387

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```yaml
~/JHipster/testAudit$ cat .jhipster/FooBar.json 
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [],
    "changelogDate": "20170406101806",
    "dto": "no",
    "service": "no",
    "entityTableName": "foo_bar",
    "pagination": "no",
    "enableEntityAudit": true
}
```

##### **Browsers and Operating System**

Shouldn't be relevant but here it is :
Xubuntu 16.04.2, Google Chrome Version 57.0.2987.98 (64-bit).

- [x] Checking this box is mandatory (this is just to show you read everything)
