### ISSUE TITLE
Cannot Run angular-cli to Generate Components

### ISSUE THREAD

**Issue by wicaksana** [jhipster/generator-jhipster#5554]
I wanted to create new Angular 2 component by using angular-cli from the root directory of the project, but got the following error:
``` 
$ ng g component mvp/description

As a forewarning, we are moving the CLI npm package to "@angular/cli" with the next release,
which will only support Node 6.9 and greater. This package will be officially deprecated
shortly after.

To disable this warning use "ng set --global warnings.packageDeprecation=false".

You have to be inside an angular-cli project in order to use the generate command.
```

I didn't change any configuration files, such as package.json or angular-cli.json on the root directory. 

##### **Use case**

It would be really helpful to be able to generate the components using angular-cli.

##### **Reproduce the error**
Generate new JHipster project and then run 'ng generate component <component-name>'

##### **JHipster configuration**

Output of 'yo jhipster:info' :

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
lap@0.0.0 /home/arif/Projects/lap
└── generator-jhipster@4.1.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.streamintelligence",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "lap",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "dasdfasdfasdfa",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v7.7.3

npm: 4.4.4

bower: 1.8.0

yeoman: 1.8.5

yarn: 0.21.3

##### **.yo-rc.json**
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.1",
    "baseName": "lap",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "dasfafqwefadfasdfadsfa",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
I cannot find .jhipster directory in my project or my home directory. 

##### **Browsers and Operating System**
Ubuntu 16.04 with Chrome

- [X] Checking this box is mandatory (this is just to show you read everything)
