### ISSUE TITLE
Hazelcast + Cucumber - Running tests in IDE throws an ApplicationContextException

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5555]
##### **Overview of the issue**

Running tests from IDE's built in test generator throws an Application Context Exception 

##### **Motivation for or Use Case**

JHipster run's tests from command line just fine, but running tests from IDE's using their nice UI's that have colorful pass/fail and store test history don't work without my proposed fix (or possible other configurations not built into JHipster).

##### **Reproduce the error**

1. Open JHipster in Intellij (gradle or maven both have the issue).   More recently using it with Maven though.
2.  IDE will detect tests in Maven/Gradle projects (e.g. for maven "Maven Projects -> Lifecycle -> test" shows up after importing the project.) **EDIT THIS WORKS FINE, ONLY SECOND OPTIONS IS BROKEN:**
  - Also, you can add the tests by right click the Projects tree's src/test/java folder then select "Run 'All Tests'" to run all unit/itests/feature (cucumber) tests (this is better as it shows up in the Configuration drop down menu).
3. For both options in # 2, when you run the test ONE test will fail with: Application Context Exception.  After the first test fails, all the others pass.
 
##### **Related issues**

I searched this issue here and outside but did not find an elegant solution.

##### **Suggest a Fix**

In CacheConfiguration.java:
```
        // Allows running all tests back to back, will throw Application Context Exception otherwise TODO wart?
        HazelcastInstance hazelCastInstance = Hazelcast.getHazelcastInstanceByName(<PROJECT NAME>);
        if(hazelCastInstance == null) {
            hazelCastInstance = Hazelcast.newHazelcastInstance(config);
        }
        return hazelCastInstance;
```

Original code just has:
```
        return Hazelcast.newHazelcastInstance(config);
```

To be safer, we can enable this wart/workaround only to happen when the DEV/test? profile is run.  After several attempts, I was not able to figure out how to detect when the project is running in DEV/test mode (vs. production). 

##### **JHipster Version(s)**

Annoying issue exists for as long as I have used JHipster (over a year).

##### **JHipster configuration**

PS C:\Users\t\hapi\server\gtw> yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gtw@0.0.0 C:\Users\t\hapi\server\gtw
+-- UNMET PEER DEPENDENCY @angular/compiler@2.4.9
+-- UNMET PEER DEPENDENCY @angular/core@2.4.9
+-- generator-jhipster@4.1.1
`-- UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.1.1",
    "baseName": "gtw",
    "packageName": "hapi.gtw",
    "packageFolder": "hapi/gtw",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es",
      "tr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.0.windows.1

node: v7.8.0

npm: 4.2.0

yeoman: 1.8.5

yarn: 0.22.0

Docker version 1.13.1, build 092cba3

docker-compose version 1.11.1, build 7afaa436

- [ X ] Checking this box is mandatory (this is just to show you read everything)

(I love the advanced mark box feature.) :)
