### ISSUE TITLE
Unable to open the home page of gateway correctly when using a UAA server

### ISSUE THREAD

**Issue by FisherYu-CN** [jhipster/generator-jhipster#5571]
##### **Overview of the issue**

Hi, I have generated a UAA server and a gateway. I start both applications by running mvn and they all starts without any errors. However, when I try to access the home page of gateway which is localhost:8080, it cannot load thing correctly. I checked the console of chrome and found the access to the resources are rejected with 401 (Unauthorized).  

![image](https://cloud.githubusercontent.com/assets/3649175/24849135/e1475ace-1dfc-11e7-9ae8-1fed503343af.png)

The strange thing is I can access these resources (links) with postman or even on chrome itself. Besides, I run yarn start on the gateway project and open the home page with localhost:9000, it works as well.

![image](https://cloud.githubusercontent.com/assets/3649175/24849593/155fde7e-1dff-11e7-9a05-4244a4bd592e.png)

##### **Motivation for or Use Case**

Cannot open the home page of gateway correctly.

##### **Reproduce the error**

1. create a UAA server
2. create a microservice gateway application
3. run mvn to start JHipster Registry
4. run mvn to start UAA server
5. run mvn to start microservice gateway application
6. access localhost:8080 on browser

##### **Related issues**

Not found.

##### **Suggest a Fix**

Not sure about the root cause.

##### **JHipster Version(s)**

```
/Users/miyuyu/Workspace/taifinance/taifinance-uaa
└── generator-jhipster@4.2.0 

```

```
tfgateway@0.0.0 /Users/miyuyu/Workspace/taifinance/taifinance-gateway
├── UNMET PEER DEPENDENCY @angular/common@4.0.0
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
├── generator-jhipster@4.2.0 
└── UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cn.taifinance.uaa",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "tfuaa",
    "packageName": "cn.taifinance.uaa",
    "packageFolder": "cn/taifinance/uaa",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ],
    "clientPackageManager": "yarn"
  }
}
```

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cn.taifinance.gateway",
      "nativeLanguage": "zh-cn"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "tfgateway",
    "packageName": "cn.taifinance.gateway",
    "packageFolder": "cn/taifinance/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "tfuaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.10.1

node: v7.8.0

npm: 4.1.2

gulp:
[14:57:03] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.22.0

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245
