### ISSUE TITLE
Configuration page shows [object Object]

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#5576]
##### **Overview of the issue**

The configuration page in admin panel shows key-value properties. But where a value is object, it shows `[object Object]`:

![configuration](https://cloud.githubusercontent.com/assets/7104443/24885411/eed72502-1e56-11e7-8cd5-ff6967a89a57.PNG)

##### **Motivation for or Use Case**

That's not informative.

##### **Suggest a Fix**

Show objects as trees or like json.  When I used JHipster 3.x, there was a json.

##### **JHipster Version(s)**

```
sample@0.0.0 D:\jhipster
+-- UNMET PEER DEPENDENCY @angular/common@4.0.0
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0
+-- generator-jhipster@4.2.0
`-- UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.sample",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "sample",
    "packageName": "com.sample",
    "packageFolder": "com/sample",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "rememberMeKey": "",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.0.windows.1

node: v6.10.0

npm: 3.10.10

yarn: 0.21.3

- [x] Checking this box is mandatory (this is just to show you read everything)
