### ISSUE TITLE
[MapStruct] Displaying image BLOB field in one-to-one relationships fails to build

### ISSUE THREAD

**Issue by rhanberry** [jhipster/generator-jhipster#5577]
##### **Overview of the issue**

When generating an app with a one-to-one relationship where the owner side of the relationship diaplays a BLOB image the app fails to compile. 

##### **Motivation for or Use Case**

I would like to display the image field of the relationship using a one-to-one relationship. I have replicated this issue with Postgres and MySQL databases, functionality for displaying String types remains functional in both cases. I can make it work, but it is a pain to go back in and manually modify a bare bones app that should be generated correctly the first time.  I have developed workarounds, but I haven't had time to dig into the generator and make a PR for a fix.

##### **Reproduce the error**

Generate (monolithic) app as normal, two entities, one with fields, one related to first without fields. Angular 1.x, hibernate cache single node, no LibSASS, Postgres or MySQL, no internationalization, JWT authentication, DTO with mapstruct.  See below info for complete app details

Generate the app as normal and it fails to build without extensive manual modification

##### **Related issues**

I have searched and am unable to find this issue documented

##### **Suggest a Fix**

Stacktrace indicates following error: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project dbexperimenter: Compilation failure
[ERROR] /home/vagrant/Desktop/exp1/src/main/java/com/dbexperimenter/service/mapper/RelMapper.java:[17,12] Can't map property "byte[] rel.app.appimage" to "java.lang.String appAppimage". Consider to declare/implement a mapping method: "java.lang.String map(byte[] value)"

There is an appropriate mapper in the mapper class, but in the DTO the image type is mistyped as String instead of byte[], changing this manually has worked, but it is clunky to go in and change it every time I want to generate an app with this relation.

##### **JHipster Version(s)**

This issue has been noted in all versions from current back to 3.1.0 (could have been happening earlier, but have not documented)

##### **JHipster configuration**

➜  exp1 yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
dbexperimenter@0.0.0 /home/vagrant/Desktop/exp1
└── generator-jhipster@4.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.dbexperimenter"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "dbexperimenter",
    "packageName": "com.dbexperimenter",
    "packageFolder": "com/dbexperimenter",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f7906d81d798294806dfc23f394a43cc40756a74",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

App.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "rel",
            "otherEntityName": "rel",
            "relationshipType": "one-to-one",
            "ownerSide": false,
            "otherEntityRelationshipName": "app"
        }
    ],
    "fields": [
        {
            "fieldName": "apptitle",
            "fieldType": "String"
        },
        {
            "fieldName": "appimage",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20170410211607",
    "dto": "mapstruct",
    "service": "no",
    "entityTableName": "app",
    "pagination": "no"
}

```

Rel.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "app",
            "otherEntityName": "app",
            "relationshipType": "one-to-one",
            "otherEntityField": "appimage",
            "ownerSide": true,
            "otherEntityRelationshipName": "rel"
        }
    ],
    "fields": [],
    "changelogDate": "20170410212201",
    "dto": "mapstruct",
    "service": "no",
    "entityTableName": "rel",
    "pagination": "infinite-scroll"
}

```

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.2

npm: 4.4.4

bower: 1.8.0

gulp:
[22:35:36] CLI version 3.9.1
[22:35:36] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.04.0-ce, build 4845c56

docker-compose version 1.12.0, build b31ff33

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

App.json: 
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "rel",
            "otherEntityName": "rel",
            "relationshipType": "one-to-one",
            "ownerSide": false,
            "otherEntityRelationshipName": "app"
        }
    ],
    "fields": [
        {
            "fieldName": "apptitle",
            "fieldType": "String"
        },
        {
            "fieldName": "appimage",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20170410211607",
    "dto": "mapstruct",
    "service": "no",
    "entityTableName": "app",
    "pagination": "no"
}

Rel.json:

{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "app",
            "otherEntityName": "app",
            "relationshipType": "one-to-one",
            "otherEntityField": "appimage",
            "ownerSide": true,
            "otherEntityRelationshipName": "rel"
        }
    ],
    "fields": [],
    "changelogDate": "20170410212201",
    "dto": "mapstruct",
    "service": "no",
    "entityTableName": "rel",
    "pagination": "infinite-scroll"
}

##### **Browsers and Operating System**

This has happened in OSX and using the jhipster Vagrant devbox and using a variety of different versions back to the early 3's

- [*] Checking this box is mandatory (this is just to show you read everything)
