### ISSUE TITLE
Absolute path bug in webpack.vendor.js

### ISSUE THREAD

**Issue by svict4** [jhipster/generator-jhipster#5580]
##### **Overview of the issue**

Bug. Was attempting to run `docker:build` when I found I didn't have webpack installed globally. When I ran `yarn add global webpack` it would run the `webpack:build` script and error with the following: 

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./target/www" is not an absolute path!
```

##### **Motivation for or Use Case**

Opening issue per guidelines.

##### **Reproduce the error**

On Windows, run `yarn run ngc && webpack --config webpack/webpack.vendor.js && webpack --config webpack/webpack.dev.js`

##### **Suggest a Fix**

Simply needs path.resolve in webpack.vendors.js
Submitting a pull request. 

##### **JHipster Version(s)**

```
irl-assign@0.0.0 C:\Users\email\Documents\irl-assign
`-- generator-jhipster@4.2.0

```

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.irl.assign"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "irlAssign",
    "packageName": "com.irl.assign",
    "packageFolder": "com/irl/assign",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "6e85759f354a8cf5f513ccb48fd44b00bb36cdfe",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.9.4

npm: 4.4.4

bower: 1.7.9

gulp:
[23:07:08] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.22.0

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.1, build 7afaa436

- [x] Checking this box is mandatory (this is just to show you read everything)
