### ISSUE TITLE
Alert Service clear is not working

### ISSUE THREAD

**Issue by santoshkt** [jhipster/generator-jhipster#5585]
##### **Overview of the issue**

This might belong to ng-jhipster but I am creating the ticket here. I am calling this.alertService.clear() from a component but the alerts in the page are not getting cleared.

##### **Motivation for or Use Case**

I want to clear the alerts on submit so that any existing messages are removed before displaying new messages. I do not want to use alert auto clear/timeout/dismissal.

##### **Reproduce the error**

Create an alert from any component that uses alert service. Clear the alert using a button or some action.

For quick testing purposes you can checkout my git project or just add lines from this - https://github.com/santoshkt/ngx-pipes-test/commit/9cd9ff410b01ae20918f9e3cfb7139d0bed728bb

##### **JHipster configuration**
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.0.8",
    "baseName": "jhipster",
    "packageName": "com.github.santoskt.ngxpipes",
    "packageFolder": "com/github/santoskt/ngxpipes",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2d99b780856b9651aecf8fe9c51ed01e38455852",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
git version 2.12.0
node: v7.7.2
npm: 4.1.2
bower: 1.8.0
gulp:
[21:14:53] CLI version 3.9.1
yeoman: 1.8.5
yarn: 0.21.3
Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.11.2, build dfed245

- [x] Checking this box is mandatory (this is just to show you read everything)
