### ISSUE TITLE
[Suggestion] remove sortpom

### ISSUE THREAD

**Issue by mbergumi** [jhipster/generator-jhipster#5621]
##### **Overview of the issue**
For those trying to stick to the maven release scheme, the sortpom fucks up the build order when reordering plugins. Since it is executed in the verify step, it will be performed and persisted in SCM during the release:prepare phase. 

##### **Motivation for or Use Case**
I am trying to stick to the Maven build cycle so i can use its versioning system. 

##### **Reproduce the error**
compare the plugin call order between
     `./mvnw -Pprod clean package`
and
     `[ ./mvnw -Pprod release:prepare &&] ./mvnw -Pprod release:perform`

##### **Related issues**
None i could find

##### **Suggest a Fix**
Remove or reconfigure sortpom plugin?

##### **JHipster Version(s)**
4.2.0 until yarn stops removing parts of tslint.

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**
```
test-release@0.0.0 /Users/matthieubertin/Workspaces/experimental/test_release
├── UNMET PEER DEPENDENCY @angular/common@4.0.0
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
├── generator-jhipster@4.2.0
└── UNMET PEER DEPENDENCY zone.js@0.8.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "test_release",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

git version 2.12.2

node: v7.9.0

npm: 4.2.0

bower: 1.8.0

gulp:
[17:19:41] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.04.0-ce, build 4845c56

docker-compose version 1.12.0, build b31ff33

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**
Mac OS Sierra (v 10.12.4 (16E195))

- [x] Checking this box is mandatory (this is just to show you read everything)
