### ISSUE TITLE
JDL generates java code with compilation error when using Cassandra + pagination

### ISSUE THREAD

**Issue by viniciusboson** [jhipster/generator-jhipster#5639]
##### **Overview of the issue**

As JHipster generation doesn't support pagination for Cassandra db. When a user tries to generate an entity via JDL using cassandra db + pagination, the output code doesn't compile.

##### **Motivation for or Use Case**

Here's the compilation error after a JDL generation using Cassandra + pagination:

```
~/dev/jhipster/src/main/java/test/jhipster/service/impl/PositionServiceImpl.java:60: error: method findAll in class PositionRepository cannot be applied to given types;
        Page<Position> result = positionRepository.findAll(pageable);
                                                  ^
  required: no arguments
  found: Pageable
  reason: actual and formal argument lists differ in length
```

##### **Reproduce the error**

 * Generate an Monolith application having Cassandra DB.
 * Start up Cassandra docker container, applying [Migration tool](https://jhipster.github.io/using-cassandra/)
 * Import a new entity using [JDL](https://jhipster.github.io/jdl/) with pagination 
`paginate <entity> with pagination`
 * Try to compile the code: `./gradlew`

##### **Related issues**

I have not found a related issue

##### **Suggest a Fix**

I believe  JDL generator could validate this invalid combination (cassandra + pagination) when it parses the file, preventing bad code generation.

##### **JHipster Version(s)**

JHipster Generator v4.3.0

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "test.jhipster"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "jhipster",
    "packageName": "test.jhipster",
    "packageFolder": "test/jhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170422130133",
    "entityTableName": "position",
    "dto": "mapstruct",
    "pagination": "pagination",
    "service": "serviceImpl"
}
```

##### **Browsers and Operating System**

```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0

node: v6.10.2

npm: 3.10.10

bower: 1.8.0

gulp:
[10:27:51] CLI version 1.2.2
[10:27:51] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.23.2

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245
```

- [x] Checking this box is mandatory (this is just to show you read everything)
