### ISSUE TITLE
JHipster 4.3.0 unable to create production build

### ISSUE THREAD

**Issue by waqas80** [jhipster/generator-jhipster#5644]
I updated the JHipster to latest version 4.3.0. I created a simple application a monolithic one. And build the project. It works perfectly fine. But when I create a production build with the following command ./mvnw -Pprod package;   I am getting the below error

[INFO] > myblog@0.0.0 ngc /Users/waqas80/Documents/jhip-proj/myblog
[INFO] > ngc -p tsconfig-aot.json
[INFO] 
[ERROR] Warning: Can't resolve all parameters for AlertService in /Users/waqas80/Documents/jhip-proj/myblog/node_modules/ng-jhipster/src/service/alert.service.d.ts: ([object Object], ?, [object Object]). This will become an error in Angular v5.x
[ERROR] Warning: Can't resolve all parameters for InterceptableHttp in /Users/waqas80/Documents/jhip-proj/myblog/node_modules/ng-jhipster/src/interceptor/interceptable-http.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
[ERROR] Template parse warnings:
[ERROR] The <template> element is deprecated. Use <ng-template> instead ("
[ERROR]   <div class="card">
[ERROR]     [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
[ERROR]       <div role="tab" id="{{panel.id}}-header"
[ERROR]         "): ng:///Users/waqas80/Documents/jhip-proj/myblog/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4
[INFO] Hash: b0a3d30ef41a8b83663d
[INFO] Version: webpack 2.3.3

And the below warning messages also appear,

[INFO]     [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 944 bytes {0} [built]
[WARNING] npm WARN angular2-cookie@1.2.6 requires a peer of @angular/common@^2.0.0 but none was installed.
[WARNING] npm WARN angular2-cookie@1.2.6 requires a peer of @angular/core@^2.0.0 but none was installed.
[WARNING] npm WARN ng-jhipster@0.1.12 requires a peer of @angular/core@4.0.0 but none was installed.
[WARNING] npm WARN ng-jhipster@0.1.12 requires a peer of @angular/http@4.0.0 but none was installed.
[WARNING] npm WARN ng2-translate@4.2.0 requires a peer of @angular/core@^2.0.0 but none was installed.
[WARNING] npm WARN ng2-translate@4.2.0 requires a peer of @angular/http@^2.0.0 but none was installed.
[INFO] 

Below is the info generated by JHipster info command 
##### **JHipster Version(s)**

```
myblog@0.0.0 /Users/waqas80/Documents/jhip-proj/myblog
└── generator-jhipster@4.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.enfocarsoft.myblog"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "myblog",
    "packageName": "com.enfocarsoft.myblog",
    "packageFolder": "com/enfocarsoft/myblog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "6786ea6f4be82863f6229cfc4ff4bd55f032536c",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

node: v6.10.0

npm: 4.6.1

yeoman: 1.8.5

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build dfed245
