### ISSUE TITLE
Jhipster:aws -->"s3.upload is not a function"

### ISSUE THREAD

**Issue by p-stav** [jhipster/generator-jhipster#5648]
##### **Overview of the issue**

I have been trying to upload a simple monolithic application to aws, and continuously get this error: 
```TypeError: s3.upload is not a function```

##### **Motivation for or Use Case**
When I run `jhipster:aws`, given that I've all the necessary dependencies installed and configured, I expect the application to deploy to aws

##### **Reproduce the error**
1) run `yo jhipster` and create a new monolithic application
2) after complete, run `yo jhipster:aws` 

When I do this, I get the below stacktrace:
```
TypeError: s3.upload is not a function
    at Response.s3.waitFor (/Users/paulstavropoulos/Documents/jhipster_tutorials/jhipster_monolithic_2/node_modules/generator-jhipster/generators/aws/lib/s3.js:116:16)
    at Request.<anonymous> (/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:350:18)
    at Request.callListeners (/Users/paulstavropoulos/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/Users/paulstavropoulos/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/Users/paulstavropoulos/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/paulstavropoulos/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:606:12)
```

##### **Related issues**
I've found similar issues about time outs of this same s3.upload command, but not this error. 

##### **Possible Issues?**
I have to believe that perhaps I've the wrong version of the aws sdk setup or something?
I simply ran `npm install aws-sdk`, and also tried downloading the awscli as well when that didn't work. I've also tried uninstalling both and reinstalling 

##### **JHipster Version(s)**
I'm using Jhipster 4
`JHipster Generator v4.3.0`

##### **JHipster configuration**
Result from yo jhipster:info
```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example.jhipster_monolith_2"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "jhipster_monolithic_2",
    "packageName": "com.example.jhipster_monolith_2",
    "packageFolder": "com/example/jhipster_monolith_2",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "<REMOVED>,
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Browsers and Operating System**

I'm on mac os sierra 10.12.4
This seems to be agnostic of browser. 

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
You do not need to install anything, the `yo jhipster:aws` subgenerator should install the AWS library automatically. Could you delete your `node_modules` and try again?

**Comment by deepu105** [comment]
I think for AWS the aws-sdk needs to be installed manually as we dont do it automatically I believe

**Comment by p-stav** [comment]
I've tried Julien's suggestion. After creating a new Jhipster monolithic
application, I still remained with the same error:

```

TypeError: s3.upload is not a function

    at Response.s3.waitFor
(/Users/paulstavropoulos/Documents/jhipster_tutorials/jhipster_monolith_ex_2/node_modules/generator-jhipster/generators/aws/lib/s3.js:116:16)

    at Request.<anonymous>
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:350:18)

    at Request.callListeners
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/sequential_executor.js:100:18)

    at Request.emit
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/sequential_executor.js:77:10)

    at Request.emit
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:604:14)

    at Request.transition
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:21:12)

    at AcceptorStateMachine.runTo
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/state_machine.js:14:12)

    at
/Users/paulstavropoulos/node_modules/aws-sdk/lib/state_machine.js:26:10

    at Request.<anonymous>
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:22:9)

    at Request.<anonymous>
(/Users/paulstavropoulos/node_modules/aws-sdk/lib/request.js:606:12)

```


Any thoughts?
Cheers!
Paul

**Comment by deepu105** [comment]
Can you please run `yo jhipster:info` and copy paste the entire output

**Comment by p-stav** [comment]
Sure !

Here is the entire output:
===
===





```

Pauls-MacBook-Pro:jhipster_monolith_ex_2 paulstavropoulos$ yo jhipster:info

Welcome to the JHipster Information Sub-Generator

```

##### **JHipster Version(s)**


```

jhipster-monolith-ex-2@0.0.0
/Users/paulstavropoulos/Documents/jhipster_tutorials/jhipster_monolith_ex_2

└── generator-jhipster@4.3.0


```



##### **JHipster configuration, a `.yo-rc.json` file generated in the root
folder**


```yaml

{

  "generator-jhipster": {

    "promptValues": {

      "packageName": "com.example.jhipster_monolith_postgres"

    },

    "jhipsterVersion": "4.3.0",

    "baseName": "jhipster_monolith_ex_2",

    "packageName": "com.example.jhipster_monolith_postgres",

    "packageFolder": "com/example/jhipster_monolith_postgres",

    "serverPort": "8080",

    "authenticationType": "jwt",

    "hibernateCache": "hazelcast",

    "clusteredHttpSession": false,

    "websocket": false,

    "databaseType": "sql",

    "devDatabaseType": "h2Memory",

    "prodDatabaseType": "mysql",

    "searchEngine": false,

    "messageBroker": false,

    "serviceDiscoveryType": false,

    "buildTool": "maven",

    "enableSocialSignIn": true,

    "jwtSecretKey": "<REMOVED_BY_ME>",

    "clientFramework": "angular1",

    "useSass": true,

    "clientPackageManager": "yarn",

    "applicationType": "monolith",

    "testFrameworks": [

      "gatling",

      "cucumber",

      "protractor"

    ],

    "jhiPrefix": "jhi",

    "enableTranslation": false

  }

}

```



##### **Entity configuration(s) `entityName.json` files generated in the
`.jhipster` directory**


ls: no such file or directory: .jhipster/*.json


##### **Browsers and Operating System**


java version "1.8.0_121"

Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)


git version 2.12.2


node: v7.9.0


npm: 4.2.0


bower: 1.8.0


gulp:

[15:42:12] CLI version 3.9.1

[15:42:12] Local version 3.9.1


yeoman: 1.8.5


yarn: 0.22.0


Docker version 17.03.1-ce, build c6d412e


docker-compose version 1.11.2, build dfed245
