### ISSUE TITLE
Unable to generate entity named 'Subscription' in Angular 4 app

### ISSUE THREAD

**Issue by jCube1980** [jhipster/generator-jhipster#5652]
##### **Overview of the issue**

Unable to generate entity named 'Subscription' in Angular 4 app. 

##### **Motivation for or Use Case**

Subscription is a common entity in many verticals. Being unable to generate a 'Subscription' could be a show-stopper in some projects.

##### **Reproduce the error**

Create an Angular4 app with a basic entity named Subscription. Running `yarn install` fails with the following error.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:3:10
    TS2300: Duplicate identifier 'Subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:6:10
    TS2300: Duplicate identifier 'Subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:15:5
    TS2687: All declarations of 'subscription' must have identical modifiers.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:16:13
    TS2300: Duplicate identifier 'subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:16:13
    TS2403: Subsequent variable declarations must have the same type.  Variable 'subscription' must be of type 'Subscription', but here has type 'any'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:16:13
    TS2687: All declarations of 'subscription' must have identical modifiers.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:35:13
    TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:35:13
    TS90010: Type 'Subscription' is not assignable to type 'Subscription'. Two different types with this name exist, but they are unrelated.
  Property 'closed' is missing in type 'Subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription-detail.component.ts:48:134
    TS2339: Property 'id' does not exist on type 'Subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription.component.ts:4:10
    TS2300: Duplicate identifier 'Subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription.component.ts:7:10
    TS2300: Duplicate identifier 'Subscription'.

ERROR in [at-loader] ./src/main/webapp/app/entities/subscription/subscription.component.ts:50:21
##### **JHipster Version(s)**

```
subscription-test@0.0.0 E:\projects\jhipster\subscription-test
+-- UNMET PEER DEPENDENCY @angular/common@4.0.0
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0
`-- generator-jhipster@4.3.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "SubscriptionTest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "0c75eb6a7a7e887ae925324073bfc6135875db74",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Subscription.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170423051400",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "subscription",
    "pagination": "no"
}

```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.10.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.23.2

- [X] Checking this box is mandatory (this is just to show you read everything)
