### ISSUE TITLE
New CanActivate implementation in UserRouteAccessService does not work

### ISSUE THREAD

**Issue by uboznikov** [jhipster/generator-jhipster#5659]
- Please follow the issue template below for bug reports and feature requests.
- If you have a support request rather than a bug please use [stackoverflow](http://stackoverflow.com/questions/tagged/jhipster) with the JHipster tag.
- For bug reports its mandatory to paste the result of command `yo jhipster:info` run in your project root folder.
- Tickets opened without any of these pieces of information will be **closed** without any explanation.

##### **Overview of the issue**

Typing an activated route URL directly in the browser does not enforce roles.

##### **Motivation for or Use Case**

If a logged-in user has a role of `ROLE_USER` only, this user can navigate to routes reserved for `ROLE_ADMIN` by typing it straight in the browser's address field. For example, `http://localhost:9000/#/jhi-metrics`. This is also true for any role added.

##### **Reproduce the error**

Please see above.

##### **Related issues**

I'm not sure if there is a related issue; encountered only in v4.3.0 thus far.

##### **Suggest a Fix**

Reverted to the old implementation for now:

```
    canActivate(route: ActivatedRouteSnapshot): boolean | Promise<boolean> {
        return this.auth.authorize(false).then((canActivate) => canActivate);
    }
```

##### **JHipster Version(s)**

v4.3.0

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway@1.0.0
├── UNMET PEER DEPENDENCY @angular/common@4.0.0
├── UNMET PEER DEPENDENCY @angular/core@4.0.0
├── UNMET PEER DEPENDENCY bootstrap@4.0.0-alpha.6
└── generator-jhipster@4.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.3.0",
    "baseName": "gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "clientFramework": "angular2"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```


##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0

node: v6.10.2

npm: 3.10.10

gulp:
[16:12:33] CLI version 3.9.1

yeoman: 1.8.5

yarn: 0.23.2

Docker version 17.04.0-ce, build 4845c56

docker-compose version 1.11.2, build dfed245

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

##### **Browsers and Operating System**

Google Chrome, Ubuntu 17.04 64-bit

- [X] Checking this box is mandatory (this is just to show you read everything)
