### ISSUE TITLE
The generated UI to create/edit users is not validating the email's min length

### ISSUE THREAD

**Issue by chomnoue** [jhipster/generator-jhipster#5673]
##### **Overview of the issue**

As an administrator, when I try to add a new user with an email such as **1@1**, 
the UI allows me to save, but a validation error happens in the back end, as the 
email length is less than 5 characters.

2017-04-27 10:33:11.204 ERROR 18021 --- [ XNIO-2 task-29] c.c.bookshop.aop.logging.LoggingAspect   : Exception in com.chomnoue.bookshop.web.rest.UserResource.createUser() with cause = 'NULL' and exception = 'Validation failed for classes [com.chomnoue.bookshop.domain.User] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='size must be between 5 and 100', propertyPath=email, rootBeanClass=class com.chomnoue.bookshop.domain.User, messageTemplate='{javax.validation.constraints.Size.message}'}
]'

javax.validation.ConstraintViolationException: Validation failed for classes [com.chomnoue.bookshop.domain.User] during persist time for groups [javax.validation.groups.Default, ]
List of constraint violations:[
	ConstraintViolationImpl{interpolatedMessage='size must be between 5 and 100', propertyPath=email, rootBeanClass=class com.chomnoue.bookshop.domain.User, messageTemplate='{javax.validation.constraints.Size.message}'}
]
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.validate(BeanValidationEventListener.java:140)
	at org.hibernate.cfg.beanvalidation.BeanValidationEventListener.onPreInsert(BeanValidationEventListener.java:80)
	at org.hibernate.action.internal.EntityIdentityInsertAction.preInsert(EntityIdentityInsertAction.java:197)
	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:75)
	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:623)
	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:277)
	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:258)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:303)
	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:67)
	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:189)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:132)
	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:58)
	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:773)
	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:758)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
	at com.sun.proxy.$Proxy142.persist(Unknown Source)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor

##### **Motivation for or Use Case**

Just as other validations made in the UI, the email min length must be checked in the UI for a better
user experience. 
Currently the user just receives an **Internal server error** message after clicking on **Save**, which
doesn't tell him much on the issue he is facing.

##### **Reproduce the error**

Login as administrator and try to create a new user with email : 1@1

##### **Suggest a Fix**

Add min length validation to the **email** field in app/admin/user-management/user-management-dialog.html:

* Add ng-minlength="5" attribute to the email input tag
* Add the following under   `<div ng-show="editForm.email.$invalid">`

`<p class="help-block" ng-show="editForm.email.$error.minlength" data-translate="entity.validation.minlength"  translate-value-min="5"> This field should be at least 5 characters. </p>`

##### **JHipster Version(s)**

```
bookshop@0.0.0 /home/chomnoue/projects/training/jhipster/bookshop-angular1
└── generator-jhipster@4.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.chomnoue.bookshop",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "bookshop",
    "packageName": "com.chomnoue.bookshop",
    "packageFolder": "com/chomnoue/bookshop",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "rememberMeKey": "**********************",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Author.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "books",
            "otherEntityName": "book",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "author"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "5"
        },
        {
            "fieldName": "birthDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170420081157",
    "dto": "no",
    "service": "no",
    "entityTableName": "author",
    "pagination": "infinite-scroll"
}

```

Book.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "author",
            "otherEntityName": "author",
            "relationshipType": "many-to-one",
            "relationshipValidateRules": [
                "required"
            ],
            "otherEntityField": "name"
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "5"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "publicationDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "price",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required",
                "min"
            ],
            "fieldValidateRulesMin": "0"
        }
    ],
    "changelogDate": "20170420082216",
    "dto": "no",
    "service": "no",
    "entityTableName": "book",
    "pagination": "infinite-scroll"
}

```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.1

npm: 3.10.10

bower: 1.8.0

gulp:
[11:30:08] CLI version 1.2.2
[11:30:08] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.22.0

Docker version 17.03.1-ce, build c6d412e32

##### **Browsers and Operating System**

I tested with Chrome browser in Linux Mint 18.1

- [X] Checking this box is mandatory (this is just to show you read everything)
