### ISSUE TITLE
On session expired , Login modal window does not open

### ISSUE THREAD

**Issue by srouaix** [jhipster/generator-jhipster#5683]
##### **Overview of the issue**

On session expired, Jhipster doesn't correctly manage the use case and doesn't open the login modal due to error in javascript .

##### **Reproduce the error**
Change the expiration of the token to a short delay.
You authenticate on Jhipster
You wait the delay
You open for exemple Audit in the Administration menu.

##### **Suggest a Fix**
It seems that storeDestinationState method is never called onStateStorageService to set the destination.
The error in the Chrome console is :  

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'destination' of null
TypeError: Cannot read property 'destination' of null
    at AuthService.authThen (auth.service.ts:25)
```   

##### **JHipster Version(s)**

```
jhipster@0.0.0 C:\kids\workspace\jhipster4.3
`-- generator-jhipster@4.3.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde
r**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d09b10ea7671b78bf26e0be3cbfc76435a566bdb",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhips
ter` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.9.0.windows.1

node: v6.10.0

npm: 4.5.0

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.0-ce, build 60ccb22

docker-compose version 1.11.2, build f963d76f

Windows 7

Tested on last Chrome version

- [x] Checking this box is mandatory (this is just to show you read everything)
