### ISSUE TITLE
Error in model.ts when using relationship with angularSuffix

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#5708]
##### **Overview of the issue**
After running "yo jhipster:import-jdl my.jh", I get the following error

Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html] ./~/html-webpack-plugin/lib/loader.js!./src/main/webapp/index.html 987 bytes {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

##### **Motivation for or Use Case**

This problem causes an incomplete front end code.

##### **Reproduce the error**

Selected components:

Angular 2
Multiple languages: en, fr, et
Social login

##### **JHipster Version(s)**

https://github.com/jhipster/generator-jhipster/issues/5400
https://github.com/jhipster/generator-jhipster/issues/5161

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
blog@0.0.0 /home/oem/Workspace-dev/jh/blog
├── generator-jhipster@4.3.0 
├─┬ generator-jhipster-darktheme@0.0.7
│ └── generator-jhipster@4.3.0  deduped
├─┬ generator-jhipster-entity-audit@2.4.0
│ └── generator-jhipster@4.3.0  deduped
└─┬ generator-jhipster-google-maps@0.0.1
  └── generator-jhipster@2.25.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.vw.blog",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "blog",
    "packageName": "com.vw.blog",
    "packageFolder": "com/vw/blog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "c3e75344881ebca279303c471fc1336c9b02ff95",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-entity-audit",
        "version": "2.4.0"
      },
      {
        "name": "generator-jhipster-darktheme",
        "version": "0.0.7"
      },
      {
        "name": "generator-jhipster-google-maps",
        "version": "0.0.1"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr",
      "en",
      "et"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Category.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "post",
            "otherEntityName": "post",
            "otherEntityRelationshipName": "category"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 45
        }
    ],
    "changelogDate": "20170504012228",
    "entityTableName": "category",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "angularJSSuffix": "md"
}
```

Comment.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "author",
            "otherEntityName": "userAccount",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "replyTo",
            "otherEntityName": "comment",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "post",
            "otherEntityName": "post",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "comment",
            "fieldType": "byte[]",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170504012232",
    "entityTableName": "comment",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass",
    "angularJSSuffix": "md"
}
```

Post.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "post",
            "otherEntityName": "post",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "relatedPosts",
            "otherEntityName": "post",
            "otherEntityRelationshipName": "post"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "comments",
            "otherEntityName": "comment",
            "otherEntityRelationshipName": "post"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "category",
            "otherEntityName": "category",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "commentator",
            "otherEntityName": "userAccount",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "tags",
            "otherEntityName": "tag",
            "otherEntityRelationshipName": "post"
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 144
        },
        {
            "fieldName": "datePublished",
            "fieldType": "ZonedDateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "content",
            "fieldType": "byte[]",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "active",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "commentenabled",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "views",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required",
                "min"
            ],
            "fieldValidateRulesMin": 0
        }
    ],
    "changelogDate": "20170504012230",
    "entityTableName": "post",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass",
    "angularJSSuffix": "md"
}
```

Tag.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "post",
            "otherEntityName": "post",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "tag",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 45
        }
    ],
    "changelogDate": "20170504012231",
    "entityTableName": "tag",
    "dto": "no",
    "pagination": "no",
    "service": "no",
    "angularJSSuffix": "md"
}
```

UserAccount.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "screenName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 45
        },
        {
            "fieldName": "firstName",
            "fieldType": "String"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String"
        },
        {
            "fieldName": "phoneNumber",
            "fieldType": "String"
        },
        {
            "fieldName": "street",
            "fieldType": "String"
        },
        {
            "fieldName": "postalCode",
            "fieldType": "String"
        },
        {
            "fieldName": "city",
            "fieldType": "String"
        },
        {
            "fieldName": "stateProvince",
            "fieldType": "String"
        },
        {
            "fieldName": "country",
            "fieldType": "Country",
            "fieldValues": "CA,US"
        },
        {
            "fieldName": "latitude",
            "fieldType": "Double"
        },
        {
            "fieldName": "longitude",
            "fieldType": "Double"
        }
    ],
    "changelogDate": "20170504012229",
    "entityTableName": "user_account",
    "dto": "mapstruct",
    "pagination": "no",
    "service": "serviceClass",
    "angularJSSuffix": "md"
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.5.0

yeoman: 1.8.5

yarn: 0.23.3

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.8.0, build unknown

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Category.json
Comment.json
Post.json
Tag.json
UserAccount.json

##### **Browsers and Operating System**

Linux Mint 18.1

- [ ] Checking this box is mandatory (this is just to show you read everything)
