### ISSUE TITLE
use route-location instead of route-id to lookup service-instances in GatewayResources routes-endpoint

### ISSUE THREAD

**Issue by Laures** [jhipster/generator-jhipster#5733]
##### **Overview of the issue**

in the microservice gateway if zuul routes are configured in the application.yaml this can cause wrong results in the GatewayResource because the route-id is not necessarily the same as the service-id. as a result the gateway ui wrongly shows ´no server available´ 

##### **Motivation for or Use Case**

If multiple routes direct to the same service or the route id is not equal to the service-id for any reason (for example it is manually set in the application.yaml), the gateway shows no server available for this route, no matter what.

##### **Reproduce the error**

generate a gateway with at least one connected service. now configure a route as follows:

    zuul.routes.service1:
            path: /test/helloWorld/**
            location: service

##### **Related issues**

...

##### **Suggest a Fix**

use route.getLocation() instead of route.getId() to lookup services.

##### **JHipster Version(s)**

4.0.3

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/jhipster/development/tigerbooksbackend/tiba-gateway
`-- generator-jhipster@4.4.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tigerbooks.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.4.0",
    "baseName": "gateway",
    "packageName": "com.tigerbooks.gateway",
    "packageFolder": "com/tigerbooks/gateway",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.3

npm: 4.5.0

bower: 1.8.0

gulp:
[12:16:02] CLI version 1.3.0
[12:16:02] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.23.4
