### ISSUE TITLE
Build with maven in docker throw {}->unix://localhost:80

### ISSUE THREAD

**Issue by general03** [jhipster/generator-jhipster#5736]
I have an issue since few days I didn't have before. Now I can't build my project with maven command.
I used Docker for Windows on Windows 10 and hyper-v

##### **Overview of the issue**

[INFO] Copying src/main/docker/app.yml -> /home/jhipster/app/target/docker/app.yml
[INFO] Copying src/main/docker/Dockerfile -> /home/jhipster/app/target/docker/Dockerfile
[INFO] Copying src/main/docker/postgresql.yml -> /home/jhipster/app/target/docker/postgresql.yml
[INFO] Copying src/main/docker/sonar.yml -> /home/jhipster/app/target/docker/sonar.yml
[INFO] Building image general03App
May 03, 2017 8:50:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
May 03, 2017 8:50:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
May 03, 2017 8:50:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
May 03, 2017 8:50:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
May 03, 2017 8:50:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://localhost:80: No such file or directory
May 03, 2017 8:50:21 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->unix://localhost:80
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:23 min
[INFO] Finished at: 2017-05-03T20:50:21+00:00
[INFO] Final Memory: 63M/226M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.13:build (default-cli) on project general03App: Exception caught: java.util.concurrent.ExecutionException: com.spotify.docker.client.shaded.javax.ws.rs.ProcessingException: java.io.IOException: No such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

##### **Motivation for or Use Case**

I can't launch the build with `./mvnw -DskipTests=true docker:build`

##### **Reproduce the error**

If you put docker:build in this command `./mvnw -DskipTests=true docker:build`

##### **Related issues**

https://github.com/spotify/docker-maven-plugin/issues/192 ? I tried without success

##### **JHipster Version(s)**

```
general03App@0.0.0 /home/jhipster/app
`-- generator-jhipster@4.2.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "fr.general03.general03App",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.2.0",
    "baseName": "general03App",
    "packageName": "fr.general03.general03App",
    "packageFolder": "fr/general03/general03App",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ac96591e4cdc2dd33fad838573cd2f58a71c3ba0",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ],
    "herokuAppName": null
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.2

npm: 4.5.0

bower: 1.8.0

gulp:
[20:43:14] CLI version 1.2.2
[20:43:14] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.22.0
