### ISSUE TITLE
login failure on new jhipster project with mongo and oauth2

### ISSUE THREAD

**Issue by hershkop** [jhipster/generator-jhipster#5746]
##### **Overview of the issue**

if you create a new project (or upgrade) login failure via web. My setup mongo and oauth

##### **Motivation for or Use Case**

cant login via web

##### **Reproduce the error**

start new project with mongo and oauth 

##### **Related issues**

account authentication via web

##### **Suggest a Fix**

solution is to fix 
appDetails.setClientId
appDetails.setResourceIds(Collections.singletonList

in the InitialSetupMigration file to be 'projectnameapp' instead of 'oauthapp' since its hardcoded elsewhere in multuple places to be projectnameapp, same for res_oauth

for example in my setup:
appDetails.setClientId("phrasehealthapp");  // default was "oauthapp"

##### **JHipster Version(s)**

I'm not sure when it was introduced, I only noticed it recently. 

##### **JHipster Version(s)**

```
phrasehealth@0.0.6 /Users/shlomo/projects/phrasehealth/code/jhipster-phrase
└── generator-jhipster@4.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.4.1",
    "baseName": "phrasehealth",
    "packageName": "com.phrasehealth.app",
    "packageFolder": "com/phrasehealth/app",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "institutions": [
     "default"
     ], 
   "herokuAppName": "phrasehealth-dev"
  }
}
```

```


##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v6.10.3

npm: 3.10.10

bower: 1.8.0

gulp:
[18:38:16] CLI version 1.3.0
[18:38:16] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.23.4

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245


- [X ] Checking this box is mandatory (this is just to show you read everything)
