### ISSUE TITLE
repository name must be lowercase

### ISSUE THREAD

**Issue by Oleg25** [jhipster/generator-jhipster#5750]
## docker-compose -f /src/main/docker/mongodb-cluster.yml up

ERROR: Service 'gateway-mongodb-node' failed to build: invalid reference format: repository name must be lowercase

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/teligent/projects/fastern/gateway
└── generator-jhipster@4.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.fastern.gateway",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.4.1",
    "baseName": "gateway",
    "packageName": "com.fastern.gateway",
    "packageFolder": "com/fastern/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "401d4627c2a3544b596c2875f619856ed39312a5",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.0

node: v6.10.2

npm: 3.10.10

bower: 1.8.0

gulp:
[14:42:17] CLI version 1.3.0
[14:42:17] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.23.2

Docker version 17.04.0-ce, build 4845c56

docker-compose version 1.11.2, build dfed245
