### ISSUE TITLE
Doing MongoDB cluster on 5 step got error

### ISSUE THREAD

**Issue by Oleg25** [jhipster/generator-jhipster#5773]
I' m try to use 6 steps instructions on https://jhipster.github.io/docker-compose/ - MongoDB cluster 
on 5 step - Init Shard

 i've got error

MongoDB shell version: 3.2.10
connecting to: test
{
        "ok" : 0,
        "errmsg" : "no such command: 'addShard', bad cmd: '{ addShard: \"rs1/docker_gateway-mongodb-node_1:27017\" }'",
        "code" : 59
}

##### **JHipster Version(s)**

```
gateway@0.0.0 /home/teligent/projects/fastern/gateway
└── generator-jhipster@4.4.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.fatsern.gateway",
      "nativeLanguage": "en",
      "microservicePath": "/home/teligent/projects/fastern/customers"
    },
    "jhipsterVersion": "4.4.1",
    "baseName": "gateway",
    "packageName": "com.fatsern.gateway",
    "packageFolder": "com/fatsern/gateway",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "spring-websocket",
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "e12795b36d9a092edaa4466efe1a3b792d6c8f35",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "ru"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Customer.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "firstName",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        },
        {
            "fieldName": "secondName",
            "fieldType": "String"
        },
        {
            "fieldName": "photo",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20170515092943",
    "dto": "mapstruct",
    "service": "serviceImpl",
    "entityTableName": "customer",
    "pagination": "pagination",
    "microserviceName": "customers",
    "searchEngine": "elasticsearch"
}

```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.0

node: v6.10.2

npm: 3.10.10

bower: 1.8.0

gulp:
[11:18:20] CLI version 1.3.0
[11:18:21] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.23.2

Docker version 17.04.0-ce, build 4845c56

docker-compose version 1.11.2, build dfed245
