### ISSUE TITLE
rancher-compose invalid container link when Consul selected 

### ISSUE THREAD

**Issue by ggotti** [jhipster/generator-jhipster#5778]
##### **Overview of the issue**
When using Consul as the Service Discovery Mechanism for a Gateway, the Rancher-Compose generator tries to link the "consul-config-loader" service to the "consul-config-sidekick" service, which is not defined.

##### **Motivation for or Use Case**
Running JHipster in Rancher from generated files.

##### **Reproduce the error**

* Generate new gateway project, with Consul as the selected option.
* Run `yo jhipster:rancher-compose` to generate the appropriate docker-compose file.
* Check line ~40; reference to service "consul-config-sidekick" which has not been defined.

docker-compose file with error:
```
    consul-config-loader:
        image: jhipster/consul-config-loader:v0.2.1
        environment:
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul
            - CONSUL_PORT=8500
        volumes:
          - /config
        volumes_from:
          - consul-config-sidekick
        labels:
          io.rancher.sidekicks: consul-config-sidekick
    registry-config-sidekick:
        # this docker image must be built with:
        # docker build -t lyon.gigliotti.com.au/registry-config-sidekick registry-config-sidekick
        image: lyon.gigliotti.com.au/registry-config-sidekick
        tty: true
        stdin_open: true
        command:
          - cat
        volumes:
          - config:/config

```

##### **Related issues**

N/A

##### **Suggest a Fix**
A couple of options:
* Introduce a new "consul-config-sidekick" service when Consul is selected.
* Rename "registry-config-sidekick" to something more generic, such as "config-sidekick"

##### **JHipster configuration**
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gateway-test@0.0.0 /Users/gerard/Code/scratchPad/gatewayTest
└── generator-jhipster@4.3.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "tech.ippon.gigliotti",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "gatewayTest",
    "packageName": "tech.ippon.gigliotti",
    "packageFolder": "tech/ippon/gigliotti",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d9cdabb7e98f89073fd3070d91ecf777fb600527",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
    "appsFolders": [
      "gatewayTest"
    ],
    "directoryPath": "../",
    "monitoring": "no",
    "dockerRepositoryName": "",
    "dockerPushCommand": "docker push",
    "enableRancherLoadBalancing": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.2

node: v7.8.0

npm: 4.2.0

yeoman: 1.8.5

yarn: 0.21.3

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

Mac OS X 10.12.4 (16E195)

- [x] Checking this box is mandatory (this is just to show you read everything)
