### ISSUE TITLE
mvnw -Pprod hangs without any error in Windows with frontend-maven-plugin.version 1.3

### ISSUE THREAD

**Issue by ticxx** [jhipster/generator-jhipster#5788]
##### **Overview of the issue**

using `mvnw -Pprod` hangs without error message or any response.
same `to mvnw -Pprod package`

##### **Motivation for or Use Case**

using:
mvnw -Pprod
produces:
$ ./mvnw -Pprod package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Inetapp 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:copy-resources (default-resources) @ inetapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 21 resources
[INFO] Copying 12 resources
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ inetapp ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 21 resources
[INFO] Copying 12 resources
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ inetapp ---
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (pre-unit-tests) @ inetapp ---
[INFO] argLine set to -javaagent:C:\\Users\\sd\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.7.9\\org.jacoco.agent-0.7.9-runtime.jar=destfile=C:\\git\\integration\\target\\test-results\\coverage\\jacoco\\jacoco.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO]
[INFO] --- spring-boot-maven-plugin:1.5.2.RELEASE:build-info (default) @ inetapp ---
[INFO]
[INFO] --- frontend-maven-plugin:1.3:install-node-and-yarn (install node and yarn) @ inetapp ---
[INFO] Node v6.10.0 is already installed.
[INFO] Yarn 0.21.3 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.3:yarn (yarn install) @ inetapp ---
[INFO] Running 'yarn install --force' in C:\git\integration
[INFO] yarn install v0.21.3
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[WARNING] warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
[INFO] info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[INFO] [3/4] Linking dependencies...
[WARNING] warning "angular2-cookie@1.2.6" has incorrect peer dependency "@angular/common@^2.0.0".
[WARNING] warning "angular2-cookie@1.2.6" has incorrect peer dependency "@angular/core@^2.0.0".
[WARNING] warning "ng2-translate@4.2.0" has incorrect peer dependency "@angular/core@^2.0.0".
[WARNING] warning "ng2-translate@4.2.0" has incorrect peer dependency "@angular/http@^2.0.0".
[INFO] [4/4] Rebuilding all packages...
[INFO] success Saved lockfile.
[INFO] $ webdriver-manager update && yarn run webpack:build
[INFO] [15:08:40] I/file_manager - creating folder C:\git\integration\node_modules\webdriver-manager\selenium
[INFO] [15:08:41] I/downloader - curl -o C:\git\integration\node_modules\webdriver-manager\selenium/chromedriver_2.29.zip https://chromedriver.storage.googleapis.com/2.29/chromedriver_win32.zip
[INFO] [15:08:41] I/downloader - curl -o C:\git\integration\node_modules\webdriver-manager\selenium/selenium-server-standalone-3.4.0.jar https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
[INFO] [15:08:43] I/downloader - curl -o C:\git\integration\node_modules\webdriver-manager\selenium/geckodriver-v0.16.1.zip https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-win64.zip
[INFO] [15:08:45] I/update - chromedriver: unzipping chromedriver_2.29.zip
[INFO] [15:08:47] I/update - geckodriver: unzipping geckodriver-v0.16.1.zip
[INFO] yarn run v0.21.3
[INFO] $ yarn run ngc && webpack --config webpack/webpack.vendor.js && webpack --config webpack/webpack.dev.js

seconds later both, the java and the node process stopping to consume any CPU

##### **Suggest a Fix**
It would be nice to have at least an error message
##### **JHipster Version(s)**
JHipster 4.3.0
JHipster 4.4.1
##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.dbconn",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.4.1",
    "baseName": "inetapp",
    "packageName": "de.dbconn",
    "packageFolder": "de/dbconn",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en",
      "fr"
    ]
  }
}

##### **Browsers and Operating System**

Win 10 Pro

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@ticxx : can you try to upgrade your Yarn from 0.21.3 to 0.24.x+ ?

**Comment by jdubois** [comment]
Can you do a "yo jhipster:info" so we have your full configuration? That's really hard to help if we have no error message...

**Comment by ticxx** [comment]
@pascalgrimaud : I changed  the the yarn version in pom.xml to ´<yarn.version>v0.24.5</yarn.version>`  and the build uses now v0.24.5. But the behavior has not changed.

**Comment by ticxx** [comment]
@jdubois: Here's the output from  yo jhipster:info

$ yo jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
inetapp@0.0.0 C:\git\integration
└── generator-jhipster@4.4.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.dbconn",
      "nativeLanguage": "de"
    },
    "jhipsterVersion": "4.4.1",
    "baseName": "inetapp",
    "packageName": "de.dbconn",
    "packageFolder": "de/dbconn",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "fd31c988fa16c59919386a8321bc64a40c5e610a",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "de",
    "languages": [
      "de",
      "en",
      "fr"
    ]
  }
}

```


##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Angebot.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "traeger",
            "otherEntityName": "traeger",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "kurs",
            "otherEntityName": "kurs",
            "otherEntityRelationshipName": "angebot"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "angebot",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "caption",
            "fieldType": "String"
        },
        {
            "fieldName": "guid",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170423095637",
    "entityTableName": "angebot",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Geschlecht.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "caption",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170423095640",
    "entityTableName": "geschlecht",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Hilfe.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "geschlecht",
            "otherEntityName": "geschlecht",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "guid",
            "fieldType": "String"
        },
        {
            "fieldName": "gesundheit",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "erziehung",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "schule",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "beruf",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "existenz",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "wiederkehrer",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "aufwand",
            "fieldType": "Double"
        }
    ],
    "changelogDate": "20170423095639",
    "entityTableName": "hilfe",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Kurs.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "angebot",
            "otherEntityName": "angebot",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "nutzung",
            "otherEntityName": "nutzung",
            "otherEntityRelationshipName": "kurs"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "termin",
            "otherEntityName": "termin",
            "otherEntityRelationshipName": "kurs"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "kurs",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "id",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "guid",
            "fieldType": "String"
        },
        {
            "fieldName": "caption",
            "fieldType": "String"
        },
        {
            "fieldName": "teilhabe",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "freizeit",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "selbstorganisation",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "sozialraumerk",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "erfassungsmodus",
            "fieldType": "Erfassungsmodus",
            "fieldValues": "EINZELFALL,GRUPPE"
        },
        {
            "fieldName": "einzelerfassung",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20170423095641",
    "entityTableName": "kurs",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Nutzung.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "kurs",
            "otherEntityName": "kurs",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "geschlecht",
            "otherEntityName": "geschlecht",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "alter",
            "fieldType": "Integer"
        },
        {
            "fieldName": "datum",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "login",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170423095643",
    "entityTableName": "nutzung",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Termin.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "kurs",
            "otherEntityName": "kurs",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "datum",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "anzm",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anzf",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anzu",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anz0bis5",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anz6bis13",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anz14bis17",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anz18bis25",
            "fieldType": "Integer"
        },
        {
            "fieldName": "anzUeber25",
            "fieldType": "Integer"
        },
        {
            "fieldName": "login",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170423095642",
    "entityTableName": "termin",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```

Traeger.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "angebot",
            "otherEntityName": "angebot",
            "otherEntityRelationshipName": "traeger"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityRelationshipName": "traeger"
        }
    ],
    "fields": [
        {
            "fieldName": "caption",
            "fieldType": "String"
        },
        {
            "fieldName": "guid",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170423095636",
    "javadoc": "not an ignored comment",
    "entityTableName": "traeger",
    "dto": "no",
    "pagination": "no",
    "service": "serviceClass"
}
```


##### **Browsers and Operating System**

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b18, mixed mode)

git version 2.8.2.windows.1

node: v7.10.0

npm: 1.4.9

yeoman: 1.8.5

yarn: 0.24.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build f963d76f
