### ISSUE TITLE
Jhipster cli 4.5.X upgrade options throws an error

### ISSUE THREAD

**Issue by ecukalla** [jhipster/generator-jhipster#5800]
The jhipster cli 4.5.1 upgrade throws an error when upgradeing a project:

    ➜  test grep jhipsterVersion .yo-rc.json 
        "jhipsterVersion": "4.5.1",
    ➜  test jhipster upgrade
    Executing jhipster:upgrade
    Welcome to the JHipster Upgrade Sub-Generator
    This will upgrade your current application codebase to the latest JHipster version
    Looking for latest generator-jhipster version...
    events.js:163
          throw er; // Unhandled 'error' event
          ^
    
    Error: ERROR! No update available. Application has already been generated with latest version.
        at Environment.error (/Users/edmond/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
        at constructor.error (/Users/edmond/.config/yarn/global/node_modules/generator-jhipster/generators/    generator-base.js:1514:18)
        at shelljs.exec (/Users/edmond/.config/yarn/global/node_modules/generator-jhipster/generators/upgrade/    index.js:141:26)
        at /Users/edmond/.config/yarn/global/node_modules/shelljs/src/exec.js:199:9
        at ChildProcess.exithandler (child_process.js:197:7)
        at emitTwo (events.js:106:13)
        at ChildProcess.emit (events.js:194:7)
        at maybeClose (internal/child_process.js:899:16)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
    ➜  test yo jhipster:upgrade
    Welcome to the JHipster Upgrade Sub-Generator
    This will upgrade your current application codebase to the latest JHipster version
    Looking for latest generator-jhipster version...
    Error jhipster:upgrade 
    
    ERROR! No update available. Application has already been generated with latest version.
    ➜  test  

    ➜  test jhipster info
    Executing jhipster:info
    Welcome to the JHipster Information Sub-Generator
    
    ##### **JHipster Version(s)**
    
    ```
    /Users/edmond/test
    └── generator-jhipster@4.5.1 
    
    ```
    
    
    ##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
    
    ```yaml
    {
      "generator-jhipster": {
        "promptValues": {
          "packageName": "com.mycompany.myapp",
          "nativeLanguage": "en"
        },
        "jhipsterVersion": "4.5.1",
        "baseName": "test",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "serverPort": "8081",
        "authenticationType": "jwt",
        "hibernateCache": "hazelcast",
        "clusteredHttpSession": false,
        "websocket": false,
        "databaseType": "sql",
        "devDatabaseType": "h2Disk",
        "prodDatabaseType": "mysql",
        "searchEngine": false,
        "messageBroker": false,
        "serviceDiscoveryType": "eureka",
        "buildTool": "maven",
        "enableSocialSignIn": false,
        "jwtSecretKey": "b822f4ec0d4731150d88326d271685499aeeee32",
        "enableTranslation": true,
        "applicationType": "microservice",
        "testFrameworks": [],
        "jhiPrefix": "jhi",
        "skipClient": true,
        "skipUserManagement": true,
        "nativeLanguage": "en",
        "languages": [
          "en"
        ],
        "clientPackageManager": "yarn"
      }
    }
    ```
    
    
    ##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
    
    ls: no such file or directory: .jhipster/*.json
    
    ##### **Browsers and Operating System**
    
    java version "1.8.0_131"
    Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
    
    git version 2.11.0 (Apple Git-81)
    
    node: v7.10.0
    
    npm: 4.6.1
    
    bower: 1.8.0
    
    gulp:
    [20:45:40] CLI version 1.3.0
    
    yeoman: 1.8.5
    
    yarn: 0.24.5
    
    Docker version 17.03.1-ce, build c6d412e
    
    docker-compose version 1.11.2, build dfed245
    
    Execution complete
    ➜  test
