### ISSUE TITLE
Entity sub-generator cannot be used in a microservice without a database

### ISSUE THREAD

**Issue by reywyn** [jhipster/generator-jhipster#5807]
##### **Overview of the issue**

Entity sub-generator fails in a microservice project created without a database; gives the following error:
```
> jhipster entity foo
Executing jhipster:entity foo
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! The entity cannot be generated as the application does not have a database configured!
    at Environment.error (/usr/local/share/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
    at constructor.error (/usr/local/share/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1514:18)
    at constructor.validateDbExistence (/usr/local/share/.config/yarn/global/node_modules/generator-jhipster/generators/entity/index.js:176:22)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:417:23)
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:25:25
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/node_modules/run-async/index.js:24:19
    at /usr/local/share/.config/yarn/global/node_modules/yeoman-generator/lib/index.js:418:9
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

##### **Motivation for or Use Case**

I have a microservice application where I don't have a database, because the data will come through external REST API endpoints. I still want to use DTOs and handle my business logic in service layer. I want JHipster to generate files until repository layer and also unit tests.

##### **Reproduce the error**

On a microservice project created without database (see .yo-rc.json) try creating a new entity by:
`jhipster entity foo`

##### **Related issues**

N/A

##### **Suggest a Fix**

Like `--skip-server` and `--skip-client` options, there could be a `--no-database` option that would skip the database related layers

##### **JHipster Version(s)**

 4.5.1

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.comodif.mobile",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "mobile",
    "packageName": "com.comodif.mobile",
    "packageFolder": "com/comodif/mobile",
    "serverPort": "8085",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "tr"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.9.3

node: v6.10.3

npm: 4.5.0

yeoman: 1.8.5

yarn: 0.24.4

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

- [x]  Checking this box is mandatory (this is just to show you read everything)
