### ISSUE TITLE
Enum's values are not displayed correctly with a "_"

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#5809]
##### **Overview of the issue**

Enum with a "_" in their values will display wrong text when using angular 4 and no translation.
![image](https://cloud.githubusercontent.com/assets/2212267/26317843/d61501dc-3ee6-11e7-9308-544e786fef70.png)

##### **Motivation for or Use Case**

An error is displayed instead of the value of the enum.

##### **Reproduce the error**

Use the jdl below to generate the entity then create it in the app (with angular 4 and no translation).

##### **Related issues**

Found nothing related.

##### **Suggest a Fix**

"_" should be added in the regex that strips html :
`/( (data-t|jhiT)ranslate="([a-zA-Z0-9 +{}'_](\.)?)+")/,`

##### **JHipster Version(s)**

4.5.1

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "86728efe6c27b1990e69576b24679c188e5323f1",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
entity TestEntity {
	enumExample EnumExample
}

enum EnumExample {
	NOSPACE, WITH_SPACE
}
```

##### **Browsers and Operating System**

Chrome 57 on OS X El Capitan

- [x] Checking this box is mandatory (this is just to show you read everything)
