### ISSUE TITLE
error when updating from 4.3 to 4.5.1

### ISSUE THREAD

**Issue by poolebu** [jhipster/generator-jhipster#5813]
##### **Overview of the issue**

 error when updating from `4.3.0` to `4.5.1` using `yo jhipster upgrade`

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Unable to checkout branch jhipster_upgrade:
error: Your local changes to the following files would be overwritten by checkout:
	package.json
Please, commit your changes or stash them before you can switch branches.
Aborting

    at Environment.error (/Users/poolebu/.config/yarn/global/node_modules/yeoman-environment/lib/environment.js:89:38)
    at constructor.error (/Users/poolebu/.config/yarn/global/node_modules/generator-jhipster/generators/generator-base.js:1514:18)
    at gitExec (/Users/poolebu/.config/yarn/global/node_modules/generator-jhipster/generators/upgrade/index.js:60:34)
    at /Users/poolebu/.config/yarn/global/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
```

##### **Motivation for or Use Case**

Ran `yo jhipster upgrade`, dont need any of the new features, just don't want to lag behind.

##### **Reproduce the error**

Do a  `yo jhipster upgrade` from a 4.3 project

##### **Related issues**

#5649 

##### **Suggest a Fix**

Cant' find any.

##### **JHipster Version(s)**

I tried with 4.3.0 and upgrading the generator to 4.5.1 and running the upgrade comand from the new CLI. Gave the same error either way.

##### **JHipster configuration**

```
xecuting jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
catwizard-sales-portal@0.0.1 /Users/poolebu/Desktop/ErnestoLab/catwizardSalesPortal
└── generator-jhipster@4.5.1 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.catwizard.sales",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.3.0",
    "baseName": "catwizardSalesPortal",
    "packageName": "io.catwizard.sales",
    "packageFolder": "io/catwizard/sales",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "rememberMeKey": "9f146d061d2b265fd3cac1040e6811ac80a0fe52",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

DocField.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "docTemplate",
            "otherEntityName": "docTemplate",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "defaultValue",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170426114235",
    "entityTableName": "doc_field",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

DocTemplate.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "docField",
            "otherEntityName": "docField",
            "otherEntityRelationshipName": "docTemplate"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "request",
            "otherEntityName": "request",
            "otherEntityRelationshipName": "docTemplate"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "language",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170426114235",
    "entityTableName": "doc_template",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

FieldValue.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "request",
            "otherEntityName": "request",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "value",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170426114235",
    "entityTableName": "field_value",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Linking.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "type",
            "fieldType": "LinkingType",
            "fieldValues": "CONTACT,ACCOUNT,OPORTUNITY,CASE_NAME",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "crmId",
            "fieldType": "Integer"
        },
        {
            "fieldName": "customFields",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170428132433",
    "entityTableName": "linking",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

ProductRequested.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "request",
            "otherEntityName": "request",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "sku",
            "fieldType": "String"
        },
        {
            "fieldName": "packageInfo",
            "fieldType": "String"
        },
        {
            "fieldName": "pricePerThousand",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "quantityPieces",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "priceTotalPieces",
            "fieldType": "BigDecimal"
        },
        {
            "fieldName": "location",
            "fieldType": "String"
        },
        {
            "fieldName": "incoTerms",
            "fieldType": "String"
        },
        {
            "fieldName": "availability",
            "fieldType": "String"
        },
        {
            "fieldName": "internalComment",
            "fieldType": "String"
        },
        {
            "fieldName": "comment",
            "fieldType": "String"
        },
        {
            "fieldName": "catwizardId",
            "fieldType": "Long"
        }
    ],
    "changelogDate": "20170426114235",
    "entityTableName": "product_requested",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

Request.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "productRequested",
            "otherEntityName": "productRequested",
            "otherEntityRelationshipName": "request"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "fieldValue",
            "otherEntityName": "fieldValue",
            "otherEntityRelationshipName": "request"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "user",
            "otherEntityName": "user",
            "otherEntityField": "login"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipValidateRules": "required",
            "relationshipName": "docTemplate",
            "otherEntityName": "docTemplate",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "status",
            "fieldType": "RequestStatus",
            "fieldValues": "NEW,OPEN,CLOSED",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "creationDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "modifiedDate",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "requiredDate",
            "fieldType": "LocalDate",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "comments",
            "fieldType": "String"
        },
        {
            "fieldName": "requester",
            "fieldType": "String"
        },
        {
            "fieldName": "salesRep",
            "fieldType": "String"
        },
        {
            "fieldName": "contactCrmId",
            "fieldType": "Integer"
        },
        {
            "fieldName": "contact",
            "fieldType": "String"
        },
        {
            "fieldName": "accountCrmId",
            "fieldType": "Integer"
        },
        {
            "fieldName": "account",
            "fieldType": "String"
        },
        {
            "fieldName": "oportunityCrmId",
            "fieldType": "Integer"
        },
        {
            "fieldName": "opportunityName",
            "fieldType": "String"
        },
        {
            "fieldName": "caseCrmId",
            "fieldType": "Integer"
        },
        {
            "fieldName": "caseName",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170426114235",
    "entityTableName": "request",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

##### **Browsers and Operating System**

java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

git version 2.3.2

node: v7.8.0

npm: 4.6.1

gulp:
[22:50:23] CLI version 3.9.0

yeoman: 1.8.5

yarn: 0.20.3

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

Execution complete

```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<!--
If the error is during an entity creation or associated with a specific entity.
If you are using JDL, please share that configuration as well.
-->

##### **Browsers and Operating System**

<!-- What OS are you on? is this a problem with all browsers or only IE8? -->

- [ ] Checking this box is mandatory (this is just to show you read everything)
