### ISSUE TITLE
LoggingAspect not working

### ISSUE THREAD

**Issue by ttardy** [jhipster/generator-jhipster#5823]
##### **Overview of the issue**

The generated `LogginAspect` is not working.

##### **Motivation for or Use Case**

Log information about method calls is very helpful.

##### **Reproduce the error**

Can be reproduced by using the [jhipster-sample-app](https://github.com/jhipster/jhipster-sample-app) and start it as documented with the dev profile active.

##### **Related issues**

#2262 - Minor bug in LoggingAspect
#2496 - Aspect Advice for Repository does not work
#5715 - LoggingAspect causing OutOfMemoryError
#5716 - restrict aspect logging to Service, Repository and Resource beans

##### **Suggest a Fix**

It looks like the && @annotation(...) condition is not working. If I remove that and only use the package restrictions, it is working.

##### **JHipster Version(s)**

```
jhipster-sample-application@0.0.0 /Users/tardy/Downloads/jhipster-sample-app-master
└── generator-jhipster@4.5.1 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "baseName": "jhipsterSampleApplication",
    "packageName": "io.github.jhipster.sample",
    "packageFolder": "io/github/jhipster/sample",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "useCompass": false,
    "buildTool": "maven",
    "rememberMeKey": "5c37379956bd1242f5636c8cb322c2966ad81277",
    "searchEngine": false,
    "enableTranslation": true,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "languages": [
      "en"
    ],
    "serverPort": 8080,
    "jhipsterVersion": "4.5.1",
    "enableSocialSignIn": false,
    "useSass": false,
    "jhiPrefix": "jhi",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "clientPackageManager": "yarn",
    "clientFramework": "angular1"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

BankAccount.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "user",
            "otherEntityName": "user",
            "relationshipType": "many-to-one",
            "otherEntityField": "login"
        },
        {
            "relationshipId": 2,
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "bankAccount"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "balance",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805124838",
    "dto": "no",
    "pagination": "no"
}
```

Label.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "operation",
            "otherEntityName": "operation",
            "relationshipType": "many-to-many",
            "ownerSide": false,
            "otherEntityRelationshipName": "label"
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "label",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "3"
        }
    ],
    "changelogDate": "20150805124936",
    "dto": "no",
    "pagination": "no"
}
```

Operation.json

```yaml
{
    "relationships": [
        {
            "relationshipId": 1,
            "relationshipName": "bankAccount",
            "otherEntityName": "bankAccount",
            "relationshipType": "many-to-one",
            "otherEntityField": "name"
        },
        {
            "relationshipId": 2,
            "relationshipName": "label",
            "otherEntityName": "label",
            "relationshipType": "many-to-many",
            "otherEntityField": "label",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "date",
            "fieldType": "DateTime",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldId": 2,
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldId": 3,
            "fieldName": "amount",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20150805125054",
    "dto": "no",
    "pagination": "infinite-scroll"
}
```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.0

node: v7.10.0

npm: 4.6.1

bower: 1.8.0

gulp:
[11:16:02] CLI version 1.3.0
[11:16:02] Local version 3.9.1

yeoman: 1.8.5

yarn: 0.24.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

- [x] Checking this box is mandatory (this is just to show you read everything)
