### ISSUE TITLE
mvn compile liquibase:diff is failing

### ISSUE THREAD

**Issue by joedayz** [jhipster/generator-jhipster#5859]
This is for me one bug. 

1.- I added a field to my entity
2.- I execute mvn compile liquibase:diff 
3.- I added my changelog manually to my master.xml

 <include file="classpath:config/liquibase/changelog/20170530174942_changelog.xml" relativeToChangelogFile="false"/>

4.- I got it error:

Caused by: org.h2.jdbc.JdbcSQLException: Sequence "HIBERNATE_SEQUENCE" already exists; SQL statement:
CREATE SEQUENCE PUBLIC.hibernate_sequence [90035-194]

Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/josediaz/Projects/microservices-for-the-masses/demos/jhipster-microservices/document
└── generator-jhipster@4.5.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "pe.com.tss",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "document",
    "packageName": "pe.com.tss",
    "packageFolder": "pe/com/tss",
    "serverPort": "8082",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mssql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "16497923c70c74765acca1d5bc5eaa7980ac8270",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Document.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "guid",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "40"
        },
        {
            "fieldName": "fileName",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        },
        {
            "fieldName": "reference",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170530153755",
    "dto": "no",
    "service": "no",
    "entityTableName": "document",
    "pagination": "pagination",
    "microserviceName": "document",
    "searchEngine": false
}

```

RepositoryDocument.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "code",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "20"
        },
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": []
        },
        {
            "fieldName": "timeoutSession",
            "fieldType": "Integer"
        }
    ],
    "changelogDate": "20170530154255",
    "dto": "no",
    "service": "no",
    "entityTableName": "repository_document",
    "pagination": "no",
    "microserviceName": "document",
    "searchEngine": false
}

```

RepositorySession.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "ipAddress",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        },
        {
            "fieldName": "loginTime",
            "fieldType": "ZonedDateTime"
        }
    ],
    "changelogDate": "20170530154350",
    "dto": "no",
    "service": "no",
    "entityTableName": "repository_session",
    "pagination": "no",
    "microserviceName": "document",
    "searchEngine": false
}

```

Tag.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "tagValue",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        }
    ],
    "changelogDate": "20170530154500",
    "dto": "no",
    "service": "no",
    "entityTableName": "tag",
    "pagination": "no",
    "microserviceName": "document",
    "searchEngine": false
}

```

UserAccount.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "account",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        },
        {
            "fieldName": "password",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        },
        {
            "fieldName": "firstName",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String",
            "fieldValidateRules": [
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": "255"
        }
    ],
    "changelogDate": "20170530155042",
    "dto": "no",
    "service": "no",
    "entityTableName": "user_account",
    "pagination": "no",
    "microserviceName": "document",
    "searchEngine": false
}

```

##### **Browsers and Operating System**

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v6.9.5

npm: 3.10.10

bower: 1.7.9

yeoman: 1.8.5

yarn: 0.24.4

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.13.0, build 1719ceb

Execution complete
