### ISSUE TITLE
Microservice/Gateway Generation of Entities has missing translations

### ISSUE THREAD

**Issue by btelintelo** [jhipster/generator-jhipster#5862]
##### **Overview of the issue**

Generated one gateway and one microservice.  The microservice has one entity.  I regenerated the entity angular code in the gateway project.  The generated angular code in the gateway project has translation tags.  I said no to the internationalization question when prompted.

ranslation-not-found[adminApp.client_config.home.title]  is splashed on every field.

##### **Reproduce the error**

Run the steps above.  No to internationalization option when using microservice and gateway project

##### **JHipster Version(s)**

latest

##### **JHipster configuration**

Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
admin@0.0.0 T:\projects\last50feet\admin
+-- UNMET PEER DEPENDENCY @angular/common@4.0.0
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0
`-- generator-jhipster@4.5.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.last50feet.admin",
      "microservicePath": "../config"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "admin",
    "packageName": "com.last50feet.admin",
    "packageFolder": "com/last50feet/admin",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d01ec0339aabe1ffa46fb6822ddd569c9b706c43",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Client_config.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "5"
        },
        {
            "fieldName": "hasPayments",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "icon",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20170601022141",
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "client_config",
    "pagination": "pagination",
    "microserviceName": "config",
    "searchEngine": false
}

```

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

node: v6.10.3

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.24.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build f963d76f

Execution complete

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "minlength"
            ],
            "fieldValidateRulesMinlength": "5"
        },
        {
            "fieldName": "hasPayments",
            "fieldType": "Boolean",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "icon",
            "fieldType": "byte[]",
            "fieldTypeBlobContent": "image"
        }
    ],
    "changelogDate": "20170601022141",
    "dto": "no",
    "service": "serviceClass",
    "entityTableName": "client_config",
    "pagination": "pagination",
    "microserviceName": "config",
    "searchEngine": false
}

##### **Browsers and Operating System**

windows

- [x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
Can you please also post your microservice `.yo-rc.json`?  I can't reproduce the issue on my computer, everything works as expected

**Comment by jdubois** [comment]
Thanks for testing @ruddell !
If the ticket isn't complete I'm closing this. We'll reopen if we have more information.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by pascalgrimaud** [comment]
Same as @ruddell, I can't reproduce:
- gateway without translation
- micro with translation
- generate entity in micro
- generate entity in gateway, using the entity from micro


But I saw something strange: with Consul, the gateway need to be started after the micro, otherwise, the gateway can't see the micro... I need to investigate, but it's another ticket

**Comment by btelintelo** [comment]
here are the files


[gateway.yo-rc.txt](https://github.com/jhipster/generator-jhipster/files/1046115/gateway.yo-rc.txt)
[micro.yo-rc.txt](https://github.com/jhipster/generator-jhipster/files/1046116/micro.yo-rc.txt)

**Comment by btelintelo** [comment]
> generate entity in gateway, using the entity from micro

thats what i was doing

**Comment by btelintelo** [comment]
![screenhunter_01 jun 01 18 57](https://cloud.githubusercontent.com/assets/3678777/26704332/50c6a698-46fc-11e7-9dfe-1d220ee8b9ab.gif)

**Comment by jdubois** [comment]
@btelintelo can you copy/paste the files here? Sorry I can't use attached files easily with my phone

**Comment by pascalgrimaud** [comment]
Your gateway:

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.last50feet.admin",
      "microservicePath": "../config"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "admin",
    "packageName": "com.last50feet.admin",
    "packageFolder": "com/last50feet/admin",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d01ec0339aabe1ffa46fb6822ddd569c9b706c43",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

Your micro:

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.last50feet.config"
    },
    "jhipsterVersion": "4.5.1",
    "baseName": "config",
    "packageName": "com.last50feet.config",
    "packageFolder": "com/last50feet/config",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "d4ac6f603df43a5df9203b8202530f765e8c1918",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "clientPackageManager": "yarn"
  }
}
```

You have both option `"enableTranslation": false,` so I can't understand how you can have a Translation issue.
I try again to reproduce but I didn't manage. Everything works fine on my side:

![issue-5862](https://cloud.githubusercontent.com/assets/9156882/26713297/34746f82-476c-11e7-90e4-b748757f29c8.png)

![issue-5862-consul](https://cloud.githubusercontent.com/assets/9156882/26713348/7ad594c4-476c-11e7-887b-d690775fc267.png)
