### ISSUE TITLE
Missing dependencies from vanilla project when running in Idea in Windows

### ISSUE THREAD

**Issue by richiethom** [jhipster/generator-jhipster#5875]
##### **Overview of the issue**

A vanilla project (Angular, MySQL, Maven) won't start from inside IntelliJ Idea (Community Edition v2017.1.3) without adding the following dependencies as provided:

- javax.servlet:javax.servlet-api:3.0.1
- io.undertow:undertow-core:1.4.12.Final
- io.undertow:undertow-servlet:1.4.12.Final

##### **Motivation for or Use Case**

Because it should Just Work™ - everything else does in JHipster :)

##### **Reproduce the error**

1. Generate a standard JHipster project.
2. In IntelliJ Idea, choose File->New->Project from Existing Sources, and import the generated pom.xml
3. Enable autoimport and activate the IDE profile
4. Clean and build the project:
    JWTFilter won't compile without the Servlet dependencies
    WebConfigurer won't compile without the the Undertow dependencies
5. The app won't start by running the Maven project from inside Idea **but will run from the command line with mvnw**.
6 . Add the dependencies listed above, all OK.

##### **Suggest a Fix**

Add the listed dependencies to the generated pom automatically,  or add something to the IDE documentation, as the project obviously runs from the command line.

##### **JHipster Version(s)**

4.5.2

##### **JHipster configuration**

C:\Users\richi\Documents\projects\jhipstertest8>jhipster info
Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipstertest-8@0.0.0 C:\Users\richi\Documents\projects\jhipstertest8
+-- UNMET PEER DEPENDENCY @angular/common@4.1.3
+-- UNMET PEER DEPENDENCY @angular/core@4.1.3
`-- generator-jhipster@4.5.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "jhipstertest8",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "07d06b444063ad06d43ef4f7e39acf743f1f4661",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

git version 2.13.0.windows.1

node: v7.10.0

npm: 4.2.0

bower: 1.8.0

gulp:
[10:43:18] CLI version 1.3.0

yeoman: 1.8.5

yarn: 0.24.6

Execution complete

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "jhipstertest8",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "07d06b444063ad06d43ef4f7e39acf743f1f4661",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

I have this problem even without any entities.

##### **Browsers and Operating System**

Windows 10

- [X] Checking this box is mandatory (this is just to show you read everything)
