### ISSUE TITLE
Social login does not redirect to home page

### ISSUE THREAD

**Issue by amehra** [jhipster/generator-jhipster#5877]
##### **Overview of the issue**

On successfully logging in using a social auth one is not redirected to the home page.

##### **Motivation for or Use Case**

Social login should be consistent with the email based login mechanism. 

##### **Reproduce the error**

To reproduce the error please do the following:

1. Register via a social login. I used Facebook.
2. Now login to JHipster.
3. Note you are redirected to http://localhost:8080/#/social-auth. This is a blank page and should actually be the home page. Note I have set up Facebook to redirection to localhost:8080 instead of a domain.

##### **Related issues**

Tried looking could not find anything. 

##### **Suggest a Fix**

Adding the following line to the end of the ngInit() method of the SocialAuthComponent has the desired effect.
`        this.router.navigate(['']);`

Happy to create a pull request if this is the desired fix. New to Angular thus not sure.

##### **JHipster Version(s)**

Using Jhipster version 4.5.2

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-ci",
        "version": "1.0.0"
      },
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-banner",
        "version": "0.0.2"
      },
      {
        "name": "generator-jhipster-bootswatch",
        "version": "1.0.2"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not Appliable

##### **Browsers and Operating System**

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

git version 2.11.0

node: v7.9.0

npm: 4.2.0

bower: 1.8.0

gulp:
[13:15:46] CLI version 1.3.0

yeoman: 1.8.5

yarn: 0.23.3

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245
