### ISSUE TITLE
JHipster upgrade failed from 4.5.0 to 4.5.2

### ISSUE THREAD

**Issue by shai2017** [jhipster/generator-jhipster#5881]
##### **Overview of the issue**
Can't upgrade from 4.5.0 to 4.5.2 as there are error blocking to upgrade.

##### **Motivation for or Use Case**

Can't upgrade to latest version of JHipster

##### **Reproduce the error**

**Run command from the root folder of micro-service gateway 
yo jhipster:upgrade
This is failing to upgrade**

shaileshs-MacBook-Pro:derivativehub capalytix$ yo jhipster:upgrade
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
Looking for latest generator-jhipster version...
New generator-jhipster version found: 4.5.2
Git repository detected
Updating generator-jhipster to 4.5.2 . This might take some time...
Error jhipster:upgrade 

ERROR! Something went wrong while updating generator! yarn add v0.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
└─ generator-jhipster@4.5.2
$ webdriver-manager update && node node_modules/phantomjs-prebuilt/install.js && yarn run webpack:build
[17:12:56] I/file_manager - creating folder /Users/capalytix/Documents/DHUB/derivativehub/node_modules/webdriver-manager/selenium
[17:12:57] I/downloader - curl -o /Users/capalytix/Documents/DHUB/derivativehub/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.4.0.jar https://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
[17:12:57] I/downloader - curl -o /Users/capalytix/Documents/DHUB/derivativehub/node_modules/webdriver-manager/selenium/chromedriver_2.29.zip https://chromedriver.storage.googleapis.com/2.29/chromedriver_mac64.zip
[17:12:59] I/downloader - curl -o /Users/capalytix/Documents/DHUB/derivativehub/node_modules/webdriver-manager/selenium/geckodriver-v0.16.1.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-macos.tar.gz
[17:13:00] I/update - chromedriver: unzipping chromedriver_2.29.zip
[17:13:00] I/update - chromedriver: setting permissions to 0755 for /Users/capalytix/Documents/DHUB/derivativehub/node_modules/webdriver-manager/selenium/chromedriver_2.29
[17:13:01] I/update - geckodriver: unzipping geckodriver-v0.16.1.tar.gz
[17:13:01] I/update - geckodriver: setting permissions to 0755 for /Users/capalytix/Documents/DHUB/derivativehub/node_modules/webdriver-manager/selenium/geckodriver-v0.16.1
Considering PhantomJS found at /Users/capalytix/Documents/DHUB/derivativehub/node_modules/.bin/phantomjs
Looks like an `npm install -g`
Could not link global install, skipping...
Download already available at /var/folders/zb/wn3ygr1d6sg04zzyk0rtkrbr0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /Users/capalytix/Documents/DHUB/derivativehub/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/zb/wn3ygr1d6sg04zzyk0rtkrbr0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1496679181615/phantomjs-2.1.1-macosx -> /Users/capalytix/Documents/DHUB/derivativehub/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/capalytix/Documents/DHUB/derivativehub/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
yarn run v0.22.0
$ yarn run ngc && webpack --config webpack/webpack.vendor.js && webpack --config webpack/webpack.dev.js 
yarn run v0.22.0
$ ngc -p tsconfig-aot.json 
Done in 17.45s.
Hash: bf847d3ae315d5551967
Version: webpack 2.3.3
Time: 4685ms
        Asset     Size  Chunks                    Chunk Names
vendor.dll.js  3.99 MB       0  [emitted]  [big]  vendor
   [1] ./~/@angular/core/@angular/core.es5.js 460 kB {0} [built]
  [11] ./~/@angular/common/@angular/common.es5.js 131 kB {0} [built]
  [19] ./~/@angular/forms/@angular/forms.es5.js 204 kB {0} [built]
  [33] ./~/@angular/platform-browser/@angular/platform-browser.es5.js 141 kB {0} [built]
  [45] ./~/@angular/http/@angular/http.es5.js 73.2 kB {0} [built]
  [99] ./~/@angular/compiler/@angular/compiler.es5.js 962 kB {0} [built]
 [100] ./~/rxjs/Rx.js 9.58 kB {0} [built]
 [229] ./~/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js 6.09 kB {0} [built]
 [233] ./~/jquery/dist/jquery.js 268 kB {0} [built]
 [234] ./~/ng-jhipster/index.js 2.66 kB {0} [built]
 [235] ./~/ng2-webstorage/dist/app.js 2.96 kB {0} [built]
 [236] ./~/ngx-infinite-scroll/modules/ngx-infinite-scroll.es5.js 17 kB {0} [built]
 [237] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
 [239] ./src/main/webapp/app/vendor.ts 172 bytes {0} [built]
 [561] dll vendor 12 bytes {0} [built]
    + 547 hidden modules

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader/lib/loader.js!./src/main/webapp/content/scss/vendor.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:952:18)
    at Object.getInstalledBinaries (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/capalytix/Documents/DHUB/derivativehub/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
 @ ./src/main/webapp/content/scss/vendor.scss 4:14-194
 @ ./src/main/webapp/app/vendor.ts
 @ dll vendor
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 warning "angular2-cookie@1.2.6" has incorrect peer dependency "@angular/common@^2.0.0".
warning "angular2-cookie@1.2.6" has incorrect peer dependency "@angular/core@^2.0.0".
warning "ng2-translate@4.2.0" has incorrect peer dependency "@angular/core@^2.0.0".
warning "ng2-translate@4.2.0" has incorrect peer dependency "@angular/http@^2.0.0".
Warning: Can't resolve all parameters for AlertService in /Users/capalytix/Documents/DHUB/derivativehub/node_modules/ng-jhipster/src/service/alert.service.d.ts: ([object Object], ?, [object Object]). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for InterceptableHttp in /Users/capalytix/Documents/DHUB/derivativehub/node_modules/ng-jhipster/src/interceptor/interceptable-http.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
  <div class="card">
    [WARNING ->]<template ngFor let-panel [ngForOf]="panels">
      <div role="tab" id="{{panel.id}}-header"
        "): ng:///Users/capalytix/Documents/DHUB/derivativehub/node_modules/@ng-bootstrap/ng-bootstrap/accordion/accordion.d.ts.NgbAccordion.html@2:4
error Command failed with exit code 2.
error Command failed with exit code 1.

##### **Related issues**
Seems similar to #5811 but reviewing the error it is bit different.

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
derivativehub@0.0.0 /Users/capalytix/Documents/DHUB/derivativehub
└── generator-jhipster@4.5.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.capalytix.dhub",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.0",
    "baseName": "derivativehub",
    "packageName": "com.capalytix.dhub",
    "packageFolder": "com/capalytix/dhub",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "05ee1b4c84a67ddba654951c382d469e75738e2b",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr",
      "de"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

git version 2.10.1 (Apple Git-78)

node: v6.10.2

npm: 4.5.0

bower: 1.8.0

gulp:
[17:24:40] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.22.0

Docker version 17.06.0-ce-rc1, build 7f8486a

docker-compose version 1.13.0, build 1719ceb
