### ISSUE TITLE
Return observable instead of promise in principal.identity()

### ISSUE THREAD

**Issue by santoshkt** [jhipster/generator-jhipster#5884]
##### **Overview of the issue**

This may be more of a Angular question than jHipster. I want to understand what is the purpose of returning a promise instead of object in principal.service.ts identity() function. I am converting it to use Observable but don't see a reason to return observable as I would want to handle the subscribe with in the identity() function. 

My function would like below

```
 identity(force?: boolean): any {
        if (force === true) {
            this.userIdentity = undefined;
        }

        // check and see if we have retrieved the userIdentity data from the server.
        // if we have, reuse it by immediately resolving
        if (this.userIdentity) {
            return this.userIdentity;
        }

        // retrieve the userIdentity data from the server, update the identity object, and then resolve.
        this.userService.getLoggedInUsersSummary().subscribe(user => {
                if (user) {
                    this.userIdentity = user;
                    this.authenticated = true;
                } else {
                    this.userIdentity = null;
                    this.authenticated = false;
                }
                this.authenticationState.next(this.userIdentity);
                return this.userIdentity;
            },
            err => {
                console.log(err);
                this.userIdentity = null;
                this.authenticated = false;
                this.authenticationState.next(this.userIdentity);
                return null;
            }
        );
    }
```
Just want to check if jHipster team returned a promise for a reason and if what I am doing above is correct. 

Also, is there a plan to convert all promises across the generator to use observables ?

##### **JHipster Version(s)**

4.5.2

##### **JHipster configuration**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.github.santoshkt.monoyada",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "monoyada",
    "packageName": "com.github.santoshkt.monoyada",
    "packageFolder": "com/github/santoshkt/monoyada",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "2019393ad6b7f36a97c006fdbddcf89dc75af577",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```
- [x] Checking this box is mandatory (this is just to show you read everything)
