### ISSUE TITLE
Webpack ignoring manifest.webapp and it's images

### ISSUE THREAD

**Issue by sohibegit** [jhipster/generator-jhipster#5904]
##### **Overview of the issue**

Webpack doesn't parse **manifest.webapp**, src path stays the same and the icons ignored

##### **JHipster Version(s)**

```
sohibe@0.0.34 /home/sohibe/jhipwork/aws/sohibe
├── UNMET PEER DEPENDENCY @angular/common@4.1.3
├── UNMET PEER DEPENDENCY @angular/core@4.1.3
└── generator-jhipster@4.5.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "tech.fikra.sohibe"
    },
    "jhipsterVersion": "4.5.3",
    "baseName": "sohibe",
    "packageName": "tech.fikra.sohibe",
    "packageFolder": "tech/fikra/sohibe",
    "serverPort": "5000",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "##############################",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "sohibe",
    "enableTranslation": false,
    "herokuAppName": "sohibe"
  }
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v7.8.0

npm: 4.2.0

bower: 1.7.9

gulp:
[10:00:37] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.24.6
