### ISSUE TITLE
Update user token with database's authorities

### ISSUE THREAD

**Issue by brevleq** [jhipster/generator-jhipster#5929]
##### **Overview of the issue**

I've verified that when I change user's roles, the REST API is rejecting some calls returning unauthorized error. After seen that the authorities was correct at database, I've opened a anonymous tab at chrome and did the same request with the same user and it worked, however the not anonymous tab, still wasn't succeeding with the request. 

##### **Motivation for or Use Case**

The application I'm developing has about 8 different authorities and a user can add or remove roles to a user. These roles changes need to be available to the user immediately.

##### **Suggest a Fix**

I've verified that when I remove or add a role to an user, the token still have the old roles, this way the Angular part can see the new roles but Spring can't. I've changed TokenProvider's code to update the token with the database's roles of the user:

    public Authentication getAuthentication(String token) {
        Claims claims = Jwts.parser()
                .setSigningKey(secretKey)
                .parseClaimsJws(token)
                .getBody();
        Collection<Authority> databaseAuthorities=userRepository.findOneWithAuthoritiesByLogin(claims.getSubject()).get().getAuthorities();
        Collection<GrantedAuthority> authorities = databaseAuthorities.stream()
                .map(databaseAuthority -> new SimpleGrantedAuthority(databaseAuthority.getName()))
                .collect(Collectors.toList());
    
        /*Collection<? extends GrantedAuthority> authorities =
                Arrays.stream(claims.get(AUTHORITIES_KEY).toString().split(","))
                        .map(SimpleGrantedAuthority::new)
                        .collect(Collectors.toList());*/

        User principal = new User(claims.getSubject(), "", authorities);

        return new UsernamePasswordAuthenticationToken(principal, token, authorities);
    }

##### **JHipster Version(s)**

```
stae-server@0.0.0 /home/hudson/projetos/stae-server
├── UNMET PEER DEPENDENCY @angular/common@4.1.3
├── UNMET PEER DEPENDENCY @angular/compiler@4.1.3
├── UNMET PEER DEPENDENCY @angular/compiler-cli@4.1.3
├── UNMET PEER DEPENDENCY @angular/core@4.1.3
├── UNMET PEER DEPENDENCY @angular/forms@4.1.3
├── UNMET PEER DEPENDENCY @angular/http@4.1.3
├── UNMET PEER DEPENDENCY @angular/platform-browser@4.1.3
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@4.1.3
├── generator-jhipster@4.5.2 
└── UNMET PEER DEPENDENCY rxjs@5.4.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.huroapps.stae_server",
      "nativeLanguage": "pt-br"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "StaeServer",
    "packageName": "com.huroapps.stae_server",
    "packageFolder": "com/huroapps/stae_server",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "pt-br",
    "languages": [
      "pt-br"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Cidade.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "estado",
      "otherEntityName": "estado",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipName": "cliente",
      "otherEntityName": "cliente",
      "otherEntityRelationshipName": "cidade"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipName": "turmaColheita",
      "otherEntityName": "turmaColheita",
      "otherEntityRelationshipName": "cidade"
    }
  ],
  "fields": [
    {
      "fieldName": "ibge",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength",
        "minlength"
      ],
      "fieldValidateRulesMaxlength": 7,
      "fieldValidateRulesMinlength": 7
    },
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 50
    }
  ],
  "changelogDate": "20170605195812",
  "entityTableName": "cidade",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "skipClient": true
}
```

Cliente.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "cidade",
      "otherEntityName": "cidade",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipName": "prazoPagamento",
      "otherEntityName": "prazoPagamento",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    },
    {
      "relationshipName": "tipoPagamento",
      "otherEntityName": "tipoPagamento",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "razaoSocial",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 50
    },
    {
      "fieldName": "nomeFantasia",
      "fieldType": "String",
      "fieldValidateRules": [
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 25
    },
    {
      "fieldName": "documento",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 14
    },
    {
      "fieldName": "tipoPessoa",
      "fieldType": "TipoPessoa",
      "fieldValues": "PF,PJ",
      "fieldValidateRules": [
        "required"
      ]
    },
    {
      "fieldName": "telefone",
      "fieldType": "String",
      "fieldValidateRules": [
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 11
    },
    {
      "fieldName": "email",
      "fieldType": "String",
      "fieldValidateRules": [
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 50
    },
    {
      "fieldName": "logradouro",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 60
    },
    {
      "fieldName": "numero",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 10
    },
    {
      "fieldName": "complemento",
      "fieldType": "String",
      "fieldValidateRules": [
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 30
    },
    {
      "fieldName": "bairro",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 30
    },
    {
      "fieldName": "cep",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 8
    },
    {
      "fieldName": "observacao",
      "fieldType": "String",
      "fieldValidateRules": [
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 255
    }
  ],
  "changelogDate": "20170605195816",
  "entityTableName": "cliente",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

Embalagem.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "tipoEmbalagem",
      "otherEntityName": "tipoEmbalagem",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "pesoMaximoSuportado",
      "fieldType": "BigDecimal",
      "fieldValidateRules": [
        "required"
      ]
    }
  ],
  "changelogDate": "20170605195818",
  "entityTableName": "embalagem",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

Estado.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipName": "cidade",
      "otherEntityName": "cidade",
      "otherEntityRelationshipName": "estado"
    }
  ],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 50
    },
    {
      "fieldName": "sigla",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength",
        "minlength"
      ],
      "fieldValidateRulesMaxlength": 2,
      "fieldValidateRulesMinlength": 2
    }
  ],
  "changelogDate": "20170605195811",
  "entityTableName": "estado",
  "dto": "no",
  "pagination": "no",
  "service": "no",
  "skipClient": true
}
```

ParcelaPrazoPagamento.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "prazoPagamento",
      "otherEntityName": "prazoPagamento",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "dias",
      "fieldType": "Integer",
      "fieldValidateRules": [
        "required",
        "min"
      ],
      "fieldValidateRulesMin": 0
    }
  ],
  "changelogDate": "20170605195814",
  "entityTableName": "parcela_prazo_pagamento",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

PrazoPagamento.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipName": "parcela",
      "otherEntityName": "parcelaPrazoPagamento",
      "otherEntityRelationshipName": "prazoPagamento"
    },
    {
      "relationshipType": "one-to-many",
      "relationshipName": "cliente",
      "otherEntityName": "cliente",
      "otherEntityRelationshipName": "prazoPagamento"
    }
  ],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 25
    }
  ],
  "changelogDate": "20170605195813",
  "entityTableName": "prazo_pagamento",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

Produto.json

```yaml
{
  "fluentMethods": true,
  "relationships": [],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 25
    },
    {
      "fieldName": "sigla",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 4
    }
  ],
  "changelogDate": "20170605195819",
  "entityTableName": "produto",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

TipoBaixaEmbalagem.json

```yaml
{
  "fluentMethods": true,
  "relationships": [],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 20
    }
  ],
  "changelogDate": "20170605195821",
  "entityTableName": "tipo_baixa_embalagem",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

TipoEmbalagem.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipName": "embalagem",
      "otherEntityName": "embalagem",
      "otherEntityRelationshipName": "tipoEmbalagem"
    }
  ],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 25
    },
    {
      "fieldName": "sigla",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength",
        "minlength"
      ],
      "fieldValidateRulesMaxlength": 2,
      "fieldValidateRulesMinlength": 2
    }
  ],
  "changelogDate": "20170605195817",
  "entityTableName": "tipo_embalagem",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

TipoEntradaEmbalagem.json

```yaml
{
  "fluentMethods": true,
  "relationships": [],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 20
    }
  ],
  "changelogDate": "20170605195820",
  "entityTableName": "tipo_entrada_embalagem",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

TipoPagamento.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipType": "one-to-many",
      "relationshipName": "cliente",
      "otherEntityName": "cliente",
      "otherEntityRelationshipName": "tipoPagamento"
    }
  ],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 25
    },
    {
      "fieldName": "ordem",
      "fieldType": "Integer",
      "fieldValidateRules": [
        "required",
        "min"
      ],
      "fieldValidateRulesMin": 1
    }
  ],
  "changelogDate": "20170605195815",
  "entityTableName": "tipo_pagamento",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

TurmaColheita.json

```yaml
{
  "fluentMethods": true,
  "relationships": [
    {
      "relationshipName": "cidade",
      "otherEntityName": "cidade",
      "relationshipType": "many-to-one",
      "otherEntityField": "id"
    }
  ],
  "fields": [
    {
      "fieldName": "nome",
      "fieldType": "String",
      "fieldValidateRules": [
        "required",
        "maxlength"
      ],
      "fieldValidateRulesMaxlength": 25
    },
    {
      "fieldName": "quantidadePessoas",
      "fieldType": "Integer",
      "fieldValidateRules": [
        "required",
        "min"
      ],
      "fieldValidateRulesMin": 1
    }
  ],
  "changelogDate": "20170605195822",
  "entityTableName": "turma_colheita",
  "dto": "no",
  "pagination": "no",
  "service": "no"
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v7.10.0

npm: 4.2.0

bower: 1.8.0

yeoman: 1.8.5

yarn: 0.24.6

Execution complete
