### ISSUE TITLE
translation-not-found for alerts when generating UI for for entities in a microservice app

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5960]
##### **Overview of the issue**

When you generate a UI on a gateway for an entity in a microservice, alerts have `translation-not-found` rather than the translated message.

![screen shot 2017-06-19 at 8 56 27 pm](https://user-images.githubusercontent.com/17892/27346756-67778480-55ab-11e7-809b-143595ae7b3b.png)

##### **Motivation for or Use Case**

Alert messages should be translated when i18n is enabled.

##### **Reproduce the error**

Create a `blog` gateway using the following `.yo-rc.json`:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.blog",
      "nativeLanguage": "en",
      "microservicePath": "../store"
    },
    "jhipsterVersion": "4.5.4",
    "baseName": "blog",
    "packageName": "org.jhipster.blog",
    "packageFolder": "org/jhipster/blog",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "f7450a034a7251b3d201cf5139852f9adf69c2d1",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ]
  }
}
```

Create a `store` microservice using the following:

```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "org.jhipster.store",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.4",
    "baseName": "store",
    "packageName": "org.jhipster.store",
    "packageFolder": "org/jhipster/store",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ea21b5b635606be4d7937e29926166e0ee56abb1",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "es"
    ],
    "clientPackageManager": "yarn"
  }
}
```

Create a `product` entity for the store using `jhipster entity product`. Add `name` and `price` fields.

The `store` app uses MongoDB, so you'll need to start that using docker-compose:

`docker-compose -f src/main/docker/mongodb.yml up`

Start a JHipster Registry, the `blog`, and the `store` applications.

Add a new product and you'll see the alert is not translated.

##### **Suggest a Fix**

The generated `product.json` has to keys for each app at its root.

```json
{
    "blogApp": {
        "product" : {
            "home": {
                "title": "Products",
                "createLabel": "Create a new Product",
                "createOrEditLabel": "Create or edit a Product",
                "search": "Search for Product"
            },
            "delete": {
                "question": "Are you sure you want to delete Product {{ id }}?"
            },
            "detail": {
                "title": "Product"
            },
            "name": "Name",
            "price": "Price"
        }
    },
    "storeApp": {
        "product" : {
            "created": "A new Product is created with identifier {{ param }}",
            "updated": "A Product is updated with identifier {{ param }}",
            "deleted": "A Product is deleted with identifier {{ param }}"
        }
    }
}
```

It seems like the created/updated/deleted keys should be under the "blogApp" instead of "storeApp".

##### **JHipster Version(s)**

4.5.4

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Product.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "price",
            "fieldType": "BigDecimal",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "dto": "no",
    "service": "no",
    "entityTableName": "product",
    "pagination": "pagination",
    "microserviceName": "store",
    "searchEngine": false
}

```

##### **Browsers and Operating System**

macOS Sierra 10.12.5
Chrome 58

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.12.2

node: v6.11.0

npm: 3.10.10

yeoman: 1.8.5

yarn: 0.24.4

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

- [x] Checking this box is mandatory (this is just to show you read everything)
