### ISSUE TITLE
Angular sub generator

### ISSUE THREAD

**Issue by superandrew** [jhipster/generator-jhipster#5983]
##### **Overview of the issue**
The Jhipster generator is great to create some boiler plate code for the front end, but If you need to create a complex angular application it would be useful to use the angular subgenerator to handle creation of new views, controllers, services etc.

##### **Motivation for or Use Case**
I need to create a gui application which uses Jhipster backend. It's ok to have the jhipster frontend code to insert and modify entities, however I need to configure a second angular app as a subgenerator, for example in localhost:8080/guiapp. 

I would love the option to add a new angular application which is able to connect to jhipster rest apis
##### **JHipster configuration**
4

Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gatorade@0.0.0 /Users/superandrew/Documents/xcode/generali-simplification-lab
└── generator-jhipster@4.5.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cc.officina.gatorade",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "4.5.4",
    "baseName": "Gatorade",
    "packageName": "cc.officina.gatorade",
    "packageFolder": "cc/officina/gatorade",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-swagger2markup",
        "version": "1.2.0"
      },
      {
        "name": "generator-jhipster-transasia",
        "version": "1.0.6"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it",
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Game.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "url",
            "fieldType": "String"
        },
        {
            "fieldName": "code",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170618194749",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "game",
    "pagination": "pager"
}

```

##### **Browsers and Operating System**

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

git version 2.6.3

node: v8.0.0

npm: 5.0.0

bower: 1.7.9

gulp:
[15:54:38] CLI version 3.9.0
[15:54:38] Local version 3.9.1

yeoman: 1.8.5

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

Execution complete

##### **Browsers and Operating System**

Mac Os 
- [x] Checking this box is mandatory (this is just to show you read everything)
