### ISSUE TITLE
Empty jhiPrefix after being specified with --jhi-prefix

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6003]
##### **Overview of the issue**

I'm generating a few applications so I wanted to change the value of jhiPrefix. Specifying the `--jhi-prefix` option doesn't work as it generates a `"jhiPrefix": ""` in the `.yo-rc.json` file.

##### **Motivation for or Use Case**

Looking at the [documentation](https://jhipster.github.io/creating-an-app/#3), it should work by specifying the `--jhi-prefix` option. 

##### **Reproduce the error**

I've tried all sorts of syntax (wondering if the order is important of not) but the result is always the same, I get an empty `jhiPrefix` : 

* `jhipster app --jhi-prefix custom`
* `jhipster --jhi-prefix custom app `
* `jhipster --jhi-prefix custom`

##### **Related issues**

* [Creation of the option](https://github.com/jhipster/generator-jhipster/pull/3302)
* [Somehow related](https://github.com/jhipster/generator-jhipster/issues/5019)

##### **JHipster Version(s)**

```
tmp@0.0.0 /Users/agoncal/Documents/Code/Pluralsight/tmp
└── generator-jhipster@4.5.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tmp.tmp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "tmp",
    "packageName": "com.tmp.tmp",
    "packageFolder": "com/tmp/tmp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "278864f1f5dce7d82c22ee0227315bcca76afeec",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.1

node: v8.1.1

npm: 5.0.3

bower: 1.8.0

gulp:
[10:50:02] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.24.6

Docker version 17.06.0-ce-rc5, build b7e4173

docker-compose version 1.14.0, build c7bdf9e
