### ISSUE TITLE
Entity getter does not have the same format as in toString

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6005]
##### **Overview of the issue**

An entity with an attributed called `m49` gets a getter called `getm49` (lowercase m) and the toString method refers to `getM49()` (uppercase M). So I've modeled the entity as follow:

```
entity Country {
    iso2 String required maxlength(2),
    iso3 String required maxlength(3),
    m49 Integer required,
} 
```

The generated code looks like this:

```
@Entity
@Table(name = "country")
public class Country implements Serializable {

    @Column(name = "m_49", nullable = false)
    private Integer m49;

    public Integer getm49() {
        return m49;
    }

    public Country m49(Integer m49) {
        this.m49 = m49;
        return this;
    }

    @Override
    public String toString() {
        return "Country{" +
            ", m49='" + getM49() + "'" +
            "}";
    }
}
```
 
##### **Motivation for or Use Case**

Countries have a few codes such as ISO2, ISO3 or [M49](https://unstats.un.org/unsd/methodology/m49/).

##### **Related issues**

* [using getter in equals() and hashcode() methods](https://github.com/jhipster/generator-jhipster/pull/5681)
* [Made the #toString method use the right getter names](https://github.com/jhipster/generator-jhipster/pull/5989)

##### **JHipster Version(s)**

```
tmp@0.0.0 /Users/agoncal/Documents/Code/Temp/jhipster/tmp
└── generator-jhipster@4.5.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.tmp.tmp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "tmp",
    "packageName": "com.tmp.tmp",
    "packageFolder": "com/tmp/tmp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ee5d0663cb34de2f0bc4fb8ef02d2a5dbfc8aea6",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Country.json

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "iso2",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 2
        },
        {
            "fieldName": "iso3",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 3
        },
        {
            "fieldName": "m49",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required"
            ]
        }
    ],
    "changelogDate": "20170629103022",
    "entityTableName": "country",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.1

node: v8.1.1

npm: 5.0.3

bower: 1.8.0

gulp:
[12:40:52] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.24.6

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e
