### ISSUE TITLE
Oracle DB: entity is too long to form constraint names

### ISSUE THREAD

**Issue by endymonium** [jhipster/generator-jhipster#6006]
##### **Overview of the issue**
Oracle as Database + tables names >11 chars + OneToMany Releationship = Generator Error

```
Executing jhipster:import-jdl src/main/resources/jdl.jh
The jdl is being parsed.
Writing entity JSON files.
Generating entities.

Found the .jhipster/Organisationseinheit.json configuration file, entity can be automatically generated!

The entity Organisationseinheit being updated.

WARNING! The table name is long for Oracle, long table names can cause issues when used to create constraint names and join table names

Found the .jhipster/Einsatzort .json configuration file, entity can be automatically generated!

The entity Einsatzort is being updated.

? The table name for this entity is too long to form constraint names. Please use a shorter table name (Einsatzort )
>> The table name is too long for Oracle, try a shorter name
```

I found a [pull request](https://github.com/jhipster/generator-jhipster/pull/3817/commits/ce895a5caa16d74a1ca6f2adea027d6808906cf4) which had logic in it to shorten the constraint names in case of Oracle DB. But the code is not present in the master version of the file, [the git history does not help to find out why.](https://github.com/jhipster/generator-jhipster/commits/master/generators/entity/templates/server/src/main/resources/config/liquibase/changelog/_added_entity_constraints.xml)

What was the reason to remove it? Was it moved?

##### **Motivation for or Use Case**
We want to use JHipster in an existing enterprise landscape, the use of Oracle as DB and the table names are fixed.

##### **Reproduce the error**
1. Use Oracle DB
2. Create a jdl with two tables with name length >11
3. Create a OneToMany Relationship
4. Run jhipster import-jdl

##### **Related issues**
https://github.com/jhipster/generator-jhipster/issues/3815

##### **JHipster Version(s)**
4.5.6

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**
```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": " my.package.com.babs"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "babsBackend",
    "packageName": "my.package.com",
    "packageFolder": "my/package/com/babs",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "skipClient": true,
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
```
DEFAULT_MAX_LENGTH = 50

entity Organisationseinheit {
  foo String maxlength(DEFAULT_MAX_LENGTH) required,
  bar String maxlength(10) required,
}

entity Einsatzort {
  foo String maxlength(3) required,
  bar String maxlength(DEFAULT_MAX_LENGTH) required,
}

relationship OneToMany {
  Organisationseinheit{einsatzort} to Einsatzort
}

paginate Einsatzort, Organisationseinheit with infinite-scroll

service all with serviceImpl
dto * with mapstruct
```

##### **Browsers and Operating System**
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.1.windows.1
node: v6.10.3
npm: 5.0.3
yeoman: 2.0.0
yarn: 0.24.5

- [X ] Checking this box is mandatory (this is just to show you read everything)
