### ISSUE TITLE
PhantomJs connect ETIMEDOUT issue

### ISSUE THREAD

**Issue by devanonym** [jhipster/generator-jhipster#6007]
##### **Overview of the issue**

 Gitlab ci-cd build pipeline fail on  ./gradlew yarn_install -PnodeInstall --no-daemon

##### **Motivation for or Use Case**

Can't create a build 

##### **Reproduce the error**

1.  Create jhipster application.
2. Create jhipster ci-cd pipeline. I use gitlab.
3. Commit project to gitlab and run pipeline with gitlab runner 
First step failed on  ./gradlew yarn_install -PnodeInstall --no-daemon. 
I have error like this. 

error /builds/evgeny_rozanov/test-project/node_modules/phantomjs-prebuilt: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /builds/evgeny_rozanov/test-project/node_modules/phantomjs-prebuilt
Output:
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Error making request.
Error: connect ETIMEDOUT 192.30.253.113:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

Please report this full log at https://github.com/Medium/phantomjs
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
:yarn_install FAILED

##### **Related issues**

https://github.com/Medium/phantomjs/issues/717
https://github.com/Medium/phantomjs/issues/634

##### **Suggest a Fix**
I fixed it by creating .yarnrc file in jhipster project and added to file another cdn for phantomjs like this :
phantomjs_cdnurl "https://bitbucket.org/ariya/phantomjs/downloads". After this change all worked. 

##### **JHipster Version(s)**

```
jhipster@0.0.0 /Users/evgeny_rozanov/Projects/test-project
└── generator-jhipster@4.5.6

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "jhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "c98f8589c3a0945db239b0125212c913885b6aed",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v6.11.0

npm: 4.2.0

bower: 1.8.0

gulp:
[16:50:31] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.24.6

Docker version 17.03.1-ce, build c6d412e

docker-compose version 1.11.2, build dfed245

- [x] Checking this box is mandatory (this is just to show you read everything)
