### ISSUE TITLE
Entity with default validations rules, not correctly stored

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#6010]
##### **Overview of the issue**

When generating an entity with default validations rules, this validation is not correctly stored in JSON.

##### **Motivation for or Use Case**

The result is a problem when exporting into JDL

##### **Reproduce the error**

Here the JSON:

```yaml
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "name",
            "fieldType": "String",
            "fieldValidateRules": [
                "minlength",
                "maxlength"
            ],
            "fieldValidateRulesMinlength": "5",
            "fieldValidateRulesMaxlength": "25"
        },
        {
            "fieldName": "age",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "required",
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": "150"
        }
    ],
    "changelogDate": "20170629215405",
    "dto": "no",
    "service": "no",
    "entityTableName": "hello",
    "pagination": "no"
}
```

Here the JDL:

```yaml
entity Hello (hello) {
  name String minlength(5) maxlength(25),
  age Integer required min max(150)
}
```

##### **Related issues**

Following the discussion here: https://github.com/jhipster/generator-jhipster/commit/8b1fd4ca9b68b978b61225fdc31c04fbc02f7c7f#commitcomment-22841709

##### **Suggest a Fix**

The problem comes directly from the JSON file. The entity should be saved with `"0"` instead of `0`, but I didn't find where...

All our entities in Travis samples are without `"0"` -> so need to be updated too

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/pgrimaud/tmp/21-default
└── generator-jhipster@4.5.6  -> /home/pgrimaud/projects/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "jhipster",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "51ee67f57224be66bdf1598160e680d469d81ec2",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```yaml
entity Hello (hello) {
  name String minlength(5) maxlength(25),
  age Integer required min max(150)
}
```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.9.3

node: v6.11.0

npm: 5.0.3

bower: 1.8.0

gulp:
[00:43:36] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.24.5

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.11.2, build dfed245

Execution complete

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@MathieuAA ping

**Comment by pascalgrimaud** [comment]
A solution would be to quote the default values here:
- https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L778
- https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L788
- using `'0'` instead of `0`, `'20'` instead of `20`, etc

Are you OK with that?
If yes, I can do a PR, and update all files here:
https://github.com/jhipster/generator-jhipster/tree/master/travis/samples/.jhipster

**Comment by deepu105** [comment]
for min length 0 is a valid entry. Can you test with the quoted stuff, since js is dynamically typed shouldn't be a problem but it might fail `===` checks if any due to different types. Ideally, i would expect the json to have numbers instead of strings for this, can you check where its converted to string for the json?

**Comment by MathieuAA** [comment]
@pascalgrimaud @deepu105 I could just fix it [there](https://github.com/jhipster/jhipster-core/blob/master/lib/parser/entity_parser.js#L207).

**Comment by deepu105** [comment]
We also need to make sure what the generator creates in the json by default. Ideally it should be number instead of string

**Comment by MathieuAA** [comment]
@deepu105 I agree. Does this require a lot of changes in the generator?

**Comment by pascalgrimaud** [comment]
Here additional tests, I added some comments:

```
➜ jhe Burger
Executing jhipster:entity Burger

The entity Burger is being created.


Generating field #1

? Do you want to add a field to your entity? Yes
? What is the name of your field? bigmac
? What is the type of your field? Integer
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Minimum, Maximum
? What is the minimum of your field? 0 // <----- I type ENTER, let the default value
? What is the maximum of your field? 100 // <----- I type ENTER, let the default value

================= Burger =================
Fields
bigmac (Integer) min='0' max='100' 


Generating field #2

? Do you want to add a field to your entity? Yes
? What is the name of your field? royalcheese
? What is the type of your field? Integer
? Do you want to add validation rules to your field? Yes
? Which validation rules do you want to add? Minimum, Maximum
? What is the minimum of your field? 0 // <------ I type manually 0
? What is the maximum of your field? 100 <----- I type manually 100

================= Burger =================
Fields
bigmac (Integer) min='0' max='100' 
royalcheese (Integer) min='0' max='100' 


Generating field #3

? Do you want to add a field to your entity? No

================= Burger =================
Fields
bigmac (Integer) min='0' max='100' 
royalcheese (Integer) min='0' max='100' 


Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= Burger =================
Fields
bigmac (Integer) min='0' max='100' 
royalcheese (Integer) min='0' max='100' 



? Do you want to use a Data Transfer Object (DTO)? No, use the entity directly
? Do you want to use separate service class for your business logic? No, the REST controller should use the repository directly
? Do you want pagination on your entity? No

Everything is configured, generating the entity...
```

Here the result in JSON

```yaml
➜ cat .jhipster/Burger.json 
{
    "fluentMethods": true,
    "relationships": [],
    "fields": [
        {
            "fieldName": "bigmac",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min",
                "max"
            ],
            "fieldValidateRulesMin": 0,
            "fieldValidateRulesMax": 100
        },
        {
            "fieldName": "royalcheese",
            "fieldType": "Integer",
            "fieldValidateRules": [
                "min",
                "max"
            ],
            "fieldValidateRulesMin": "0",
            "fieldValidateRulesMax": "100"
        }
    ],
    "changelogDate": "20170630065014",
    "dto": "no",
    "service": "no",
    "entityTableName": "burger",
    "pagination": "no"
}
```

The 2 fieldValidateRulesMin are not consistent. One without double quote, one with.
