### ISSUE TITLE
An attribute Name With A Upper Case Character After The First Character  ...

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#6012]
### **Overview of the issue**

An attribute of an entity is named as, "tMail". a pair of the getter and setter is "gettMail" and "settMail" and the toString method calls "getTMail" in the generated code. That will cause a comple error.

It also causes a problem on the front end. After I type something in the required field, it still complains that it is blank. 

##### **Motivation for or Use Case**

A name of an attribute can have a upper case character right after the first character.

##### **Suggest a Fix**

?

##### **JHipster Version(s)**

4.5.6

##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
pacific-trader@0.0.0 /home/oem/Workspace-dev/e-commerce/pacificTrader
└── generator-jhipster@4.5.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.abc.app"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "app",
    "packageName": "com.abc.app",
    "packageFolder": "com/abc/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "5d4fd0fa29e3943e3e9d8c7ff8106bb32d55e312",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-nav-element",
        "version": "1.2.2"
      },
      {
        "name": "generator-jhipster-vuejs",
        "version": "0.0.3"
      }
    ],
    "enableTranslation": false
  }
}

....

```
    "changelogDate": "20170628175149",
    "entityTableName": "volumn_pricing_s",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass",
    "angularJSSuffix": "ts"
}
```


##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.5.0

bower: 1.8.0

gulp:
[16:42:53] CLI version 1.3.0
[16:42:53] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.23.4

Docker version 17.03.1-ce, build c6d412e

.yo-rc.jo
##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<!--
If the error is during an entity creation or associated with a specific entity.
If you are using JDL, please share that configuration as well.
-->

- [ ] Checking this box is mandatory (this is just to show you read everything)
##### **Overview of the issue**

An attribute of an entity is named as, "tMai"l. a pair of the getter and setter is "gettMail" and "settMail" and the toString method calls "getTMail" in the generated code. That will cause a comple error. This problem occurs after running a updated jd file and it didn't occur on the first time.

##### **Motivation for or Use Case**

A name of an attribute can have a upper case character right after the first character.

##### **Suggest a Fix**

<!-- For bug reports, if you can't fix the bug yourself, perhaps you can point to what might be
  causing the problem (line of code or commit) -->

##### **JHipster Version(s)**

4.5.6

##### **JHipster configuration**

<!--
To provide all information we need, you should run `jhipster info` in the project root folder, and
copy/paste the result here.
The `.yo-rc.json` file generated in the root folder is mandatory for bug reports. This will help us to replicate the scenario.
You should remove any sensitive information like the rememberMe key or the jwtSecretKey key.
-->
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
pacific-trader@0.0.0 /home/oem/Workspace-dev/e-commerce/pacificTrader
└── generator-jhipster@4.5.6 

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.abc.app"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "app",
    "packageName": "com.abc.app",
    "packageFolder": "com/abc/app",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "5d4fd0fa29e3943e3e9d8c7ff8106bb32d55e312",
    "clientFramework": "angular1",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-nav-element",
        "version": "1.2.2"
      },
      {
        "name": "generator-jhipster-vuejs",
        "version": "0.0.3"
      }
    ],
    "enableTranslation": false
  }
}

....

```
    "changelogDate": "20170628175149",
    "entityTableName": "volumn_pricing_s",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass",
    "angularJSSuffix": "ts"
}
```


##### **Browsers and Operating System**

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.7.4

node: v6.10.0

npm: 4.5.0

bower: 1.8.0

gulp:
[16:42:53] CLI version 1.3.0
[16:42:53] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.23.4

Docker version 17.03.1-ce, build c6d412e


- [ ] Checking this box is mandatory (this is just to show you read everything)
