### ISSUE TITLE
ng serve not working

### ISSUE THREAD

**Issue by alexsintoni** [jhipster/generator-jhipster#6050]
jhipster info
Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
jhipster@0.0.0 /home/alex/Development/workspace/java/TestsAndTutorials/jqw-jhip
└── generator-jhipster@4.5.6 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test.jqwjhipster",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "jhipster",
    "packageName": "com.test.jqwjhipster",
    "packageFolder": "com/test/jqwjhipster",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": true,
    "jwtSecretKey": "3807aa33830e9624c28e68dd6e82aadfc970e167",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "it"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Address.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "customer",
            "otherEntityName": "customer",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "address1",
            "fieldType": "String"
        },
        {
            "fieldName": "address2",
            "fieldType": "String"
        },
        {
            "fieldName": "city",
            "fieldType": "String"
        },
        {
            "fieldName": "postcode",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 10
        },
        {
            "fieldName": "country",
            "fieldType": "String",
            "fieldValidateRules": [
                "required",
                "maxlength"
            ],
            "fieldValidateRulesMaxlength": 2
        }
    ],
    "changelogDate": "20170707075618",
    "entityTableName": "address",
    "dto": "no",
    "pagination": "pager",
    "service": "no"
}
```

Category.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "parent",
            "otherEntityName": "category",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-many",
            "otherEntityRelationshipName": "category",
            "relationshipName": "product",
            "otherEntityName": "product",
            "otherEntityField": "title",
            "ownerSide": true
        }
    ],
    "fields": [
        {
            "fieldName": "linky",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "description",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "sortOrder",
            "fieldType": "Integer"
        },
        {
            "fieldName": "dateAdded",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "dateModified",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "status",
            "fieldType": "CategoryStatus",
            "fieldValues": "AVAILABLE,RESTRICTED,DISABLED"
        }
    ],
    "changelogDate": "20170707075615",
    "entityTableName": "category",
    "dto": "no",
    "pagination": "pagination",
    "service": "serviceClass"
}
```

Customer.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "address",
            "otherEntityName": "address",
            "otherEntityRelationshipName": "customer"
        },
        {
            "relationshipType": "one-to-many",
            "relationshipName": "whislist",
            "otherEntityName": "wishlist",
            "otherEntityRelationshipName": "customer"
        }
    ],
    "fields": [
        {
            "fieldName": "firstName",
            "fieldType": "String"
        },
        {
            "fieldName": "lastName",
            "fieldType": "String"
        },
        {
            "fieldName": "email",
            "fieldType": "String"
        },
        {
            "fieldName": "telephone",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20170707075617",
    "entityTableName": "customer",
    "dto": "no",
    "pagination": "pagination",
    "service": "no"
}
```

Product.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "many-to-one",
            "relationshipName": "wishlist",
            "otherEntityName": "wishlist",
            "otherEntityField": "id"
        },
        {
            "relationshipType": "many-to-many",
            "relationshipName": "category",
            "otherEntityName": "category",
            "ownerSide": false,
            "otherEntityRelationshipName": "product"
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "keywords",
            "fieldType": "String"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "rating",
            "fieldType": "Integer"
        },
        {
            "fieldName": "dateAdded",
            "fieldType": "LocalDate"
        },
        {
            "fieldName": "dateModified",
            "fieldType": "LocalDate"
        }
    ],
    "changelogDate": "20170707075616",
    "entityTableName": "product",
    "dto": "no",
    "pagination": "infinite-scroll",
    "service": "no"
}
```

Wishlist.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipType": "one-to-many",
            "relationshipName": "product",
            "otherEntityName": "product",
            "otherEntityRelationshipName": "wishlist"
        },
        {
            "relationshipType": "many-to-one",
            "relationshipName": "customer",
            "otherEntityName": "customer",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "title",
            "fieldType": "String",
            "fieldValidateRules": [
                "required"
            ]
        },
        {
            "fieldName": "restricted",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20170707075619",
    "entityTableName": "wishlist",
    "dto": "no",
    "pagination": "no",
    "service": "no"
}
```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v8.0.0

npm: 5.0.4

bower: 1.8.0

gulp:
[10:12:38] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.27.3

Execution complete

##### **Overview of the issue**
I have just created a JHipster app with last jhipster version 4.5.6.
When I try to run the command "ng serve" this is the result:
Your global Angular CLI version (1.1.3) is greater than your local
version (1.0.6). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **
Hash: edbf92e44be02e8d47da
Time: 18357ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 562 kB {3} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 204 kB {4} [initial] [rendered]
chunk    {2} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 148 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.78 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in ./src/main/webapp/manifest.webapp
Module parse failed: /home/alex/Development/workspace/java/TestsAndTutorials/jqw-jhip/src/main/webapp/manifest.webapp Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
| {
|   "name": "Jhipster",
|   "short_name": "Jhipster",
|   "icons": [
 @ ./src/main/webapp/app/polyfills.ts 6:0-29
 @ multi ./src/main/webapp/app/polyfills.ts
webpack: Failed to compile.

--------------------
I have also a JHipster app created with a previous version of jhipster command and it works fine.

I don't know why with the new version "ng serve" doesn't work
