### ISSUE TITLE
Getting "TypeError: The header content contains invalid characters" when searching with non ASCII text

### ISSUE THREAD

**Issue by aleris** [jhipster/generator-jhipster#6052]
##### **Overview of the issue**

With default generated code, when using Elasticsearch and Angular 2, getting "TypeError: The header content contains invalid characters" when searching with non ASCII characthers, for example "ș". Below the client side exception:

```
TypeError: The header content contains invalid characters
    at ServerResponse.setHeader (_http_outgoing.js:374:11)
    at setHeader (D:\Dev\openjob10\node_modules\http-proxy-middleware\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:94:15)
    at D:\Dev\openjob10\node_modules\http-proxy-middleware\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.js:116:7
    at Array.forEach (native)
    at Array.writeHeaders (D:\Dev\openjob10\node_modules\http-proxy-middleware\node_modules\http-proxy\lib\http-proxy\passes\web-outgoing.
js:111:35)
    at ClientRequest.<anonymous> (D:\Dev\openjob10\node_modules\http-proxy-middleware\node_modules\http-proxy\lib\http-proxy\passes\web-in
coming.js:166:20)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
```

##### **Motivation for or Use Case**

Bug?

##### **Reproduce the error**

In the search field of an entity put "școala" for example and hit enter. 

##### **Suggest a Fix**

1. In request-util.ts wrap `req.query` with `encodeURIComponent`:

`params.set('query', encodeURIComponent(req.query));`

2. Add a new `QueryUtil` class in \web\rest\util and an utility static method which is using `URLDecoder.decode` to decode the query as encoded by `encodeURIComponent` on client.

3. 
Change `queryStringQuery(query)` to use `QueryUtil `decode method in:
```
\generators\entity\templates\server\src\main\java\package\common\search_stream_template.ejs
\generators\entity\templates\server\src\main\java\package\common\search_template.ejs
\generators\entity\templates\server\src\main\java\package\service\impl\_EntityServiceImpl.java
\generators\server\templates\src\main\java\package\web\rest\_UserResource.java
```

I can make the changes and make a PR if is ok.

##### **JHipster Version(s)**

```
`-- generator-jhipster@4.5.6
```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "snip",
      "nativeLanguage": "ro"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "snip",
    "packageName": "snip",
    "packageFolder": "snip",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "snip",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "oj",
    "enableTranslation": true,
    "nativeLanguage": "ro",
    "languages": [
      "ro",
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**
Not relevant

- [x] Checking this box is mandatory (this is just to show you read everything)
