### ISSUE TITLE
jhipster .original war deployed on tomcat(8) throws error

### ISSUE THREAD

**Issue by superandrew** [jhipster/generator-jhipster#6054]
##### **Overview of the issue**
When deployed with production profile in a tomcat8 installation, the application launchthrows a "nosuchmethod" error

When deployed to a tomcat8 application server, the application throws this error stack:+

2017-07-07 14:44:34.682 ERROR 8373 --- [ost-startStop-6] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionFactoryImplementor.getProperties()Ljava/util/Properties;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5244)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionFactoryImplementor.getProperties()Ljava/util/Properties;
	at org.hibernate.jpa.internal.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:124)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:890)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:370)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:359)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 29 common frames omitted

Jul 07, 2017 2:44:34 PM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/gatorade]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.hibernate.engine.spi.SessionFactoryImplementor.getProperties()Ljava/util/Properties;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5244)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 10 more

##### **Motivation for or Use Case**
I'm not sure if this is a jhipster / spring boot problem, as I found this:

https://jira.spring.io/browse/SPR-14365

##### **JHipster configuration**

Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
gatorade@0.0.0 /Users/superandrew/Documents/xcode/generali-simplification-lab
└── generator-jhipster@4.5.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "cc.officina.gatorade",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "4.5.4",
    "baseName": "Gatorade",
    "packageName": "cc.officina.gatorade",
    "packageFolder": "cc/officina/gatorade",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "jwtSecretKey": "**",
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "otherModules": [
      {
        "name": "generator-jhipster-bootstrap-material-design",
        "version": "3.5.1"
      },
      {
        "name": "generator-jhipster-swagger2markup",
        "version": "1.2.0"
      },
      {
        "name": "generator-jhipster-transasia",
        "version": "1.0.6"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": [
      "it",
      "en"
    ],
    "herokuAppName": "gatoradeapp"
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Attempt.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "match",
            "otherEntityName": "match",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "attemptScore",
            "fieldType": "Long"
        },
        {
            "fieldName": "startAttempt",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "stopAttempt",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "levelReached",
            "fieldType": "String"
        },
        {
            "fieldName": "lastUpdate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "cancelled",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "completed",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20170627085006",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "attempt",
    "pagination": "pager"
}

```

Game.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "matches",
            "otherEntityName": "match",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "game"
        }
    ],
    "fields": [
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "url",
            "fieldType": "String"
        },
        {
            "fieldName": "code",
            "fieldType": "String"
        },
        {
            "fieldName": "actionId",
            "fieldType": "String"
        },
        {
            "fieldName": "type",
            "fieldType": "Integer"
        },
        {
            "fieldName": "useLevels",
            "fieldType": "Boolean"
        },
        {
            "fieldName": "levelsNumber",
            "fieldType": "Long"
        }
    ],
    "changelogDate": "20170618194749",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "game",
    "pagination": "pager"
}

```

Match.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "game",
            "otherEntityName": "game",
            "relationshipType": "many-to-one",
            "otherEntityField": "description"
        },
        {
            "relationshipName": "template",
            "otherEntityName": "matchTemplate",
            "relationshipType": "many-to-one",
            "otherEntityField": "description"
        },
        {
            "relationshipName": "attempts",
            "otherEntityName": "attempt",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "match"
        },
        {
            "relationshipName": "session",
            "otherEntityName": "session",
            "relationshipType": "many-to-one",
            "otherEntityField": "id"
        }
    ],
    "fields": [
        {
            "fieldName": "start",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "stop",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "diffLevel",
            "fieldType": "Long"
        },
        {
            "fieldName": "userId",
            "fieldType": "String"
        },
        {
            "fieldName": "lastStart",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "timeSpent",
            "fieldType": "Long"
        }
    ],
    "changelogDate": "20170627083527",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "match",
    "pagination": "pager"
}

```

MatchTemplate.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "game",
            "otherEntityName": "game",
            "relationshipType": "many-to-one",
            "otherEntityField": "description"
        }
    ],
    "fields": [
        {
            "fieldName": "maxDuration",
            "fieldType": "Long"
        },
        {
            "fieldName": "maxAttempt",
            "fieldType": "Long"
        },
        {
            "fieldName": "description",
            "fieldType": "String"
        },
        {
            "fieldName": "custom",
            "fieldType": "Boolean"
        }
    ],
    "changelogDate": "20170626123633",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "match_template",
    "pagination": "pager"
}

```

Session.json

```yaml
{
    "fluentMethods": true,
    "relationships": [
        {
            "relationshipName": "matches",
            "otherEntityName": "match",
            "relationshipType": "one-to-many",
            "otherEntityRelationshipName": "session"
        }
    ],
    "fields": [
        {
            "fieldName": "startDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "endDate",
            "fieldType": "ZonedDateTime"
        },
        {
            "fieldName": "extId",
            "fieldType": "Long"
        }
    ],
    "changelogDate": "20170705100048",
    "dto": "no",
    "service": "serviceImpl",
    "entityTableName": "session",
    "pagination": "pager"
}

```

##### **Browsers and Operating System**

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

git version 2.13.2

node: v8.0.0

npm: 5.0.0

bower: 1.7.9

gulp:
[17:07:41] CLI version 3.9.0
[17:07:41] Local version 3.9.1

yeoman: 2.0.0

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.14.0, build c7bdf9e

Execution complete

##### **Browsers and Operating System**

- [X] Checking this box is mandatory (this is just to show you read everything)
