### ISSUE TITLE
Heroku deployment failed with Angular4

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#6059]
##### **Overview of the issue**

With the recent changes on production build, a fresh application with Angular4 can't be deployed to **Heroku**

##### **Motivation for or Use Case**

When trying to deploy to Heroku, I got this error:
```
 65% building modules 499/542 modules 43 active ...storage/dist/decorators/webStorage.js
 66% building modules 507/542 modules 35 active ...storage/dist/decorators/webStorage.js
 67% building modules 515/542 modules 27 active ...storage/dist/decorators/webStorage.js
 67% building modules 523/542 modules 19 active ...storage/dist/decorators/webStorage.js
 68% building modules 531/542 modules 11 active ...storage/dist/decorators/webStorage.js
 68% building modules 534/544 modules 10 active ...xjs/observable/FromEventObservable.j 
 69% building modules 536/544 modules 8 active ...xjs/observable/FromEventObservable.js
 69% building modules 542/547 modules 5 active ...est/node_modules/rxjs/util/isArray.js
 65% building modules 542/583 modules 41 active ...dules/rxjs/operator/defaultIfEmpty.js
 63% building modules 542/610 modules 68 active ...t/node_modules/rxjs/operatortition.js
✖ { Error: stdout maxBuffer exceeded
    at Socket.<anonymous> (child_process.js:257:14)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:547:20) cmd: './mvnw package -DskipTests=true -B -Pprod' }
```

##### **Reproduce the error**

- generate a new application with Angular4
- launch `jhipster heroku`

##### **Suggest a Fix**

Following this post: https://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

See https://github.com/jhipster/generator-jhipster/pull/6060

##### **JHipster Version(s)**

```
pgrimaudherokutest@0.0.0 /home/pgrimaud/projects/pascalgrimaud/herokutest
└── generator-jhipster@4.6.0  -> /home/pgrimaud/projects/jhipster/generator-jhipster

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "io.github.pascalgrimaud",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.0",
    "baseName": "pgrimaudherokutest",
    "packageName": "io.github.pascalgrimaud",
    "packageFolder": "io/github/pascalgrimaud",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```yaml





```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.9.3

node: v6.11.0

npm: 5.0.3

bower: 1.8.0

gulp:
[00:59:28] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.27.5

Docker version 17.05.0-ce, build 89658be

docker-compose version 1.11.2, build dfed245

Execution complete

- [x] Checking this box is mandatory (this is just to show you read everything)
