### ISSUE TITLE
Self referenced entities generated using JDL import error on Angular 4

### ISSUE THREAD

**Issue by scepanovicmarko** [jhipster/generator-jhipster#6063]
Executing jhipster:info
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
alt-test-app-ang-4@0.0.0 /Users/markoscepanovic/Documents/Alt36/AltTestAppAng4
└── generator-jhipster@4.6.0

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.alt36",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.6.0",
    "baseName": "AltTestAppAng4",
    "packageName": "com.alt36",
    "packageFolder": "com/alt36",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "7174c7a4e2c35623ab11cc88cb723782c9759b5d",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```yaml
entity Region (region) {
  regionName String
}
entity Country (country) {
  countryName String
}
/**
 * not an ignored comment
 */
entity Location (location) {
  streetAddress String,
  postalCode String,
  city String,
  stateProvince String
}
entity Department (department) {
  departmentName String required
}
/**
 * Task entity.
 * @author The JHipster team.
 */
entity Task (task) {
  title String,
  description String
}
/**
 * The Employee entity.
 */
entity Employee (employee) {
  /**
   * The firstname attribute.
   */
  firstName String,
  lastName String,
  email String,
  phoneNumber String,
  hireDate ZonedDateTime,
  salary Long,
  commissionPct Long
}
entity Job (job) {
  jobTitle String,
  minSalary Long,
  maxSalary Long
}
entity JobHistory (job_history) {
  startDate ZonedDateTime,
  endDate ZonedDateTime,
  language Language
}

enum Language {
  FRENCH,
  ENGLISH,
  SPANISH
}

relationship OneToOne {
  Country{region} to Region,
  Location{country} to Country,
  Department{location} to Location,
  JobHistory{job} to Job,
  JobHistory{department} to Department,
  JobHistory{employee} to Employee
}
relationship OneToMany {
  /**
   * A relationship
   */
  Department{employee} to Employee{department},
  Employee{job} to Job{employee}
}
relationship ManyToOne {
  Employee{manager} to Employee
}
relationship ManyToMany {
  Job{task(title)} to Task{job}
}

dto Region with mapstruct
service Region with serviceImpl
angularSuffix Region with mySuffix
dto Country with mapstruct
service Country with serviceImpl
angularSuffix Country with mySuffix
dto Location with mapstruct
service Location with serviceImpl
angularSuffix Location with mySuffix
dto Department with mapstruct
service Department with serviceImpl
angularSuffix Department with mySuffix
dto Task with mapstruct
service Task with serviceImpl
angularSuffix Task with mySuffix
dto Employee with mapstruct
paginate Employee with infinite-scroll
angularSuffix Employee with mySuffix
dto Job with mapstruct
paginate Job with pagination
angularSuffix Job with mySuffix
dto JobHistory with mapstruct
paginate JobHistory with infinite-scroll
service JobHistory with serviceImpl
angularSuffix JobHistory with mySuffix

```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.2

node: v6.11.0

npm: 3.10.10

bower: 1.8.0

gulp:
[14:35:57] CLI version 1.3.0

yeoman: 2.0.0

yarn: 0.24.6
