### ISSUE TITLE
making all entities implement base-entity.ts is against Type-Safe

### ISSUE THREAD

**Issue by sohibegit** [jhipster/generator-jhipster#6068]
```
class A {}
class B {}

a: A;
this.a = new B(); fail
```
 the compiler will complain here and this is good as A is not B 

```
class a implements BaseEntity{}
class b implements BaseEntity{}

a: A;
this.a = new B(); pass
```
the compiler will **not** complain here and i guess this is bad

##### **JHipster Version(s)**

```
goldenc@0.0.0 /home/sohibe/Dropbox/fikra/goldenc
└── generator-jhipster@4.6.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "tech.fikra.goldenc",
      "nativeLanguage": "fa"
    },
    "jhipsterVersion": "4.6.0",
    "baseName": "goldenc",
    "packageName": "tech.fikra.goldenc",
    "packageFolder": "tech/fikra/goldenc",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fa",
    "languages": [
      "fa",
      "en"
    ]
  }
}
```

##### **Browsers and Operating System**

openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.4

node: v8.1.3

npm: 5.0.3

yarn: 0.27.5
