### ISSUE TITLE
reload page your request cannot be processed

### ISSUE THREAD

**Issue by MatthewGouws** [jhipster/generator-jhipster#6100]
##### **Overview of the issue**
When reloading a page on the running application (Default port 8080) the angular router does not pick up a request.

##### **Motivation for or Use Case**
This issue is preventing activation and direct navigation throughout the app.

##### **Reproduce the error**
When running ./gradlew and refreshing a page, the application attempts to make a backend call instead of a call to the router

##### **JHipster Version(s)**
4.0.1

##### **JHipster configuration**
```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.4.1",
    "baseName": "x",
    "packageName": "com.x",
    "packageFolder": "com/x",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "useSass": false,
    "clientPackageManager": "npm",
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling",
      "cucumber",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "de"
    ],
    "serviceDiscoveryType": false,
    "clientFramework": "angular2"
  }
}

```

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```yaml





```

##### **Browsers and Operating System**

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

git version 2.7.4

node: v7.4.0

npm: 4.1.1

bower: 1.7.9

gulp:
[22:51:08] CLI version 1.2.2

yeoman: 1.8.5

yarn: 0.27.5

Docker version 1.13.1, build 092cba3

Execution complete

##### **Browsers and Operating System**

all Browsers

- [X ] Checking this box is mandatory (this is just to show you read everything)
