### ISSUE TITLE
Hibernate Validation, Custom Messages for fields are not set in fieldErrors.message 

### ISSUE THREAD

**Issue by Pinguwien** [jhipster/generator-jhipster#6104]
##### **Overview of the issue**

Using JHipster 4.5.2, when adding `message="myMessage here"` to any object-field for JSR303-Validation using Hibernate Validator, the message does not get served to the frontend because   

##### **Motivation for or Use Case**

It is a bug for me because we use JHipster without client and our use case is to make the messages configurable by a cms module and serve them from serverside. This is not possible in the standard implementation. I am aware messages are served on clientside when using jhipster-client, too. 

##### **Reproduce the error**

1. Create a new JHipster Project (monolith, see config, but I think it works with others as well?!)
2. Extend the Size-validation rule for "password" (or any other) in Class `ManagedUserVM` in `web.rest/vm` package like this:
```
...
public static final int PASSWORD_MIN_LENGTH = 4;

    public static final int PASSWORD_MAX_LENGTH = 100;

    @Size(min = PASSWORD_MIN_LENGTH, max = PASSWORD_MAX_LENGTH, message="wrong pw!")
...
```

3. Start instance, call http://localhost:8080/api/register with a POST request with following body:

```
{
	"login": "test",
	"password": "asd",
	"firstName": "Tester"
}
```

You''ll get a response like this:

```
{
    "message": "error.validation",
    "description": null,
    "fieldErrors": [
        {
            "objectName": "managedUserVM",
            "field": "password",
            "message": "Size"
        }
    ]
}
```

Here, "message" should have the value `wrong pw!` to mimic standard hibernate validation functionality.

##### **Related issues**

didn't find any.

##### **Suggest a Fix**
I don't know if this behaviour is intended for some processing of the message-value in the client, so no pullrequest, but this:

In Package `web.rest/errors` in Class `ExceptionTranslator` in Method `processValidationError` on line 42, the value of message is set to `fieldError.getCode()` - to prevent the non-standard-behaviour, this should be set to `fieldError.getDefaultMessage()` instead, which actually returns the entered message.

##### **JHipster Version(s)**

```
sample@0.0.0 /Git/jhipster-sample
└── generator-jhipster@4.5.2 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "de.gatesservices"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "sample",
    "packageName": "de.gatesservices",
    "packageFolder": "de/gatesservices",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.11.0 (Apple Git-81)

node: v6.10.3

npm: 5.0.1

yeoman: 2.0.0

yarn: 0.24.6

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

every entity.

##### **Browsers and Operating System**

OSX 10.12.5, every browser (serverside issue)

- [x] Checking this box is mandatory (this is just to show you read everything)
