### ISSUE TITLE
If user is already logged in, navbar show unauthenticated menu entries on refresh on route that does not need specific authorities

### ISSUE THREAD

**Issue by bbbenja** [jhipster/generator-jhipster#6190]
##### **Overview of the issue**

If user is already logged in, navbar show unauthenticated menu entries on refresh on route that does not need specific authorities

In `UserRouteAccessService`, if no `authorities`, `checkLogin` is not called, so `authenticated` field is not updated in `Principal`

##### **Motivation for or Use Case**

Create a new route accessible by everyone, log in with your user, go to this route, refresh the page

##### **Suggest a Fix**

Change to always call `checkLogin` in `UserRouteAccessService`

##### **JHipster Version(s)**

4.5.6

##### **JHipster Version(s)**

```
senstools@0.0.0 /Users/bcousin/workspace/rcp/sensotools-back
└── generator-jhipster@4.5.6

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "4.5.6",
    "baseName": "",
    "packageName": "",
    "packageFolder": "",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": true,
    "jwtSecretKey": "",
    "clientFramework": "angular2",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "languages": [
      "fr"
    ]
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.7.0

node: v7.10.0

npm: 5.0.4

bower: 1.8.0

yeoman: 1.8.5

yarn: 0.24.5

Docker version 17.06.1-ce-rc1, build 77b4dce

docker-compose version 1.14.0, build c7bdf9e

- [x] Checking this box is mandatory (this is just to show you read everything)
