### ISSUE TITLE
Replace OAuth 2.0 embedded with redirect to IdP

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#6360]
Discussion at https://github.com/gmarziou/jhipster-keycloak/issues/2

##### **Overview of the issue**

The current OAuth 2.0 implementation uses an embedded server and doesn't support external OAuth 2.0 providers. OAuth 2.0 and OIDC make it easy to get user information from 3rd party sources. We should make it easier for developers to leverage these protocols.

##### **Motivation for or Use Case**

No one uses our current OAuth 2.0 support and Keycloak and Okta are pretty cool IdPs.

##### **Reproduce the error**

Try creating a JHipster app with OAuth 2.0 and witness that there's a service that embeds the clientId and clientSecret in its authentication call. Not a best practice.

##### **Related issues**

Possibly, not sure.

##### **Suggest a Fix**

Working on a PR now.

##### **JHipster Version(s)**

4.8.1

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by danielpetisme** [comment]
@mraible the `jhipster-keycloak` image have made can be replace by a bit of `docker-compose` config.
```
version: '2'
services:
  keycloak:
    image: jboss/keycloak:3.3.0.CR1
    command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"]
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 9080:8080
      - 8443:8443
      - 9990:9990
```
With this version you have to generate the `realm-config` with the `jhipster-realm.json` and `jhipster-users-0.json` files ( the one you can find [here](https://github.com/danielpetisme/jhipster-keycloak/tree/master/import))
The `command` execute is actually the one I ran in the `Dockerfile` of the image I have built.

The main benefit of using the above `docker-compose` is that Jhipster is not depending on a lazy boy like may to provide up to date images 😉  it uses directly the official images provided by the keycloak team. 
So a bit more configuration to generate but for me it sounds way more convenient for JHipster.
