### ISSUE TITLE
Integration tests and @Transactional

### ISSUE THREAD

**Issue by xtremebiker** [jhipster/generator-jhipster#6415]
##### **Integration tests shouldn't be @Transactional at all**

I don't think the generated integration tests should be `@Transactional` as they currently are. Integration tests might perform several operations against `Resource` or `Service` classes and they might involve several transactions, depending on how they are configured. In short words, an integration test should never declare a transaction, IMO, as the real use case might involve a single transaction or more.

##### **Reproduce the error**

Even with `@Transactional` annotations on each test method, sometimes the context gets dirty and we get some previously saved info in the tests. This violates the principle of isolation between each of the tests.

##### **Suggest a Fix**

Using [`@DirtiesContext(classMode = ClassMode.BEFORE_EACH_TEST_METHOD)`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/test/annotation/DirtiesContext.html) in top of the test classes avoids this kinds of issues. It creates a new context for each test, which happens to be slower in execution, but guarantees isolation between each test: https://stackoverflow.com/a/37246354/1199132

##### **JHipster Version(s)**

4.4.1

##### **JHipster configuration**

Test application.yml:

```
spring:
  application:
    name: selfprotection
  jackson:
    serialization.write_dates_as_timestamps: false
  cache:
    type: none
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:selfprotection;DB_CLOSE_DELAY=-1
    name: null
    username: null
    password: null
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedH2Dialect
    database: H2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.hbm2ddl.auto: create-drop
  mail:
    host: localhost
  messages:
    basename: i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
flyway:
  enabled: false
security:
  basic:
    enabled: false
server:
  port: 10344
  address: localhost
jhipster:
  async:
    core-pool-size: 1
    max-pool-size: 50
    queue-capacity: 10000
  security:
    remember-me:
      key: 5ec625f10cf662a48031f6f2acb2d1846c5ce666
  metrics:
    jmx.enabled: true
```
