### ISSUE TITLE
UAA: can't access to administration pages

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#6486]
##### **Overview of the issue**

When using UAA option, I can't access to the administration pages

That's why the build for UAA + Protractor tests failed since more than 1 week:
- https://travis-ci.org/hipster-labs/jhipster-travis-build/builds/284099556
- https://travis-ci.org/hipster-labs/jhipster-travis-build/jobs/284099559

It works for 4.9.0, but it's broken in current master.

##### **Reproduce the error**

- generate a UAA project
- generate a gateway
- start the registry
- start UAA and wait
- start the gateway

##### **Related issues**

Similar to this ticket: https://github.com/jhipster/generator-jhipster/issues/6443

##### **Suggest a Fix**

Probably related to Angular part, so I have no idea for the moment, sorry :(
But some solution have been discuted here https://github.com/jhipster/generator-jhipster/issues/6443

##### **JHipster Version(s)**

Master only
Not in the last release 4.9.0

##### **JHipster configuration**

UAA project:
```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "uaa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bed31ce04f0071dd3700faff9e94b2131a0588d1",
    "enableTranslation": false,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "clientPackageManager": "yarn"
  }
}
```

Gateway project:
```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.9.0",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Environment and Tools**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.0

node: v6.11.1

npm: 5.4.2

bower: 1.8.0

gulp:
[01:22:05] CLI version 1.2.2

yeoman: 1.8.5

yarn: 1.1.0

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.16.1, build 6d1ac21

Execution complete

- [x] Checking this box is mandatory (this is just to show you read everything)
