### ISSUE TITLE
[Feature] Set log levels configuration in YAML properties rather than logback.xml

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/generator-jhipster#6709]
##### **Overview of the issue**

Currently, log levels are setup in `src/main/resources/logback-spring.xml` as such:
```
    <logger name="io.github.jhipster.sample" level="#logback.loglevel#"/>
    <logger name="io.github.jhipster" level="#logback.loglevel#"/>

    <logger name="javax.activation" level="WARN"/>
    <logger name="javax.mail" level="WARN"/>
    <logger name="javax.xml.bind" level="WARN"/>
    <logger name="ch.qos.logback" level="WARN"/>
    <logger name="com.codahale.metrics" level="WARN"/>
    <logger name="com.ryantenney" level="WARN"/>
    <logger name="com.sun" level="WARN"/>
    <logger name="com.zaxxer" level="WARN"/>
    <logger name="io.undertow" level="WARN"/>
    <logger name="io.undertow.websockets.jsr" level="ERROR"/>
    <logger name="org.ehcache" level="WARN"/>
    <logger name="org.apache" level="WARN"/>
    <logger name="org.apache.catalina.startup.DigesterFactory" level="OFF"/>
    <logger name="org.bson" level="WARN"/>
    <logger name="org.hibernate.validator" level="WARN"/>
    <logger name="org.hibernate" level="WARN"/>
    <logger name="org.hibernate.ejb.HibernatePersistence" level="OFF"/>
    <logger name="org.springframework" level="WARN"/>
    <logger name="org.springframework.web" level="WARN"/>
    <logger name="org.springframework.security" level="WARN"/>
    <logger name="org.springframework.cache" level="WARN"/>
    <logger name="org.thymeleaf" level="WARN"/>
    <logger name="org.xnio" level="WARN"/>
    <logger name="springfox" level="WARN"/>
    <logger name="sun.rmi" level="WARN"/>
    <logger name="liquibase" level="WARN"/>
    <logger name="LiquibaseSchemaResolver" level="INFO"/>
    <logger name="sun.rmi.transport" level="WARN"/>

    <root level="#logback.loglevel#">
        <appender-ref ref="CONSOLE"/>
    </root>
```
However Spring Boot allows configuring those log levels as properties: 
```
logging:
    level:
        ROOT: #logback.loglevel#
        io.github.jhipster.sample:  #logback.loglevel#
        io.github.jhipster:  #logback.loglevel#
        javax.activation: WARN
        javax.mail: WARN
        javax.xml.bind: WARN
        ch.qos.logback: WARN
        com.codahale.metrics: WARN
        com.ryantenney: WARN
        com.sun: WARN
        com.zaxxer: WARN
        io.undertow: WARN
        io.undertow.websockets.jsr: ERROR
        org.ehcache: WARN
        org.apache: WARN
        org.apache.catalina.startup.DigesterFactory: OFF
        org.bson: WARN
        org.hibernate.validator: WARN
        org.hibernate: WARN
        org.hibernate.ejb.HibernatePersistence: OFF
        org.springframework: WARN
        org.springframework.web: WARN
        org.springframework.security: WARN
        org.springframework.cache: WARN
        org.thymeleaf: WARN
        org.xnio: WARN
        springfox: WARN
        sun.rmi: WARN
        liquibase: WARN
        LiquibaseSchemaResolver: INFO
        sun.rmi.transport: WARN
```
##### **Motivation for or Use Case**

- Handle the case of running the app without starting the maven build will cause the logback.xml file (YAML file treat `#` as comments)
- Set all configuration in one place
- For apps using the registry this is cleaner when defining those properties from the Registry (config server) as you know which property will take priority.

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/6703

##### **JHipster Version(s)**

v4.10.2

##### **JHipster configuration**

All JHipster configurations will be affected

- [X] Checking this box is mandatory (this is just to show you read everything)

As requested by @jdubois this will be subject to a vote as it might break existing configurations. So please 👍 or 👎.
