### ISSUE TITLE
App restart inappropriately after connect in h2-console when I started application using main method inside Eclipse IDE

### ISSUE THREAD

**Issue by netstart** [jhipster/generator-jhipster#6858]
##### **Overview of the issue**

Up application using Java file with method main(String [] args), after initialization enter in the[ h2 console ](http://localhost:8081/h2-console) and connect, It will restart aplication inappropriately

I my case I am use right button's mouse to start aplication in Eclipse.

##### **Reproduce the error**

Make app using this options:

? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? teste
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8081
? What is your default Java package name? com.mycompany.myapp
? Which service discovery server do you want to use? No service discovery
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *type* of database would you like to use? SQL (H2, MySQL, MariaDB, PostgreSQL, Oracle)
? Which *production* database would you like to use? PostgreSQL
? Which *development* database would you like to use? H2 with disk-based persistence
? Do you want to use Hibernate 2nd level cache? Yes, with HazelCast (distributed cache, for multiple nodes)
? Would you like to use Maven or Gradle for building the backend? Gradle
? Which other technologies would you like to use? API first development using swagger-codegen
? Would you like to enable internationalization support? No
? Besides JUnit and Karma, which testing frameworks would you like to use?
? Would you like to install other generators from the JHipster Marketplace? No

##### **JHipster Version(s)**

```
teste@0.0.0 C:\src\portaldainovacao\teste
`-- generator-jhipster@4.12.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "4.12.0",
    "baseName": "teste",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": false,
    "applicationType": "microservice",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

##### **Browsers and Operating System**
Windows 8 
Chrome Versão 62.0.3202.94 (Versão oficial) 64 bits

##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.15.0.windows.1
node: v9.0.0
npm: 5.5.1
bower: 1.8.2
gulp:
CLI version 3.9.1
yeoman: 2.0.0
yarn: 1.3.2

- [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I just tested with Intellij IDEA and had absolutely no issue at all.... I guess this is caused by your version of Eclipse, or maybe you have some specific plugin doing this?
This is a setup issue with Eclipse, not JHipster, so I'm closing this. You could run your application using Gradle, I guess Eclipse won't "see" it.

**Comment by netstart** [comment]
Sorry but I thinks it´s not Eclipse bug.
I tested as following versions: oxygen, neon, mars, luna, kepler. All this versios have the same problem.

In another project built without JHipster, this works

**Comment by gmarziou** [comment]
Are you able to reproduce the issue using only `gradlew`  from Windows command prompt?

**Comment by gmarziou** [comment]
By the way, you're using nodejs 9 which is not an LTS version (our recommendation), not related to your issue but you'd be safer to downgrade.

**Comment by netstart** [comment]
Using gradlew it woks, but i cant use break point :D

I try use node 8.9.3, it's not work too


##### **Environment and Tools**
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
git version 2.15.0.windows.1
node: v8.9.3
npm: 5.5.1
bower: 1.8.2
gulp:
[14:34:27] CLI version 3.9.1
yeoman: 2.0.0
yarn: 1.3.2

**Comment by jdubois** [comment]
I just opened it with the latest Eclipse Neon, on Mac OS X, no problem at all. I'm sorry but I can't reproduce, even with Eclipse.

**Comment by Sebastiandg7** [comment]
Same thing happening here. Starting project from Windows CMD and the project keeps restarting after I start a session in the H2 Console.

**Comment by gmarziou** [comment]
@Sebastiandg7 please paste the output of `jhipster info` so that I try to reproduce.

**Comment by gmarziou** [comment]
i wonder whether this could be related to h2.properties being saved and triggering a restart, maybe we could exclude it [as documented](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart-exclude).

**Comment by Sebastiandg7** [comment]
@gmarziou Yes, I thought about that but had no luck excluding it from the devtools reload. Here is the jhipster info output:

Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
<appname>@0.0.0 D:\GitKraken\******
`-- generator-jhipster@4.14.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "my.package",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "4.14.1",
    "baseName": "appname",
    "packageName": "my.package",
    "packageFolder": "my/package",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mssql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": [
      "es",
      "en"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
** 
... JDL model here...
**

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.16.2.windows.1

node: v8.9.4

npm: 5.6.0

yeoman: 2.0.1

yarn: 1.5.1

Congratulations, JHipster execution is complete!

**Comment by ruddell** [comment]
I also couldn't reproduce either, @ederagp also reported this in the Gitter when using VIsual Studio Code.

**Comment by gmarziou** [comment]
> @Ederagp also reported this in the Gitter when using VIsual Studio Code.

I also ran VS Code in parallel with the app and I was on Windows 10.

**Comment by Ederagp** [comment]
> I set these exclusions in application-dev.yml:
> 
>     devtools:
>         restart:
>             enabled: true
>             exclude: .h2.server.properties,static/**,templates/**

** has worked for me working in Visual Studio Code **
Note: however if I remove the exclusion it keeps restarting and this is for all the projects that I have

**Comment by gmarziou** [comment]
So maybe it is related to your Visual Studio Code setup, maybe some extensions you have installed.
Could you list them with `code --list-extensions` ?

On my system it prints:

~~~
DigitalBrainstem.javascript-ejs-support
donjayamanne.githistory
eg2.tslint
jhipster-ide.jdl
mrmlnc.vscode-scss
msjsdiag.debugger-for-chrome
natewallace.angular2-inline
QassimFarid.ejs-language-support
raymondcamden.CSSLint
richie5um2.vscode-sort-json
swyphcosmo.spellchecker
Valiantsin.operatormonodarktheme
wmaurer.change-case
~~~

I suspect some extensions dealing with java code or properties files, I don't use any because I use IntelliJ for server code and VS Code only for client code.

**Comment by Ederagp** [comment]
@gmarziou the installed extensions that my system lists:

```
Angular.ng-template
abusaidm.html-snippets
herrherrmann.angular-bootstrap
johnpapa.Angular1
msjsdiag.debugger-for-chrome
redhat.java
samverschueren.yo
vscjava.vscode-java-debug
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
wcwhitehead.bootstrap-3-snippets
```

do you think any of it is the cause of the problem?

**Comment by gmarziou** [comment]
You could try disabling redhat.java and vscjava.*

**Comment by Ederagp** [comment]
@gmarziou, undo the suggested extensions and work the connection to h2-console without any problem.
the extensions that you uninstall, in visual studio code, give support to help with commands and autocomplete in java encoding, without these extensions you do not mark syntax errors among others. I'll find another one and I'll try it

**Comment by gmarziou** [comment]
OK but even the community edition of IntelliJ does all this and so much more.

Anyway, if the exclusions in application-dev.yml work, we could add them to generator.
I'd like to get some feedback from other users like @netstart who opened the issue.

**Comment by jdubois** [comment]
Very interesting! Indeed there's an issue with the IDE but if we can
exclude the files then let's do it.

Le mer. 28 mars 2018 à 18:58, Gaël Marziou <notifications@github.com> a
écrit :

**Comment by Ederagp** [comment]
hello again, I made a change to my file `applicaction-dev-yml` removed the extensions that cause the problem and removing the `exclude: .h2.server.properties,static/**,templates/**`
But now it does not automatically restart the app when I make a change in some .java file, which is the cause?

`application-dev.yml:`
```
logging:
    level:
        ROOT: DEBUG
        com.roni.recolector: DEBUG
        io.github.jhipster: DEBUG

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/recolectorresiduos;DB_CLOSE_DELAY=-1
        username: recolectorResiduos
        password:
    h2:
        console:
            enabled: false
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
```

**Comment by gmarziou** [comment]
No idea.

**Comment by xmeng1** [comment]
@Ederagp  method works, exclude the h2 file which lead to this issue (after connect to H2, the file in this folder change and after check this change, the devtools restart the server)
```
devtools:
        restart:
            enabled: true
            exclude: .h2.server.properties,static/**,templates/**
```

**Comment by ebaccon** [comment]
Same problem for me with v5.3.1.

Like said @Ederagp, the solution below is correct in application-dev.yml :

```
devtools:
        restart:
            enabled: true
            exclude: .h2.server.properties,static/**,templates/**
```
