### ISSUE TITLE
app.constants.ts is not regenerating

### ISSUE THREAD

**Issue by iceddante** [jhipster/generator-jhipster#6898]
##### Cannot get app.constants.ts to regenerate
the message in app.constants for my Angular 2 project is clear: you should not modify that file directly but should change the webpack/webpack.common.js file instead. So I did!

```
const DATAS = {
    VERSION: JSON.stringify(require("../package.json").version),
    DEBUG_INFO_ENABLED: options.env === 'dev',
    TESTCONFIG: JSON.stringify('hello world')
};
```

Web pack redeploys but I don't see my new constant in app.constants.ts

I tried running the webpack build script and deleting the app.constants.ts file to see if it would regenerate but neither of these worked. This seems to be a bug, but perhaps I am missing a step.

##### **Motivation for or Use Case**
Based on my reading of the environment, adding a new constant to DATAS should cause it to appear in app.consts... I'm trying to do some environment-based configuration inside of my angular app and this is necessary for that.

It seems like many people would have tried this by now... so I am probably doing something wrong. If that is the case my apologies!

##### **Reproduce the error**

1. Generate a monolithic Angular 2 application
2. Run the server with ./mvnw
3. Run webpack with `yarn start`
4. edit webpack/webpack.common.js at module.exports.DATA to add an entry
5. Wait for webpack to redeploy and check the app.constants.ts file

##### **Suggest a Fix**
At this moment I am not sure- I do plan on manually editing the app.constants.ts file for now just so I can keep moving :-)

##### **JHipster Version(s)**

```
cdmadmin@0.0.0 /Users/iceddante/git/angular2jhipster
├── UNMET PEER DEPENDENCY @angular/common@4.1.3
├── UNMET PEER DEPENDENCY @angular/core@4.1.3
└── generator-jhipster@4.5.3 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.hcbcbs.cdmadmin"
    },
    "jhipsterVersion": "4.5.3",
    "baseName": "cdmadmin",
    "packageName": "com.hcbcbs.cdmadmin",
    "packageFolder": "com/hcbcbs/cdmadmin",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "no",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "89ba10e5129d8396d20693c0fde6fa0ee683ca70",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json

##### **Browsers and Operating System**

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

git version 2.13.6 (Apple Git-96)

node: v6.11.0

npm: 3.10.10

bower: 1.8.0

yeoman: 2.0.0

yarn: 0.24.6

Docker version 17.09.1-ce, build 19e2cf6

docker-compose version 1.17.1, build 6d101fb

Execution complete

##### **Browsers and Operating System**

Mac OSX, Windows 7
- [X] Checking this box is mandatory (this is just to show you read everything)
