### ISSUE TITLE
Docker instructions for jhipster.github.io

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#7067]
The Docker instruction for [jhipster.github.io](https://github.com/jhipster/jhipster.github.io) is not correct.

This command `docker container run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 4000:4000 jekyll/jekyll:pages bundle exec jekyll serve` doesn't work, with the following stacktrace:
```
17:55:52 in projects/jhipster/jhipster.github.io on  master [⇡] took 3s 
➜ docker container run --rm --label=jekyll --volume=$(pwd):/srv/jekyll -it -p 4000:4000 jekyll/jekyll:pages bundle exec jekyll serve
Unable to find image 'jekyll/jekyll:pages' locally
pages: Pulling from jekyll/jekyll
ff3a5c916c92: Already exists 
8e2da6035957: Pull complete 
fbe0bab22a62: Pull complete 
8e2667ae1d45: Pull complete 
478ded4e5d89: Pull complete 
Digest: sha256:ea071af041b6409633a34ed3f7d51dd2c244439577bb623ee03659ddbfce6804
Status: Downloaded newer image for jekyll/jekyll:pages
Traceback (most recent call last):
	14: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	13: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
	11: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	10: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:257:in `resolve'
	 4: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:22:in `resolve'
	 3: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:48:in `start'
	 2: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:257:in `verify_gemfile_dependencies_are_found!'
	 1: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:257:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/resolver.rb:289:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

I will try to fix it.

**Comment by pascalgrimaud** [comment]
@agoncal @PierreBesson : can you try this `docker-compose.yml` inside the `jhipster.github.io` project and tell me if it works for you plz ? The site will be available at `http://0.0.0.0:4000`
Note: it will create a volume to your `~/volumes/jhipster.github.io` folder, so you won't need to download all gems, each time you start the container.

```yaml
version: "2.1"
services:
  site:
    container_name: jhipster.github.io
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      # this volume will keep all gems
      - ~/volumes/jhipster.github.io/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
```

**Comment by pascalgrimaud** [comment]
After discussion with @PierreBesson, a better solution would be to mount a local volume to the project, and add `vendor/` folder to `.gitignore` :

```yaml
version: "2.1"
services:
  site:
    container_name: jhipster.github.io
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      # this volume will keep all gems
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
```

If OK, I will do a PR
