### ISSUE TITLE
Change OAuth for microservices to use jwk.key-set-uri instead of jwt.key-uri

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7116]
##### **Overview of the issue**

Currently, the OAuth implementation for microservices uses `jwt.key-uri`:

```yaml
security:
    oauth2:
        client:
            access-token-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token
            user-authorization-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth
            <%_ if (applicationType === 'gateway' || applicationType === 'monolith') { _%>
            client-id: web_app
            client-secret: web_app
            client-authentication-scheme: form
            scope: openid profile email
            <%_ } _%>
            <%_ if (applicationType === 'microservice') { _%>
            client-id: internal
            client-secret: internal
            authentication-scheme: header
            client-authentication-scheme: header
            <%_ } _%>
        resource:
            filter-order: 3
            user-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            token-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token/introspect
            <%_ if (applicationType === 'gateway' || applicationType === 'microservice') {  _%>
            jwt:
                key-uri: http://localhost:9080/auth/realms/jhipster
            <%_ } _%>
```
And then it fetches the public key in [`MicroservicesSecurityConfiguration.java`](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/config/_MicroserviceSecurityConfiguration.java#L303):

```java
@Bean
@ConditionalOnProperty("security.oauth2.resource.jwt.key-uri")
public TokenStore tokenStore(JwtAccessTokenConverter jwtAccessTokenConverter) {
    return new JwtTokenStore(jwtAccessTokenConverter);
}

@Bean
@ConditionalOnProperty("security.oauth2.resource.jwt.key-uri")
public JwtAccessTokenConverter jwtAccessTokenConverter() {
    JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
    converter.setVerifierKey(getKeyFromAuthorizationServer());
    return converter;
}

private String getKeyFromAuthorizationServer() {
    return Optional.ofNullable(
        new RestTemplate()
            .exchange(
                resourceServerProperties.getJwt().getKeyUri(),
                HttpMethod.GET,
                new HttpEntity<Void>(new HttpHeaders()),
                Map.class
            )
            .getBody()
            .get("public_key"))
        .map(publicKey -> String.format("-----BEGIN PUBLIC KEY-----\n%s\n-----END PUBLIC KEY-----", publicKey))
        .orElse(resourceServerProperties.getJwt().getKeyValue());
}
```

##### **Motivation for or Use Case**

This works, but it'd be much easier to use `jwt.key-set-uri` which would allow for key rotation and works for both Keycloak and Okta.

##### **Suggest a Fix**

Change `src/main/resources/config/application.yml` to use the following for microservices:

```yaml
security:
    basic:
        enabled: false
    oauth2:
        client:
            access-token-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token
            user-authorization-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth
            client-id: internal
            client-secret: internal
            authentication-scheme: header
            client-authentication-scheme: header
        resource:
            filter-order: 3
            user-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            token-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token/introspect
            prefer-token-info: false
            jwk:
                key-set-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/certs
```

##### **JHipster Version(s)**

4.14.0

- [x] Checking this box is mandatory (this is just to show you read everything)
