### ISSUE TITLE
OAuth2 configuration refinements

### ISSUE THREAD

**Issue by farrault** [jhipster/generator-jhipster#7281]
##### **Overview of the issue**

I think that Jhipster generates some unused artifact with OAuth2 authentifications profiles. 
And that it could be simplified.

##### **Motivation for or Use Case**

In a Microservice or Gateway application, the application.yml file contains : 
```
security:
    oauth2:
        resource:
            user-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            token-info-uri: http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token/introspect
            prefer-token-info: false
            jwt:
                key-uri: http://localhost:9080/auth/realms/jhipster
```

A vanilla Spring Boot application uses only one of these three uris. 
- it prefers the jwt.key-uri if present, to decode the access_token without calling the authorization server
- if the latter is not present, it uses user-info-uri OR token-info-uri (depending on prefer-token-info) to call the authz server and extract the user information
  but I'm not aware of a situation where it could use BOTH
(see Spring Boot's ResourceServerTokenServicesConfiguration) 
                    
That being said, in a JHipster microservice or gateway, there is a MicroserviceSecurityConfiguration that defined : 
- a custom ResourceServerTokenServices (based on UserInfoTokenServices that uses the user-info-uri )
- a custom TokenStore    
           
The presence of this UserInfoTokenServices disables the standard Spring Boot behaviour (offline jwt decoding) : 
```
   ResourceServerTokenServicesConfiguration.JwtTokenServicesConfiguration#jwtTokenServices:
      Did not match:
         - @ConditionalOnMissingBean (types: org.springframework.security.oauth2.provider.token.ResourceServerTokenServices; SearchStrategy: all) found bean 'userInfoTokenServices' (OnBeanCondition)
```
( And I didn't find the usage of the custom TokenStore ) 
      
So in the end, token-info-uri and jwt.key-uri doesn't seems to be used in either gateway or microservice application :
Jhipster calls the authz server to validate and decode the access_token
(which is probably the reason you use a cache on this call, on CachedUserInfoTokenServices (which is essentially useful on the micro-service)) 
      
      
Is that the intented behaviour ?
The presence of all these uris are miss-leading at the moment I think.
( And I can confirm that without the TokenStore/ and without token-info-uri/jwt.key-uri : a simple gateway/micro-service setup does work )

##### **Reproduce the error**

n/a

##### **Suggest a Fix**

I'll be happy to contribute a pull request to clean this if appropriate.  

##### **JHipster Version(s)**

4.14.1

##### **JHipster configuration**

( If needed, I can add more info ) 

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

n/a

##### **Browsers and Operating System**

Chrome/Windows

- [x] Checking this box is mandatory (this is just to show you read everything)
