### ISSUE TITLE
JWT token always expires after 3600 seconds

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#7500]
##### **Overview of the issue**

Spring should create JWT token set to last for 24 hours, but it somehow expires after 3600 seconds (1 hour). This way, backend invalidates JWT token and throws 401 Unauthorized error.

##### **Motivation for or Use Case**

Correct lifetime of JWT token, according to settings.

##### **Reproduce the error**

This is my `application-dev.yml` setting of JWT expiration time

```yml
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
```

This is a relevant `SecurityConfiguration.java` setting:

```java
        http
            .addFilterBefore(corsFilter, UsernamePasswordAuthenticationFilter.class)
            .exceptionHandling()
            .authenticationEntryPoint(problemSupport)
            .accessDeniedHandler(problemSupport)
        .and()
            .csrf()
            .disable()
            .headers()
            .frameOptions()
            .disable()
        .and()
            .sessionManagement()
            .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
```

##### **JHipster Version(s)**

jHipster v4.14.0
Spring Boot 1.5.9.RELEASE

##### **Environment and Tools**

```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.17.0

node: v9.8.0

npm: 5.6.0

gulp:
[11:05:39] CLI version 3.9.1

yeoman: 2.0.2

yarn: 1.6.0

```
##### **Browsers and Operating System**

MacOS High Sierra
Google Chrome
