### ISSUE TITLE
JHipster 4.14.4 mongodb cluster docker problem

### ISSUE THREAD

**Issue by unikzforce** [jhipster/generator-jhipster#7662]
##### **Overview of the issue**
Couldn't build and run docker images for mongodb cluster mode.

the instructions i follow to Build and run mongodb cluster in Docker can be found [here](https://www.jhipster.tech/docker-compose/).

##### **Reproduce the error**

build instruction:
`docker-compose -f src/main/docker/mongodb-cluster.yml build`
error after built:
```
Building genomics-mongodb-node
Step 1/2 : FROM mongo:3.4.10
 ---> e905a87e116d
Step 2/2 : ADD mongodb/scripts/init_replicaset.js init_replicaset.js
ERROR: Service 'genomics-mongodb-node' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder226407831/mongodb/scripts/init_replicaset.js: no such file or directory
```
i managed to resolve the error in according to this [stackoverflow](https://stackoverflow.com/questions/46198569/docker-compose-failed-to-execute-mongodb-script-file) question . by modifying ".dockerignore" it resolved the build error.

and after building it it failed to start, the command to start was:
`docker-compose -f src/main/docker/mongodb-cluster.yml up`
and it produced:
```
genomics-mongodb_1         | BadValue: configdb supports only replica set connection string
genomics-mongodb_1         | try 'mongos --help' for more information
```
and i was able to resovle it according this [stackoverflow](https://stackoverflow.com/questions/42392923/unable-to-launch-mongos) link by modifying mongodb-cluster.yml.
mongodb-cluster.yml was this:
```
version: '2'
services:
    genomics-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb genomics-mongodb-config
    genomics-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    genomics-mongodb-config:
        image: mongo:3.4.10
        container_name: genomics-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
```
and after i changed it to:
```
version: '2'
services:
    genomics-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb rs1/genomics-mongodb-config
    genomics-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    genomics-mongodb-config:
        image: mongo:3.4.10
        container_name: genomics-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
```
it resolved the problem

##### **Suggest a Fix**

to resolve build problem, i removed **/* from ".dockerignore" .
to resolve starting problem i've just added replica set string: behind mongodb-config in mongodb-cluster.yml.

##### **JHipster Version(s)**
4.14.4

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)
