### ISSUE TITLE
JHipster UAA missing port binding in docker-compose app.yml.

### ISSUE THREAD

**Issue by binakot** [jhipster/generator-jhipster#7837]
Generate new JHipster UAA v5.0.0 and run with docker-compose:

```bash
./gradlew bootWar -Pprod buildDocker
docker-compose -f src/main/docker/app.yml up -d
```

Registry on http://localhost:8761 is available, but UAA server is not. 
I'm trying to open http://localhost:9999/oauth/token_key.

Then I check `app.yml` and didn't find port binding for UAA service:

```yaml
version: '2'
services:
    uaa-app:
        image: uaa
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://uaa-postgresql:5432/uaa
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
    uaa-postgresql:
        extends:
            file: postgresql.yml
            service: uaa-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
```

When I added port binding for `uaa-app`, everyting works fine:

```yaml
        ports:
            - 9999:9999
```
