### ISSUE TITLE
Using h2db in prod profile breaks after upgrade to jhipster 5.1.0

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#7997]
##### **Overview of the issue**

Using h2db in prod profile breaks after upgrade to jhipster 5.1.0 (was runable in 4.x)

Error message:
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> Failed to bind properties under '' to com.zaxxer.hikari.HikariDataSource:
> 
>     Property: driverclassname
>     Value: org.h2.Driver
>     Origin: "driverClassName" from property source "source"
>     Reason: Failed to load driver class org.h2.Driver in either of HikariConfig class loader or Thread context classloader
> 
> Action:
> 
> Update your application's configuration

##### **Motivation for or Use Case**

I don't really have the need for a db and so using h2db as a file on my prod system was suitable. After upgrading my application from 4.x to 5.1.0 the prod package breaks.

##### **Reproduce the error**

1. generate new jhipster project using h2db in dev and mariadb in prod. 
2. Copy db part from application-dev.yml to application-prod.yml
3. run ./mvnw -Pprod

```
datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:.target/h2db/db/test;DB_CLOSE_DELAY=-1
        username: ab
        password:c
    h2:
        console:
            enabled: false
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    liquibase:
        contexts: prod
```

##### **JHipster Version(s)**

```
##### **JHipster configuration**

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Gitlab/test
└── generator-jhipster@5.1.0

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.biao.bascha"
    },
    "jhipsterVersion": "5.1.0",
    "applicationType": "monolith",
    "baseName": "bascha",
    "packageName": "com.biao.bascha",
    "packageFolder": "com/biao/bascha",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mariadb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.3

node: v8.11.3

npm: 6.2.0

yeoman: 2.0.1

yarn: 1.7.0
```

##### **Browsers and Operating System**

MacOS

- [ x ] Checking this box is mandatory (this is just to show you read everything)
