### ISSUE TITLE
Impossible to configure Spring Cloud Config Server

### ISSUE THREAD

**Issue by anthonyrichir** [jhipster/generator-jhipster#8126]
##### **Overview of the issue**

When using the docker-compose subgenerator, the generated jhipster-registry.yml has commented lines for using Spring Cloud Config Server, but uncommenting those lines and remove the native profile doesn't work. It seems that it's not aligned anymore with the current way to use Spring Cloud Config.
[See this discussion on Stackoverflow](https://stackoverflow.com/questions/51884749/how-to-set-the-git-uri-of-spring-cloud-server-for-jhipster-registry-via-env-vars)

##### **Motivation for or Use Case**

The generated jhipster-registry.yml should be self-explanatory, or at least the [documentation](https://www.jhipster.tech/jhipster-registry/) should describe how to achieve this.

##### **Reproduce the error**

Run the jhipster generator, all defaults.
Then in a sibling folder, run the subgenerator jhipster docker-compose.
Edit the jhipster-registry.yml to point to your git repository containing a sample config.

```
version: '2'
services:
    jhipster-registry:
        image: jhipster/jhipster-registry
        environment:
        - SPRING_PROFILES_ACTIVE=prod,git
        - SPRING_SECURITY_USER_PASSWORD=admin
        - JHIPSTER_REGISTRY_PASSWORD=admin
        - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
        - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
        - JHIPSTER_METRICS_LOGS_ENABLED=true
        - JHIPSTER_METRICS_LOGS_REPORTFREQUENCY=60
        - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE=https://github.com/anthonyrichir/demo-feign-config
        - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
        - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/anthonyrichir/demo-feign-config
        ports:
        - 8761:8761
```

##### **Related issues**

Couldn't find one.

##### **Suggest a Fix**

Best solution would be to fix the generator, but an up-to-date documentation would already be a good start.

##### **JHipster Version(s)**

5.2.1

###### Main project
```
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

monolith@0.0.0 /home/arichir/Tests/spring-cloud-config/monolith
└── generator-jhipster@5.2.1 



##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "monolith",
    "baseName": "monolith",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.10.0

npm: 5.6.0

yeoman: 2.0.4

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.17.1, build unknown

Congratulations, JHipster execution is complete!
```
###### jhipster docker-compose
```
Using JHipster version installed globally
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

/home/arichir/Tests/spring-cloud-config/compose
└── (empty)


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "appsFolders": [
      "monolith"
    ],
    "directoryPath": "../",
    "monitoring": "elk",
    "consoleOptions": [],
    "serviceDiscoveryType": "eureka",
    "adminPassword": "admin",
    "jwtSecretKey": "replaced-by-jhipster-info"
  }
}
</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.17.1

node: v8.10.0

npm: 5.6.0

yeoman: 2.0.4

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.17.1, build unknown

Congratulations, JHipster execution is complete!
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Not relevant.

##### **Browsers and Operating System**

Ubuntu 18.04

- [X] Checking this box is mandatory (this is just to show you read everything)
