### ISSUE TITLE
JHipster Registry docker-compose file not working on master

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#8190]
##### **Overview of the issue**

Using `docker-compose -f src/main/docker/jhipster-registry.yml up -d` in a generated project (only on the `master` branch), the registry fails to launch with the following error:
```
Description:

Binding to target [Bindable@235a0c16 type = io.github.jhipster.config.JHipsterProperties, value = 'provided', annotations = array<Annotation>[@org.springframework.boot.context.properties.ConfigurationProperties(ignoreInvalidFields=false, ignoreUnknownFields=false, value=jhipster, prefix=jhipster)]] failed:

    Property: jhipster.security.authentication.jwt.base64-secret
    Value: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
    Origin: "jhipster.security.authentication.jwt.base64-secret" from property source "bootstrapProperties"
    Reason: The elements [jhipster.security.authentication.jwt.base64-secret] were left unbound.

Action:

Update your application's configuration

```
##### **Motivation for or Use Case**
The provided docker-compose files should work, this is also causing the Travis logs for microservices to be extremely long and hard to read

##### **Reproduce the error**
Run `docker-compose -f src/main/docker/jhipster-registry.yml up -d` in a generated project (from the master branch)

##### **Related issues**
Looks like it's related to the recent base64 secret key changes

##### **Suggest a Fix**
Not sure

##### **JHipster Version(s)**
Master only

##### **JHipster configuration**
<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.2.1",
    "applicationType": "microservice",
    "baseName": "ms",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "enableTranslation": true,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "clientPackageManager": "yarn",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true,
    "skipUserManagement": true
  }
}
</pre>
</details>

- [x] Checking this box is mandatory (this is just to show you read everything)
