### ISSUE TITLE
Use gitlab ci stages

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#8358]
##### Improve generated gitlab ci pipeline

Currently there is only one step in the gitlab ci pipeline. We should use different stages

##### **Motivation for or Use Case**

In case one step fails we we have to execute all steps of teh script before. Furthermore when using deploy to heroku we can't see which commit is currently deployed in gitlabs environment overview and maybe rollback. 

An example looks like this:

```
image: jhipster/jhipster:v5.3.4

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - .gradle/wrapper
        - .gradle/caches
stages:
    - build
    - test
    - analyze
    - assemble
    - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew npmInstall -PnodeInstall --no-daemon

gradle-build:
    stage: build
    script:
        - ./gradlew compileJava -x check -PnodeInstall --no-daemon
gradle-test:
    stage: test
    script:
        - ./gradlew test -PnodeInstall --no-daemon
npm-test:
    stage: test
    script: 
        - ./gradlew npm_test -PnodeInstall --no-daemon
sonar-check:
    stage: analyze
    script:
        - ./gradlew sonarqube --no-daemon -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
gradle-assemble:
    stage: assemble
    script:
        - ./gradlew bootWar -Pprod -x check -PnodeInstall --no-daemon
    artifacts:
        paths:
            - build/libs/*.war
        # Uncomment following to expire the artifacts after defined period, https://docs.gitlab.com/ee/ci/yaml/README.html#artifacts-expire_in
        # expire_in: 90 day
heroku-deploy-to-production:
    stage: deploy
    environment:
        name: production
    only:
        - master
    script:
        - ./gradlew deployHeroku --no-daemon
```
Also gound gradle seems not to support deploy to artifactory. Can do a PR for both if you think this is useful. We could also use the gitlab container registry to build and push a docker image of the application.

##### **Related issues or PR**

None found.

- [x] Checking this box is mandatory (this is just to show you read everything)
