### ISSUE TITLE
docker-compose generator strips ticks (') which breaks mssql

### ISSUE THREAD

**Issue by jsm174** [jhipster/generator-jhipster#8428]
##### **Overview of the issue**

The docker-compose generator strips ticks. This is preventing mssql databases from being created with the app name.

##### **Motivation for or Use Case**

Need to use mssql on a project.

##### **Reproduce the error**

import the following jdl:

```
application {
  config {
    applicationType uaa,
    baseName uaa,
    packageName com.optimoit.ia.uaa,
    authenticationType uaa,
    uaaBaseName "uaa",
    prodDatabaseType mssql,
    serviceDiscoveryType eureka,
    buildTool gradle,
    skipClient true
  }
}
```

run `jhipster docker-compose` and examine docker-compose.yml:

```
    uaa-mssql:
        image: microsoft/mssql-server-linux:latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password
            - MSSQL_DATABASE=uaa
            - MSSQL_SLEEP=7
        command:             /bin/bash -c /opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec
            for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U
            sa -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE
            $$MSSQL_DATABASE)"; wait;
```

If you look at uaa/src/main/docker/mssql.yml:

```
version: '2'
services:
    uaa-mssql:
        image: microsoft/mssql-server-linux:latest
        # volumes are not supported on macOS
        # volumes:
        #     - ~/volumes/jhipster/tempdb/mssql/:/var/opt/mssql/data/
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrong(!)Password
            - MSSQL_DATABASE=uaa
            - MSSQL_SLEEP=7
        ports:
            - 1433:1433
        command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -d tempdb -q "EXIT(CREATE DATABASE $$MSSQL_DATABASE)"; wait;'
```

When you run `docker-compose up` you would expect to see:

```
uaa-mssql_1          | wait 7 sec for DB to start
.
.
.
2018-10-01 16:47:12.12 spid51      Starting up database 'uaa'.
2018-10-01 16:47:12.37 spid51      Parallel redo is started for database 'uaa' with worker pool size [3].
2018-10-01 16:47:12.40 spid51      Parallel redo is shutdown for database 'uaa' with worker pool size [3].
```

However, this will not happen:

```
2018-10-01 16:53:54.92 Logon       Error: 18456, Severity: 14, State: 38.
2018-10-01 16:53:54.92 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'uaa'. [CLIENT: 192.168.224.4]
aa-app_1            | 2018-10-01 16:53:55.958 ERROR 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Exception during pool initialization.
uaa-app_1            |
uaa-app_1            | com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "uaa" requested by the login. The login failed. ClientConnectionId:3f58c1c6-c1a7-4efe-b513-3fbc8db59c56
uaa-app_1            | 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
```

##### **Suggest a Fix**

I'm not quite sure of the fix. `docker-compose/index.js` deliberately strip ticks.

https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/index.js#L291

```
    // Fix the output file which is totally broken!!!
                    const yamlArray = yamlString.split('\n');
                    for (let j = 0; j < yamlArray.length; j++) {
                        yamlArray[j] = `    ${yamlArray[j]}`;
                        yamlArray[j] = yamlArray[j].replace(/'/g, '');
                    }
                    yamlString = yamlArray.join('\n');
                    yamlString = yamlString.replace(/>-\n/g, '');
                    yamlString = yamlString.replace(/-\s\s+/g, '- ');
                    this.appsYaml.push(yamlString);
```

##### **JHipster Version(s)**

5.3.4

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

```
application {
  config {
    applicationType uaa,
    baseName uaa,
    packageName com.optimoit.ia.uaa,
    authenticationType uaa,
    uaaBaseName "uaa",
    prodDatabaseType mssql,
    serviceDiscoveryType eureka,
    buildTool gradle,
    skipClient true
  }
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)
