### ISSUE TITLE
Why not use Prettier for json and yaml?

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8709]
##### **Overview of the issue**

Prettier is currently used for ts, css and scss, but json and yaml are supported.

##### **Motivation for or Use Case**

Standardise the format of more files. Using Prettier for Java is already planned. The only issues with YAML files is that placeholders become [unordered lists][3], e.g. [`password:`][2] becomes `? password`. The current JSON files seem to have minor corrections.

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Update Angular [package.json.ejs][4] prettier to 1.14.3 (YAML added in 1.14 and React [package.json.ejs][1] is already 1.14.2). Update both package.json.ejs files' prettier:format script to include .yml and .json files.

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[1]: https://github.com/jhipster/generator-jhipster/blob/0d91b01ae216fd109f9e10d44ecad3cd2b601313/generators/client/templates/react/package.json.ejs#L128
[2]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L92
[3]: http://yaml.org/spec/1.2/spec.html#id2761292
[4]: https://github.com/jhipster/generator-jhipster/blob/31a05c76e84a77dceed97a988f2bc8b3671d58dd/generators/client/templates/angular/package.json.ejs#L114

**Comment by Fydon** [comment]
Okay. Sure I've created a pull request that sets up the formatting and updates the formatting for JSON.

I noticed that the formatting for Typescript has changed, but I forgot to update the scripts for that as well. Should I also update those and squash my commit?

**Comment by deepu105** [comment]
@Fydon you don't have to format the templates, let me look at the PR

**Comment by Fydon** [comment]
Prettier now support [HTML formatting for Angular components][1], but I assume that we want to wait for a while so that any bugs are addressed as it was only release yesterday? If not then I could open another issue and do a pull request.

[1]: https://prettier.io/blog/2018/11/07/1.15.0.html

**Comment by PierreBesson** [comment]
On the topic of the YAML "?bug" with prettier. I have stumbled on this myself as well and I'm thinking that maybe it wouldn't be much of an issue to remove the empty keys. If we could have auto yaml format it would be really awesome as just a tiny yaml indent mistake can prevent your app from starting.

**Comment by Fydon** [comment]
@PierreBesson We could also just comment them out like the [cors definition is], as that formatting then stays the same. Would that be acceptable?

[1]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application.yml.ejs#L246

**Comment by PierreBesson** [comment]
@Fydon yes absolutely.

**Comment by Fydon** [comment]
As comment blocks will be aligned, some formatting of the generator files needs to changed so that the alignment won't break the configuration. Should the user remove just the comment character (#), as in there shouldn't be any spaces?

Would this just be for the server generator files or would other generators be affected, as Prettier is only applying to the src folder currently?

Some files may need to changed, as not all YAML files seem to use 4 characters for spacing. Also I see some issues:

The [feign part of application.yml.ejs][1]
```
feign:
    hystrix:
        enabled: true
#    client:
#        config:
#            default:
#                connectTimeout: 5000
#                readTimeout: 5000
```

[I Prettier changes to][2]:

```
feign:
    hystrix:
        enabled: true
#    client:
#        config:
#            default:
#                connectTimeout: 5000
#                readTimeout: 5000
```

The [cors part of application.yml.ejs][3]:

```
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        #exposed-headers: "Link,X-Total-Count"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
```
[Prettier changes to][4]:

```
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
    #allowed-origins: "*"
    #allowed-methods: "*"
    #allowed-headers: "*"
    #exposed-headers: "Link,X-Total-Count"
    #exposed-headers: "Authorization,Link,X-Total-Count"
    #allow-credentials: true
#max-age: 1800
```

So I assume we'd need to make it this:
```
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
    #    allowed-origins: "*"
    #    allowed-methods: "*"
    #    allowed-headers: "*"
    #    exposed-headers: "Link,X-Total-Count"
    #    exposed-headers: "Authorization,Link,X-Total-Count"
    #    allow-credentials: true
    #    max-age: 1800
```

[1]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application.yml.ejs#L90
[2]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzOBLA5lJAdKAAmMIAsBPAZxgCcMAPfIklhAQwCMAbOAEyUK0ArnAIBiFmC4YEMJhJYlIUVNnmKNhXnFRshXOeM3HCyqHDAwAKhgC2cCELmEArAAYPRkxppw2vG3tHZ3cPEAAaEAgABxgMaEpkUDYaGggAdwAFFIRElDYANwgMXgiQDho2MABrOBgAZWiqjCgsZGE4SNIYWy4AdVIMeEomsDh63KGMAqHyZHBKRMiWyjgaGEzKrFs2ZF0uVciAK0p6ACFKmrr6tnsAGRa4PbYDzpAT+nqWrB4ARSEIPBnq9Ik0aKsaPNyLcuGVonRYH0SjBSMgAIwAFjcoLSqz6lWi83hcAhBSekV8AEchBhfJs2Ntdkh9ocQKtbBh2jQRJFKN8-gCgUgOpEYJwkbwUcgMaLKhhpK0AMIQWw7eZQaDkkBCVZWTh5FlwAC+RqAA
[3]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application.yml.ejs#L246
[4]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEArAFgSwA4Gd4BOSAOlAAQVkCGuAnlGCeZS5AXALTYQQA2HuTAC84SMgCZSLFgFsqADy49+gkWICsABinSKARwCucIxzBVsVMJhi0xARk2PtzCgGIyAIVpkAJnABmVAa8MGQAwgDyAEoAymSYuL4JVABGvHA+AHRkAKoMEDIyCKEwEGQIqemZOm5suEy6blS8vBAA7hkcEASYAOaYUPVkxCAAVCM10q7NrR0+HEUw6BA+QyPjIJMs0y3tnehwVH4Ea2MTLlNw8ty4+4fHpwAyAwDWADQAGhwAKhAwzRwwhADLBzo0yK4rjc7kc4CcxCMAIIGJbdYRUGCYaBvZ5Qd5fX7-fhAkEwMGNHazUzsPywTDNIYwAhGLaUVxyRRUXqiMh2AAcjhAbxAEGwmOguGQoCoBAI7QACjKEJKUFQAG4QTA+IUgFIESwvOAwGIWKxQXrIJlGYXoGAyXgAdSw8FwprgMWV1kwaustGQ4FwkuFA1uBBg8v1vTkyECvFuwtQuHkHn1YENxqoRVxcBjDLgCaTMQGvXSAEUDH8c0hY-GQBYTnD-bRM7wddgerAHVqlsg7AAWTTC9sQW4O-XYf3tuChtU54XsQyYdgRrnR6t54W3GSYS3M-MgQTmssV+C760gf4pLs+HtIPvCplUTC8YtAwpUf1QaBzkAGW7fVIVRrOAAF8QKAA
