### ISSUE TITLE
Use Prettier for yaml

### ISSUE THREAD

**Issue by Fydon** [jhipster/generator-jhipster#8805]
##### **Overview of the issue**

Prettier is currently used for json, ts, css and scss, but and yaml is also supported.

##### **Motivation for or Use Case**

The YAML part of #8709. Standardise the format of more files. An issues with YAML files is that placeholders become [unordered lists][3], e.g. [`password:`][2] becomes `? password`. We could overcome this by commenting out the keys without values (as suggested [here][5]), but some files would need to be reformatted so that the alignment is still correct. [A comment character and a space][6] will be added for each line that is commented out. 

##### **Reproduce the error**

N/A

##### **Related issues**

None found

##### **Suggest a Fix**

Update YAML files that are affected by Prettier, i.e. they will be off src when generated, so that they will be formatted correctly when Prettier is applied, e.g. the cors part of application.yml.ejs changes from

```yaml
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    #cors:
        #allowed-origins: "*"
        #allowed-methods: "*"
        #allowed-headers: "*"
        <%_ if (authenticationType === 'session') { _%>
        #exposed-headers: "Link,X-Total-Count"
        <%_ } else { _%>
        #exposed-headers: "Authorization,Link,X-Total-Count"
        <%_ } _%>
        #allow-credentials: true
        #max-age: 1800
```

to
```yaml
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    # cors:
    #     allowed-origins: "*"
    #     allowed-methods: "*"
    #     allowed-headers: "*"
          <%_ if (authenticationType === 'session') { _%>
    #     exposed-headers: "Link,X-Total-Count"
          <%_ } else { _%>
    #     exposed-headers: "Authorization,Link,X-Total-Count"
          <%_ } _%>
    #     allow-credentials: true
    #     max-age: 1800
```

##### **JHipster Version(s)**

```
prototype@0.0.0 
`-- generator-jhipster@5.5.0

```

##### **JHipster configuration**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.example",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.5.0",
    "applicationType": "monolith",
    "baseName": "example",
    "packageName": "com.example",
    "packageFolder": "com/example",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": "spring-websocket",
    "databaseType": "sql",
    "devDatabaseType": "oracle",
    "prodDatabaseType": "oracle",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Browsers and Operating System**

java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

git version 2.17.1.windows.2

node: v10.13.0

npm: 6.4.1

yeoman: 2.0.5

Docker version 18.06.1-ce, build e68fc7a

docker-compose version 1.22.0, build f46880fe

-   [X] Checking this box is mandatory (this is just to show you read everything)

[2]: https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L93
[3]: http://yaml.org/spec/1.2/spec.html#id2761292
[5]: https://github.com/jhipster/generator-jhipster/issues/8709#issuecomment-437836030
[6]: https://github.com/jhipster/generator-jhipster/issues/8709#issuecomment-437866649

**Comment by Fydon** [comment]
@PierreBesson Which of the following is correct for the above example?

```yaml
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    # cors:
    #     allowed-origins: "*"
    #     allowed-methods: "*"
    #     allowed-headers: "*"
          <%_ if (authenticationType === 'session') { _%>
    #     exposed-headers: "Link,X-Total-Count"
          <%_ } else { _%>
    #     exposed-headers: "Authorization,Link,X-Total-Count"
          <%_ } _%>
    #     allow-credentials: true
    #     max-age: 1800
```
or
```yaml
jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    # cors:
    #     allowed-origins: "*"
    #     allowed-methods: "*"
    #     allowed-headers: "*"
    <%_ if (authenticationType === 'session') { _%>
    #     exposed-headers: "Link,X-Total-Count"
    <%_ } else { _%>
    #     exposed-headers: "Authorization,Link,X-Total-Count"
    <%_ } _%>
    #     allow-credentials: true
    #     max-age: 1800
```
