### ISSUE TITLE
Use correct api versions for Kubernetes

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#9165]
Our usage of apiVersion is very inconsistent, For some of the generated Kubernetes files we are still using `extensions/v1beta1`. For services we use `apiVersion: v1` and for some deployments `apps/v1` I think we need to review and update them. Especially the SQL database maifests. See below for example

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: invoice-mysql
  namespace: xl-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: invoice-mysql
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: mysql
        image: mysql:5.7.20
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MYSQL_DATABASE
          value: invoice
        args:
        - --lower_case_table_names=1
        - --skip-ssl
        - --character_set_server=utf8mb4
        - --explicit_defaults_for_timestamp
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: invoice-mysql
  namespace: xl-demo
spec:
  selector:
    app: invoice-mysql
  ports:
  - port: 3306

```
@PierreBesson @srinivasa-vasu could you guys have a glance
