### ISSUE TITLE
Spring profile for 'local' properties

### ISSUE THREAD

**Issue by ecostanzi** [jhipster/generator-jhipster#9602]
##### **Overview of the feature request**

Add a `local` profile to the list of spring profiles included in the `application-dev.yml` so that an `application-local.yml` file can be used to set local properties.  

##### **Motivation for or Use Case**

During development it always happens we have to set local variables (logging levels, custom application properties, local endpoints etc..). We usually add a `local` spring profiles so that all these custom variables can be set in the `application-local.yml` file.

- `application-dev.yml` is used for the common/shared/default development properties, 

- `application-local.yml`  for local variables, not shared. This file is can be .gitignored.

The local profile can be included in the `application-dev.yml` file:

```
spring:
    profiles:
        active: dev
        include:
            - swagger
            - local
            # Uncomment to activate TLS for the dev profile
            #- tls
```

##### **Related issues or PR**

I'm aware of the fact that the topic has already been discussed here in 2015 https://github.com/jhipster/generator-jhipster/issues/1554 and I understand the need to keep things simple. However, I wonder if this possibility can be reconsidered, it's something we add in every project. It also reduces the risk to commit some local properties in the -dev.yml file.

-   [X] Checking this box is mandatory (this is just to show you read everything)
