### ISSUE TITLE
kubernetes namespace should not be present the yml files

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#9777]
##### **Overview of the issue**
Kubectl can't deploy to the right namespace since the valu ein the context is overridden by the yml file

##### **Motivation for or Use Case**
Having different namespaces for test and prod

the namespace can be defined in kubeconf per context so that each one uses it's own namespace
##### **Reproduce the error**
generate kubernetes

##### **Suggest a Fix**
remove kubernetesNamespace from the generator (or have it optional is you want)

##### **JHipster Version(s)**

5.0.1 this not a regression
##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Hawkurane** [comment]
@yelhouti hello, when do you say the context is overriden by the yml file, do you mean the generated files for deployments/services?

By having the value 'default' the namespace.yml file should not be generated

**Comment by yelhouti** [comment]
@Hawkurane When I say context I mean the kubeconf context, ex:
```
contexts:
- context:
    cluster: dev
    namespace: sb
    user: yelhouti
  name: dev
- context:
    cluster: prod
    namespace: default
    user: yelhouti
```
this tells kubectl to use the specified context for all requests, equivalent to automatically adding `--namespace=sb`, I have the same problem with the URLs in the deployements.yml files URLS should be:
http://jhipster-registry instead of http://jhipster-registry.sb.svc.cluster.local

**Comment by Hawkurane** [comment]
I see,
does having a metadata.namespace variable in the deployment files override the kubeconf context then?
If we remove the metadata.namespace value from the files does your configuration work ?

**Comment by yelhouti** [comment]
Yes and Yes :)

**Comment by Hawkurane** [comment]
I found the culprits:

https://github.com/jhipster/generator-jhipster/blob/ee2aa63fde43242749ec5295e554d688e7a47533/generators/kubernetes/templates/deployment.yml.ejs#L21-L23

https://github.com/jhipster/generator-jhipster/blob/ee2aa63fde43242749ec5295e554d688e7a47533/generators/kubernetes/templates/service.yml.ejs#L21-L25

by checking if the value is 'default' we can omit the namespace part of the .yml
Unsure if this is good practice though.
WDYT?

**Comment by yelhouti** [comment]
I think we can always omit the value, the point is having the same yml files for all environments. yml files houls never be namespace depend. `kubernetesNamespace` should never be used.

**Comment by Hawkurane** [comment]
At this point of time, there is no kubeconf context generated so every namespace are declared when generating the application in each depoyment files. If we want to remove this kubernetesNamespace constant, we should generate a kubeconf context file as you said that would be equivalent to automatically executing the --namespace command.

**Comment by yelhouti** [comment]
a kubeconf file is as simple as this:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: ssl/dev/ca.crt
    server: https://<dev-cluster-ip>:6443
  name: dev
- cluster:
    certificate-authority: ssl/prod/ca.crt
    server: https://<prod-cluster-ip>:6443
  name: prod
contexts:
- context:
    cluster: dev
    namespace: sb
    user: yelhouti
  name: dev
- context:
    cluster: prod
    user: yelhouti
  name: prod
current-context: dev
kind: Config
preferences: {}
users:
- name: yelhouti
  user:
    client-certificate: ssl/dev/user.crt
    client-key: ssl/dev/user.key
```
it is used by simply exporting it's path: `export KUBECONFIG=./kubeconfig`
